import assert from 'node:assert/strict';
import {clone,validateScenario} from '../src/engine.js?v=20261006-measurement-history-14';
import {createSimulation,sharedSteps,recordingPayload,restoreRecording,closestPathPoint} from '../src/recorded-engine.js?v=20261006-measurement-history-14';
import {editableDefinition,removeDefinition,moveDefinition,editWaypoint} from '../src/editor.js?v=20261006-measurement-history-14';
const point=(x,y=0,z=0)=>({x,y,z}),ref=id=>({$param:id});
const unit=(id,x=0,y=0)=>({id,name:id,domain:'surface',faction:'friendly',manned:false,speed:10,initial:point(x,y),route:[],routeMode:'once'});
const source={version:3,unitsSystem:'SI',title:'担当値',duration:400,terrain:{columns:5,rows:5,spacing:10000,origin:point(-10000,-10000),seaLevel:0,elevations:Array(25).fill(-500)},units:[unit('a'),unit('b')],routes:[{id:'east',name:'東',points:[point(0),point(1000)]},{id:'north',name:'北',points:[point(0),point(0,1000)]}],destinations:[{id:'x',name:'X',kind:'point',point:point(2000)},{id:'y',name:'Y',kind:'point',point:point(0,2000)}],behaviors:[{id:'g',name:'共通挙動',initial:'wait',parameters:[{id:'route',name:'巡回経路',type:'route'},{id:'destination',name:'退避先',type:'destination'},{id:'seconds',name:'待機時間',type:'number',unit:'s',default:10},{id:'distance',name:'接近距離',type:'number',unit:'m',default:100}],nodes:[{id:'wait',kind:'wait',seconds:ref('seconds')},{id:'follow',kind:'follow',routeId:ref('route')},{id:'move',kind:'move',destinationId:ref('destination')},{id:'stop',kind:'stop'}],triggers:[],edges:[{from:'wait',to:'follow',when:'elapsed'},{from:'follow',to:'move',when:'arrived'},{from:'move',to:'stop',when:'near',destinationId:ref('destination'),distance:ref('distance'),distanceMode:'horizontal'}]}],behaviorAssignments:[{id:'ta',name:'担当A',behaviorId:'g',targets:['unit:a'],parameters:{route:'east',destination:'x'}},{id:'tb',name:'担当B',behaviorId:'g',targets:['unit:b'],parameters:{route:'north',destination:'y',seconds:20,distance:300}}],recording:{step:10,interval:10}};
function run(s){const m=createSimulation(s),steps=sharedSteps(m,undefined,undefined,{record:true});while(!steps.next().done){}return m;}
const near=(a,b)=>assert(Math.abs(a-b)<1e-5,`${a} != ${b}`);
const m=run(source);near(m.result.actionEvents.find(e=>e.type==='near'&&e.unitId==='a').time,200);near(m.result.actionEvents.find(e=>e.type==='near'&&e.unitId==='b').time,190);
assert.deepEqual(m.source.behaviors[0].nodes[0].seconds,ref('seconds'));assert.equal(m.states[0].graph.nodes[0].seconds,10);assert.equal(m.states[1].graph.nodes[0].seconds,20);assert.notEqual(m.states[0].graph,m.states[1].graph);
assert.deepEqual(restoreRecording(recordingPayload(m)).evaluate(130).units,m.evaluate(130).units);
const onMap=clone(source);onMap.behaviors[0].initial='follow';assert.equal(editableDefinition(onMap,'a').navigationRoute.id,'east');assert.equal(editableDefinition(onMap,'b').navigationRoute.id,'north');
for(const change of [s=>delete s.behaviorAssignments[0].parameters.route,s=>s.behaviorAssignments[0].parameters.seconds=90000,s=>s.behaviors[0].nodes[0].seconds=ref('route'),s=>s.behaviors[0].nodes[0].seconds=ref('missing'),s=>s.behaviorAssignments[0].parameters.distance=-1,s=>s.behaviorAssignments[0].parameters.route='missing',s=>s.behaviorAssignments[0].parameters.extra=10,s=>s.behaviors[0].parameters={},s=>s.behaviors[0].parameters[2].unit='m']){const bad=clone(source);change(bad);assert.throws(()=>validateScenario(bad),/担当|タスク|待機|接近/);}
// Time events resolve separately for each assignment, including repeat scheduling.
const triggers=clone(source);triggers.behaviors[0].triggers=[{id:'timer',event:'time',seconds:ref('seconds'),to:'wait',once:false}];triggers.behaviors[0].edges=[];triggers.duration=40;
assert.deepEqual(run(triggers).result.actionEvents.filter(e=>e.type==='triggered'&&e.unitId==='b').map(e=>e.time),[20,40]);
// Unit placeholders bind report recipients, and deleting bound units is guarded.
const recipient=clone(source);recipient.behaviors[0].parameters.push({id:'recipient',name:'報告先',type:'unit',default:'b'});recipient.behaviors[0].nodes.push({id:'report',kind:'report',receiverId:ref('recipient')});assert.doesNotThrow(()=>validateScenario(recipient));assert.throws(()=>removeDefinition(recipient,'b'),/担当値/);
// The nearest point lies in the middle of a segment, not at a sampled vertex.
const closest=closestPathPoint({nodes:[{...point(0),d:0},{...point(1000),d:1000}]},point(337,500));near(closest.along,337);near(closest.point.x,337);near(closest.point.y,0);
const entry=clone(source);entry.units=[unit('a',337,500)];entry.units[0].speed=10;entry.behaviorAssignments=[{id:'ta',name:'A',behaviorId:'g',targets:['unit:a'],parameters:{route:'east',destination:'x'}}];entry.behaviors[0].initial='follow';entry.behaviors[0].nodes.find(n=>n.id==='follow').joinMode='nearest';entry.behaviors[0].edges=[{from:'follow',to:'stop',when:'arrived'}];
const placed=clone(entry),originalRoute=clone(placed.routes[0]);moveDefinition(placed,'a',{x:100,y:200});assert.deepEqual(placed.routes[0],originalRoute);assert.equal(placed.units[0].initial.x,437);assert.equal(editableDefinition(placed,'a').unit.initial.x,437);editWaypoint(placed,'a',0,point(25));assert.equal(placed.routes[0].points[0].x,25);
const shortest=run(entry);near(shortest.evaluate(0).units[0].position.x,337);near(shortest.evaluate(0).units[0].position.y,500);near(shortest.evaluate(50).units[0].position.x,337);near(shortest.evaluate(50).units[0].position.y,0);near(shortest.result.actionEvents.find(e=>e.type==='arrived').time,116.3);near(shortest.evaluate(400).units[0].distance,1163);
const far=clone(entry);far.duration=20;far.units[0].initial=point(9500,500);far.units[0].speed=100;far.routes[0].points[1]=point(10000);const farResult=run(far);near(farResult.result.actionEvents.find(e=>e.type==='arrived').time,10);near(farResult.evaluate(20).units[0].position.x,10000);near(farResult.evaluate(20).units[0].distance,1000);
entry.behaviors[0].nodes.find(n=>n.id==='follow').joinMode='start';near(run(entry).result.actionEvents.find(e=>e.type==='arrived').time,100);
// Both patrol entry modes preserve current position on transitions.
const patrol=clone(entry);patrol.behaviors[0].initial='wait';patrol.behaviors[0].nodes=[{id:'wait',kind:'wait',seconds:10},{id:'patrol',kind:'patrol',routeId:'east',speedFraction:1,joinMode:'start'}];patrol.behaviors[0].parameters=[];patrol.behaviorAssignments[0].parameters={};patrol.behaviors[0].edges=[{from:'wait',to:'patrol',when:'elapsed'}];patrol.routes[0].points=[point(0),point(1000),point(1000,1000)];
const start=run(patrol);near(start.evaluate(10).units[0].position.x,337);assert.equal(start.states[0].node.kind,'patrol');
patrol.behaviors[0].nodes[1].joinMode='nearest';const nearest=run(patrol);near(nearest.evaluate(10).units[0].position.x,337);assert.notDeepEqual(nearest.evaluate(20).units[0].position,start.evaluate(20).units[0].position);
console.log('PASS: typed per-assignment bindings, defaults, validation, independent time events, recipient guards, main-map references, recording round-trip and exact start/nearest path entry');
