import {clickWorkspace,showNavigator} from './workspace-browser-helpers.mjs';
import {UI_BUILD} from '../src/ui-dom.js?v=20261009-map-workspace-29';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SIMSIM_PLAYWRIGHT??'playwright'),root=path.resolve(fileURLToPath(new URL('..',import.meta.url))),folder=fs.mkdtempSync(path.join(os.tmpdir(),'simsim-information-'));
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'text/plain');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; worker-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:");try{res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.SIMSIM_BROWSER_EXECUTABLE?{executablePath:process.env.SIMSIM_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.stack);});page.on('console',e=>{if(e.type()==='error')console.error('CONSOLE',e.text());});
 page.on('dialog',d=>d.accept());page.setDefaultTimeout(15000);await page.goto('http://127.0.0.1:'+server.address().port+(process.env.SIMSIM_PORTABLE?'/portable/index.html':''));try{await page.waitForSelector('#boot[hidden]',{state:'attached',timeout:15000});}catch(e){console.error(await page.locator('#boot').innerText());throw e;}assert.equal(await page.locator('#title').inputValue(),'情報制約下の監視・中継・対処');

 assert.equal(await page.locator('.inspector input,.inspector select').count(),0);
 await showNavigator(page);await page.locator('.unit-item[data-id="uav"]').click();await clickWorkspace(page,'settings-open');await page.locator('[data-settings-category="capabilities"]').click();await page.locator('[data-settings-module="unit.resources"]').evaluate(e=>e.open=true);await page.locator('#resource-add').click();
 const field=id=>page.locator('input[data-setting-id="'+id+'"],select[data-setting-id="'+id+'"]');
 for(const [id,value] of [['resource.capacity','50'],['resource.initial','25'],['resource.perMetre','2']]){await field(id).fill(value);await field(id).press('Tab');}
 await page.locator('#settings-apply').click();await page.waitForSelector('#settings-editor[hidden]',{state:'attached'});
 const save=async name=>{const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);const file=path.join(folder,name);await download.saveAs(file);return JSON.parse(fs.readFileSync(file));};
 assert.equal((await save('resources.txt')).units.find(u=>u.id==='uav').resources.fuel.perMetre,.002);
 await page.locator('#undo').click();assert.equal((await save('undo.txt')).units.find(u=>u.id==='uav').resources,undefined);await page.locator('#redo').click();assert.equal((await save('redo.txt')).units.find(u=>u.id==='uav').resources.fuel.capacity,50);
 // Switching targets never silently applies a draft; explicit discard selects the requested target.
 await clickWorkspace(page,'settings-open');await page.locator('#unit-name').fill('下書き名');await page.locator('#unit-name').press('Tab');await showNavigator(page);await page.locator('.unit-item[data-id="relay"]').click();assert(await page.locator('#settings-leave-dialog').isVisible());await page.locator('#settings-keep').click();assert.equal(await page.locator('#unit-name').inputValue(),'下書き名');await showNavigator(page);await page.locator('.unit-item[data-id="relay"]').click();await page.locator('#settings-discard').click();assert((await page.locator('#inspector-name').innerText()).includes('relay'));assert.equal((await save('discard.txt')).units.find(u=>u.id==='uav').name,'uav');
 // The same contract renders new standard fields without a handwritten DOM entry.
 const automatic=await page.evaluate(async build=>{const {renderFields}=await import('/src/settings-form.js?v='+build),{number,fieldErrors}=await import('/src/configuration-schema.js?v='+build);const host=document.createElement('div'),record={reserve:3},f=number('fixture.reserve','reserve','予備量',0,10);renderFields(host,[f],record,{},(field,value)=>record.reserve=value);const input=host.querySelector('input');input.value='6';input.dispatchEvent(new Event('change'));return {value:record.reserve,valid:fieldErrors([f],record).length,type:input.type};},UI_BUILD);assert.deepEqual(automatic,{value:6,valid:0,type:'number'});
 // Scenario collections and model assumptions are authorable and survive file round trips.
 await clickWorkspace(page,'scenario-settings-open');await page.locator('[data-add-collection="scenario.initialInformation"]').click();await field('initial.time').fill('-15');await field('initial.time').press('Tab');await page.locator('[data-settings-category=communication]').click();await page.locator('[data-settings-module="scenario.links"]').evaluate(e=>e.open=true);await page.locator('[data-add-collection="scenario.links"]').click();await page.locator('[data-settings-module="scenario.disruptions"]').evaluate(e=>e.open=true);await page.locator('[data-add-collection="scenario.disruptions"]').click();await page.locator('[data-settings-category=operation]').click();await page.locator('[data-add-collection="scenario.operational"]').click();await field('operational.time').fill('5');await field('operational.time').press('Tab');await page.locator('#settings-apply').click();await page.waitForSelector('#settings-editor[hidden]',{state:'attached'});
 const collections=await save('collections.txt');assert.equal(collections.initialInformation.at(-1).observation.observationTime,-15);assert(!Object.hasOwn(collections.communicationDisruptions.at(-1),'linkIds'));assert.equal(collections.operationalEvents.at(-1).time,5);await page.locator('#file').setInputFiles(path.join(folder,'collections.txt'));await page.waitForFunction(()=>document.getElementById('file').value==='');
 // Analysis uses the selected target and current value from the shared metadata.
 await showNavigator(page);await page.locator('.unit-item[data-id="uav"]').click();await clickWorkspace(page,'settings-open');await page.locator('[data-settings-category=capabilities]').click();await page.locator('[data-settings-module="entity.movement"]').getByRole('button',{name:'比較に追加',exact:true}).click();assert(await page.locator('#analysis-dialog').isVisible());assert((await page.locator('#factors-editor').textContent()).includes('属性'));await page.locator('#analysis-close').click();
 // Group members write the saved template, with scope visible before applying.
 await page.locator('#sample-picker').selectOption('island-patrol-demo.txt');await page.waitForFunction(()=>document.getElementById('title').value.includes('島'));await showNavigator(page);await page.locator('.unit-item[data-id*="__"]').first().click();await clickWorkspace(page,'settings-open');assert((await page.locator('#settings-scope').innerText()).includes('群「'));await page.locator('[data-settings-module="group.placement"]').evaluate(e=>e.open=true);await field('group.count').fill('7');await field('group.count').press('Tab');await page.locator('[data-settings-category=capabilities]').click();await page.locator('[data-settings-module="unit.resources"]').evaluate(e=>e.open=true);await page.locator('#resource-add').click();await page.setViewportSize({width:1200,height:900});await page.screenshot({path:process.env.SIMSIM_SETTINGS_SCREENSHOT??'/tmp/simsim-settings-editor.png'});assert(await page.locator('#settings-content').evaluate(e=>e.scrollWidth<=e.clientWidth));assert(await page.locator('.inspector').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#settings-apply').click();await page.waitForSelector('#settings-editor[hidden]',{state:'attached'});const group=(await save('group.txt')).groups.find(g=>g.template.resources?.fuel);assert.equal(group.count,7);assert.equal(group.template.resources.fuel.capacity,100);
 assert.deepEqual(errors,[]);assert(!await page.locator('#error-dialog').isVisible());console.log('PASS: inspector separation, automatic contract field rendering, resources and SI round trip, Undo/Redo, draft target-switch protection, information/link/disruption/event collections, reload, analysis handoff, group scope and 1200px layout');

}finally{await browser?.close();server.close();fs.rmSync(folder,{recursive:true,force:true});}
