import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SIMSIM_PLAYWRIGHT??'playwright'),root=path.resolve(fileURLToPath(new URL('..',import.meta.url))),folder=fs.mkdtempSync(path.join(os.tmpdir(),'simsim-information-'));
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'text/plain');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; worker-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:");try{res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.SIMSIM_BROWSER_EXECUTABLE?{executablePath:process.env.SIMSIM_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message);});page.on('console',e=>{if(e.type()==='error')console.error('CONSOLE',e.text());});
 await page.goto('http://127.0.0.1:'+server.address().port);try{await page.waitForSelector('#boot[hidden]',{state:'attached',timeout:15000});}catch(e){console.error(await page.locator('#boot').innerText());throw e;}assert.equal(await page.locator('#title').inputValue(),'情報制約下の監視・中継・対処');
 await page.locator('.unit-item[data-id="uav"]').click();await page.locator('#record-run').click();await page.waitForFunction(()=>!document.getElementById('play').disabled);
 await page.locator('#timeline').evaluate(e=>{e.value='20';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForFunction(()=>document.getElementById('knowledge-summary').textContent.includes('track-1'));
 await page.locator('.map-toolbar .menu-popover summary').click();await page.locator('#information-perspective').selectOption('selected');await page.locator('.map-toolbar .menu-popover summary').click();assert((await page.locator('#knowledge-summary').innerText()).includes('鮮度'),await page.locator('#knowledge-summary').innerText());await page.screenshot({path:path.join(folder,'knowledge.png')});
 await page.locator('.map-toolbar .menu-popover summary').click();await page.locator('#information-perspective').selectOption('truth');await page.locator('#task-aggregation').selectOption('tasks');await page.locator('.map-toolbar .menu-popover summary').click();await page.waitForSelector('#task-summary tr');assert.equal(await page.locator('#task-summary tr').count(),3);await page.locator('#task-summary tr').last().click();assert.equal(await page.locator('#task-aggregation').inputValue(),'units');
 await page.locator('#unit-task-open').click();await page.locator('#graph-edit-tab').click();await page.locator('#behavior-canvas g[data-edge="0"]').click();assert.equal(await page.locator('#edge-condition').inputValue(),'condition');assert((await page.locator('#edge-expression').inputValue()).includes('knowledge.selectedContact.age'));await page.locator('#edge-decision-preset').selectOption('missing');assert(await page.locator('#edge-unknown').isChecked());await page.locator('#behavior-cancel').click();
 await page.locator('#analysis-open').click();await page.locator('#experiment-open').click();for(const [id,v] of [['experiment-candidates','4'],['experiment-trials','1']]){await page.locator('#'+id).fill(v);await page.locator('#'+id).dispatchEvent('change');}await page.locator('#experiment-run').click();await page.waitForFunction(()=>document.getElementById('experiment-progress').textContent.includes('探索完了'),{},{timeout:60000});assert.equal(await page.locator('#experiment-results tr').count(),4);
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#experiment-save').click()]);const saved=path.join(folder,'experiment.txt');await download.saveAs(saved);const payload=JSON.parse(fs.readFileSync(saved));assert.equal(payload.completed,8);assert.equal(payload.model,'information-behavior-v4');await page.locator('#experiment-close').click();
 await page.locator('.unit-item[data-id="observer"]').click();await page.locator('.unit-item[data-id="observer"]').click({button:'right'});await page.getByRole('menuitem',{name:'この地点を中心に監視任務を作成',exact:true}).click();await page.locator('#mission-template-radius').fill('500');await page.locator('#mission-template-receiver').selectOption('relay');await page.locator('#mission-template-apply').click();await page.waitForSelector('#behavior-dialog[open]');assert((await page.locator('#behavior-name').inputValue()).includes('監視'));await page.locator('#behavior-cancel').click();await page.locator('#undo').click();assert.equal(await page.locator('.task-item').count(),3);await page.locator('#redo').click();assert.equal(await page.locator('.task-item').count(),3);
 assert.deepEqual(errors,[]);assert(!await page.locator('#error-dialog').isVisible());console.log('PASS: v4 startup, local information seek/perspective, task aggregation, condition authoring, multi-variable Worker run/export, direct map template and undo/redo');
}finally{await browser?.close();server.close();fs.rmSync(folder,{recursive:true,force:true});}
