import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SIMSIM_PLAYWRIGHT??'playwright');
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url))),folder=fs.mkdtempSync(path.join(os.tmpdir(),'simsim-navigation-'));
const server=http.createServer((req,res)=>{
  const pathname=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));
  if(!file.startsWith(root+path.sep)){res.statusCode=403;res.end();return;}
  res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; worker-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:");
  res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'text/plain');
  try{res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;
try{
  browser=await chromium.launch({headless:true,...(process.env.SIMSIM_BROWSER_EXECUTABLE?{executablePath:process.env.SIMSIM_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('console',event=>{if(event.type()==='error')errors.push(event.text());});
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.waitForFunction(()=>document.getElementById('recording-info').textContent.includes('未計算'));
  const source={version:3,unitsSystem:'SI',title:'Route A -> B',duration:100,seed:'ui-nav',terrain:{columns:5,rows:5,spacing:10000,origin:{x:-10000,y:-10000,z:0},seaLevel:0,elevations:Array(25).fill(-500)},units:[{id:'actor',name:'行動ユニット',domain:'surface',faction:'friendly',manned:false,speed:100,initial:{x:-500,y:0,z:0},route:[{x:500,y:0,z:0}],routeMode:'once',sensor:{enabled:true,range:5000,probabilityPerMinute:1,domains:['surface'],terrainLOS:false}},{id:'target',name:'相手ユニット',domain:'surface',faction:'hostile',manned:false,speed:5,initial:{x:2500,y:0,z:0},route:[{x:5000,y:0,z:0}],routeMode:'once'}],behaviors:[{id:'g',name:'切り替え',initial:'a',triggers:[],nodes:[{id:'a',kind:'follow',x:100,y:100}],edges:[]}],behaviorAssignments:[{id:'t',name:'切り替えタスク',behaviorId:'g',targets:['unit:actor'],spacing:'none'}],recording:{step:10,interval:10}};
  fs.writeFileSync(path.join(folder,'input.jsn'),JSON.stringify(source));await page.locator('#file').setInputFiles(path.join(folder,'input.jsn'));
  await page.locator('.unit-item[data-id="actor"]').click();await page.locator('#unit-task-open').click();await page.locator('#graph-edit-tab').click();
  const node=id=>page.locator('#behavior-canvas [data-node="'+id+'"] > rect:first-child');
  const add=async id=>{await page.locator('#graph-add-menu summary').click();await page.locator('#'+id).click();};
  const connect=async(from,to,trigger=false)=>{await page.locator('#behavior-fit').click();await page.locator('#graph-connect').click();await (trigger?page.locator('#behavior-canvas [data-trigger="'+from+'"] > rect:first-child'):node(from)).click();await node(to).click();};
  await node('a').click();await page.locator('#node-route-new').click();
  assert(await page.locator('#navigation-dialog').isVisible());
  await page.locator('#navigation-name').fill('航路A');await page.locator('#navigation-points').fill('-500, 0, 0\n500, 0, 0');await page.locator('#navigation-save').click();
  const routeA=await page.locator('#node-route').inputValue();assert(routeA);
  await page.locator('#behavior-undo').click();assert.equal(await page.locator('#node-route').inputValue(),'');await page.locator('#behavior-redo').click();assert.equal(await page.locator('#node-route').inputValue(),routeA);
  await add('node-add');await page.locator('#node-kind').selectOption('follow');const b=await page.locator('#behavior-canvas .selected').getAttribute('data-node');
  await page.locator('#node-route-new').click();await page.locator('#navigation-name').fill('航路B');await page.locator('#navigation-draw').click();
  assert(await page.locator('#behavior-dialog').isHidden());assert(await page.locator('#navigation-dialog').isHidden());
  await page.locator('#viewtop').click();const canvas=await page.locator('#map canvas').boundingBox();
  for(const [x,y] of [[.3,.4],[.5,.3],[.6,.6]])await page.mouse.click(canvas.x+canvas.width*x,canvas.y+canvas.height*y);
  await page.keyboard.press('Escape');assert(await page.locator('#navigation-dialog').isVisible());
  assert.equal((await page.locator('#navigation-points').inputValue()).split('\n').length,3);
  await page.locator('#navigation-points').fill('-500, 500, 0\n500, 500, 0');await page.locator('#navigation-save').click();
  const routeB=await page.locator('#node-route').inputValue();assert.notEqual(routeB,routeA);
  await page.locator('#node-route-edit').click();await page.locator('#navigation-name').fill('航路B（変更後）');await page.locator('#navigation-save').click();
  assert((await page.locator('#node-route option:checked').textContent()).includes('変更後'));
  // The catalog can edit/delete an unused resource without assigning it first.
  await page.locator('#node-route').selectOption('');await add('route-new');await page.locator('#navigation-resource').selectOption(routeB);await page.locator('#navigation-delete').click();
  assert.equal(await page.locator('#node-route option[value="'+routeB+'"]').count(),0);
  await page.locator('#behavior-undo').click();await page.locator('#behavior-undo').click();assert.equal(await page.locator('#node-route').inputValue(),routeB);
  await connect('a',b);await page.locator('#edge-condition').selectOption('detected');
  await add('node-add');await page.locator('#node-kind').selectOption('move');const move=await page.locator('#behavior-canvas .selected').getAttribute('data-node');
  assert.equal(await page.locator('#node-kind option[value="return"]').count(),0);
  await page.locator('#node-destination-new').click();await page.locator('#navigation-name').fill('地点X');await page.locator('#navigation-pick').click();
  await page.mouse.click(canvas.x+canvas.width*.4,canvas.y+canvas.height*.5);
  assert(await page.locator('#navigation-dialog').isVisible());
  await page.locator('#navigation-pick').click();await page.keyboard.press('Escape');assert(await page.locator('#navigation-dialog').isVisible());
  await page.locator('#navigation-x').fill('2');await page.locator('#navigation-y').fill('0');await page.locator('#navigation-z').fill('0');await page.locator('#navigation-save').click();
  const destinationX=await page.locator('#node-destination').inputValue();assert(destinationX);
  await page.locator('#node-destination-new').click();await page.locator('#navigation-name').fill('追跡対象');await page.locator('#navigation-kind').selectOption('unit');
  assert.equal(await page.locator('#navigation-name').inputValue(),'追跡対象');await page.locator('#navigation-unit').selectOption('target');await page.locator('#navigation-save').click();
  const target=await page.locator('#node-destination').inputValue();assert.notEqual(target,destinationX);
  await page.locator('#node-destination').selectOption(destinationX);await page.locator('#node-destination').selectOption(target);
  await connect(b,move);await page.locator('#edge-condition').selectOption('near');
  await page.locator('#edge-near-destination').selectOption(target);await page.locator('#edge-near-distance').fill('300');await page.locator('#edge-near-distance').press('Tab');await page.locator('#edge-near-mode').selectOption('absolute');
  assert((await page.locator('#behavior-canvas [data-edge="1"]').textContent()).includes('300m以内（絶対）'));
  await add('trigger-add');await page.locator('#trigger-event').selectOption('near');await page.locator('#trigger-near-destination').selectOption(destinationX);await page.locator('#trigger-near-distance').fill('200');await page.locator('#trigger-near-distance').press('Tab');await page.locator('#trigger-near-mode').selectOption('horizontal');await page.locator('#trigger-once').selectOption('repeat');
  const trigger=await page.locator('#behavior-canvas .trigger-node.selected').getAttribute('data-trigger');await connect(trigger,move,true);
  await node(move).click();await page.locator('#node-destination-edit').click();await page.locator('#navigation-delete').click();assert((await page.locator('#navigation-error').textContent()).includes('使用中'));await page.locator('#navigation-cancel').click();
  if(process.env.SIMSIM_NAV_SCREENSHOT)await page.locator('#behavior-dialog').screenshot({path:process.env.SIMSIM_NAV_SCREENSHOT});
  await page.locator('#behavior-apply').click();await page.waitForSelector('#behavior-dialog:not([open])',{state:'attached'});
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);await download.saveAs(path.join(folder,'output.jsn'));
  const saved=JSON.parse(fs.readFileSync(path.join(folder,'output.jsn'))),graph=saved.behaviors[0];
  assert.equal(saved.routes.length,2);assert.equal(saved.destinations.length,2);assert.equal(graph.nodes.find(n=>n.id==='a').routeId,routeA);assert.equal(graph.nodes.find(n=>n.id===b).routeId,routeB);assert.equal(graph.nodes.find(n=>n.id===move).destinationId,target);assert.equal(graph.edges[1].distance,300);assert.equal(graph.edges[1].distanceMode,'absolute');assert.equal(graph.triggers[0].once,false);
  await page.locator('#file').setInputFiles(path.join(folder,'output.jsn'));await page.locator('#unit-task-open').click();await page.locator('#graph-edit-tab').click();await page.locator('#behavior-fit').click();await node(move).click();assert.equal(await page.locator('#node-destination').inputValue(),target);await page.locator('#behavior-cancel').click();
  await page.locator('#record-run').click();await page.waitForFunction(()=>!document.getElementById('play').disabled,{},{timeout:60000});
  await page.locator('#timeline').evaluate(el=>{el.value=100;el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#events-open').click();assert((await page.locator('#event-list').textContent()).includes('探知'));await page.locator('#events-close').click();
  const [record]=await Promise.all([page.waitForEvent('download'),page.locator('#record-save').click()]);await record.saveAs(path.join(folder,'record.jsn'));await page.locator('#file').setInputFiles(path.join(folder,'record.jsn'));await page.waitForFunction(()=>!document.getElementById('play').disabled);
  await page.setViewportSize({width:390,height:844});await page.locator('#unit-task-open').click();await page.locator('#graph-edit-tab').click();await page.locator('#behavior-fit').click();await node(move).click();await page.locator('#node-destination-edit').click();
  assert(await page.locator('#navigation-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.equal(await page.locator('#navigation-unit').inputValue(),'target');await page.locator('#navigation-cancel').click();await page.locator('#behavior-cancel').click();
  assert.deepEqual(errors,[]);
  console.log('PASS: node-first named routes and destinations, map drawing/picking, transactional cancel and Undo, resource editing and referenced deletion guards, moving-unit selection, proximity edges/events, definition/Worker/record round-trip, event history and mobile layout');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));fs.rmSync(folder,{recursive:true,force:true});}
