import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateScenario,clone} from '../src/engine.js?v=20261007-plans-23';
import {capturePlan,applyPlan,planDifferences} from '../src/plan-settings.js?v=20261007-plans-23';
import {preparePlans,planTrialSource,summarizePlans,restorePlansResult} from '../src/plans.js?v=20261007-plans-23';
import {trialScenario} from '../src/parameters.js?v=20261007-plans-23';
import {runDetection,summarizeRow} from '../src/detection.js?v=20261007-plans-23';
import {createSimulation} from '../src/recorded-engine.js?v=20261007-plans-23';
import {RECORD_MODEL} from '../src/recording.js?v=20261007-plans-23';
const s=JSON.parse(fs.readFileSync(new URL('fixtures/state-measurement.txt',import.meta.url)));
s.analysis={...s.analysis,mode:'plans',factors:[],trials:4,uncertainties:[{target:'group:group',parameter:'rate.movement.speed',distribution:'uniform',min:50,max:100}]};
s.analysis.plans={metric:'mission.time',baselineId:'base',items:[{id:'base',name:'基準',operation:capturePlan(s)}]};
const changed=clone(s);changed.behaviors[0].nodes.find(n=>n.id==='a').seconds=1;changed.groups[0].template.initial.x+=100;changed.groups[0].template.route[0].x+=500;
s.analysis.plans.items.push({id:'fast',name:'配置・経路・待機変更',operation:capturePlan(changed)});
assert(!('analysis' in s.analysis.plans.items[0].operation));assert.deepEqual(planDifferences(capturePlan(s),capturePlan(changed)),['群の配置・個数・能力','挙動・報告間隔']);
assert.equal(applyPlan(s,s.analysis.plans.items[1]).mission.deadline,s.mission.deadline);
const run=source=>{const p=preparePlans(source);return p.conditions.map(c=>{const trials=[];for(let i=0;i<p.analysis.trials;i++){const {scenario,sampled}=trialScenario(p.sources[c.id],c,p.startTrial+i),result=runDetection(createSimulation(scenario));trials.push({...result,trial:scenario.trial,sampled});}return {...summarizeRow(c.count,trials),condition:c};});};
const rows=run(s),pairs=summarizePlans(s,rows);assert.equal(pairs.length,1);assert.equal(pairs[0].delta,-2);assert.equal(pairs[0].pairs,4);
for(let i=0;i<4;i++)assert.deepEqual(rows[0].trials[i].sampled,rows[1].trials[i].sampled);
const reversed=clone(s);reversed.analysis.plans.items.reverse();assert.deepEqual(run(reversed),rows);
const replay=planTrialSource(s,rows[1].condition);assert(!replay.analysis.plans);assert(!replay.analysis.mode);assert.equal(replay.groups[0].template.initial.x,1100);
const payload={type:'SimSim-plans',version:1,model:RECORD_MODEL,source:s,rows,elapsedMs:5},restored=restorePlansResult(payload);assert.equal(restored.completed,8);assert.equal(restored.planned,8);assert.equal(restored.mode,'plans');assert.equal(summarizePlans(restored.source,restored.rows)[0].delta,-2);
const partial=clone(payload);partial.rows[1].trials.pop();assert.equal(restorePlansResult(partial).completed,7);
const tamper=clone(payload);tamper.rows[1].trials[0].sampled[0].value+=1;assert.throws(()=>restorePlansResult(tamper),/抽出値/);
const orphan=clone(payload);orphan.rows.shift();assert.throws(()=>restorePlansResult(orphan),/基準試行/);
const duplicate=clone(payload);duplicate.rows[1]=duplicate.rows[0];assert.throws(()=>restorePlansResult(duplicate),/重複/);
const mismatch=clone(s);mismatch.analysis.plans.items[1].operation.behaviors[0].nodes=mismatch.analysis.plans.items[1].operation.behaviors[0].nodes.filter(n=>n.id!=='b');assert.throws(()=>preparePlans(mismatch),/運用案/);
const none=clone(s);none.analysis.plans.items.pop();assert.throws(()=>preparePlans(none),/2件以上/);
const high=clone(s);high.analysis.trials=2000;for(let i=0;i<4;i++)high.analysis.plans.items.push({id:'extra-'+i,name:'案 '+i,operation:capturePlan(s)});assert.throws(()=>preparePlans(high),/10000/);
const nested=clone(s);nested.analysis.plans.items[0].operation.analysis={};assert.throws(()=>validateScenario(nested),/配列/);
const ids=clone(s);ids.analysis.plans.items[1].id='base';assert.throws(()=>validateScenario(ids),/ID/);
const units=clone(s);units.analysis.plans.items[1].operation.groups[0].count=-1;assert.throws(()=>validateScenario(units),/運用案/);
const missing=clone(rows);missing[1].trials[0].success=false;missing[1].trials[0].successTime=null;assert.equal(summarizePlans(s,missing)[0].pairs,3);assert.equal(summarizePlans(s,missing)[0].changedMissing,1);
console.log('PASS: multi-setting plans, common criteria/environment/RNG, reorder, paired timing/missing values, exact replay, partial archive integrity, schema and limits');
