import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {restorePlansResult,summarizePlans} from '../src/plans.js?v=20261009-authoring-display-27';
import {restoreRecording} from '../src/recorded-engine.js?v=20261009-authoring-display-27';
const {chromium}=await import(process.env.SIMSIM_PLAYWRIGHT??'playwright');
const root=path.resolve(process.env.SIMSIM_WEB_ROOT??fileURLToPath(new URL('..',import.meta.url))),folder=fs.mkdtempSync(path.join(os.tmpdir(),'simsim-sensitivity-'));
const server=http.createServer((req,res)=>{
  const pathname=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));
  if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}
  res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; worker-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:");
  res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'text/plain');
  try{res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end('Not found');}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{
  browser=await chromium.launch({headless:true,...(process.env.SIMSIM_BROWSER_EXECUTABLE?{executablePath:process.env.SIMSIM_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.getElementById('recording-info').textContent.includes('未計算'));
  const source=JSON.parse(fs.readFileSync(new URL('fixtures/state-measurement.txt',import.meta.url)));delete source.mission;source.analysis.factors=[];
  const input=path.join(folder,'input.txt');fs.writeFileSync(input,JSON.stringify(source));await page.locator('#file').setInputFiles(input);
  assert.equal(await page.locator('.plan-toolbar #plan-select').count(),1);assert.equal(await page.locator('#analysis-dialog #plan-select').count(),0);
  await page.locator('#analysis-open').click();assert.equal(await page.locator('#mission-enabled').count(),0);await page.locator('#mission-state').selectOption('b');await page.locator('#analysis-run').click();await page.waitForFunction(()=>!document.getElementById('analysis-run').disabled&&document.querySelectorAll('#analysis-rows tr').length===1);await page.locator('#analysis-close').click();
  const nameDialog=async name=>{await page.locator('#plan-name').fill(name);await page.locator('#plan-name-submit').click();assert(await page.locator('#plan-name-dialog').isHidden());};
  const menu=async id=>{await page.locator('#plan-menu > summary').click();await page.locator('#'+id).click();};
  const waitNode=async(value)=>{await page.locator('.unit-item[data-id="group__1"]').click();await page.locator('#unit-task-open').click();await page.locator('#graph-edit-tab').click();await page.locator('#behavior-fit').click();await page.locator('#behavior-canvas [data-node="a"] > rect:first-child').click();if(value!==undefined){await page.locator('#node-value').fill(String(value));await page.locator('#node-value').press('Tab');await page.locator('#behavior-apply').click();}else{const n=Number(await page.locator('#node-value').inputValue());await page.locator('#behavior-cancel').click();return n;}};
  const downloadScenario=async name=>{const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);const p=path.join(folder,name);await d.saveAs(p);return p;};
  await page.locator('#plan-save').click();await nameDialog('A：待機3秒');assert.equal(await page.locator('#plan-select').inputValue(),'plan-1');assert.equal(await page.locator('#plan-save').textContent(),'更新');assert(await page.locator('#plan-save').isDisabled());
  await waitNode(1);assert((await page.locator('#plan-current').textContent()).includes('未更新'));await menu('plan-new');await nameDialog('B：待機1秒');assert.equal(await page.locator('#plan-select').inputValue(),'plan-2');
  // B gains a unit, and its deferred editing stays isolated from A.
  await page.locator('#viewtop').click();await page.locator('#template').selectOption('surface');await page.locator('#add').click();const box=await page.locator('#map').boundingBox();await page.locator('#map').click({position:{x:box.width*.65,y:box.height*.55}});await page.waitForFunction(()=>document.getElementById('unit-count').textContent==='4');
  await page.locator('#plan-select').selectOption('plan-1');assert.equal(await page.locator('#unit-count').textContent(),'3');assert.equal(await waitNode(),1);await waitNode(8);
  await page.locator('#plan-select').selectOption('plan-2');assert.equal(await page.locator('#unit-count').textContent(),'4');assert.equal(await waitNode(),1);assert((await page.locator('#plan-select').textContent()).includes('未更新'));
  const draftFile=await downloadScenario('drafts.txt'),draft=JSON.parse(fs.readFileSync(draftFile));assert.equal(draft.analysis.plans.items[0].operation.behaviors[0].nodes[0].seconds,3);assert.equal(draft.analysis.plans.items[1].operation.units.length,1);assert.equal(draft.analysis.plans.editor.drafts.find(d=>d.id==='plan-1').operation.behaviors[0].nodes[0].seconds,8);
  await page.locator('#file').setInputFiles(draftFile);await page.waitForFunction(()=>document.getElementById('file').value==='');await page.locator('#plan-select').selectOption('plan-1');assert.equal(await waitNode(),8);await page.locator('#plan-select').selectOption('plan-2');assert.equal(await page.locator('#unit-count').textContent(),'4');await page.locator('#plan-save').click();assert(await page.locator('#plan-save').isDisabled());
  await menu('plan-rename');await nameDialog('B：増員＋待機1秒');assert((await page.locator('#plan-select').textContent()).includes('増員'));
  await page.locator('#analysis-open').click();assert(await page.locator('#plans-editor').isVisible());assert(await page.locator('#comparison-editor').isHidden());assert((await page.locator('#plan-analysis-note').textContent()).includes('A：待機3秒'));await page.locator('#plan-metric').selectOption('mission.time');await page.locator('#analysis-run').click();await page.waitForFunction(()=>!document.getElementById('analysis-run').disabled&&document.querySelectorAll('#plan-result-rows tr').length===1);assert((await page.locator('#plan-result-rows').textContent()).includes('-2秒'));assert.equal(await page.locator('#analysis-rows tr').count(),2);
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#analysis-export').click()]);const file=path.join(folder,'plans.txt');await download.saveAs(file);const restored=restorePlansResult(JSON.parse(fs.readFileSync(file)));assert.equal(restored.completed,4);assert.equal(summarizePlans(restored.source,restored.rows)[0].delta,-2);
  await page.locator('#plan-trial').selectOption('1');await page.locator('#plan-replay-changed').click();await page.waitForFunction(()=>!document.getElementById('play').disabled);assert(await page.locator('#plan-save').isDisabled());assert((await page.locator('#plan-current').textContent()).includes('再生中'));const [changedDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#record-save').click()]);const recordFile=path.join(folder,'record.txt');await changedDownload.saveAs(recordFile);const changed=restoreRecording(JSON.parse(fs.readFileSync(recordFile)));assert.equal(changed.source.trial,1);assert.equal(changed.result.successTime,1);
  await page.locator('#analysis-open').click();await page.locator('#plan-replay-base').click();await page.waitForFunction(()=>!document.getElementById('play').disabled);const [baseDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#record-save').click()]);await baseDownload.saveAs(recordFile);const base=restoreRecording(JSON.parse(fs.readFileSync(recordFile)));assert.equal(base.result.successTime,3);
  // A normal-screen selection exits replay, restoring the author's deferred edits.
  await page.locator('#plan-select').selectOption('plan-1');assert.equal(await waitNode(),8);assert.equal(await page.locator('#authoring-toggle').getAttribute('aria-pressed'),'true');assert(!await page.locator('#analysis-dialog').isVisible());
  await menu('plan-delete');assert.equal(await page.locator('#plan-list tr').count(),1);assert((await page.locator('#plan-current').textContent()).includes('未保存'));assert.equal(await waitNode(),8);await page.locator('#undo').click();assert.equal(await page.locator('#plan-list tr').count(),2);
  await page.locator('#file').setInputFiles(file);await page.waitForFunction(()=>document.getElementById('analysis-dialog').open||document.getElementById('error-dialog').open);assert(!await page.locator('#error-dialog').isVisible());assert((await page.locator('#analysis-progress').textContent()).includes('再計算なし'));await page.locator('#plan-baseline').selectOption('plan-2');await page.locator('#analysis-run').click();await page.waitForFunction(()=>!document.getElementById('analysis-run').disabled&&document.querySelectorAll('#plan-result-rows tr').length===1);assert((await page.locator('#plan-result-rows').textContent()).includes('+2秒'));await page.locator('#analysis-close').click();
  await page.setViewportSize({width:1200,height:900});await page.locator('#plan-menu > summary').click();const popup=await page.locator('#plan-menu > div').boundingBox(),panel=await page.locator('.main-panel').boundingBox();assert(popup.x>=panel.x&&popup.x+popup.width<=panel.x+panel.width);await page.locator('#plan-menu > summary').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  if(process.env.SIMSIM_PLAN_SWITCH_SCREENSHOT)await page.screenshot({path:process.env.SIMSIM_PLAN_SWITCH_SCREENSHOT});
  await page.locator('#file').setInputFiles(path.resolve(new URL('fixtures/legacy/plans-demo.txt',import.meta.url).pathname));await page.waitForFunction(()=>document.getElementById('title').value==='運用案比較：配置・経路・報告周期');assert.equal(await page.locator('#plan-select').inputValue(),'base');await page.locator('#plan-select').selectOption('deployment');assert(!await page.locator('#analysis-dialog').isVisible());await page.locator('#analysis-open').click();await page.locator('#analysis-run').click();await page.waitForFunction(()=>!document.getElementById('analysis-run').disabled&&document.querySelectorAll('#plan-result-rows tr').length===2);
  console.log('PASS: normal-screen plan save/switch/update/rename/delete/Undo, isolated additional unit, per-plan deferred editing and file round-trip, saved-only paired analysis, replay safety and return to editing, archives, sample and 1200px layout');
}finally{await browser?.close();await new Promise(r=>server.close(r));fs.rmSync(folder,{recursive:true,force:true});}
