import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Simulation,clone,validateScenario} from '../src/engine.js?v=20261007-observed-position-21';
import {random01,noiseVector} from '../src/random.js?v=20261007-observed-position-21';
const terrain={columns:21,rows:5,spacing:500,origin:{x:0,y:0},seaLevel:0,elevations:Array(105).fill(-500)};
const unit={id:'uuv',name:'UUV',domain:'subsurface',faction:'friendly',manned:false,speed:10,initial:{x:1000,y:1000,z:-100},route:[{x:9000,y:1000,z:-100}],routeMode:'once',motion:{horizontal:120,vertical:20,scale:1000,startDelay:300,speedVariation:.2}};
const source={version:1,title:'Random test',unitsSystem:'SI',duration:3600,terrain,seed:'test-seed',trial:8,units:[unit]};
const a=new Simulation(source),b=new Simulation(clone(source));
assert.deepEqual(a.evaluate(1234),b.evaluate(1234));
const expected=a.evaluate(567);for(let t=0;t<2000;t+=.37)a.evaluate(t);
assert.deepEqual(a.evaluate(567),expected,'Replay must not depend on evaluation frequency/order');
const changed=clone(source);changed.trial++;
assert.notDeepEqual(a.routePoints('uuv'),new Simulation(changed).routePoints('uuv'));
changed.trial=source.trial;changed.seed='other';assert.notDeepEqual(a.evaluate(800),new Simulation(changed).evaluate(800));
const nodes=a.routePoints('uuv');assert.deepEqual({...nodes[0],d:undefined},{...unit.initial,d:undefined});
assert.deepEqual({x:nodes.at(-1).x,y:nodes.at(-1).y,z:nodes.at(-1).z},unit.route[0]);
assert(nodes.some(p=>Math.abs(p.y-1000)>1));assert(nodes.every(p=>Math.abs(p.y-1000)<=120 && Math.abs(p.z+100)<=20));
assert(nodes.at(-1).d>=8000);
const state=a.evaluate(0).units[0];assert(state.actualSpeed>=8&&state.actualSpeed<=12);assert(state.startDelay>=0&&state.startDelay<=300);
assert.equal(a.evaluate(state.startDelay/2).units[0].status,'waiting');
assert(Math.abs(a.evaluate(400).units[0].distance-a.evaluate(390).units[0].distance-state.actualSpeed*10)<1e-8);
const disabled=clone(source);disabled.units[0].motion={horizontal:0,vertical:0,commonHorizontal:0};
const plain=clone(disabled);delete plain.units[0].motion;
assert.deepEqual(new Simulation(disabled).evaluate(40),new Simulation(plain).evaluate(40));
const surface=clone(source);surface.units[0].domain='surface';assert(new Simulation(surface).routePoints('uuv').every(p=>p.z===0));
const ping=clone(source);ping.units[0].routeMode='pingpong';ping.units[0].motion.startDelay=0;ping.units[0].motion.speedVariation=0;
const ps=new Simulation(ping),outLength=ps.paths.get('uuv').length/2;
assert(Math.hypot(ps.evaluate(outLength/10*2).units[0].position.x-1000,ps.evaluate(outLength/10*2).units[0].position.y-1000)<1e-7);
const grouped=clone(source);grouped.units=[];grouped.groups=[{id:'group',name:'Group',count:1000,placement:'random',width:600,height:600,template:unit}];
const start=performance.now(),large=new Simulation(grouped),compileMs=performance.now()-start;
assert.equal(large.scenario.units.length,1000);assert(large.evaluate(3600).units.every(s=>!s.error));
const small=clone(grouped);small.groups[0].count=100;
const ss=new Simulation(small);assert.deepEqual(large.evaluate(500).units.slice(0,100),ss.evaluate(500).units,'Random deployment retains existing member streams when count changes');
const reordered=clone(source);reordered.units.push({...clone(unit),id:'other',name:'other'});
const reverse=clone(reordered);reverse.units.reverse();
assert.deepEqual(new Simulation(reordered).evaluate(500).units[0],new Simulation(reverse).evaluate(500).units[1]);
const common=clone(small);common.groups[0].count=2;common.groups[0].template.motion={horizontal:0,vertical:0,commonHorizontal:150,scale:1000};
const shared=new Simulation(common),[one,two]=shared.scenario.units;
const p1=shared.routePoints(one.id),p2=shared.routePoints(two.id);
assert.equal(p1.length,p2.length);
for(let i=0;i<p1.length;i++){assert(Math.abs((p1[i].x-one.initial.x)-(p2[i].x-two.initial.x))<1e-8);assert(Math.abs((p1[i].y-one.initial.y)-(p2[i].y-two.initial.y))<1e-8);}
const invalid=clone(source);invalid.units[0].motion.scale=0;assert.throws(()=>validateScenario(invalid),/scale/);
const over=clone(grouped);over.groups[0].count=2001;assert.throws(()=>validateScenario(over),/count/);
const dup=clone(grouped);dup.units=[{...clone(unit),id:'group__1'}];assert.throws(()=>validateScenario(dup),/重複/);
const blocked=clone(source);blocked.units[0].initial.z=-499;assert.equal(new Simulation(blocked).evaluate(0).units[0].status,'blocked');
const drift=clone(source);drift.units[0].initial.y=5;drift.units[0].route[0].y=5;drift.units[0].motion.horizontal=1000;drift.units[0].motion.vertical=0;
const driftSim=new Simulation(drift);assert.equal(driftSim.evaluate(3600).units[0].status,'blocked','Invalid noise paths must be kept as failures');
const cap=new Simulation(plain);cap.nodeCount=2000000;assert.throws(()=>cap.compile(plain.units[0]),/200万/);
for(let i=0;i<100;i++){const v=noiseVector('noise',i*71,1000);assert(Math.hypot(v[0],v[1])<=1+1e-12);assert(Math.abs(v[2])<=1);assert(random01('seed'+i)>=0&&random01('seed'+i)<1);}
assert.deepEqual(validateScenario(JSON.parse(JSON.stringify(grouped))),grouped);
const sample=JSON.parse(fs.readFileSync(new URL('../data/group-demo.txt',import.meta.url),'utf8'));
const demo=new Simulation(sample);assert.equal(demo.evaluate(0).units.length,1007);
assert(demo.evaluate(3600).units.every(s=>!s.error));
const evalStart=performance.now();for(let t=0;t<3600;t+=10)large.evaluate(t);
console.log(JSON.stringify({status:'PASS',checks:'seed/trial replay, stream independence, speed/delay, bounded smooth paths, group common offsets, count sweeps, terrain failures, import validation, 1000-unit sample',compileMs:Math.round(compileMs),evaluations:360000,evaluateMs:Math.round(performance.now()-evalStart)}));
