import {createSimulation,sharedSteps} from '../src/recorded-engine.js?v=20261006-label-rail-15';
import {importScenario} from '../src/scenario-import.js?v=20261006-label-rail-15';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Simulation,clone} from '../src/engine.js?v=20261006-label-rail-15';
import {runDetection,prepareAnalysis,summarizeRow,restoreAnalysisResult,detectionSteps} from '../src/detection.js?v=20261006-label-rail-15';
import {trialScenario} from '../src/parameters.js?v=20261006-label-rail-15';
const source=JSON.parse(fs.readFileSync(new URL('../data/response-demo.txt',import.meta.url)));
const {conditions}=prepareAnalysis(source),rows=[],start=performance.now();assert.equal(conditions.length,12);
for(const condition of conditions){const trials=[];for(let trial=0;trial<source.analysis.trials;trial++){const sample=trialScenario(source,condition,trial),model=createSimulation(sample.scenario),r=runDetection(model);assert.equal(r.invalidUnits,0);assert.equal(r.constrainedPaths,0);if(r.success){const firstReceived=r.actionEvents.find(e=>e.type==='received'&&e.unitId==='response-uav'),departed=r.actionEvents.find(e=>e.type==='departed'),arrived=r.actionEvents.find(e=>e.type==='arrived'&&e.unitId==='response-uav');assert(firstReceived);assert(departed.time>=firstReceived.time+180);assert.equal(arrived.time,r.successTime);assert(model.states.find(s=>s.unit.id==='response-uav').distance>0);}trials.push({...r,trial,sampled:sample.sampled});}rows.push({...summarizeRow(condition.count,trials),condition});}
// Extra observers or longer ranges preserve earlier reports with the same fixed tick RNG streams.
for(const a of rows)for(const b of rows){const [n1,r1]=a.condition.settings.map(s=>s.value),[n2,r2]=b.condition.settings.map(s=>s.value);if(n2>=n1&&r2>=r1)for(let i=0;i<a.trials.length;i++)if(a.trials[i].success){assert(b.trials[i].success);assert(b.trials[i].successTime<=a.trials[i].successTime);}}
assert(rows[0].rate<rows.at(-1).rate);assert(rows.some(r=>r.trials.some(t=>t.detectedCount>0&&!t.success)),'The sample distinguishes detection from a completed response');
const payload={type:'SimSim-analysis',version:5,model:'trigger-behavior-v3',source:importScenario(source),rows};assert.equal(restoreAnalysisResult(payload).completed,600);
const selected=rows.at(-1).trials.find(t=>t.success),sample=trialScenario(source,rows.at(-1).condition,selected.trial).scenario,full=createSimulation(sample),gen=detectionSteps(full,full.scenario.mission,10,{horizon:sample.duration,record:true});let state=gen.next();while(!state.done)state=gen.next();assert.equal(state.value.successTime,selected.successTime,'Full playback and deadline-limited analysis agree');
const noLink=clone(sample);noLink.groups[0].template.communication.enabled=false;const noLinkModel=createSimulation(noLink);assert.equal(runDetection(noLinkModel).success,false);assert.equal(noLinkModel.states.find(u=>u.unit.id==='response-uav').status,'standby');
console.log(JSON.stringify({status:'PASS',checks:'fictional detect-relay-prepare-depart-arrive sample, 600 trials, paired quantity/range streams, deadline/playback agreement, disabled communication, result round-trip',elapsedMs:Math.round(performance.now()-start),rows:rows.map(r=>({count:r.condition.settings[0].value,range:r.condition.settings[1].value,detected:r.trials.filter(t=>t.detectedCount>0).length,arrived:r.successes}))}));
