/* SimSim portable 20261007-plan-switch-25-0e9cff0967fc. Generated by npm run build:portable. */
(()=>{var Ht="20261007-plan-switch-25",ft="20261007-plan-switch-25-0e9cff0967fc",wn="v"+Ht.replace(/^(\d{4})(\d{2})(\d{2})-.*-(\d+)$/,"$1.$2.$3.$4");var Vt={number:"数値",route:"経路",destination:"目的地",unit:"単体ユニット"},ht={routeId:"route",destinationId:"destination",receiverId:"unit",seconds:"number",speedFraction:"\
number",distance:"number"},ie=t=>!!t&&typeof t=="object"&&!Array.isArray(t)&&Object.keys(t).length===1&&typeof t.$param=="string";function Se(t,e,n){if(!ie(t))return t;let i=Array.
isArray(e?.parameters)?e.parameters.find(r=>r?.id===t.$param):null;return Object.hasOwn(n?.parameters??{},t.$param)?n.parameters[t.$param]:i?.default}function Ae(t,e){if(!t)return t;
let n=i=>i&&typeof i=="object"?Object.fromEntries(Object.entries(i).map(([r,o])=>[r,Se(o,t,e)])):i;return{...t,nodes:t.nodes.map(n),edges:t.edges.map(n),triggers:(t.triggers??[]).map(
n)}}function Ge(t,e,n){if(!Array.isArray(e.nodes)||!Array.isArray(e.edges)||e.triggers!==void 0&&!Array.isArray(e.triggers))return["挙動のノード・条件の形式が不正です。"];
let i=[],r=e.parameters??[],o=new Set;if(!Array.isArray(r)||r.length>64)return["担当時に指定する値は最大64件の配列です。"];let s=(a,d)=>a.type==="number"?Number.
isFinite(d):typeof d=="string"&&(a.type==="route"?t.routes:a.type==="destination"?t.destinations:t.units)?.some?.(c=>c.id===d);for(let a of r){if(!a||!/^[a-zA-Z0-9_-]{1,80}$/.test(
a.id??"")||o.has(a.id)||typeof a.name!="string"||!a.name.trim()||a.name.length>120||!Object.hasOwn(Vt,a.type)){i.push("担当値のID・名前・種類が不正または重複しています。");
continue}o.add(a.id),a.unit!==void 0&&(a.type!=="number"||!["s","m","ratio"].includes(a.unit))&&i.push("担当値の単位が不正です。"),Object.hasOwn(a,"default")&&!s(a,a.default)&&
i.push("担当値「"+a.name+"」の既定値が不正です。"),n&&!s(a,Se({$param:a.id},e,n))&&i.push("タスク「"+n.name+"」で「"+a.name+"」を指定してください。")}
for(let a of[...e.nodes,...e.edges,...e.triggers??[]].filter(d=>d&&typeof d=="object"))for(let[d,c]of Object.entries(a))if(c&&typeof c=="object"&&(Object.hasOwn(c,"$param")||ht[d])){
let l=ie(c)?r.find(g=>g?.id===c.$param):null,p={seconds:"s",distance:"m",speedFraction:"ratio"}[d];(!l||l.type!==ht[d]||p&&l.unit&&l.unit!==p)&&i.push("担当値の参照・種類・単位が不正です: "+
d)}return n?.parameters!==void 0&&(!n.parameters||typeof n.parameters!="object"||Array.isArray(n.parameters)||Object.keys(n.parameters).some(a=>!o.has(a)))&&i.push("タスクの担当値に未定義の項目が\
あります。"),i}var mt=Number.isFinite,X=class{constructor(e){this.data=e,this.minX=e.origin.x,this.minY=e.origin.y,this.maxX=this.minX+(e.columns-1)*e.spacing,this.maxY=this.minY+(e.rows-1)*(e.spacingY??
e.spacing),this.cellSize=Math.min(e.spacing,e.spacingY??e.spacing)}contains(e,n){return mt(e)&&mt(n)&&e>=this.minX&&e<=this.maxX&&n>=this.minY&&n<=this.maxY}height(e,n){if(!this.contains(
e,n))return null;let i=this.data,r=(e-this.minX)/i.spacing,o=(n-this.minY)/(i.spacingY??i.spacing),s=Math.min(i.columns-2,Math.floor(r)),a=Math.min(i.rows-2,Math.floor(o)),d=r-s,c=o-
a,l=(p,g)=>i.elevations[(a+g)*i.columns+s+p];return(l(0,0)*(1-d)+l(1,0)*d)*(1-c)+(l(0,1)*(1-d)+l(1,1)*d)*c}project(e,n){let i={...e},r=this.height(i.x,i.y),o=this.data.seaLevel;return r===
null?{point:i,error:"地形データの範囲外です"}:n==="ground"&&(i.z=r,r<=o)?{point:i,error:"地上ユニットは陸上に配置してください"}:n==="surface"&&(i.z=o,r>
o-5)?{point:i,error:"水上ユニットには5m以上の水深が必要です"}:n==="subsurface"&&(i.z>o-1||i.z<r+5||r>=o)?{point:i,error:"水中ユニットは海面下かつ海底から5m以上離してください"}:
n==="air"&&i.z<=Math.max(r,o)+10?{point:i,error:"空中ユニットは地表・海面から10mより高くしてください"}:{point:i,error:null}}};var Gt=["ground","surface","subsurface","air"],Ne=Number.isFinite,Pe=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n}),fe=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z);
function ve(t){return!t||typeof t!="object"||Array.isArray(t)||!Gt.includes(t.domain)||t.clearance!==void 0&&(!Ne(t.clearance)||t.clearance<0||t.clearance>1e4)?["経路検査の領域・地表／海底からの余裕\
（0～10000m）が不正です。"]:[]}function We(t,e="once"){let n=ve(t);return!t||n.length||((!Array.isArray(t.via)||t.via.length<(e==="loop"?3:2)||t.via.length>100||t.via.some(
i=>!i||!["x","y"].every(r=>Ne(i[r])&&Math.abs(i[r])<=1e6)))&&n.push("自動生成の必須経由地点は2～100点（周回は3点以上）の東西・南北座標です。"),["ai\
r","subsurface"].includes(t.domain)&&(!Ne(t.height)||t.height<-1e6||t.height>1e6)&&n.push("自動生成する高度・深度のz座標を指定してください。"),t.height!==void 0&&
(!Ne(t.height)||Math.abs(t.height)>1e6)&&n.push("高度・深度は数値で指定してください。")),n}function Kt(t,e,n){let i=t.height(e.x,e.y),r=t.data.seaLevel;return i===
null?-1/0:n==="ground"?i-r:n==="surface"?r-i-5:n==="subsurface"?Math.min(e.z-i-5,r-e.z-1):e.z-Math.max(i,r)-10}function ye(t,e,n){let i=Kt(t,e,n.domain),r=n.clearance??0;if(i<r-1e-7||
["ground","air"].includes(n.domain)&&i<=0){let o=t.project(e,n.domain);return{point:{...e},reason:o.error??"地表・海底／海面からの余裕 "+r+"mを満たしていません。",
margin:i}}return null}function Ee(t,e,n,i){let r=t instanceof X?t:new X(t),o=ye(r,e,i),s=ye(r,n,i);if(o)return o;if(s)return s;let a=[0,1],d=r.data;for(let[c,l,p,g]of[["x",d.columns,
d.spacing,d.origin.x],["y",d.rows,d.spacingY??d.spacing,d.origin.y]]){let m=n[c]-e[c];if(!m)continue;let b=Math.min(e[c],n[c]),w=Math.max(e[c],n[c]);for(let x=Math.max(1,Math.ceil(
(b-g)/p));x<=Math.min(l-2,Math.floor((w-g)/p));x++){let z=(g+x*p-e[c])/m;z>0&&z<1&&a.push(z)}}a.sort((c,l)=>c-l);for(let c=1;c<a.length;c++){let l=a[c-1],p=a[c];if(p-l<1e-12)continue;
let g=Pe(e,n,l),m=Pe(e,n,p),b=Pe(e,n,(l+p)/2),w=r.height(g.x,g.y),x=r.height(m.x,m.y),z=r.height(b.x,b.y),I=2*(w+x-2*z),A=x-w-I,j=[0,1];if(Math.abs(I)>1e-12)for(let D of[-A,m.z-g.z-
A]){let f=D/(2*I);f>0&&f<1&&j.push(f)}for(let D of j){let f=ye(r,Pe(e,n,l+(p-l)*D),i);if(f)return f}}return null}function Wt(t,e,n,{loop:i=!1}={}){let r=ve(n);if(r.length)throw Error(
r[0]);let o=t instanceof X?t:new X(t),s=[];if(!Array.isArray(e)||!e.length)return{ok:!0,issues:s};if(e.length===1){let a=ye(o,e[0],n);a&&s.push({segment:0,from:e[0],to:e[0],...a})}
for(let a=1;a<e.length+(i?1:0);a++){let d=e[a-1],c=e[a%e.length],l=Ee(o,d,c,n);l&&s.push({segment:a-1,from:{...d},to:{...c},...l})}return{ok:!s.length,issues:s}}var Ke=class{constructor(){
this.values=[]}push(e){let n=this.values.length;for(this.values.push(e);n;){let i=n-1>>1;if(this.values[i].score<=e.score)break;this.values[n]=this.values[i],n=i}this.values[n]=e}pop(){
let e=this.values[0],n=this.values.pop();if(this.values.length){let i=0;for(;i*2+1<this.values.length;){let r=i*2+1;if(r+1<this.values.length&&this.values[r+1].score<this.values[r].
score&&r++,this.values[r].score>=n.score)break;this.values[i]=this.values[r],i=r}this.values[i]=n}return e}};function Xt(t,e,n,i,r){if(!Ee(t,e,n,i))return[{...e},{...n}];let{nx:o,ny:s,
sx:a,sy:d,height:c}=r,l=o*s,p=new Array(l),g=new Float64Array(l).fill(1/0),m=new Int32Array(l).fill(-1),b=new Uint8Array(l),w=new Ke,x=v=>{if(p[v]!==void 0)return p[v];let R={x:t.minX+
v%o*a,y:t.minY+Math.floor(v/o)*d,z:c},H=t.project(R,i.domain);return p[v]=ye(t,R,i)?null:H.point},z=v=>{let R=Math.round((v.x-t.minX)/a),H=Math.round((v.y-t.minY)/d),V=[];for(let B=-2;B<=
2;B++)for(let J=-2;J<=2;J++){let $=R+J,Y=H+B;if($<0||$>=o||Y<0||Y>=s)continue;let h=Y*o+$,S=x(h);S&&!Ee(t,v,S,i)&&V.push(h)}return V},I=new Set(z(n));if(!I.size)throw Error("目的地付近に\
接続できる通行可能な経路がありません。地点・高度／深度・余裕を調整してください。");for(let v of z(e))g[v]=fe(e,x(v)),w.push({i:v,score:g[v]+
fe(x(v),n)});let A=-1;for(;w.values.length;){let{i:v}=w.pop();if(b[v])continue;if(b[v]=1,I.has(v)){A=v;break}let R=v%o,H=Math.floor(v/o),V=x(v);for(let B=-1;B<=1;B++)for(let J=-1;J<=
1;J++){if(!J&&!B)continue;let $=R+J,Y=H+B;if($<0||$>=o||Y<0||Y>=s)continue;let h=Y*o+$;if(b[h])continue;let S=x(h);if(!S)continue;let T=g[v]+fe(V,S);T>=g[h]||Ee(t,V,S,i)||(m[h]=v,g[h]=
T,w.push({i:h,score:T+fe(S,n)}))}}if(A<0)throw Error("この領域・高度／深度・余裕では経路を生成できませんでした。通れる海峡・陸地がつながっているか、必須地点を確認してください。");
let j=[{...n}];for(let v=A;v>=0;v=m[v])j.push(x(v));j.push({...e}),j.reverse();let D=[j[0]],f=0;for(;f<j.length-1;){let v=j.length-1;for(;v>f+1&&Ee(t,j[f],j[v],i);)v--;D.push(j[v]),
f=v}return D}function Zt(t,e,{mode:n="once"}={}){let i=We(e,n);if(i.length)throw Error(i.join(`
`));let r=t instanceof X?t:new X(t),o={domain:e.domain,clearance:e.clearance??0},s=e.height??r.data.seaLevel,a=e.via.map((x,z)=>{let I={x:x.x,y:x.y,z:s},A=ye(r,I,o);if(A)throw Error(
"必須地点 "+(z+1)+"："+A.reason);return r.project(I,e.domain).point});if(a.every(x=>fe(x,a[0])<1e-6))throw Error("異なる出発地点・目的地を指定してください。");
let d=r.maxX-r.minX,c=r.maxY-r.minY,l=Math.max(Math.min(r.data.spacing,r.data.spacingY??r.data.spacing)/4,Math.max(d,c)/256),p=Math.max(2,Math.ceil(d/l)+1),g=Math.max(2,Math.ceil(c/
l)+1),m={nx:p,ny:g,sx:d/(p-1),sy:c/(g-1),height:s},b=[a[0]];for(let x=1;x<a.length+(n==="loop"?1:0);x++)fe(b.at(-1),a[x%a.length])<1e-8||b.push(...Xt(r,b.at(-1),a[x%a.length],o,m).
slice(1));if(n==="loop"&&fe(b[0],b.at(-1))<1e-6&&b.pop(),b.length>500)throw Error("生成経路が500点を超えました。必須地点を減らしてください。");if(b.length<
(n==="loop"?3:2))throw Error("周回は異なる必須地点を3点以上指定してください。");if(!Wt(r,b,o,{loop:n==="loop"}).ok)throw Error("生成経路の検査に失敗しました。条件を調整してください。");
return{points:b,navigation:o}}function gt(t){for(let e of t.routes??[])if(e.generate)try{let n=Zt(t.terrain,e.generate,{mode:e.mode??"once"});Object.assign(e,n),delete e.generate}catch(n){
throw Error("経路「"+e.name+"」："+n.message)}return t}function Re(t,e,n,i){let r=t.behaviors?.find(a=>a.id===e?.behaviorId),o=Se(n?.routeId,r,e),s=o?t.routes?.find(a=>a.id===o):null;return{id:s?.id??"default",points:s?.points??e?.route??
[i.initial,...i.route],mode:n?.kind==="patrol"?"loop":s?.mode??e?.routeMode??i.routeMode}}function se(t,e,n){let i=Se(n?.destinationId,t.behaviors?.find(r=>r.id===e?.behaviorId),e);
return i?t.destinations?.find(r=>r.id===i):e?.base?{kind:"point",point:e.base}:null}function ae(t){let e=t.when??t.event;return e==="near"?[e,t.destinationId,t.distance,t.distanceMode??
"absolute"].map(n=>ie(n)?JSON.stringify(n):n).join("|"):e==="time"?e+"|"+(ie(t.seconds)?JSON.stringify(t.seconds):t.seconds):e}var yt=(t,e,n="absolute")=>Math.hypot(t.x-e.x,t.y-e.y,
n==="horizontal"?0:t.z-e.z);function vt(t){let e=[],n=(r,o,s)=>Number.isFinite(r)&&r>=o&&r<=s,i=r=>r&&["x","y","z"].every(o=>n(r[o],-1e6,1e6));for(let[r,o]of[["routes",128],["desti\
nations",256]]){let s=t[r]??[],a=new Set;if(!Array.isArray(s)||s.length>o){e.push(r==="routes"?"経路は最大128件の配列です。":"目的地は最大256件の配列です。");
continue}for(let d of s){if(!d||!/^[a-zA-Z0-9_-]{1,80}$/.test(d.id??"")||a.has(d.id)||typeof d.name!="string"||!d.name.trim()||d.name.length>120){e.push("経路・目的地のIDまたは名前が不正・重複しています。");
continue}a.add(d.id),r==="routes"?(d.generate!==void 0?(d.points!==void 0&&e.push("経路にはpointsかgenerateのどちらか一方を指定してください。"),e.push(...We(d.
generate,d.mode??"once"))):(!Array.isArray(d.points)||d.points.length<2||d.points.length>500||d.points.some(c=>!i(c)))&&e.push("経路は2～500点の座標で指定してください。"),
d.navigation!==void 0&&e.push(...ve(d.navigation)),["once","loop","pingpong"].includes(d.mode??"once")||e.push("経路の繰り返し方式が不正です。")):d.kind==="point"?i(
d.point)||e.push("目的地の地点座標が不正です。"):d.kind==="unit"?t.units?.some(c=>c.id===d.unitId)||e.push("目的地のユニットがありません。"):d.kind!=="\
received"&&e.push("目的地は地点・ユニット・取得した目標位置（探知・受信）を指定してください。")}}return e}function Xe(t,e,n=!1){let i=[];return!(n&&
ie(e.destinationId))&&(!Array.isArray(t.destinations)||!t.destinations.some(r=>r?.id===e.destinationId))&&i.push("接近条件の目的地を選択してください。"),!(n&&ie(e.
distance))&&(!Number.isFinite(e.distance)||e.distance<0||e.distance>1e6)&&i.push("接近距離は0～1000000mです。"),["horizontal","absolute"].includes(e.distanceMode??"absolut\
e")||i.push("距離の種類は水平距離または絶対距離です。"),i}var Qt={follow:"経路を進む",patrol:"協調して周回",signal:"情報を待つ",report:"報告",move:"目的に向かって進む",wait:"時間待ち",stop:"終了"},en={received:"\
情報受信",time:"時間経過",detected:"対象探知",near:"指定距離まで近づく"};function bt(t){return t.initial??t.entry??(Array.isArray(t.triggers)?t.triggers.find(e=>e?.
event==="scenarioStart")?.to:void 0)}function Qe(t){return(t.triggers??[]).filter(e=>e?.event!=="scenarioStart")}function xt(t){for(let e of t.behaviors??[]){let n=bt(e);n!==void 0&&
(e.initial=n),e.triggers=Qe(e);for(let i of e.triggers)delete i.policy;for(let i of e.nodes)i.kind==="return"&&(i.kind="move");delete e.entry}return t}var tn={follow:["detected","received","arrived","near"],patrol:["detected","received","near"],signal:["received","detected","near"],report:["sent","sendFailed","near"],move:["arriv\
ed","received","detected","near"],return:["arrived","received","detected","near"],wait:["elapsed","received","detected","near"],stop:[]};var Z=(t,e,n)=>Number.isFinite(t)&&t>=e&&t<=n,Ze=t=>t&&["x","y","z"].every(e=>Z(t[e],-1e6,1e6));function et(t,e=!1){let n=vt(t),i=t.behaviors??[],r=t.behaviorAssignments??[];if(!Array.
isArray(i)||i.length>50)return["挙動は最大50件の配列です。"];if(!Array.isArray(r)||r.length>100)return["タスクは最大100件の配列です。"];let o=Array.isArray(
t.routes)?t.routes:[],s=Array.isArray(t.destinations)?t.destinations:[],a=new Set,d=new Set,c=new Set;for(let m of i){if(!m||!/^[a-zA-Z0-9_-]{1,80}$/.test(m.id??"")||a.has(m.id)){n.
push("挙動IDが不正または重複しています。");continue}if(a.add(m.id),(typeof m.name!="string"||!m.name.trim()||m.name.length>120)&&n.push("挙動名は1～120文字です。"),
!Array.isArray(m.nodes)||!m.nodes.length||m.nodes.length>64||!Array.isArray(m.edges)||m.edges.length>128){n.push("挙動は1～64ノード、最大128接続です。");continue}e||
n.push(...Ge(t,m));let b=(f,v,R)=>!e&&ie(f)||Z(f,v,R),w=f=>!ie(f),x=new Map,z=new Set;for(let f of m.nodes){if(!f||!/^[a-zA-Z0-9_-]{1,80}$/.test(f.id??"")||x.has(f.id)||!(Qt[f.kind]||
f.kind==="return")){n.push("ノードID・種類が不正です。");continue}if(x.set(f.id,f),f.routeId!==void 0&&(!["follow","patrol"].includes(f.kind)||w(f.routeId)&&!o.some(v=>v?.
id===f.routeId))&&n.push("状態ノードの経路参照が不正です。"),f.destinationId!==void 0&&(!["move","return"].includes(f.kind)||w(f.destinationId)&&!s.some(v=>v?.id===
f.destinationId))&&n.push("状態ノードの目的地参照が不正です。"),f.kind==="patrol"&&f.routeId&&w(f.routeId)&&o.find(v=>v?.id===f.routeId)?.points?.length<3&&n.push(
"周回経路は3点以上必要です。"),f.kind==="patrol"&&f.routeId&&w(f.routeId)){let v=o.find(R=>R?.id===f.routeId);v?.generate&&v.mode!=="loop"&&n.push("協調して周回する自動生成経路はmode\
をloopにしてください。")}f.kind==="wait"&&!b(f.seconds,0,86400)&&n.push("待機時間は0～86400秒です。"),f.kind==="patrol"&&!b(f.speedFraction??.7,.05,1)&&n.push("巡\
回速度比は0.05～1です。"),f.kind==="report"&&!f.receiverId&&!f.receiverRole&&n.push("報告先または報告先の役割を指定してください。"),f.receiverId&&w(f.
receiverId)&&!t.units?.some(v=>v.id===f.receiverId)&&n.push("報告先の単体ユニットがありません: "+f.receiverId),f.joinMode!==void 0&&(!["follow","patrol"].includes(f.
kind)||!["start","nearest"].includes(f.joinMode))&&n.push("経路への入り方は最初から／最短地点からを選択してください。"),f.heightMode!==void 0&&(f.kind!==
"move"||!["keep","target"].includes(f.heightMode))&&n.push("移動の高度・深度は維持する／目的地に合わせるを選択してください。"),f.sensor!==void 0&&typeof f.
sensor!="boolean"&&n.push("ノードのsensorはbooleanです。"),(f.x!==void 0&&!Z(f.x,0,4e3)||f.y!==void 0&&!Z(f.y,0,4e3))&&n.push("ノード位置が不正です。")}let I=bt(
m),A=m.triggers??[],j=new Set,D=new Set;if(I!==void 0&&!x.has(I)&&n.push("初期状態の参照先がありません。"),(m.initial!==void 0&&m.entry!==void 0&&m.initial!==m.entry||
m.triggers?.some?.(f=>f?.event==="scenarioStart"&&f.to!==I))&&n.push("初期状態の指定が重複しています。"),!Array.isArray(A)||A.length>32)n.push("イベントノードは最大32件の配列です。");else if(I===
void 0&&!A.length)n.push("初期状態またはイベントノードを指定してください。");else for(let f of A){(!f||!/^[a-zA-Z0-9_-]{1,80}$/.test(f.id??"")||j.has(f.id)||
!(Object.hasOwn(en,f.event)||f.event==="scenarioStart")||!x.has(f.to))&&n.push("イベントノードのID・種類・接続先が不正です。"),j.add(f?.id);let v=f?ae(f):"";D.
has(v)&&n.push("同じイベント・時間のイベントノードは一つだけ指定できます。"),D.add(v),f?.event==="time"&&(!b(f.seconds,0,86400)||f.once===!1&&f.seconds===
0)&&n.push("時間イベントは0～86400秒、繰り返す場合は0より大きい秒数です。"),f?.policy!==void 0&&!["idle","interrupt"].includes(f.policy)&&n.push("起動方法はid\
le・interruptです。"),f?.once!==void 0&&typeof f.once!="boolean"&&n.push("イベントノードのonceはbooleanです。"),f?.event==="near"&&n.push(...Xe(t,f,!e)),(f?.x!==void 0&&
!Z(f.x,0,4e3)||f?.y!==void 0&&!Z(f.y,0,4e3))&&n.push("イベントノードの位置が不正です。")}for(let f of m.edges){let v=f?.from+"|"+(f?ae(f):""),R=x.get(f?.from);(!f||
!R||!x.has(f.to)||!(tn[R.kind]??[]).includes(f.when)||z.has(v))&&n.push("接続条件が始点ノードに対応しないか、接続が不正・重複しています。"),f?.once!==
void 0&&typeof f.once!="boolean"&&n.push("接続のonceはbooleanです。"),f?.when==="near"&&n.push(...Xe(t,f,!e)),z.add(v)}}for(let m of r){if(!m||!/^[a-zA-Z0-9_-]{1,80}$/.test(
m.id??"")||d.has(m.id)){n.push("タスクIDが不正または重複しています。");continue}d.add(m.id),(typeof m.name!="string"||!m.name.trim()||m.name.length>120)&&n.push("タ\
スク名は1～120文字です。");let b=i.find(I=>I.id===m.behaviorId);if(b||n.push("タスクの挙動がありません。"),!Array.isArray(m.targets)||!m.targets.length&&!(t.
mission?.type==="state"&&t.mission.assignmentId===m.id)&&!t.measurements?.some(I=>I.assignmentId===m.id)||m.targets.length>100){n.push("タスクの担当を選んでください。");
continue}for(let I of m.targets){let A=typeof I=="string"?I.split(":")[0]:"",j=typeof I=="string"?I.slice(A.length+1):"";(!(A==="unit"?t.units?.find(f=>f.id===j):A==="group"&&t.groups?.
find(f=>f.id===j)?.template)||c.has(I))&&n.push("タスクの担当が不正または重複しています。"),c.add(I)}if(b){let I=Ge(t,b,m);if(n.push(...I),!I.length&&b.parameters?.
length){let A=Ae(b,m);n.push(...et({...t,behaviors:[A],behaviorAssignments:[]},!0).map(j=>"タスク「"+m.name+"」: "+j))}}let w=b&&Array.isArray(b.nodes)&&Array.isArray(b.edges)?
Ae(b,m):null,x=w?.nodes.some(I=>I.kind==="patrol"&&!I.routeId),z=w?.nodes.some(I=>["return","move"].includes(I.kind)&&!I.destinationId);x&&(!Array.isArray(m.route)||m.route.length<
3)&&n.push("周回タスクは3点以上の共有経路が必要です。"),m.route!==void 0&&(!Array.isArray(m.route)||m.route.length>500||m.route.some(I=>!Ze(I)))&&n.push("タスクの経路\
が不正です。"),z&&!Ze(m.base)&&n.push("目的に向かって進む状態の目的地を選択してください。"),m.base!==void 0&&!Ze(m.base)&&n.push("帰投地点が不正です。"),
m.routeMode!==void 0&&!["once","loop","pingpong"].includes(m.routeMode)&&n.push("タスクの経路方式が不正です。"),["even","fixed","none"].includes(m.spacing??"none")||n.
push("間隔方式が不正です。"),(!Z(m.spacingDistance??500,0,1e5)||!Z(m.gain??.01,0,1)||!Z(m.preparation??0,0,86400)||!Z(m.phase??0,0,1))&&n.push("タスクの間隔・調整係数・準備時間・開始割合が不正です\
。"),w?.nodes.some(I=>I.receiverRole&&!I.receiverId)&&!t.units?.some(I=>I.id===m.receiverId)&&n.push("タスクの報告先を選んでください。")}let l=t.recording??{},p=l.
step??t.analysis?.step??10,g=l.interval??p;return(!Z(p,.1,300)||!Z(g,.1,300)||g<p||Math.abs(g/p-Math.round(g/p))>1e-8||t.duration/p>1e5)&&n.push("計算刻み0.1～300秒、記録間隔は刻みの整数倍・300秒以下、最大\
10万ステップです。"),t.version===3&&t.analysis&&t.analysis.step!==p&&n.push("分析と記録の計算刻みを一致させてください。"),n}function tt(t,e){let n=t.units?.find(r=>r.id===e),i=n?.groupId??t.groups?.find(r=>e?.slice(0,e.lastIndexOf("__"))===r.id)?.id;return t.behaviorAssignments?.find(r=>r.targets.includes(
"unit:"+e)||i&&r.targets.includes("group:"+i))}function q(t){let e=2166136261;for(let n=0;n<t.length;n++)e^=t.charCodeAt(n),e=Math.imul(e,16777619);return e^=e>>>16,e=Math.imul(e,2146121005),e^=e>>>15,e=Math.imul(e,2221713035),
e^=e>>>16,(e>>>0)/4294967296}var nn=t=>t*t*(3-2*t);function nt(t,e,n){let i=Math.floor(e/n),r=nn(e/n-i),o=d=>{let c=q(t+"|angle|"+d)*Math.PI*2,l=Math.sqrt(q(t+"|radius|"+d));return[
Math.cos(c)*l,Math.sin(c)*l,q(t+"|z|"+d)*2-1]},s=o(i),a=o(i+1);return s.map((d,c)=>d+(a[c]-d)*r)}function re(t,e,n){return"simsim-rng-v1|"+JSON.stringify([t.seed??"SimSim",t.trial??
0,e,n])}function it(t){let e=t.units.map(n=>({...n}));for(let n of t.groups??[]){let i=Math.ceil(Math.sqrt(n.count)),r=Math.ceil(n.count/i);for(let o=0;o<n.count;o++){let s=n.id+"_\
_"+(o+1),a=re(t,s,"deployment"),d=n.placement==="random"?q(a+"|x"):(o%i+.5)/i,c=n.placement==="random"?q(a+"|y"):(Math.floor(o/i)+.5)/r,l=(d-.5)*n.width,p=(c-.5)*n.height,g=w=>({...w,
x:w.x+l,y:w.y+p}),m=n.loopStartMode??"template",b=n.template.routeMode==="loop"&&m!=="template"?{...n.template.motion,loopStart:((n.template.motion?.loopStart??0)+(m==="even"?o/n.count:
q(re(t,s,"loop-start-placement-v1"))))%1}:n.template.motion;e.push({...n.template,...b?{motion:b}:{},enabled:n.enabled!==!1,id:s,name:(n.name+" "+(o+1)).slice(0,120),groupId:n.id,initial:g(
n.template.initial),route:n.template.route.map(g)})}}return e}var N=(t,e,n,i,r,o,s={})=>({key:t,label:e,family:n,path:i,min:r,max:o,scale:1,scope:"entity",...s}),Fe=[N("rate.movement.speed","移動速度","Rate","speed",0,1500,{unit:"m/s",default:0}),
N("extent.sense.radius","最大探知距離","Extent","sensor.range",.001,1e5,{unit:"km",scale:1e3,sensor:!0}),N("interaction.detection.probability","距離0で1分の探知確率",
"Interaction","sensor.probabilityPerMinute",0,1,{unit:"%",scale:.01,sensor:!0}),N("extent.communication.radius","最大通信距離","Extent","communication.range",.001,1e5,{unit:"\
km",scale:1e3,communication:!0}),N("interaction.communication.delay","通信遅延","Interaction","communication.delay",0,86400,{unit:"s",communication:!0}),N("interaction.communic\
ation.probability","通信成功確率","Interaction","communication.probability",0,1,{unit:"%",scale:.01,communication:!0}),N("behavior.preparation","出発準備時間","Behavior",
"preparation",0,86400,{unit:"s",scope:"assignment",preparation:!0,default:0}),N("extent.signature.coefficient","被探知係数","Extent","detectability",0,10,{unit:"倍",default:1}),
N("state.position.x","配置・経路の中心 x","State","initial.x",-1e6,1e6,{unit:"km",scale:1e3,translate:"x"}),N("state.position.y","配置・経路の中心 y","State","initi\
al.y",-1e6,1e6,{unit:"km",scale:1e3,translate:"y"}),N("state.position.z","高度・深度 z","State","initial.z",-2e4,1e5,{unit:"m",translate:"z",vertical:!0}),N("extent.sense.moun\
tHeight","センサー取付高","Extent","sensor.mountHeight",0,1e3,{unit:"m",sensor:!0,default:0}),N("state.route.phase","周回の出発点","State","motion.loopStart",0,1,{unit:"\
%",scale:.01,default:0,loopOnly:!0}),N("motion.horizontal","個体の水平ずれ上限","Motion","motion.horizontal",0,1e4,{unit:"m",default:0}),N("motion.commonHorizontal","群共通の水\
平ずれ上限","Motion","motion.commonHorizontal",0,1e4,{unit:"m",default:0}),N("motion.vertical","上下ずれ上限","Motion","motion.vertical",0,3e3,{unit:"m",default:0,vertical:!0}),
N("motion.scale","航跡の変動間隔","Motion","motion.scale",10,1e5,{unit:"m",default:2e3}),N("motion.startDelay","出発遅れ上限","Motion","motion.startDelay",0,86400,{unit:"\
s",default:0}),N("motion.speedVariation","個体速度のばらつき","Motion","motion.speedVariation",0,1,{unit:"±%",scale:.01,default:0}),N("capacity.population","群の個数",
"Capacity","count",0,2e3,{unit:"個",scope:"group",integer:!0}),N("extent.deployment.width","配置幅 x","Extent","width",0,1e5,{unit:"km",scale:1e3,scope:"group"}),N("extent.depl\
oyment.height","配置幅 y","Extent","height",0,1e5,{unit:"km",scale:1e3,scope:"group"}),N("task.route.x","共有経路の基準 x","State","route.0.x",-1e6,1e6,{unit:"km",scale:1e3,
scope:"assignment",routeAxis:"x"}),N("task.route.y","共有経路の基準 y","State","route.0.y",-1e6,1e6,{unit:"km",scale:1e3,scope:"assignment",routeAxis:"y"}),N("task.route.z",
"共有経路の高度・深度","State","route.0.z",-2e4,1e5,{unit:"m",scope:"assignment",routeAxis:"z"}),N("task.route.phase","共有周回の出発点","State","phase",0,1,{unit:"\
%",scale:.01,scope:"assignment",default:0,patrol:!0}),N("coordination.spacing","協調する指定間隔","Behavior","spacingDistance",0,1e5,{unit:"m",scope:"assignment",fixedSpacing:!0,
default:500}),N("coordination.gain","間隔の調整係数","Behavior","gain",0,1,{unit:"1/s",scope:"assignment",default:.01}),N("mission.deadline","成功条件の期限","Mission",
"mission.deadline",1e-6,86400,{unit:"min",scale:60,scope:"scenario"})];function le(t){let e=Fe.find(s=>s.key===t);if(e)return e;let n=/^behavior\.(node|trigger)\.([A-Za-z0-9_-]{1,80})\.(seconds|speedFraction)$/.
exec(t??"");if(!n||n[1]==="trigger"&&n[3]!=="seconds")return;let[,i,r,o]=n;return N(t,(i==="trigger"?"イベント ":"状態 ")+r+" · "+(o==="seconds"?"待機・発火時間":"周回速\
度割合"),"Behavior",o,o==="speedFraction"?.05:0,o==="speedFraction"?1:86400,{scope:"behavior",unit:o==="seconds"?"s":"%",scale:o==="seconds"?1:.01,default:o==="speedFraction"?.7:
void 0,collection:i==="node"?"nodes":"triggers",itemId:r})}var Q=t=>JSON.stringify([t.target,t.parameter]);function wt(t){let e=JSON.parse(JSON.stringify(t));return e.factors=[...t.groupId?[{target:"group:"+t.groupId,parameter:"capacity.po\
pulation",values:[...t.counts].sort((n,i)=>n-i)}]:[],...e.factors??[]],delete e.groupId,delete e.counts,e}var rn=t=>JSON.parse(JSON.stringify(t));function It(t,e,n){if(e==="scenari\
o"){if(n.scope!=="scenario"||!t.mission)throw new Error("成功条件を設定してください。");return t}let i=e?.indexOf(":")??-1,r=e?.slice(0,i),o=e?.slice(i+1),s=r==="unit"?
t.units?.find(d=>d.id===o):r==="group"?t.groups?.find(d=>d.id===o):r==="assignment"?t.behaviorAssignments?.find(d=>d.id===o):r==="behavior"?t.behaviors?.find(d=>d.id===o):null;if(!s||
n.scope==="scenario"||n.scope==="group"&&r!=="group")throw new Error("変数の対象が見つかりません: "+e);if(n.scope==="behavior"){let d=r==="behavior"?s[n.collection]?.find(
c=>c.id===n.itemId):null;if(!d||(n.collection==="triggers"?d.event!=="time":n.path==="seconds"?d.kind!=="wait"||d.parameter==="preparation":d.kind!=="patrol")||d[n.path]!==void 0&&
typeof d[n.path]!="number")throw Error("ノードの数値設定がありません。");return d}if(r==="behavior")throw Error("変数の対象が一致しません。");if(n.scope===
"assignment"!=(r==="assignment"))throw new Error("変数の対象が一致しません。");let a=r==="group"&&n.scope==="entity"?s.template:s;if(r!=="assignment"&&tt(t,r==="group"?
o+"__1":o)?.route?.length&&(n.translate||n.loopOnly||n.key.startsWith("extent.deployment.")))throw new Error("共有経路の位置・開始割合はタスク側の変数を選んでください。");
if(n.loopOnly&&a.routeMode!=="loop")throw new Error("周回の出発点は周回経路の対象に指定してください。");if(n.communication&&!a.communication?.enabled)throw new Error(
"通信変数の対象で通信を有効にしてください。");if(n.behavior&&!a.behavior)throw new Error("条件付き行動の設定がありません。");if(n.sensor&&!a.sensor)
throw new Error("探知変数の対象にセンサーがありません。");return a}var on=(t,e)=>e.split(".").reduce((n,i)=>n?.[i],t);function pe(t,e){let n=le(e.parameter);if(!n)
throw new Error("未対応の変数です。");let i=It(t,e.target,n);return on(i,n.path)??(n.key==="extent.sense.mountHeight"&&i.domain==="ground"?2:n.default)}function sn(t,e,n){
let i=le(e.parameter),r=It(t,e.target,i),o=i.path.split(".");if(i.routeAxis){let a=n-r.route[0][i.routeAxis];for(let d of r.route)d[i.routeAxis]+=a;return}if(i.translate){let a=n-r.
initial[i.translate];for(let d of r.route??[])d[i.translate]+=a}let s=r;for(let a of o.slice(0,-1))s[a]===void 0&&(s[a]={}),s=s[a];s[o.at(-1)]=n}function Mt(t){let e=[],n=(i,r,o,s)=>{
let a=tt(t,s==="group"?i.slice(6)+"__1":i.slice(5));for(let d of Fe)a?.route?.length&&(d.translate||d.loopOnly||d.key.startsWith("extent.deployment."))||d.scope==="assignment"||d.loopOnly&&
o.routeMode!=="loop"||d.scope==="scenario"||d.scope==="group"&&s!=="group"||d.sensor&&!o.sensor?.enabled||d.communication&&!o.communication?.enabled||d.behavior&&!o.behavior||d.vertical&&
["ground","surface"].includes(o.domain)||e.push({target:i,targetLabel:(s==="group"?"群: ":"ユニット: ")+r,parameter:d.key,label:r+" · "+d.family+" · "+d.label+" ("+d.unit+")"})};
for(let i of t.units??[])n("unit:"+i.id,i.name,i,"unit");for(let i of t.groups??[])n("group:"+i.id,i.name,i.template,"group");for(let i of t.behaviorAssignments??[])for(let r of Fe.
filter(o=>o.scope==="assignment"&&(!o.fixedSpacing||i.spacing==="fixed")&&(!o.routeAxis||i.route?.length)&&(!o.patrol||t.behaviors?.find(s=>s.id===i.behaviorId)?.nodes.some(s=>s.kind===
"patrol"))&&(!o.preparation||t.behaviors?.find(s=>s.id===i.behaviorId)?.nodes.some(s=>s.parameter==="preparation"))))e.push({target:"assignment:"+i.id,targetLabel:"協調: "+i.name,
parameter:r.key,label:i.name+" · "+r.label+" ("+r.unit+")"});for(let i of t.behaviors??[])for(let[r,o]of[["node",i.nodes],["trigger",i.triggers]])for(let s of o??[]){let a=r==="tr\
igger"&&s.event==="time"||r==="node"&&s.kind==="wait"&&s.parameter!=="preparation"?"seconds":r==="node"&&s.kind==="patrol"?"speedFraction":null;if(!a||s[a]!==void 0&&typeof s[a]!="\
number")continue;let d="behavior."+r+"."+s.id+"."+a,c=le(d);e.push({target:"behavior:"+i.id,targetLabel:"挙動: "+i.name+"（使用する全タスク）",parameter:d,label:i.name+
" · "+c.label+" ("+c.unit+")"})}if(t.mission)for(let i of Fe.filter(r=>r.scope==="scenario"))e.push({target:"scenario",targetLabel:"シナリオ・ミッション",parameter:i.key,
label:i.label+" ("+i.unit+")"});return e}function De(t,e,n){let i=le(e.parameter),r=e.target;return e.target.startsWith("group:")&&(r=t.groups?.find(o=>o.id===e.target.slice(6))?.name??
r),e.target.startsWith("assignment:")&&(r=t.behaviorAssignments?.find(o=>o.id===e.target.slice(11))?.name??r),e.target.startsWith("behavior:")&&(r=t.behaviors?.find(o=>o.id===e.target.
slice(9))?.name??r),e.target.startsWith("unit:")&&(r=t.units?.find(o=>o.id===e.target.slice(5))?.name??r),r+" / "+i.label+" = "+Number((n/i.scale).toFixed(5))+" "+i.unit}function St(t,e){
let n=[],i=new Set;t.groupId&&i.add(Q({target:"group:"+t.groupId,parameter:"capacity.population"}));for(let[o,s]of[["factors",t.factors??[]],["uncertainties",t.uncertainties??[]]]){
let a=o==="factors"?9:8;if(!Array.isArray(s)||s.length>a){n.push(o+"は最大"+a+"変数にしてください。");continue}for(let d of s){let c=le(d?.parameter),l=Q(d??{});if(!c||
typeof d.target!="string"){n.push("未対応の変数または対象です。");continue}i.has(l)&&n.push("同じ変数を重複して指定できません。"),i.add(l);let p=c.key===
"mission.deadline"?Math.min(c.max,e):c.max,g=m=>typeof m=="number"&&Number.isFinite(m)&&m>=c.min&&m<=p&&(!c.integer||Number.isInteger(m));o==="factors"?(!Array.isArray(d.values)||!d.
values.length||d.values.length>12||d.values.some(m=>!g(m))||new Set(d.values).size!==d.values.length)&&n.push(c.label+": 比較値は範囲内で重複しない数値を1～12個指定してください。"):
(!["uniform","triangular"].includes(d.distribution)||!g(d.min)||!g(d.max)||d.min>d.max||d.distribution==="triangular"&&(!g(d.mode)||d.mode<d.min||d.mode>d.max))&&n.push(c.label+": \
分布の範囲・最頻値が不正です。")}}let r=(t.groupId?t.counts?.length??0:1)*(Array.isArray(t.factors)?t.factors.reduce((o,s)=>o*(s?.values?.length??0),1):1);return r>24&&
n.push("比較値の組合せは最大24条件にしてください。"),!["sensitivity","plans"].includes(t.mode)&&r*t.trials>1e4&&n.push("条件数×試行数は10000以下にしてください。"),
n}function At(t){let e=t.analysis,n=e.groupId?[...e.counts].sort((i,r)=>i-r).map(i=>({count:i,settings:[{target:"group:"+e.groupId,parameter:"capacity.population",value:i}]})):[{settings:[]}];
for(let i of e.factors??[])n=n.flatMap(r=>i.values.map(o=>({...r,settings:[...r.settings,{target:i.target,parameter:i.parameter,value:o}]})));return n.map((i,r)=>({...i,id:JSON.stringify(
i.settings.map(o=>[Q(o),o.value]).sort((o,s)=>o[0]<s[0]?-1:o[0]>s[0]?1:0)),index:r+1,label:i.settings.map(o=>De(t,o,o.value)).join(" / ")||"基準条件"}))}function be(t,e,n,{maximum:i=!1}={}){
let r=rn(t),o=[];r.trial=n,r.analysis&&(delete r.analysis.sensitivity,delete r.analysis.plans,delete r.analysis.mode);for(let s of t.analysis.uncertainties??[]){let a=q(re(r,Q(s),"\
parameter-sample-v1")),d=s.min;if(i)d=s.max;else if(s.max>s.min)if(s.distribution==="uniform")d=s.min+a*(s.max-s.min);else{let c=s.max-s.min,l=(s.mode-s.min)/c;d=a<l?s.min+Math.sqrt(
a*c*(s.mode-s.min)):s.max-Math.sqrt((1-a)*c*(s.max-s.mode))}le(s.parameter).integer&&(d=Math.round(d)),o.push({target:s.target,parameter:s.parameter,value:d})}for(let s of[...e.settings,
...o])sn(r,s,s.value);if(r.groups=r.groups?.filter(s=>s.count!==0),r.behaviorAssignments&&(r.behaviorAssignments=r.behaviorAssignments.map(s=>({...s,targets:s.targets.filter(a=>!a.
startsWith("group:")||r.groups?.some(d=>d.id===a.slice(6)))})).filter(s=>s.targets.length||r.mission?.type==="state"&&r.mission.assignmentId===s.id||r.measurements?.some(a=>a.assignmentId===
s.id))),r.analysis){let s=a=>a.target==="scenario"?!!r.mission:a.target.startsWith("behavior:")?r.behaviors?.some(d=>d.id===a.target.slice(9)):a.target.startsWith("assignment:")?r.
behaviorAssignments?.some(d=>d.id===a.target.slice(11)):a.target.startsWith("group:")?r.groups?.some(d=>d.id===a.target.slice(6)):r.units.some(d=>d.id===a.target.slice(5));for(let a of[
"factors","uncertainties"])r.analysis[a]=r.analysis[a]?.filter(s);r.analysis.groupId&&!r.groups?.some(a=>a.id===r.analysis.groupId)&&(delete r.analysis.groupId,delete r.analysis.counts)}
return{scenario:r,sampled:o}}var an=32;function ke(t){let e=t.mission?[{id:"mission.rate",label:"ミッションの成立率",kind:"rate"},{id:"mission.time",label:"ミッションの成立時刻",kind:"time"}]:
[];for(let n of t.measurements??[])for(let i of["rate","time","duration"])e.push({id:"point."+n.id+"."+i,label:n.name+" · "+{rate:"到達率",time:"成立時刻",duration:"起点からの所要\
時間"}[i],kind:i,measurementId:n.id});return e}function dn(t){let e=new Set((t.analysis?.uncertainties??[]).map(Q));return Mt(t).filter(n=>{if(n.target==="scenario"||e.has(Q(n))||
n.target.startsWith("unit:")&&t.units.find(i=>i.id===n.target.slice(5))?.enabled===!1||n.target.startsWith("group:")&&t.groups.find(i=>i.id===n.target.slice(6))?.enabled===!1)return!1;
try{return Number.isFinite(pe(t,n))}catch{return!1}})}function _e(t){let e=t.analysis,n=e?.sensitivity,i=[];if(e?.mode!==void 0&&!["comparison","sensitivity","plans"].includes(e.mode)&&i.push("分析の種類はcomparison・sensitivity・plansです。"),
n===void 0)return i;if(!n||typeof n!="object"||Array.isArray(n))return[...i,"感度分析の設定はオブジェクトにしてください。"];if(ke(t).some(s=>s.id===n.metric)||
i.push("感度分析の評価指標を選択してください。"),!Array.isArray(n.candidates)||n.candidates.length>an)return[...i,"感度分析は最大32項目です。"];let r=new Set(
dn(t).map(Q)),o=new Set;for(let s of n.candidates){let a=le(s?.parameter),d=Q(s??{});if(!a||!r.has(d)){i.push("感度分析の対象・性能が不在、無効、または試行のばらつきと重複しています。");
continue}o.has(d)&&i.push("感度分析の項目は重複できません。"),o.add(d);let c=l=>Number.isFinite(l)&&l>=a.min&&l<=a.max&&(!a.integer||Number.isInteger(l));(!c(s.low)||
!c(s.high)||s.low>s.high)&&i.push(a.label+": 小さい値・大きい値を範囲内で指定してください。")}return i}var Le=["units","groups","behaviors","behaviorAssignments","routes","destinations"],Et=t=>JSON.parse(JSON.stringify(t));function Ue(t,e){return{...Et(t),...Et(e.operation)}}function kt(t){let e=t.analysis?.plans;if(e===void 0)return[];if(!e||typeof e!="object"||Array.isArray(e))return["運用案の設定はオブジェクト\
にしてください。"];let n=[];if(typeof e.metric!="string"&&n.push("運用案の評価指標を選択してください。"),!Array.isArray(e.items)||e.items.length>8)return[
...n,"運用案は最大8件です。"];let i=new Set;for(let o of e.items)(!o||typeof o.id!="string"||!/^[A-Za-z0-9_-]{1,80}$/.test(o.id)||i.has(o.id))&&n.push("運用案IDは重複しない英数字・_・-\
にしてください。"),i.add(o?.id),(typeof o?.name!="string"||!o.name.trim()||o.name.length>120)&&n.push("運用案名は1～120文字にしてください。"),(!o?.operation||
typeof o.operation!="object"||Array.isArray(o.operation)||Object.keys(o.operation).some(s=>!Le.includes(s))||Le.some(s=>!Array.isArray(o.operation[s])))&&n.push("運用案には配置・経路・挙動の配列を保\
存してください。");let r=e.editor;if(r!==void 0){let o=s=>typeof s=="string"&&(s===""||/^[A-Za-z0-9_-]{1,80}$/.test(s));if(!r||typeof r!="object"||Array.isArray(r)||!o(r.activeId)||
!Array.isArray(r.drafts)||r.drafts.length>16)n.push("運用案の編集保持は有効な案IDと最大16件の配列にしてください。");else{let s=new Set;for(let a of r.drafts)
(!a||!o(a.id)||s.has(a.id)||typeof a.name!="string"||!a.name.trim()||a.name.length>120)&&n.push("保持する運用案のID・名前が不正です。"),s.add(a?.id),(!a?.operation||
typeof a.operation!="object"||Array.isArray(a.operation)||Object.keys(a.operation).some(d=>!Le.includes(d))||Le.some(d=>!Array.isArray(a.operation[d])))&&n.push("編集中の運用案には配置・経路・挙動の\
配列を保持してください。");r.activeId&&!i.has(r.activeId)&&!s.has(r.activeId)&&n.push("編集中の運用案がありません。")}}return e.items.length&&!i.has(e.baselineId)&&
n.push("基準となる運用案を選択してください。"),n}function zt(t){return ke(t).find(e=>e.id===t.analysis?.plans?.metric)}function Ct(t){let e=t.mission;if(e?.type!=="state")return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=t.behaviors?.find(r=>r.id===n?.behaviorId);return n?i?.nodes?.
some(r=>r.id===e.nodeId)?[]:["計測対象の状態を選択してください。"]:["計測対象のタスクがありません。"]}function rt(t,e=t.mission){if(e?.type!=="state")
return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=[];for(let r of n?.targets??[])if(r.startsWith("unit:")){let o=t.units.find(s=>s.id===r.slice(5));o&&o.enabled!==
!1&&i.push(o.id)}else{let o=t.groups?.find(s=>s.id===r.slice(6));if(o&&o.enabled!==!1)for(let s=1;s<=o.count;s++)i.push(o.id+"__"+s)}return i.sort()}var cn=(t,e)=>t.join==="all"?e:
t.join==="count"?t.requiredCount:1;function Be(t,e,n,i=e.deadline){let r=t.filter(s=>s.time<=Math.min(i,e.deadline)).sort((s,a)=>s.time-a.time||s.unitId.localeCompare(a.unitId)),o=cn(
e,n);return{stateTargetCount:n,stateReachedCount:r.length,stateEntries:r,success:n>0&&o>0&&r.length>=o,successTime:n>0&&o>0&&r.length>=o?r[o-1].time:null}}var he=class{constructor(e,n){
this.mission=e,this.members=new Set(n),this.first=new Map,this.cursor=0}update(e){for(;this.cursor<e.length;this.cursor++){let n=e[this.cursor];["initialized","nodeChanged"].includes(
n.type)&&n.nodeId===this.mission.nodeId&&n.time<=this.mission.deadline&&this.members.has(n.unitId)&&!this.first.has(n.unitId)&&this.first.set(n.unitId,n.time)}return Be([...this.first].
map(([n,i])=>({unitId:n,time:i})),this.mission,this.members.size)}};function Ot(t){if(t.measurements===void 0)return[];if(!Array.isArray(t.measurements)||t.measurements.length>12)return["measurementsは最大12件の配列にしてください。"];
let e=[],n=new Set;for(let i of t.measurements){if(!i||typeof i!="object"){e.push("計測点はオブジェクトにしてください。");continue}let r=t.behaviorAssignments?.find(
s=>s.id===i.assignmentId),o=t.behaviors?.find(s=>s.id===r?.behaviorId);(typeof i.id!="string"||!/^[A-Za-z0-9_-]{1,64}$/.test(i.id)||n.has(i.id))&&e.push("計測点のidは重複しない英数字・_・-（64文字以内\
）です。"),(typeof i.name!="string"||!i.name.trim()||i.name.length>120)&&e.push("計測点のnameは1～120文字です。"),(i.type!=="state"||!o?.nodes?.some(s=>s.id===i.nodeId))&&
e.push("計測点のtypeはstate、assignmentId・nodeIdは存在するタスク・状態を指定してください。"),(!["any","all","count"].includes(i.join)||i.join==="count"&&
(!Number.isInteger(i.requiredCount)||i.requiredCount<1||i.requiredCount>2e3))&&e.push("計測点のjoinはany・all・count、requiredCountは1～2000です。"),(!Number.isFinite(
i.deadline)||i.deadline<=0||i.deadline>t.duration)&&e.push("計測点のdeadlineは0より大きく終了時刻以下にしてください。"),i.previousId!==void 0&&!n.has(i.previousId)&&
e.push("所要時間の基準previousIdには、この計測点より前に登録した計測点を指定してください。"),n.add(i.id)}return e}function ot(t,e,n=t.duration){
return(t.measurements??[]).map(i=>({id:i.id,...new he({...i,deadline:Math.min(n,i.deadline)},rt(t,i)).update(e)}))}var jt=t=>typeof t=="number"&&Number.isFinite(t);function Pt(t,e="unit",n=new Set){let i=[],r=t.communication,o=t.behavior;if(r!==void 0)if(!r||typeof r!="object"||Array.isArray(r))
i.push(e+": communicationはオブジェクトにしてください。");else{(typeof r.enabled!="boolean"||typeof r.terrainLOS!="boolean")&&i.push(e+": 通信のenabled・terrainLOSはboole\
anにしてください。");for(let[s,a,d]of[["range",.001,1e5],["delay",0,86400],["probability",0,1]])(!jt(r[s])||r[s]<a||r[s]>d)&&i.push(e+": communication."+s+"は"+a+"～"+d+"\
にしてください。")}if(o!==void 0){if(!o||typeof o!="object"||Array.isArray(o))return[...i,e+": behaviorはオブジェクトにしてください。"];if(typeof o.hold!="bo\
olean"&&i.push(e+": behavior.holdはbooleanにしてください。"),(!jt(o.preparation)||o.preparation<0||o.preparation>86400)&&i.push(e+": behavior.preparationは0～86400秒にしてください。"),
!Array.isArray(o.rules)||o.rules.length>16)i.push(e+": 行動ルールは最大16件にしてください。");else{let s=new Set;for(let a of o.rules){if(!a||typeof a!="object"){i.
push(e+": ルールはオブジェクトにしてください。");continue}(typeof a.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(a.id)||s.has(a.id))&&i.push(e+": ルールidは重複しない英数字・_・\
-にしてください。"),s.add(a.id),(!["detected","received","arrived"].includes(a.when)||!["send","depart"].includes(a.action)||!["any","waiting"].includes(a.state)||typeof a.
once!="boolean")&&i.push(e+": ルールの条件・動作・実行回数が不正です。"),a.action==="send"&&!n.has(a.receiverId)&&i.push(e+": 送信先の単体ユニットが見つかりません: "+
a.receiverId),a.action==="depart"&&!o.hold&&i.push(e+": 出発ルールには「指令まで待機」を設定してください。")}}}return i}var un=["ground","surface","subsurface","air"],Nt=["friendly","hostile","neutral"],me=t=>typeof t=="number"&&Number.isFinite(t);function Rt(t,e="unit"){let n=[],i=t.sensor;if(t.detectability!==
void 0&&(!me(t.detectability)||t.detectability<0||t.detectability>10)&&n.push(e+": detectabilityは0～10にしてください。"),i!==void 0){if(!i||typeof i!="object"||Array.isArray(
i))return[...n,e+": sensorはオブジェクトにしてください。"];typeof i.enabled!="boolean"&&n.push(e+": sensor.enabledはbooleanにしてください。"),(!me(i.range)||
i.range<=0||i.range>1e5)&&n.push(e+": sensor.rangeは0より大きく100000m以下にしてください。"),(!me(i.probabilityPerMinute)||i.probabilityPerMinute<0||i.probabilityPerMinute>
1)&&n.push(e+": sensor.probabilityPerMinuteは0～1にしてください。"),(!Array.isArray(i.domains)||!i.domains.length||i.domains.some(r=>!un.includes(r)))&&n.push(e+": sensor\
.domainsには対象領域を1つ以上指定してください。"),typeof i.terrainLOS!="boolean"&&n.push(e+": sensor.terrainLOSはbooleanにしてください。"),i.mountHeight!==
void 0&&(!me(i.mountHeight)||i.mountHeight<0||i.mountHeight>1e3)&&n.push(e+": sensor.mountHeightは0～1000mにしてください。")}return n}function Je(t,e){if(t===void 0)return[];
let n=[];return!t||typeof t!="object"||Array.isArray(t)?["missionはオブジェクトにしてください。"]:(["detect","arrive","state"].includes(t.type)||n.push("mission.type\
はdetect・arrive・stateにしてください。"),t.type==="arrive"&&(!Array.isArray(t.responderIds)||!t.responderIds.length||t.responderIds.length>2e3||t.responderIds.some(i=>typeof i!=
"string")||new Set(t.responderIds).size!==t.responderIds.length)&&n.push("mission.responderIdsに到着を評価する単体ユニットIDを指定してください。"),t.type!==
"state"&&(!Nt.includes(t.observerFaction)||!Nt.includes(t.targetFaction)||t.observerFaction===t.targetFaction)&&n.push("観測側と対象側には異なる陣営を指定してください。"),
(t.type==="state"?["any","all","count"]:["any","all"]).includes(t.join)||n.push("mission.joinはany・all（状態計測ではcountも可）にしてください。"),t.type==="sta\
te"&&(typeof t.assignmentId!="string"||typeof t.nodeId!="string")&&n.push("計測するタスクと状態を選択してください。"),t.join==="count"&&(!Number.isInteger(t.requiredCount)||
t.requiredCount<1||t.requiredCount>2e3)&&n.push("到達を必要とする担当数は1～2000です。"),(!me(t.deadline)||t.deadline<=0||t.deadline>e)&&n.push("mission.deadlineは0よ\
り大きく終了時刻以下にしてください。"),t.targetIds!==void 0&&(!Array.isArray(t.targetIds)||!t.targetIds.length||t.targetIds.length>2e3||t.targetIds.some(i=>typeof i!=
"string")||new Set(t.targetIds).size!==t.targetIds.length)&&n.push("mission.targetIdsは重複しない対象IDの配列にしてください。"),n)}function Ye(t,e){if(t===void 0)
return[];if(!t||typeof t!="object"||Array.isArray(t))return["analysisはオブジェクトにしてください。"];let n=[];return t.groupId!==void 0&&typeof t.groupId!="string"&&
n.push("analysis.groupIdは文字列にしてください。"),t.groupId&&(!Array.isArray(t.counts)||!t.counts.length||t.counts.length>12||t.counts.some(i=>!Number.isInteger(i)||i<
0||i>2e3)||new Set(t.counts).size!==t.counts.length)&&n.push("analysis.countsは重複しない0～2000の整数（最大12条件）にしてください。"),(!Number.isInteger(t.
trials)||t.trials<1||t.trials>2e3)&&n.push("analysis.trialsは1～2000にしてください。"),(!me(t.step)||t.step<.1||t.step>300||Math.ceil(e/t.step)>1e5)&&n.push("判定間隔は0.1～300\
秒、シナリオ全体で10万区間以内にしてください。"),(!me(t.requiredRate)||t.requiredRate<0||t.requiredRate>1)&&n.push("analysis.requiredRateは0～1にしてください。"),
n.push(...St(t,e)),n}var st=2e3,ln=["ground","surface","subsurface","air"];var $e=t=>JSON.parse(JSON.stringify(t)),te=t=>typeof t=="number"&&Number.isFinite(t),Ft=t=>t&&["x","y","z"].every(e=>te(t[e]));function de(t){let e=[];if(!t||typeof t!="object")throw new Error(
"シナリオはオブジェクトで指定してください。");[1,2,3].includes(t.version)||e.push("versionは1・2・3にしてください。"),t.unitsSystem!=="SI"&&e.push("\
unitsSystemはSI（m・s）にしてください。"),(typeof t.title!="string"||!t.title.trim()||t.title.length>160)&&e.push("titleは1～160文字で指定してください。"),
(!te(t.duration)||t.duration<=0||t.duration>86400)&&e.push("durationは0より大きく86400秒以下にしてください。");let n=t.terrain;!n||!Number.isInteger(n.columns)||!Number.
isInteger(n.rows)||n.columns<2||n.rows<2||n.columns>513||n.rows>513?e.push("terrainのcolumns・rowsは2～513の整数にしてください。"):((!te(n.spacing)||n.spacing<1||n.spacing>
1e4)&&e.push("terrain.spacingは1～10000mにしてください。"),n.spacingY!==void 0&&(!te(n.spacingY)||n.spacingY<1||n.spacingY>1e4)&&e.push("terrain.spacingYは1～10000mにしてください。"),
(!n.origin||!te(n.origin.x)||!te(n.origin.y))&&e.push("terrain.originのx・yが必要です。"),(!Array.isArray(n.elevations)||n.elevations.length!==n.columns*n.rows||n.elevations.
some(o=>!te(o)||o<-12e3||o>1e4))&&e.push("terrain.elevationsは格子数と同じ長さの標高配列（-12000～10000m）にしてください。"),te(n.seaLevel)||e.push("terrai\
n.seaLevelが必要です。")),t.seed!==void 0&&(typeof t.seed!="string"||t.seed.length>100)&&e.push("seedは100文字以下の文字列にしてください。"),t.trial!==void 0&&
(!Number.isInteger(t.trial)||t.trial<0||t.trial>1e9)&&e.push("trialは0～1000000000の整数にしてください。");let i=t.groups??[],r=new Set;if(!Array.isArray(i)||i.length>
100)e.push("groupsは最大100件の配列にしてください。");else for(let o of i){if(!o||typeof o!="object"){e.push("groupはオブジェクトにしてください。");continue}
o.enabled!==void 0&&typeof o.enabled!="boolean"&&e.push("group.enabledはbooleanにしてください。"),(typeof o.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(o.id)||r.has(o.id))&&
e.push("group.idは重複しない英数字・_・-（50文字以下）にしてください。"),r.add(o.id),(typeof o.name!="string"||!o.name.trim()||o.name.length>100)&&e.push("\
group.nameは1～100文字にしてください。"),(!Number.isInteger(o.count)||o.count<1||o.count>st)&&e.push("group.countは1～2000にしてください。"),o.loopStartMode!==
void 0&&!["template","even","random"].includes(o.loopStartMode)&&e.push("group.loopStartModeはtemplate、even、randomにしてください。"),["grid","random"].includes(o.placement)||
e.push("group.placementはgridまたはrandomにしてください。");for(let s of["width","height"])(!te(o[s])||o[s]<0||o[s]>1e5)&&e.push("group."+s+"は0～100000mにしてください。")}
if(!Array.isArray(t.units)||t.units.length>st)e.push("unitsは最大2000件の配列にしてください。");else{let o=new Set,s=new Set(t.units.map(a=>a?.id));[...t.units,...Array.
isArray(i)?i.map(a=>a?.template):[]].forEach((a,d)=>{let c="units["+d+"]";if(!a||typeof a!="object"){e.push(c+": オブジェクトが必要です。");return}if((typeof a.id!="str\
ing"||!/^[a-zA-Z0-9_-]{1,80}$/.test(a.id)||d<t.units.length&&o.has(a.id))&&e.push(c+": idは重複しない英数字・_・-にしてください。"),d<t.units.length&&o.add(a.id),
(typeof a.name!="string"||!a.name.trim()||a.name.length>120)&&e.push(c+": nameは1～120文字にしてください。"),e.push(...Rt(a,c),...Pt(a,c,s)),t.version===3&&a.behavior&&
e.push(c+": 旧行動ルールは読み込み時にノードへ変換してください。"),a.navigation!==void 0&&e.push(...ve(a.navigation)),ln.includes(a.domain)||e.push(c+": d\
omainが不正です。"),["friendly","hostile","neutral"].includes(a.faction)||e.push(c+": factionが不正です。"),a.enabled!==void 0&&typeof a.enabled!="boolean"&&e.push(c+":\
 enabledはbooleanにしてください。"),typeof a.manned!="boolean"&&e.push(c+": mannedはbooleanにしてください。"),(!te(a.speed)||a.speed<0||a.speed>1500)&&e.push(c+":\
 speedは0～1500m/sにしてください。"),Ft(a.initial)||e.push(c+": initialのx,y,zが必要です。"),["once","loop","pingpong"].includes(a.routeMode)||e.push(c+": routeMod\
eが不正です。"),a.groupId!==void 0&&d<t.units.length&&e.push(c+": groupIdは生成ユニット専用です。"),a.motion!==void 0)if(!a.motion||typeof a.motion!="object"||Array.
isArray(a.motion))e.push(c+": motionはオブジェクトにしてください。");else for(let[l,p,g]of[["horizontal",0,1e4],["vertical",0,3e3],["commonHorizontal",0,1e4],["scale",
10,1e5],["startDelay",0,86400],["speedVariation",0,1],["loopStart",0,1]])a.motion[l]!==void 0&&(!te(a.motion[l])||a.motion[l]<p||a.motion[l]>g)&&e.push(c+": motion."+l+"は"+p+"～"+
g+"にしてください。");(!Array.isArray(a.route)||a.route.length>500||a.route.some(l=>!Ft(l)))&&e.push(c+": routeは最大500件、各点にx,y,zが必要です。")})}if(Array.
isArray(t.units)&&Array.isArray(i)&&!e.length){let o=t.units.length+i.reduce((s,a)=>s+a.count,0);if(o>st)e.push("単体と群を合わせて最大2000ユニットにしてください。");else{
let s=it(t);new Set(s.map(a=>a.id)).size!==o&&e.push("生成ユニットのidが単体ユニットと重複しています。")}}if(e.push(...Je(t.mission,t.duration),...Ye(t.analysis,
t.duration),...et(t),...Ct(t),...Ot(t)),t.mission?.type==="arrive"&&t.mission.responderIds?.some(o=>!t.units?.some(s=>s.id===o))&&e.push("到着評価の対象となる単体ユニットが見つかりません。"),
t.version===3&&!e.length)for(let o of[...t.analysis?.factors??[],...t.analysis?.uncertainties??[]])try{pe(t,o)}catch(s){e.push(s.message)}if(e.length||e.push(..._e(t)),e.length||e.
push(...kt(t)),!e.length&&t.analysis?.plans)for(let o of[...t.analysis.plans.items,...t.analysis.plans.editor?.drafts??[]])try{let s=Ue(t,o);delete s.analysis,delete s.mission,delete s.
measurements,de(s)}catch(s){e.push("運用案「"+o.name+"」: "+s.message)}if(e.length)throw new Error(e.slice(0,30).join(`
`));return gt(xt($e(t)))}var qe=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),ze=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function pn(t,e){let n=[0];for(let d=1;d<
t.length;d++)n.push(n.at(-1)+qe(t[d-1],t[d]));let i=n.at(-1);if(i===0)return t;let r=i*e,o=n.findIndex((d,c)=>c>0&&d>r),s=o<0?t.length-1:o,a=ze(t[s-1],t[s],(r-n[s-1])/(n[s]-n[s-1]));
return[a,...t.slice(s,-1),...t.slice(0,s),{...a}]}var xe=class{constructor(e,{deferPaths:n=!1}={}){let i=de(e);this.source=i,this.scenario={...i,units:it(i)},this.nodeCount=0,this.
terrain=new X(this.scenario.terrain),this.paths=n?new Map:new Map(this.scenario.units.filter(r=>r.enabled!==!1).map(r=>[r.id,this.compile(r)]))}compile(e){let n=this.terrain.project(
e.initial,e.domain),i=[{...n.point,d:0}],r=e.motion??{},o=re(this.scenario,e.id,"motion"),s=(r.startDelay??0)*q(o+"|delay"),a=e.speed*(1+(q(o+"|speed")*2-1)*(r.speedVariation??0)),
d={delay:s,actualSpeed:a},c=e.routeMode==="loop"?(r.loopStart??0)%1:0,l=c>0&&e.route.length>0;if(n.error&&!l)return{...d,nodes:i,length:0,error:n.error,errorAt:"初期位置",periodic:!1};
let p=[n.point,...e.route.map(w=>this.terrain.project(w,e.domain).point)];e.route.length&&e.routeMode==="loop"&&p.push(n.point);let g=p.slice(1).reduce((w,x,z)=>w+qe(p[z],x),0);if(g>
0&&(r.horizontal??0)+(r.vertical??0)+(r.commonHorizontal??0)>0){let w=[n.point],x=r.scale??2e3,z=Math.min(125,this.terrain.cellSize/4,x/8),I=0;for(let A=1;A<p.length;A++){let j=p[A-
1],D=p[A],f=qe(j,D),v=Math.max(1,Math.ceil(f/z));if(v>2e4)throw new Error("航跡生成の区間が長すぎます。");for(let R=1;R<=v;R++){let H=I+f*R/v,V=ze(j,D,R/v),B=Math.min(
1,H/x,(g-H)/x),J=Math.max(0,B),$=J*J*(3-2*J),Y=nt(o,H,x),h=nt(re(this.scenario,e.groupId??e.id,"common-motion"),H,x);if(V.x+=$*(Y[0]*(r.horizontal??0)+h[0]*(r.commonHorizontal??0)),
V.y+=$*(Y[1]*(r.horizontal??0)+h[1]*(r.commonHorizontal??0)),["subsurface","air"].includes(e.domain)&&(V.z+=$*Y[2]*(r.vertical??0)),w.push(V),w.length>1e5)throw new Error("航跡生成の点数が\
多すぎます。経路を短くするか変動間隔を大きくしてください。")}I+=f}p=w}if(l){let w=[p[0]],x=Math.min(125,this.terrain.cellSize/4);for(let I=1;I<p.length;I++){
let A=p[I-1],j=p[I],D=Math.max(1,Math.ceil(Math.hypot(j.x-A.x,j.y-A.y)/x));if(D>2e4)return{...d,nodes:i,length:0,error:"経路区間が長すぎます",errorAt:"初期位置",periodic:!1};
for(let f=1;f<=D;f++)if(w.push(this.terrain.project(ze(A,j,f/D),e.domain).point),w.length>2000001)throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}
p=pn(w,c);let z=this.terrain.project(p[0],e.domain);if(i=[{...z.point,d:0}],z.error)return{...d,nodes:i,length:0,error:z.error,errorAt:"初期位置",periodic:!1}}let m=p.slice();e.
route.length&&e.routeMode==="pingpong"&&p.push(...m.slice(0,-1).reverse());let b=Math.min(125,this.terrain.cellSize/4);for(let w=1;w<p.length;w++){let x=p[w-1],z=p[w],I=Math.max(1,
Math.ceil(Math.hypot(z.x-x.x,z.y-x.y)/b));if(I>2e4)return{...d,nodes:i,length:i.at(-1).d,error:"経路区間が長すぎます",errorAt:"区間 "+w,periodic:!1};for(let A=1;A<=I;A++){
let j=this.terrain.project(ze(x,z,A/I),e.domain);if(j.error)return{...d,nodes:i,length:i.at(-1).d,error:j.error,errorAt:"区間 "+w,periodic:!1};let D=i.at(-1),f=D.d+qe(D,j.point);
if(f>D.d&&(i.push({...j.point,d:f}),++this.nodeCount>2e6))throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}}return{...d,nodes:i,length:i.
at(-1).d,error:null,errorAt:null,periodic:e.routeMode!=="once"}}evaluate(e){let n=Math.min(this.scenario.duration,Math.max(0,Number(e)||0));return{time:n,units:this.scenario.units.
map(i=>this.evaluateUnit(i,n))}}evaluateUnit(e,n,i=!0){if(e.enabled===!1)return{id:e.id,position:{...e.initial},status:"disabled",heading:0,distance:0,routeDistance:0,error:null,errorAt:null,
actualSpeed:0,startDelay:0,eta:null};let r=Math.max(0,Number(n)||0),o=i?Math.min(this.scenario.duration,r):r,s=this.paths.get(e.id),a=s.actualSpeed??e.speed,d=s.delay??0,c=a*Math.max(
0,o-d),l=!s.periodic&&a>0&&o>=d+s.length/a?Math.max(c,s.length):c,p=s.periodic&&s.length>0?l%s.length:Math.min(l,s.length),g=0,m=s.nodes.length-1;for(;g<m;){let I=Math.ceil((g+m)/2);
s.nodes[I].d<=p?g=I:m=I-1}let b=s.nodes[g],w=s.nodes[Math.min(g+1,s.nodes.length-1)],x=ze(b,w,w.d>b.d?(p-b.d)/(w.d-b.d):0);e.domain==="ground"&&(x.z=this.terrain.height(x.x,x.y)??x.
z);let z=s.length===0?"idle":"moving";return s.error&&l>=s.length?z="blocked":!s.periodic&&s.length>0&&l>=s.length?z="arrived":a===0?z="idle":o<d&&(z="waiting"),{id:e.id,position:x,
status:z,heading:Math.atan2(w.x-b.x,w.y-b.y),distance:Math.min(l,s.periodic?l:s.length),routeDistance:s.length,error:s.error,errorAt:s.errorAt,actualSpeed:a,startDelay:Number.isFinite(
d)?d:null,eta:a>0&&Number.isFinite(d)?d+s.length/a:null}}routePoints(e){return this.paths.get(e)?.nodes||[]}};function ce(t){let e=de(t);if(e.version===3)return e;e.version=3,e.behaviors??=[],e.behaviorAssignments??=[];let n=e.recording?.step??e.analysis?.step??10;e.recording??={step:n,interval:n},
e.analysis&&(e.analysis={...wt(e.analysis),step:n});for(let[i,r]of[...e.units.map(o=>["unit:"+o.id,o]),...(e.groups??[]).map(o=>["group:"+o.id,o.template])]){let o=r.behavior;if(o){
if(o.hold||o.rules.length){if(e.behaviorAssignments.some(p=>p.targets.includes(i)))throw Error("旧ルールとタスクが重複しています: "+i);let s=new Set;for(let p of o.
rules){if(s.has(p.when)||p.state!=="any"&&!(o.hold&&p.when==="received"))throw Error("自動変換できない旧ルールです。同じ条件の複数動作・状態条件はノードで再設計してください: "+
i);s.add(p.when)}let a="import-"+i.replace(":","-");if(e.behaviors.some(p=>p.id===a)||e.behaviorAssignments.some(p=>p.id===a))throw Error("変換先IDが重複しています: "+a);
let d=o.hold?"signal":"follow",c=[{id:d,kind:o.hold?"signal":"follow",x:320,y:70}],l=[];o.hold&&c.push({id:"follow",kind:"follow",x:1080,y:70}),o.rules.forEach((p,g)=>{let m=p.when===
"received"&&o.hold?"signal":"follow";p.action==="depart"?(c.push({id:p.id,kind:"wait",parameter:"preparation",seconds:o.preparation,x:680,y:70+g*150}),l.push({from:m,to:p.id,when:p.
when,once:p.once},{from:p.id,to:"follow",when:"elapsed"})):(c.push({id:p.id,kind:"report",receiverId:p.receiverId,x:680,y:70+g*150}),l.push({from:m,to:p.id,when:p.when,once:p.once},
{from:p.id,to:d,when:"sent",resume:!0},{from:p.id,to:d,when:"sendFailed",resume:!0}))}),e.behaviors.push({id:a,name:r.name+"の挙動",initial:d,triggers:[],nodes:c,edges:l}),e.behaviorAssignments.
push({id:a,name:r.name+"のタスク",behaviorId:a,targets:[i],spacing:"none",preparation:o.preparation});for(let p of[e.analysis?.factors,e.analysis?.uncertainties])for(let g of p??
[])g.target===i&&g.parameter==="behavior.preparation"&&(g.target="assignment:"+a)}delete r.behavior}}return de(e)}function He(t,e,n){let i=Math.hypot(n.x-e.x,n.y-e.y),r=Math.max(1,Math.ceil(i/Math.min(125,t.cellSize/4)));for(let o=0;o<=r;o++){let s=o/r,a=e.x+(n.x-e.x)*s,d=e.y+(n.y-e.y)*s,c=e.z+
(n.z-e.z)*s,l=t.height(a,d);if(l===null||c<l-1e-6)return!1}return!0}function at(t,e,n,i){if(i<=0||n<=0||e>=t.range||t.probabilityPerMinute<=0)return 0;if(t.probabilityPerMinute>=1)
return 1;let r=-Math.log1p(-t.probabilityPerMinute)/60;return-Math.expm1(-r*i*n*(1-e/t.range)**2)}var dt=(t,e)=>({...t,z:t.z+(e.sensor?.mountHeight??(e.domain==="ground"?2:0))}),fn=(t,e,n)=>Math.
floor(t/n)+","+Math.floor(e/n);function Dt(t,e){let n=new Map;for(let i of t){let r=fn(i.position.x,i.position.y,e);n.has(r)||n.set(r,[]),n.get(r).push(i)}return n}function*_t(t,e,n){
let i=Math.floor(e.x/n),r=Math.floor(e.y/n);for(let o=-1;o<=1;o++)for(let s=-1;s<=1;s++)for(let a of t.get(i+s+","+(r+o))??[])yield a}var mn=256*1048576;var ct=["idle","moving","arrived","blocked","waiting","standby","preparing"],Lt=128*1048576,oe=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),Ce=(t,e)=>(t%e+e)%e,Oe=(t,e,n)=>({x:t.x+(e.
x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function Te(t,e){let n=Math.min(t.length,Math.max(0,e)),i=t.nodes,r=0,o=i.length-1;for(;r<o;){let d=Math.ceil((r+o)/2);i[d].d<=n?r=d:
o=d-1}let s=i[r],a=i[Math.min(r+1,i.length-1)];return{point:Oe(s,a,a.d>s.d?(n-s.d)/(a.d-s.d):0),segment:r,heading:Math.atan2(a.x-s.x,a.y-s.y)}}function Ut(t,e){let n={point:t.nodes[0],
along:0,distance:1/0};for(let i=1;i<t.nodes.length;i++){let r=t.nodes[i-1],o=t.nodes[i],s=o.x-r.x,a=o.y-r.y,d=o.z-r.z,c=s*s+a*a+d*d,l=c?Math.max(0,Math.min(1,((e.x-r.x)*s+(e.y-r.y)*
a+(e.z-r.z)*d)/c)):0,p=Oe(r,o,l),g=oe(e,p);g<n.distance&&(n={point:p,along:r.d+(o.d-r.d)*l,distance:g})}return n}var ue=class extends xe{constructor(e){super(ce(e),{deferPaths:!0}),
this.frames=null,this.result=null,this.computeCount=0,this.nodeNames=[],this.assignments=this.source.behaviorAssignments,this.initialEvents=[];let n=new Map(this.source.behaviors.map(
i=>[i.id,i]));this.states=[],this.byId=new Map;for(let i of this.scenario.units.filter(r=>r.enabled!==!1).sort((r,o)=>r.id.localeCompare(o.id))){let r=this.assignments.find(g=>g.targets.
includes("unit:"+i.id)||i.groupId&&g.targets.includes("group:"+i.groupId)),o=r?Ae(n.get(r.behaviorId),r):null,s=o?.nodes.find(g=>g.id===o.initial),a=Re(this.source,r,s,i),c=r?.route?.
length>=2||s?.routeId?{...i,initial:a.points[0],route:a.points.slice(1),routeMode:s?.kind==="patrol"?"loop":a.mode,motion:{...i.motion,loopStart:0}}:i,l=this.compile(c);this.paths.
set(i.id,l);let p={unit:i,assignment:r,graph:o,path:l,basePath:l,pathCache:new Map,routeContexts:new Map,nearInside:new Map,node:null,nodeTime:0,position:{...l.nodes[0]},heading:0,
status:"idle",distance:0,progress:0,segment:-1,error:l.errorAt==="初期位置"?l.error:null,fired:new Set,triggerFired:new Set,triggerTimes:new Map,activated:!1,observation:null,latestObservation:null,
receivedPosition:null,moveGoal:null,moveHeight:null,trace:[],routeStarted:null,routePaused:0};if(s?.joinMode==="nearest"){let g=this.terrain.project(i.initial,i.domain);p.position=
g.point,g.error&&(p.error=g.error)}this.states.push(p),this.byId.set(i.id,p);for(let g of o?.nodes??[])this.nodeNames.includes(o.id+":"+g.id)||this.nodeNames.push(o.id+":"+g.id)}this.
inactiveUnits=this.scenario.units.filter(i=>i.enabled===!1).map(i=>super.evaluateUnit(i,0));for(let i of this.assignments){let r=this.states.filter(o=>o.assignment===i);r.forEach((o,s)=>{
o.initialPhase=Ce((i.phase??0)+(i.spacing==="none"?o.unit.motion?.loopStart??0:s/r.length),1),o.status=o.error?"blocked":"standby",o.graph.initial&&(o.activated=!0,this.enter(o,o.graph.
initial,0,!0),this.initialEvents.push({type:"initialized",time:0,unitId:o.unit.id,nodeId:o.graph.initial}))})}for(let i of this.states)i.graph||Object.assign(i,super.evaluateUnit(i.
unit,0))}enter(e,n,i,r=!1,o=!1,s=null){let a=e.node;a?.kind==="follow"&&e.routeContexts.set(a.routeId??"default",{path:e.path,started:e.routeStarted,travel:e.routeTravel??0,offset:e.
routeOffset??0,paused:i,join:e.join}),e.node=e.graph.nodes.find(c=>c.id===n),a&&e.error&&(e.error=this.terrain.project(e.position,e.unit.domain).error),e.moveHeight=e.position.z;let d=this.
observedPosition(e,s);if(e.moveGoal=e.node.kind==="move"&&se(this.source,e.assignment,e.node)?.kind==="received"&&d?{...d}:null,e.nodeTime=i,e.sent=!1,e.elapsed=!1,e.destinationArrived=
!1,e.join=null,e.nearInside=new Map([...e.nearInside].filter(([c])=>c.startsWith("trigger:"))),["follow","patrol"].includes(e.node.kind)){let c=Re(this.source,e.assignment,e.node,e.
unit),l=c.id+"|"+e.node.kind;if(r&&e.pathCache.set(l,e.path),!e.pathCache.has(l)){let p=!e.node.routeId;e.pathCache.set(l,this.compile({...e.unit,initial:c.points[0],route:c.points.
slice(1),routeMode:c.mode,motion:{...e.unit.motion,...p?{}:{loopStart:0}}}))}e.path=e.pathCache.get(l),this.paths.set(e.unit.id,e.path)}if(e.error){e.status="blocked";return}if(e.status=
"idle",e.node.kind==="patrol"){if(r&&e.node.joinMode!=="nearest"){e.progress=(e.node.joinMode==="start"?0:e.initialPhase)*e.path.length;let c=Te(e.path,e.progress);e.position=c.point,
e.heading=c.heading,e.segment=c.segment}else{let c=(e.node.joinMode??"nearest")==="nearest"?Ut(e.path,e.position):Te(e.path,0);e.progress=c.along??0,e.join=oe(e.position,c.point)>1e-7?
c.point:null}e.readyAt=i+(r?e.path.delay:0),e.status=i<e.readyAt?"waiting":"moving"}else if(e.node.kind==="follow"){let c=o?e.routeContexts.get(e.node.routeId??"default"):null;if(c&&
c.path===e.path)e.routeStarted=c.started===null?null:c.started+i-c.paused,e.routeTravel=c.travel,e.routeOffset=c.offset,e.join=c.join;else{let l=e.node.joinMode==="nearest"?Ut(e.path,
e.position):{point:e.path.nodes[0],along:0};e.routeOffset=l.along,e.routeTravel=l.along,e.routeArrived=!1,e.join=(!r||e.node.joinMode==="nearest")&&oe(e.position,l.point)>1e-7?l.point:
null,e.routeStarted=e.join?null:i-(e.path.actualSpeed?e.routeOffset/e.path.actualSpeed:0)-(e.routeOffset>0?e.path.delay:0)}e.status=e.join?"moving":i<(e.routeStarted??i)+(r?e.path.
delay:0)?"waiting":e.path.length&&e.path.actualSpeed?"moving":"idle"}else e.node.kind==="signal"?e.status="standby":e.node.kind==="wait"?e.status=e.node.parameter==="preparation"?"\
preparing":"waiting":e.node.kind==="move"&&(e.status=se(this.source,e.assignment,e.node)?.kind==="received"&&!e.moveGoal?"standby":"moving")}activate(e,n,i,r,o){if(!e?.graph||e.status===
"blocked"&&n!=="received")return!1;let s=Qe(e.graph).find(c=>c.event===n&&(n!=="near"||ae(c)===o?.conditionKey)&&(n!=="time"||Math.abs(this.nextTriggerTime(e,c)-i)<1e-8)&&(!e.triggerFired.
has(c.id)||c.once===!1));if(!s)return!1;let a=e.unit.id+"|trigger|"+s.id;if(o?.trace?.includes(a))return!1;if(o?(e.observation=o,e.trace=[...o.trace??[],a]):(e.observation=null,e.trace=
[]),e.trace.length>64)throw Error("情報の中継が64段を超えました。");e.triggerFired.add(s.id),e.triggerTimes.set(s.id,i);let d=e.node?.id;return e.activated=!0,this.enter(
e,s.to,i,!1,!1,o),r.push({type:"triggered",time:i,unitId:e.unit.id,triggerId:s.id,event:n,nodeId:s.to}),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d??null,nodeId:s.to}),
e.node.parameter==="preparation"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.
node.id}),!0}nextTriggerTime(e,n){return e.triggerFired.has(n.id)?n.once===!1?(e.triggerTimes.get(n.id)??0)+n.seconds:1/0:n.seconds}transition(e,n,i,r,o){if(!e?.graph||e.status==="\
blocked"&&n!=="received")return!1;if(this.activate(e,n,i,r,o))return!0;if(!e.node)return!1;let s=e.graph.edges.find(c=>c.from===e.node.id&&c.when===n&&(n!=="near"||ae(c)===o?.conditionKey));
if(!s)return!1;let a=e.unit.id+"|"+s.from+"|"+ae(s);if(s.once&&e.fired.has(a)||o?.trace?.includes(a))return!1;if(s.once&&e.fired.add(a),o&&(e.observation=o,e.trace=[...o.trace??[],
a]),e.trace.length>64)throw Error("情報の中継が64段を超えました。");e.node.kind==="follow"&&(e.pauseTime=i);let d=e.node.id;return this.enter(e,s.to,i,!1,s.resume,o),
r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d,nodeId:s.to}),e.node.parameter==="preparation"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.
kind==="follow"&&!s.resume&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}rememberObservation(e,n){let i=e.latestObservation,r=o=>o.observationTime??o.sampleTime??
o.time;(!i||i.targetId!==n.targetId||r(n)>=r(i))&&(e.latestObservation=n)}observedPosition(e,n){let i=e.latestObservation??e.receivedPosition,r=s=>s.observationTime??s.sampleTime??
s.time;return(n?.targetPosition&&!(i?.targetId===n.targetId&&r(i)>r(n))?n:i)?.targetPosition??null}destination(e,n=e.node,i){let r=se(this.source,e.assignment,n);return r?r.kind===
"received"?e.node?.kind==="move"&&se(this.source,e.assignment,e.node)?.id===r.id?e.moveGoal:this.observedPosition(e):r.kind==="point"?r.point:i?.get(r.unitId)??this.byId.get(r.unitId)?.
position??null:null}movementDestination(e,n){let i=this.destination(e,e.node,n),r=se(this.source,e.assignment,e.node);return i?(e.node.heightMode??(r?.kind==="point"?"target":"keep"))===
"keep"?{...i,z:e.moveHeight??e.position.z}:i:null}predict(e,n,i,r){if(e.status==="blocked"||!e.node&&e.graph)return e.position;if(!e.graph||e.node.kind==="follow"&&!e.join){let l=e.
graph?e.routeStarted??0:0;return xe.prototype.evaluateUnit.call(this,e.unit,Math.max(0,n-l),!1).position}let o=Math.max(0,n-(this.currentTime??0));if(e.node.kind==="patrol"&&!e.join)
return Te(e.path,Ce(e.progress+(i.get(e.unit.id)??e.path.actualSpeed)*Math.max(0,n-Math.max(this.currentTime??0,e.readyAt)),e.path.length||1)).point;let s=e.join??(e.node.kind==="m\
ove"?this.movementDestination(e,r):null);if(!s)return e.position;let a=this.terrain.project(s,e.unit.domain);if(a.error)return e.position;let d=oe(e.position,a.point),c=Math.min(d,
e.path.actualSpeed*o);return Oe(e.position,a.point,d?c/d:1)}replayPath(e,n){if(!e.graph)return e.path;if(!e.replayRoutes){e.replayRoutes=[{time:0,node:e.graph.nodes.find(s=>s.id===
e.graph.initial)}];for(let s of this.result.actionEvents)s.unitId===e.unit.id&&s.type==="nodeChanged"&&e.replayRoutes.push({time:s.time,node:e.graph.nodes.find(a=>a.id===s.nodeId)});
e.replayRoutes=e.replayRoutes.filter(s=>["follow","patrol"].includes(s.node?.kind))}let i=e.replayRoutes.findLast(s=>s.time<=n)?.node;if(!i)return e.basePath;let r=Re(this.source,e.
assignment,i,e.unit),o=r.id+"|"+i.kind;return e.pathCache.has(o)||e.pathCache.set(o,this.compile({...e.unit,initial:r.points[0],route:r.points.slice(1),routeMode:r.mode,motion:{...e.
unit.motion,...i.routeId?{loopStart:0}:{}}})),e.pathCache.get(o)}stateSnapshot(e,n=e.path){return{id:e.unit.id,position:{x:e.position.x,y:e.position.y,z:e.position.z},heading:e.heading,
status:e.status,distance:e.distance,routeDistance:n.length,error:e.error,errorAt:n.errorAt,actualSpeed:n.actualSpeed,startDelay:n.delay,nodeId:e.node?.id,behaviorId:e.graph?.id,eta:null}}evaluate(e){
let n=Math.max(0,Math.min(this.source.duration,Number(e)||0));if(!this.frames)return{time:0,units:[...this.states.map(g=>this.stateSnapshot(g)),...this.inactiveUnits],actionsPending:!0,
recordingPending:!0};let i=0,r=this.frames.length-1;for(;i<r;){let g=Math.ceil((i+r)/2);this.frames[g].time<=n?i=g:r=g-1}let o=this.frames[i],s=this.frames[Math.min(i+1,this.frames.
length-1)],a=s.time>o.time?(n-o.time)/(s.time-o.time):0,d=this.states.map((g,m)=>{let b=m*5,w=o.values,x=s.values,z=this.nodeNames[o.nodes[m]-1],I=Ce(x[b+3]-w[b+3]+Math.PI,Math.PI*
2)-Math.PI;return{...this.stateSnapshot(g,this.replayPath(g,n)),position:{x:w[b]+(x[b]-w[b])*a,y:w[b+1]+(x[b+1]-w[b+1])*a,z:w[b+2]+(x[b+2]-w[b+2])*a},heading:w[b+3]+I*a,distance:w[b+
4]+(x[b+4]-w[b+4])*a,status:ct[o.status[m]],nodeId:z?.split(":")[1],error:o.status[m]===3?"記録された地形制約停止":null,actualSpeed:s.time>o.time?Math.max(0,(x[b+4]-w[b+
4])/(s.time-o.time)):0}}),c=this.result,l=c.events.filter(g=>g.time<=n),p=this.source.mission;return{time:n,units:[...d,...this.inactiveUnits],actionEvents:c.actionEvents.filter(g=>g.
time<=n),mission:p?{...p.type==="state"?Be(c.stateEntries,p,c.stateTargetCount,n):{},events:l,detectedCount:new Set(l.map(g=>g.targetId)).size,targetCount:c.targetCount,reachedCount:new Set(
c.actionEvents.filter(g=>g.type==="arrived"&&g.time<=n&&p.responderIds?.includes(g.unitId)).map(g=>g.unitId)).size,responderCount:c.responderCount,status:c.successTime!==null&&c.successTime<=
n?"success":n>=p.deadline?"failure":"pending",deadline:p.deadline}:void 0,recording:{frames:this.frames.length,bytes:this.recordBytes,computeCount:this.computeCount,step:this.source.
recording.step,interval:this.source.recording.interval},actionsPending:!1}}trailPoints(e,n,i=1e3){if(!this.frames)return[];let r=this.states.findIndex(l=>l.unit.id===e);if(r<0)return[];
let o=this.frames.filter(l=>l.time<=n),s=Math.max(1,Math.ceil(o.length/i)),a=o.filter((l,p)=>p%s===0||p===o.length-1).map(l=>({x:l.values[r*5],y:l.values[r*5+1],z:l.values[r*5+2]})),
d=this.frames.findLast(l=>l.time<=n),c=this.frames.find(l=>l.time>n)??d;if(d){let l=c.time>d.time?(n-d.time)/(c.time-d.time):0,p=r*5;a.push({x:d.values[p]+(c.values[p]-d.values[p])*
l,y:d.values[p+1]+(c.values[p+1]-d.values[p+1])*l,z:d.values[p+2]+(c.values[p+2]-d.values[p+2])*l})}return a}record(e,n){if(n.at(-1)?.time===e)return;let i=this.states.length,r=new Float32Array(
i*5),o=new Uint16Array(i),s=new Uint8Array(i);if(this.states.forEach((a,d)=>{r.set([a.position.x,a.position.y,a.position.z,a.heading,a.distance],d*5),o[d]=a.node?this.nodeNames.indexOf(
a.graph.id+":"+a.node.id)+1:0,s[d]=ct.indexOf(a.status)}),n.push({time:e,values:r,nodes:o,status:s}),n.length>100001||n.length*(i*23+8)>Lt)throw Error("再生記録が128MiBを超えました。期間・個数・記録間隔\
を調整してください。")}get recordBytes(){return this.frames?.reduce((e,n)=>e+8+n.values.byteLength+n.nodes.byteLength+n.status.byteLength,0)??0}};function ut(t,e,n,i,r){let o=t.
terrain.project(n,e.unit.domain);if(o.error)return e.status="blocked",e.error=o.error,!1;let s=oe(e.position,o.point),a=Math.min(s,i*r),d=Oe(e.position,o.point,s?a/s:1),c=Math.max(
1,Math.ceil(a/Math.min(125,t.terrain.cellSize/4)));for(let l=1;l<=c;l++){let p=t.terrain.project(Oe(e.position,d,l/c),e.unit.domain);if(p.error)return e.status="blocked",e.error=p.
error,!1}return e.heading=Math.atan2(d.x-e.position.x,d.y-e.position.y),e.position=t.terrain.project(d,e.unit.domain).point,e.distance+=a,e.status=s<=a+1e-7?"arrived":"moving",e.status===
"arrived"}function*Bt(t,e=t.source?.mission??t.scenario.mission,n,i={}){let r=t instanceof ue?t:new ue(t.source),o=i.horizon??(r.source.measurements?.length?r.source.duration:e?.deadline??
r.source.duration),s=i.record??!1,a=r.source.recording.step,d=r.source.recording.interval;if(!Number.isFinite(o)||o<0||o>r.source.duration)throw Error("計算終了時刻が不正です。");
if(r.computeCount)throw Error("計算済みです。新しい試行を作成してください。");r.computeCount++;let c=r.states,l=[...r.initialEvents],p=new Map,g=new Set,m=[],
b=s?[]:null,w=c.filter(h=>h.unit.faction!=="neutral"),x=e?.type==="state"?[]:e?.targetIds?e.targetIds.map(h=>r.byId.get(h)).filter(Boolean):c.filter(h=>e?h.unit.faction===e.targetFaction:
h.unit.faction!=="neutral");if(e&&e.type!=="state"&&e.targetIds?.some(h=>!r.scenario.units.some(S=>S.id===h&&S.faction===e.targetFaction))||e?.type==="detect"&&!r.scenario.units.some(
h=>h.faction===e.targetFaction))throw Error("成功条件に合う対象がありません。");let z=e?.type==="arrive"?e.responderIds.filter(h=>r.byId.has(h)):[],I=e?.type==="sta\
te"?new he(e,c.filter(h=>h.assignment?.id===e.assignmentId).map(h=>h.unit.id)):null,A={success:!1,successTime:null,targetCount:e?.type==="state"?w.length:x.length,detectedCount:0,responderCount:z.
length,reachedCount:0,events:[],actionEvents:l,invalidUnits:c.filter(h=>h.error).length,constrainedPaths:0},j=0,D=0,f=0,v=Math.max(1,...c.filter(h=>h.unit.sensor?.enabled).map(h=>h.
unit.sensor.range)),R=(h,S,T,C={})=>(l.push({type:S,time:T,unitId:h.unit.id,nodeId:h.node?.id,...C}),r.transition(h,S,T,l,C));function H(){let h=new Map;for(let S of r.assignments){
let T=new Map;for(let C of c.filter(y=>y.assignment===S&&y.node?.kind==="patrol"&&y.status!=="blocked"&&!y.join)){let y=C.node.routeId??"default";T.has(y)||T.set(y,[]),T.get(y).push(
C)}for(let C of T.values()){C.sort((y,E)=>y.progress/y.path.length-E.progress/E.path.length||y.unit.id.localeCompare(E.unit.id));for(let y=0;y<C.length;y++){let E=C[y],F=C[(y+1)%C.
length],M=E.path.actualSpeed,O=M*(E.node.speedFraction??.7),U=O;if(S.spacing!=="none"&&C.length>1){let ee=(F.progress/F.path.length-E.progress/E.path.length+(y===C.length-1?1:0))*E.
path.length,u=S.spacing==="fixed"?S.spacingDistance??500:E.path.length/C.length,P=(S.gain??.01)*(ee-u),L=P<0?O*.5:M-O;L>0&&(U+=L*Math.tanh(P/L))}h.set(E.unit.id,U)}}}return h}function V(h,S){
let T=h.unit.communication,C=r.byId.get(h.node.receiverId??h.assignment.receiverId),y=C?oe(h.position,C.position):1/0,E=h.observation?.type==="received"&&h.observation.targetPosition?
h.observation:h.latestObservation??(h.observation?.targetPosition?h.observation:null),F=re(r.source,h.unit.id,"unified-report-v2")+"|"+JSON.stringify([h.node.id,E?.targetId,E?.originObserverId??
E?.observerId??h.unit.id]),M=null;T?.enabled?C?y>T.range?M="通信範囲外":T.terrainLOS&&!He(r.terrain,h.position,C.position)?M="地形遮蔽":q(F)>=T.probability&&(M="通信試行失敗"):
M="受信先不在（無効・計算対象外）":M="通信無効",h.sent=!0;let O={receiverId:C?.unit.id,distance:Number.isFinite(y)?y:null,reason:M,targetId:E?.targetId,targetPosition:E?.
targetPosition?{...E.targetPosition}:void 0,observationTime:E?.observationTime??E?.sampleTime??E?.time,originObserverId:E?.originObserverId??E?.observerId??h.unit.id,trace:[...h.trace],
sourcePosition:{...h.position},receiverPosition:C?{...C.position}:void 0};return M||m.push({...O,type:"received",time:S+T.delay,unitId:C.unit.id,senderId:h.unit.id}),R(h,M?"sendFai\
led":"sent",S,O)}function B(h){return[...(h.graph?.triggers??[]).filter(S=>S.event==="near").map(S=>({c:S,key:"trigger:"+S.id})),...(h.graph?.edges??[]).filter(S=>S.from===h.node?.
id&&S.when==="near").map(S=>({c:S,key:"edge:"+S.from+"|"+ae(S)}))]}function J(h,S){let T=!1;for(let{c:C,key:y}of B(h)){let E=r.destination(h,C);if(!E)continue;let F=yt(h.position,E,
C.distanceMode),M=F<=C.distance+1e-6,O=h.nearInside.get(y)??!1;if(h.nearInside.set(y,M),M&&!O&&!(y.startsWith("trigger:")&&C.once!==!1&&h.triggerFired.has(C.id))){let U={destinationId:C.
destinationId,distance:F,distanceMode:C.distanceMode??"absolute",conditionKey:ae(C)};if(R(h,"near",S,U)){T=!0;break}}}return T}function $(h,S,T){let C=new Map(c.map(M=>[M.unit.id,{
...M.position}])),y=new Set;for(let M of c)for(let{c:O}of B(M)){y.add(M);let U=se(r.source,M.assignment,O);U?.kind==="unit"&&r.byId.has(U.unitId)&&y.add(r.byId.get(U.unitId))}if(!y.
size)return S;for(let M of y)if(M.status!=="blocked"&&(M.join&&M.path.actualSpeed&&(S=Math.min(S,h+oe(M.position,M.join)/M.path.actualSpeed)),!M.join&&(!M.graph||["follow","patrol"].
includes(M.node?.kind))&&M.path.actualSpeed&&M.path.length)){let O=M.node?.kind==="patrol"?M.progress:Ce(M.routeTravel??M.distance,M.path.length),U=M.path.nodes.find(ee=>ee.d>O+1e-7);
U&&(S=Math.min(S,h+(U.d-O)/(T.get(M.unit.id)??M.path.actualSpeed)))}let E=new Map(c.map(M=>[M.unit.id,r.predict(M,S,T,C)])),F=S;for(let M of c)for(let{c:O,key:U}of B(M)){if(M.nearInside.
get(U)||U.startsWith("trigger:")&&O.once!==!1&&M.triggerFired.has(O.id))continue;let ee=r.destination(M,O,C),u=r.destination(M,O,E);if(!ee||!u)continue;let P=M.position,L=E.get(M.unit.
id),k=[P.x-ee.x,P.y-ee.y,O.distanceMode==="horizontal"?0:P.z-ee.z],_=[L.x-u.x-k[0],L.y-u.y-k[1],O.distanceMode==="horizontal"?0:L.z-u.z-k[2]],G=_.reduce((W,ne)=>W+ne*ne,0),K=2*k.reduce(
(W,ne,je)=>W+ne*_[je],0),ge=k.reduce((W,ne)=>W+ne*ne,0)-O.distance*O.distance,Me=K*K-4*G*ge;if(G>1e-12&&ge>1e-6&&Me>=0){let W=(-K-Math.sqrt(Me))/(2*G);W>1e-9&&W<=1&&(F=Math.min(F,h+
(S-h)*W))}}return F}function Y(h){let S=!1;for(let y of c)for(let E=0;E<(y.graph?.triggers.length??0)&&r.activate(y,"time",h,l);E++)S=!0;let T=y=>{for(let E=0;E<64;E++){if(y.status===
"blocked")return;let F=J(y,h);if(F){S=!0;continue}if(y.node?.kind==="report"&&!y.sent?F=V(y,h):y.node?.kind==="wait"&&!y.elapsed&&h-y.nodeTime>=(y.node.parameter==="preparation"?y.
assignment.preparation??y.node.seconds:y.node.seconds)&&(y.elapsed=!0,F=R(y,"elapsed",h)),S=S||F,!F)return}throw Error("即時ノード遷移が64段を超えました。循環を見直してください。")};
for(let y of c)T(y);let C=0;for(;;){if(m.sort((F,M)=>F.time-M.time||F.unitId.localeCompare(M.unitId)),!m[0]||m[0].time>h)return S;if(++C>1e5||l.length>1e5)throw Error("情報イベントが10万件を\
超えました。");let y=m.shift(),E=r.byId.get(y.unitId);if(l.push(y),E.observation=y,y.targetPosition&&["x","y","z"].every(F=>Number.isFinite(y.targetPosition[F]))){let F=E.receivedPosition;
(!F||F.targetId!==y.targetId||(y.observationTime??y.time)>=(F.observationTime??F.time))&&(E.receivedPosition={...y,targetPosition:{...y.targetPosition}},r.rememberObservation(E,E.receivedPosition))}
S=r.transition(E,"received",h,l,y)||S,T(E)}}Y(0),I&&Object.assign(A,I.update(l)),s&&r.record(0,b);for(let h=0;h<o;){let S=Math.min(o,(Math.floor((h+1e-8)/a)+1)*a,e?.deadline>h?e.deadline:
1/0),T=1/0;for(let u of m)u.time>h+1e-8&&(T=Math.min(T,u.time));for(let u of c)if(u.status!=="blocked"){if(u.node?.kind==="wait"&&!u.elapsed){let P=u.node.parameter==="preparation"?
u.assignment.preparation??u.node.seconds:u.node.seconds;u.nodeTime+P>h+1e-8&&(T=Math.min(T,u.nodeTime+P))}for(let P of u.graph?.triggers??[])if(P.event==="time"){let L=r.nextTriggerTime(
u,P);L>h+1e-8&&(T=Math.min(T,L))}if((!u.graph||u.node?.kind==="follow")&&!u.join&&!u.path.periodic&&u.path.length&&u.path.actualSpeed&&!u.routeArrived){let P=(u.graph?u.routeStarted??
0:0)+u.path.delay+u.path.length/u.path.actualSpeed;P>h+1e-8&&(T=Math.min(T,P))}if(u.join&&u.path.actualSpeed){let P=h+oe(u.position,u.join)/u.path.actualSpeed;P>h+1e-8&&(T=Math.min(
T,P))}if(u.node?.kind==="move"&&u.status!=="arrived"&&u.path.actualSpeed&&["point","received"].includes(se(r.source,u.assignment,u.node)?.kind)&&r.movementDestination(u)){let P=h+oe(
u.position,r.terrain.project(r.movementDestination(u),u.unit.domain).point)/u.path.actualSpeed;P>h+1e-8&&(T=Math.min(T,P))}}r.currentTime=h;let C=H(),y=$(h,Math.min(S,T),C),E=y-h,F=new Map(
c.map(u=>[u.unit.id,{...u.position}])),M=new Map(c.map(u=>[u.unit.id,r.predict(u,y,C,F)])),O=!1;for(let u of c)if(u.status!=="blocked"&&!(u.graph&&!u.node)){if(u.node?.kind==="foll\
ow"&&u.join){ut(r,u,u.join,u.path.actualSpeed,E)&&(u.join=null,u.routeStarted=y-(u.path.actualSpeed?u.routeOffset/u.path.actualSpeed:0)-(u.routeOffset>0?u.path.delay:0),u.routeTravel=
u.routeOffset),O=!0;continue}if(!u.graph||u.node.kind==="follow"){let P=u.status,L=u.segment,k=u.graph?u.routeStarted??0:0,_=xe.prototype.evaluateUnit.call(r,u.unit,Math.max(0,y-k),
!1);if(u.graph){let G=u.distance+Math.max(0,_.distance-(u.routeTravel??0));u.routeTravel=_.distance,Object.assign(u,_),u.distance=G}else Object.assign(u,_);u.segment=Te(u.path,u.path.
periodic?_.distance%u.path.length:_.distance).segment,(P!==u.status||L!==u.segment)&&(O=!0),u.status==="arrived"&&!u.routeArrived&&(u.routeArrived=!0,O=R(u,"arrived",y)||O)}else if(u.
node.kind==="patrol"){if(y<=u.readyAt){u.status="waiting";continue}let P=y-Math.max(h,u.readyAt);if(u.join){ut(r,u,u.join,u.path.actualSpeed,P)&&(u.join=null),O=!0;continue}if(!u.path.
length){u.status="blocked",u.error="周回経路の長さが0です。",O=!0;continue}let L=(C.get(u.unit.id)??u.path.actualSpeed)*P,k=u.progress+L;if(u.path.error&&k>=u.path.length){
u.position={...u.path.nodes.at(-1)},u.status="blocked",u.error=u.path.error,O=!0;continue}u.progress=Ce(k,u.path.length);let _=Te(u.path,u.progress);u.position=_.point,u.heading=_.
heading,u.distance+=L,u.status="moving",_.segment!==u.segment&&(O=!0,u.segment=_.segment)}else if(u.node.kind==="move"){let P=r.movementDestination(u,M),L=se(r.source,u.assignment,
u.node)?.kind,k=L==="unit";if(!P){if(L==="received"){u.status="standby";continue}u.status="blocked",u.error="目的地が見つかりません。",O=!0;continue}(u.status!=="arrive\
d"||k)&&ut(r,u,P,u.path.actualSpeed,E)&&u.status==="arrived"&&!u.destinationArrived&&(u.destinationArrived=!0,O=!0,R(u,"arrived",y))}}if(Math.abs(y-S)<1e-8){let u=c.filter(k=>k.unit.
sensor?.enabled&&k.status!=="blocked"&&k.node?.kind!=="stop"&&k.node?.sensor!==!1),P=Dt(u.map(k=>({unit:k.unit,position:dt(k.position,k.unit),state:k})),v),L=[];for(let k of w){if(k.
error&&k.path.errorAt==="初期位置"||k.unit.detectability===0)continue;let _=dt(k.position,{domain:k.unit.domain});for(let G of _t(P,_,v)){++j%256===0&&(yield{time:h,result:A});
let K=G.state,ge=K.unit.sensor,Me=K.unit.id+"|"+k.unit.id;if(K.unit.faction===k.unit.faction||!ge.domains.includes(k.unit.domain))continue;let W=oe(G.position,_),ne=at(ge,W,k.unit.
detectability??1,y-f);if(!(ne<=0||ge.terrainLOS&&!He(r.terrain,G.position,_))&&q(re(r.source,K.unit.id,"unified-detect-v2")+"|"+JSON.stringify([k.unit.id,f,y]))<ne){let je={type:"d\
etected",time:y,sampleTime:y,observationTime:y,observerId:K.unit.id,unitId:K.unit.id,targetId:k.unit.id,distance:W,observerPosition:{...G.position},targetPosition:{..._},trace:[]};
r.rememberObservation(K,je),(!g.has(Me)||K.graph?.triggers.some(pt=>pt.event==="detected"&&pt.once===!1))&&L.push(je),g.add(Me)}}}L.sort((k,_)=>k.unitId.localeCompare(_.unitId)||k.
targetId.localeCompare(_.targetId));for(let k of L){let _=r.byId.get(k.unitId);(!e||e.type==="state"||_.unit.faction===e.observerFaction&&x.some(G=>G.unit.id===k.targetId))&&!p.has(
k.targetId)&&(p.set(k.targetId,k),A.events.push(k)),_.observation=k,O=R(_,"detected",y,k)||O}f=y}if(O=Y(y)||O,l.length+m.length>1e5)throw Error("行動イベントが10万件を超えました。");
A.detectedCount=A.events.filter(u=>!e||u.time<=e.deadline).length,A.reachedCount=new Set(l.filter(u=>u.type==="arrived"&&z.includes(u.unitId)&&(!e||u.time<=e.deadline)).map(u=>u.unitId)).
size,I&&Object.assign(A,I.update(l));let U=e?.type==="arrive"?A.reachedCount:A.detectedCount,ee=e?.join==="all"?e.type==="arrive"?z.length:x.length:1;if(e&&e.type!=="state"&&ee>0&&
y<=e.deadline&&U>=ee&&A.successTime===null&&(A.success=!0,A.successTime=y),s&&(O||y-D>=d-1e-8||y===o)&&(r.record(y,b),D=y),h=y,yield{time:y,result:A},!r.source.measurements?.length&&
!s&&!c.some(u=>u.graph)&&e?.type==="detect"&&A.detectedCount===x.length)break}return r.source.measurements?.length&&(A.measurements=ot(r.source,l,o)),A.constrainedPaths=c.filter(h=>h.
status==="blocked").length,s&&(r.frames=b,r.result=A),A}var Jt=t=>new ue(t);function*Yt(t,e=t.scenario.mission,n=t.scenario.analysis?.step??10,i={}){if(!(t instanceof ue)&&t.source.version!==3&&n!==void 0){let r=ce(t.source);r.recording={step:n,interval:n},
r.analysis&&(r.analysis.step=n),t=new ue(r)}return yield*Bt(t,e,n,i)}function gn(t,e){if(e===0)return{rate:null,low:null,high:null};let n=1.959963984540054,i=t/e,r=1+n*n/e,o=(i+n*n/(2*e))/r,s=n*Math.sqrt(i*(1-i)/e+n*n/(4*e*e))/r;return{rate:i,low:Math.
max(0,o-s),high:Math.min(1,o+s)}}function we(t){let e=ce(t),n=[...Je(e.mission,e.duration),...Ye(e.analysis,e.duration)];if((!e.mission||!e.analysis)&&n.push("成功条件と分析条件を設定してください。"),
n.length)throw new Error(n.join(`
`));let i=e.analysis,r=e.trial??0;if(r+i.trials-1>1e9)throw new Error("試行番号の上限を超えます。");let o=At(e);for(let s of o){for(let a of[...s.settings,...i.uncertainties??
[]])pe(e,a);de(be(e,s,r,{maximum:!0}).scenario)}return{scenario:e,analysis:i,startTrial:r,conditions:o}}function lt(t,e){let n=e.filter(s=>s.success).length,i=e.filter(s=>s.success).
map(s=>s.successTime).sort((s,a)=>s-a),r=i.length,o=r?r%2?i[(r-1)/2]:(i[r/2-1]+i[r/2])/2:null;return{count:t,total:e.length,successes:n,...gn(n,e.length),median:o,invalidTrials:e.filter(
s=>s.invalidUnits>0).length,trials:e}}function vn(t){let e=$e(t);return e.analysis.factors=[],delete e.analysis.groupId,delete e.analysis.counts,delete e.analysis.mode,delete e.analysis.sensitivity,delete e.analysis.plans,
e}function qt(t){let e=ce(t),n=e.analysis?.sensitivity,i=_e(e);if(n?.candidates.length||i.push("感度分析で調べる性能を一つ以上選択してください。"),i.length)
throw Error(i.join(`
`));let r=vn(e),o=we(r),s=ke(e).find(d=>d.id===n.metric),a=[{id:"baseline",index:1,label:"基準条件（現在の設定）",settings:[]}];for(let d of n.candidates){let c=pe(e,d);
if(d.low>c||d.high<c)throw Error(De(e,d,c)+"：小さい値 ≤ 基準値 ≤ 大きい値にしてください。");if(d.low===c&&d.high===c)throw Error("基準値と異なる値を一つ以上指定してください。");
for(let[l,p]of[["low",d.low],["high",d.high]]){if(p===c)continue;let g={target:d.target,parameter:d.parameter,value:p};a.push({id:JSON.stringify([Q(d),l,p]),index:a.length+1,label:De(
e,d,p),settings:[g],candidate:{target:d.target,parameter:d.parameter},direction:l,baseValue:c})}}if(a.length*o.analysis.trials>1e4)throw Error("感度分析の条件数×試行数は10000以下にしてください。");
for(let d of a)de(be(r,d,o.startTrial,{maximum:!0}).scenario);return{...o,scenario:e,trialSource:r,metric:s,conditions:a}}function bn(t,e){let n=t.analysis.plans.items.find(r=>"plan:"+r.id===e.id);if(!n)throw Error("運用案が見つかりません。");let i=Ue(t,n);i.analysis.factors=[];for(let r of[
"mode","plans","sensitivity","groupId","counts"])delete i.analysis[r];return i}function $t(t){let e=ce(t),n=e.analysis?.plans;if(!n||n.items.length<2)throw Error("比較する運用案を2件以上保存してく\
ださい。");let i=zt(e);if(!i)throw Error("運用案の評価指標を選択してください。");if(n.items.length*e.analysis.trials>1e4)throw Error("運用案数×試行数は10000以下にしてください。");
let o=[n.items.find(d=>d.id===n.baselineId),...n.items.filter(d=>d.id!==n.baselineId)].map((d,c)=>({id:"plan:"+d.id,index:c+1,label:d.name,settings:[],planId:d.id})),s={},a;for(let d of o)
try{let c=bn(e,d);a=we(c),s[d.id]=a.scenario}catch(c){throw Error("運用案「"+d.label+"」: "+c.message)}return{...a,scenario:e,conditions:o,sources:s,metric:i}}var Ie=0;self.onmessage=({data:t})=>{if(t.type==="ping"){self.postMessage({type:"pong",build:ft});return}if(t.type==="cancel"){Ie++;return}["run","sensitivity","plans"].includes(t.
type)&&xn(t,++Ie)};async function xn(t,e){let n=performance.now();try{let{scenario:i,trialSource:r,sources:o,analysis:s,startTrial:a,conditions:d}=t.type==="plans"?$t(t.scenario):t.
type==="sensitivity"?qt(t.scenario):we(t.scenario),c=[],l=d.length*s.trials,p=0,g=0,m=performance.now();for(let b of d){let w=[];for(let x=0;x<s.trials;x++){if(e!==Ie)return;let z=a+
x,{scenario:I,sampled:A}=be(o?.[b.id]??r??i,b,z),j=Jt(I),D=Yt(j,I.mission,s.step),f=D.next();for(;!f.done;){if(performance.now()-m>16&&(await new Promise(R=>setTimeout(R,0)),m=performance.
now(),e!==Ie))return;f=D.next()}let v=f.value;w.push({...v.measurements?{measurements:v.measurements}:{},...I.mission?.type==="state"?{stateEntries:v.stateEntries,stateTargetCount:v.
stateTargetCount,stateReachedCount:v.stateReachedCount}:{},reachedCount:v.reachedCount??0,responderCount:v.responderCount??0,trial:z,sampled:A,success:v.success,successTime:v.successTime,
detectedCount:v.detectedCount,targetCount:v.targetCount,invalidUnits:v.invalidUnits,constrainedPaths:v.constrainedPaths}),p++,(performance.now()-g>120||x===s.trials-1)&&(g=performance.
now(),self.postMessage({type:"progress",runId:t.runId,completed:p,planned:l,elapsedMs:performance.now()-n,rows:[...c,{...lt(b.count,w),condition:b}]})),await new Promise(R=>setTimeout(
R,0)),m=performance.now()}c.push({...lt(b.count,w),condition:b})}e===Ie&&self.postMessage({type:"complete",runId:t.runId,completed:p,planned:l,elapsedMs:performance.now()-n,rows:c})}catch(i){
e===Ie&&self.postMessage({type:"error",runId:t.runId,message:i.message})}}})();
