/* SimSim portable 20261005-text-files-10-c089c119936b. Generated by npm run build:portable. */
(()=>{var bt={number:"数値",route:"経路",destination:"目的地",unit:"単体ユニット"},$e={routeId:"route",destinationId:"destination",receiverId:"unit",seconds:"number",speedFraction:"\
number",distance:"number"},G=t=>!!t&&typeof t=="object"&&!Array.isArray(t)&&Object.keys(t).length===1&&typeof t.$param=="string";function fe(t,e,n){if(!G(t))return t;let i=Array.isArray(
e?.parameters)?e.parameters.find(r=>r?.id===t.$param):null;return Object.hasOwn(n?.parameters??{},t.$param)?n.parameters[t.$param]:i?.default}function he(t,e){if(!t)return t;let n=i=>i&&
typeof i=="object"?Object.fromEntries(Object.entries(i).map(([r,o])=>[r,fe(o,t,e)])):i;return{...t,nodes:t.nodes.map(n),edges:t.edges.map(n),triggers:(t.triggers??[]).map(n)}}function je(t,e,n){
if(!Array.isArray(e.nodes)||!Array.isArray(e.edges)||e.triggers!==void 0&&!Array.isArray(e.triggers))return["挙動のノード・条件の形式が不正です。"];let i=[],r=e.parameters??
[],o=new Set;if(!Array.isArray(r)||r.length>64)return["担当時に指定する値は最大64件の配列です。"];let a=(s,d)=>s.type==="number"?Number.isFinite(d):typeof d=="st\
ring"&&(s.type==="route"?t.routes:s.type==="destination"?t.destinations:t.units)?.some?.(c=>c.id===d);for(let s of r){if(!s||!/^[a-zA-Z0-9_-]{1,80}$/.test(s.id??"")||o.has(s.id)||typeof s.
name!="string"||!s.name.trim()||s.name.length>120||!Object.hasOwn(bt,s.type)){i.push("担当値のID・名前・種類が不正または重複しています。");continue}o.add(s.
id),s.unit!==void 0&&(s.type!=="number"||!["s","m","ratio"].includes(s.unit))&&i.push("担当値の単位が不正です。"),Object.hasOwn(s,"default")&&!a(s,s.default)&&i.push("担\
当値「"+s.name+"」の既定値が不正です。"),n&&!a(s,fe({$param:s.id},e,n))&&i.push("タスク「"+n.name+"」で「"+s.name+"」を指定してください。")}for(let s of[
...e.nodes,...e.edges,...e.triggers??[]].filter(d=>d&&typeof d=="object"))for(let[d,c]of Object.entries(s))if(c&&typeof c=="object"&&(Object.hasOwn(c,"$param")||$e[d])){let f=G(c)?
r.find(g=>g?.id===c.$param):null,l={seconds:"s",distance:"m",speedFraction:"ratio"}[d];(!f||f.type!==$e[d]||l&&f.unit&&f.unit!==l)&&i.push("担当値の参照・種類・単位が不正です: "+
d)}return n?.parameters!==void 0&&(!n.parameters||typeof n.parameters!="object"||Array.isArray(n.parameters)||Object.keys(n.parameters).some(s=>!o.has(s)))&&i.push("タスクの担当値に未定義の項目が\
あります。"),i}function Me(t,e,n,i){let r=t.behaviors?.find(s=>s.id===e?.behaviorId),o=fe(n?.routeId,r,e),a=o?t.routes?.find(s=>s.id===o):null;return{id:a?.id??"default",points:a?.points??e?.route??
[i.initial,...i.route],mode:n?.kind==="patrol"?"loop":a?.mode??e?.routeMode??i.routeMode}}function me(t,e,n){let i=fe(n?.destinationId,t.behaviors?.find(r=>r.id===e?.behaviorId),e);
return i?t.destinations?.find(r=>r.id===i):e?.base?{kind:"point",point:e.base}:null}function X(t){let e=t.when??t.event;return e==="near"?[e,t.destinationId,t.distance,t.distanceMode??
"absolute"].map(n=>G(n)?JSON.stringify(n):n).join("|"):e==="time"?e+"|"+(G(t.seconds)?JSON.stringify(t.seconds):t.seconds):e}var He=(t,e,n="absolute")=>Math.hypot(t.x-e.x,t.y-e.y,n===
"horizontal"?0:t.z-e.z);function Ke(t){let e=[],n=(r,o,a)=>Number.isFinite(r)&&r>=o&&r<=a,i=r=>r&&["x","y","z"].every(o=>n(r[o],-1e6,1e6));for(let[r,o]of[["routes",128],["destinati\
ons",256]]){let a=t[r]??[],s=new Set;if(!Array.isArray(a)||a.length>o){e.push(r==="routes"?"経路は最大128件の配列です。":"目的地は最大256件の配列です。");continue}
for(let d of a){if(!d||!/^[a-zA-Z0-9_-]{1,80}$/.test(d.id??"")||s.has(d.id)||typeof d.name!="string"||!d.name.trim()||d.name.length>120){e.push("経路・目的地のIDまたは名前が不正・重複しています。");
continue}s.add(d.id),r==="routes"?((!Array.isArray(d.points)||d.points.length<2||d.points.length>500||d.points.some(c=>!i(c)))&&e.push("経路は2～500点の座標で指定してください。"),
["once","loop","pingpong"].includes(d.mode??"once")||e.push("経路の繰り返し方式が不正です。")):d.kind==="point"?i(d.point)||e.push("目的地の地点座標が不正です。"):
d.kind==="unit"?t.units?.some(c=>c.id===d.unitId)||e.push("目的地のユニットがありません。"):e.push("目的地は地点またはユニットを指定してください。")}}
return e}function Oe(t,e,n=!1){let i=[];return!(n&&G(e.destinationId))&&(!Array.isArray(t.destinations)||!t.destinations.some(r=>r?.id===e.destinationId))&&i.push("接近条件の目的地を選択してくださ\
い。"),!(n&&G(e.distance))&&(!Number.isFinite(e.distance)||e.distance<0||e.distance>1e6)&&i.push("接近距離は0～1000000mです。"),["horizontal","absolute"].includes(e.distanceMode??
"absolute")||i.push("距離の種類は水平距離または絶対距離です。"),i}var vt={follow:"経路を進む",patrol:"協調して周回",signal:"情報を待つ",report:"報告",move:"目的に向かって進む",wait:"時間待ち",stop:"終了"},It={received:"\
情報受信",time:"時間経過",detected:"対象探知",near:"指定距離まで近づく"};function Ve(t){return t.initial??t.entry??(Array.isArray(t.triggers)?t.triggers.find(e=>e?.
event==="scenarioStart")?.to:void 0)}function Pe(t){return(t.triggers??[]).filter(e=>e?.event!=="scenarioStart")}function Ge(t){for(let e of t.behaviors??[]){let n=Ve(e);n!==void 0&&
(e.initial=n),e.triggers=Pe(e);for(let i of e.triggers)delete i.policy;for(let i of e.nodes)i.kind==="return"&&(i.kind="move");delete e.entry}return t}var wt={follow:["detected","received","arrived","near"],patrol:["detected","received","near"],signal:["received","detected","near"],report:["sent","sendFailed","near"],move:["arriv\
ed","received","detected","near"],return:["arrived","received","detected","near"],wait:["elapsed","received","detected","near"],stop:[]};var H=(t,e,n)=>Number.isFinite(t)&&t>=e&&t<=n,Ne=t=>t&&["x","y","z"].every(e=>H(t[e],-1e6,1e6));function Fe(t,e=!1){let n=Ke(t),i=t.behaviors??[],r=t.behaviorAssignments??[];if(!Array.
isArray(i)||i.length>50)return["挙動は最大50件の配列です。"];if(!Array.isArray(r)||r.length>100)return["タスクは最大100件の配列です。"];let o=Array.isArray(
t.routes)?t.routes:[],a=Array.isArray(t.destinations)?t.destinations:[],s=new Set,d=new Set,c=new Set;for(let h of i){if(!h||!/^[a-zA-Z0-9_-]{1,80}$/.test(h.id??"")||s.has(h.id)){n.
push("挙動IDが不正または重複しています。");continue}if(s.add(h.id),(typeof h.name!="string"||!h.name.trim()||h.name.length>120)&&n.push("挙動名は1～120文字です。"),
!Array.isArray(h.nodes)||!h.nodes.length||h.nodes.length>64||!Array.isArray(h.edges)||h.edges.length>128){n.push("挙動は1～64ノード、最大128接続です。");continue}e||
n.push(...je(t,h));let w=(p,R,L)=>!e&&G(p)||H(p,R,L),v=p=>!G(p),M=new Map,T=new Set;for(let p of h.nodes){if(!p||!/^[a-zA-Z0-9_-]{1,80}$/.test(p.id??"")||M.has(p.id)||!(vt[p.kind]||
p.kind==="return")){n.push("ノードID・種類が不正です。");continue}M.set(p.id,p),p.routeId!==void 0&&(!["follow","patrol"].includes(p.kind)||v(p.routeId)&&!o.some(R=>R?.
id===p.routeId))&&n.push("状態ノードの経路参照が不正です。"),p.destinationId!==void 0&&(!["move","return"].includes(p.kind)||v(p.destinationId)&&!a.some(R=>R?.id===
p.destinationId))&&n.push("状態ノードの目的地参照が不正です。"),p.kind==="patrol"&&p.routeId&&v(p.routeId)&&o.find(R=>R?.id===p.routeId)?.points?.length<3&&n.push(
"周回経路は3点以上必要です。"),p.kind==="wait"&&!w(p.seconds,0,86400)&&n.push("待機時間は0～86400秒です。"),p.kind==="patrol"&&!w(p.speedFraction??.7,.05,1)&&
n.push("巡回速度比は0.05～1です。"),p.kind==="report"&&!p.receiverId&&!p.receiverRole&&n.push("報告先または報告先の役割を指定してください。"),p.receiverId&&
v(p.receiverId)&&!t.units?.some(R=>R.id===p.receiverId)&&n.push("報告先の単体ユニットがありません: "+p.receiverId),p.joinMode!==void 0&&(!["follow","patrol"].includes(
p.kind)||!["start","nearest"].includes(p.joinMode))&&n.push("経路への入り方は最初から／最短地点からを選択してください。"),p.sensor!==void 0&&typeof p.sensor!=
"boolean"&&n.push("ノードのsensorはbooleanです。"),(p.x!==void 0&&!H(p.x,0,4e3)||p.y!==void 0&&!H(p.y,0,4e3))&&n.push("ノード位置が不正です。")}let I=Ve(h),S=h.triggers??
[],F=new Set,j=new Set;if(I!==void 0&&!M.has(I)&&n.push("初期状態の参照先がありません。"),(h.initial!==void 0&&h.entry!==void 0&&h.initial!==h.entry||h.triggers?.some?.(
p=>p?.event==="scenarioStart"&&p.to!==I))&&n.push("初期状態の指定が重複しています。"),!Array.isArray(S)||S.length>32)n.push("イベントノードは最大32件の配列です。");else if(I===
void 0&&!S.length)n.push("初期状態またはイベントノードを指定してください。");else for(let p of S){(!p||!/^[a-zA-Z0-9_-]{1,80}$/.test(p.id??"")||F.has(p.id)||
!(Object.hasOwn(It,p.event)||p.event==="scenarioStart")||!M.has(p.to))&&n.push("イベントノードのID・種類・接続先が不正です。"),F.add(p?.id);let R=p?X(p):"";j.has(
R)&&n.push("同じイベント・時間のイベントノードは一つだけ指定できます。"),j.add(R),p?.event==="time"&&(!w(p.seconds,0,86400)||p.once===!1&&p.seconds===0)&&
n.push("時間イベントは0～86400秒、繰り返す場合は0より大きい秒数です。"),p?.policy!==void 0&&!["idle","interrupt"].includes(p.policy)&&n.push("起動方法はidle・i\
nterruptです。"),p?.once!==void 0&&typeof p.once!="boolean"&&n.push("イベントノードのonceはbooleanです。"),p?.event==="near"&&n.push(...Oe(t,p,!e)),(p?.x!==void 0&&!H(
p.x,0,4e3)||p?.y!==void 0&&!H(p.y,0,4e3))&&n.push("イベントノードの位置が不正です。")}for(let p of h.edges){let R=p?.from+"|"+(p?X(p):""),L=M.get(p?.from);(!p||!L||
!M.has(p.to)||!(wt[L.kind]??[]).includes(p.when)||T.has(R))&&n.push("接続条件が始点ノードに対応しないか、接続が不正・重複しています。"),p?.once!==void 0&&
typeof p.once!="boolean"&&n.push("接続のonceはbooleanです。"),p?.when==="near"&&n.push(...Oe(t,p,!e)),T.add(R)}}for(let h of r){if(!h||!/^[a-zA-Z0-9_-]{1,80}$/.test(h.id??"")||
d.has(h.id)){n.push("タスクIDが不正または重複しています。");continue}d.add(h.id),(typeof h.name!="string"||!h.name.trim()||h.name.length>120)&&n.push("タスク名は1～120文字\
です。");let w=i.find(I=>I.id===h.behaviorId);if(w||n.push("タスクの挙動がありません。"),!Array.isArray(h.targets)||!h.targets.length&&!(t.mission?.type==="state"&&
t.mission.assignmentId===h.id)||h.targets.length>100){n.push("タスクの担当を選んでください。");continue}for(let I of h.targets){let S=typeof I=="string"?I.split(":")[0]:
"",F=typeof I=="string"?I.slice(S.length+1):"";(!(S==="unit"?t.units?.find(p=>p.id===F):S==="group"&&t.groups?.find(p=>p.id===F)?.template)||c.has(I))&&n.push("タスクの担当が不正または重複しています。"),
c.add(I)}if(w){let I=je(t,w,h);if(n.push(...I),!I.length&&w.parameters?.length){let S=he(w,h);n.push(...Fe({...t,behaviors:[S],behaviorAssignments:[]},!0).map(F=>"タスク「"+h.name+
"」: "+F))}}let v=w&&Array.isArray(w.nodes)&&Array.isArray(w.edges)?he(w,h):null,M=v?.nodes.some(I=>I.kind==="patrol"&&!I.routeId),T=v?.nodes.some(I=>["return","move"].includes(I.
kind)&&!I.destinationId);M&&(!Array.isArray(h.route)||h.route.length<3)&&n.push("周回タスクは3点以上の共有経路が必要です。"),h.route!==void 0&&(!Array.isArray(h.
route)||h.route.length>500||h.route.some(I=>!Ne(I)))&&n.push("タスクの経路が不正です。"),T&&!Ne(h.base)&&n.push("目的に向かって進む状態の目的地を選択してください。"),
h.base!==void 0&&!Ne(h.base)&&n.push("帰投地点が不正です。"),h.routeMode!==void 0&&!["once","loop","pingpong"].includes(h.routeMode)&&n.push("タスクの経路方式が不正です。"),
["even","fixed","none"].includes(h.spacing??"none")||n.push("間隔方式が不正です。"),(!H(h.spacingDistance??500,0,1e5)||!H(h.gain??.01,0,1)||!H(h.preparation??0,0,86400)||
!H(h.phase??0,0,1))&&n.push("タスクの間隔・調整係数・準備時間・開始割合が不正です。"),v?.nodes.some(I=>I.receiverRole&&!I.receiverId)&&!t.units?.some(I=>I.
id===h.receiverId)&&n.push("タスクの報告先を選んでください。")}let f=t.recording??{},l=f.step??t.analysis?.step??10,g=f.interval??l;return(!H(l,.1,300)||!H(g,.1,300)||
g<l||Math.abs(g/l-Math.round(g/l))>1e-8||t.duration/l>1e5)&&n.push("計算刻み0.1～300秒、記録間隔は刻みの整数倍・300秒以下、最大10万ステップです。"),
t.version===3&&t.analysis&&t.analysis.step!==l&&n.push("分析と記録の計算刻みを一致させてください。"),n}function We(t,e){let n=t.units?.find(r=>r.id===e),i=n?.groupId??t.groups?.find(r=>e?.slice(0,e.lastIndexOf("__"))===r.id)?.id;return t.behaviorAssignments?.find(r=>r.targets.includes(
"unit:"+e)||i&&r.targets.includes("group:"+i))}function Y(t){let e=2166136261;for(let n=0;n<t.length;n++)e^=t.charCodeAt(n),e=Math.imul(e,16777619);return e^=e>>>16,e=Math.imul(e,2146121005),e^=e>>>15,e=Math.imul(e,2221713035),
e^=e>>>16,(e>>>0)/4294967296}var xt=t=>t*t*(3-2*t);function Re(t,e,n){let i=Math.floor(e/n),r=xt(e/n-i),o=d=>{let c=Y(t+"|angle|"+d)*Math.PI*2,f=Math.sqrt(Y(t+"|radius|"+d));return[
Math.cos(c)*f,Math.sin(c)*f,Y(t+"|z|"+d)*2-1]},a=o(i),s=o(i+1);return a.map((d,c)=>d+(s[c]-d)*r)}function W(t,e,n){return"simsim-rng-v1|"+JSON.stringify([t.seed??"SimSim",t.trial??
0,e,n])}function _e(t){let e=t.units.map(n=>({...n}));for(let n of t.groups??[]){let i=Math.ceil(Math.sqrt(n.count)),r=Math.ceil(n.count/i);for(let o=0;o<n.count;o++){let a=n.id+"_\
_"+(o+1),s=W(t,a,"deployment"),d=n.placement==="random"?Y(s+"|x"):(o%i+.5)/i,c=n.placement==="random"?Y(s+"|y"):(Math.floor(o/i)+.5)/r,f=(d-.5)*n.width,l=(c-.5)*n.height,g=v=>({...v,
x:v.x+f,y:v.y+l}),h=n.loopStartMode??"template",w=n.template.routeMode==="loop"&&h!=="template"?{...n.template.motion,loopStart:((n.template.motion?.loopStart??0)+(h==="even"?o/n.count:
Y(W(t,a,"loop-start-placement-v1"))))%1}:n.template.motion;e.push({...n.template,...w?{motion:w}:{},enabled:n.enabled!==!1,id:a,name:(n.name+" "+(o+1)).slice(0,120),groupId:n.id,initial:g(
n.template.initial),route:n.template.route.map(g)})}}return e}var O=(t,e,n,i,r,o,a={})=>({key:t,label:e,family:n,path:i,min:r,max:o,scale:1,scope:"entity",...a}),Mt=[O("rate.movement.speed","移動速度","Rate","speed",0,1500,{unit:"m/s",default:0}),
O("extent.sense.radius","最大探知距離","Extent","sensor.range",.001,1e5,{unit:"km",scale:1e3,sensor:!0}),O("interaction.detection.probability","距離0で1分の探知確率",
"Interaction","sensor.probabilityPerMinute",0,1,{unit:"%",scale:.01,sensor:!0}),O("extent.communication.radius","最大通信距離","Extent","communication.range",.001,1e5,{unit:"\
km",scale:1e3,communication:!0}),O("interaction.communication.delay","通信遅延","Interaction","communication.delay",0,86400,{unit:"s",communication:!0}),O("interaction.communic\
ation.probability","通信成功確率","Interaction","communication.probability",0,1,{unit:"%",scale:.01,communication:!0}),O("behavior.preparation","出発準備時間","Behavior",
"preparation",0,86400,{unit:"s",scope:"assignment",preparation:!0,default:0}),O("extent.signature.coefficient","被探知係数","Extent","detectability",0,10,{unit:"倍",default:1}),
O("state.position.x","配置・経路の中心 x","State","initial.x",-1e6,1e6,{unit:"km",scale:1e3,translate:"x"}),O("state.position.y","配置・経路の中心 y","State","initi\
al.y",-1e6,1e6,{unit:"km",scale:1e3,translate:"y"}),O("state.position.z","高度・深度 z","State","initial.z",-2e4,1e5,{unit:"m",translate:"z",vertical:!0}),O("extent.sense.moun\
tHeight","センサー取付高","Extent","sensor.mountHeight",0,1e3,{unit:"m",sensor:!0,default:0}),O("state.route.phase","周回の出発点","State","motion.loopStart",0,1,{unit:"\
%",scale:.01,default:0,loopOnly:!0}),O("motion.horizontal","個体の水平ずれ上限","Motion","motion.horizontal",0,1e4,{unit:"m",default:0}),O("motion.commonHorizontal","群共通の水\
平ずれ上限","Motion","motion.commonHorizontal",0,1e4,{unit:"m",default:0}),O("motion.vertical","上下ずれ上限","Motion","motion.vertical",0,3e3,{unit:"m",default:0,vertical:!0}),
O("motion.scale","航跡の変動間隔","Motion","motion.scale",10,1e5,{unit:"m",default:2e3}),O("motion.startDelay","出発遅れ上限","Motion","motion.startDelay",0,86400,{unit:"\
s",default:0}),O("motion.speedVariation","個体速度のばらつき","Motion","motion.speedVariation",0,1,{unit:"±%",scale:.01,default:0}),O("capacity.population","群の個数",
"Capacity","count",0,2e3,{unit:"個",scope:"group",integer:!0}),O("extent.deployment.width","配置幅 x","Extent","width",0,1e5,{unit:"km",scale:1e3,scope:"group"}),O("extent.depl\
oyment.height","配置幅 y","Extent","height",0,1e5,{unit:"km",scale:1e3,scope:"group"}),O("task.route.x","共有経路の基準 x","State","route.0.x",-1e6,1e6,{unit:"km",scale:1e3,
scope:"assignment",routeAxis:"x"}),O("task.route.y","共有経路の基準 y","State","route.0.y",-1e6,1e6,{unit:"km",scale:1e3,scope:"assignment",routeAxis:"y"}),O("task.route.z",
"共有経路の高度・深度","State","route.0.z",-2e4,1e5,{unit:"m",scope:"assignment",routeAxis:"z"}),O("task.route.phase","共有周回の出発点","State","phase",0,1,{unit:"\
%",scale:.01,scope:"assignment",default:0,patrol:!0}),O("coordination.spacing","協調する指定間隔","Behavior","spacingDistance",0,1e5,{unit:"m",scope:"assignment",fixedSpacing:!0,
default:500}),O("coordination.gain","間隔の調整係数","Behavior","gain",0,1,{unit:"1/s",scope:"assignment",default:.01}),O("mission.deadline","成功条件の期限","Mission",
"mission.deadline",1e-6,86400,{unit:"min",scale:60,scope:"scenario"})],ye=t=>Mt.find(e=>e.key===t),ge=t=>JSON.stringify([t.target,t.parameter]);function Xe(t){let e=JSON.parse(JSON.
stringify(t));return e.factors=[...t.groupId?[{target:"group:"+t.groupId,parameter:"capacity.population",values:[...t.counts].sort((n,i)=>n-i)}]:[],...e.factors??[]],delete e.groupId,
delete e.counts,e}var St=t=>JSON.parse(JSON.stringify(t));function Ze(t,e,n){if(e==="scenario"){if(n.scope!=="scenario"||!t.mission)throw new Error("成功条件を設定してください。");
return t}let i=e?.indexOf(":")??-1,r=e?.slice(0,i),o=e?.slice(i+1),a=r==="unit"?t.units?.find(d=>d.id===o):r==="group"?t.groups?.find(d=>d.id===o):r==="assignment"?t.behaviorAssignments?.
find(d=>d.id===o):null;if(!a||n.scope==="scenario"||n.scope==="group"&&r!=="group")throw new Error("変数の対象が見つかりません: "+e);if(n.scope==="assignment"!=(r==="a\
ssignment"))throw new Error("変数の対象が一致しません。");let s=r==="group"&&n.scope==="entity"?a.template:a;if(r!=="assignment"&&We(t,r==="group"?o+"__1":o)?.route?.length&&
(n.translate||n.loopOnly||n.key.startsWith("extent.deployment.")))throw new Error("共有経路の位置・開始割合はタスク側の変数を選んでください。");if(n.loopOnly&&
s.routeMode!=="loop")throw new Error("周回の出発点は周回経路の対象に指定してください。");if(n.communication&&!s.communication?.enabled)throw new Error("通信変数\
の対象で通信を有効にしてください。");if(n.behavior&&!s.behavior)throw new Error("条件付き行動の設定がありません。");if(n.sensor&&!s.sensor)throw new Error(
"探知変数の対象にセンサーがありません。");return s}var At=(t,e)=>e.split(".").reduce((n,i)=>n?.[i],t);function Se(t,e){let n=ye(e.parameter);if(!n)throw new Error(
"未対応の変数です。");let i=Ze(t,e.target,n);return At(i,n.path)??(n.key==="extent.sense.mountHeight"&&i.domain==="ground"?2:n.default)}function Et(t,e,n){let i=ye(e.parameter),
r=Ze(t,e.target,i),o=i.path.split(".");if(i.routeAxis){let s=n-r.route[0][i.routeAxis];for(let d of r.route)d[i.routeAxis]+=s;return}if(i.translate){let s=n-r.initial[i.translate];
for(let d of r.route??[])d[i.translate]+=s}let a=r;for(let s of o.slice(0,-1))a[s]===void 0&&(a[s]={}),a=a[s];a[o.at(-1)]=n}function kt(t,e,n){let i=ye(e.parameter),r=e.target;return e.target.startsWith("group:")&&(r=t.groups?.find(o=>o.id===e.target.slice(6))?.name??r),e.target.startsWith("assignment:")&&
(r=t.behaviorAssignments?.find(o=>o.id===e.target.slice(11))?.name??r),e.target.startsWith("unit:")&&(r=t.units?.find(o=>o.id===e.target.slice(5))?.name??r),r+" / "+i.label+" = "+Number(
(n/i.scale).toFixed(5))+" "+i.unit}function Qe(t,e){let n=[],i=new Set;t.groupId&&i.add(ge({target:"group:"+t.groupId,parameter:"capacity.population"}));for(let[o,a]of[["factors",t.
factors??[]],["uncertainties",t.uncertainties??[]]]){let s=o==="factors"?9:8;if(!Array.isArray(a)||a.length>s){n.push(o+"は最大"+s+"変数にしてください。");continue}for(let d of a){
let c=ye(d?.parameter),f=ge(d??{});if(!c||typeof d.target!="string"){n.push("未対応の変数または対象です。");continue}i.has(f)&&n.push("同じ変数を重複して指定できません。"),
i.add(f);let l=c.key==="mission.deadline"?Math.min(c.max,e):c.max,g=h=>typeof h=="number"&&Number.isFinite(h)&&h>=c.min&&h<=l&&(!c.integer||Number.isInteger(h));o==="factors"?(!Array.
isArray(d.values)||!d.values.length||d.values.length>12||d.values.some(h=>!g(h))||new Set(d.values).size!==d.values.length)&&n.push(c.label+": 比較値は範囲内で重複しない数値を1～12個指定してください。"):
(!["uniform","triangular"].includes(d.distribution)||!g(d.min)||!g(d.max)||d.min>d.max||d.distribution==="triangular"&&(!g(d.mode)||d.mode<d.min||d.mode>d.max))&&n.push(c.label+": \
分布の範囲・最頻値が不正です。")}}let r=(t.groupId?t.counts?.length??0:1)*(Array.isArray(t.factors)?t.factors.reduce((o,a)=>o*(a?.values?.length??0),1):1);return r>24&&
n.push("比較値の組合せは最大24条件にしてください。"),r*t.trials>1e4&&n.push("条件数×試行数は10000以下にしてください。"),n}function et(t){let e=t.
analysis,n=e.groupId?[...e.counts].sort((i,r)=>i-r).map(i=>({count:i,settings:[{target:"group:"+e.groupId,parameter:"capacity.population",value:i}]})):[{settings:[]}];for(let i of e.
factors??[])n=n.flatMap(r=>i.values.map(o=>({...r,settings:[...r.settings,{target:i.target,parameter:i.parameter,value:o}]})));return n.map((i,r)=>({...i,id:JSON.stringify(i.settings.
map(o=>[ge(o),o.value]).sort((o,a)=>o[0]<a[0]?-1:o[0]>a[0]?1:0)),index:r+1,label:i.settings.map(o=>kt(t,o,o.value)).join(" / ")||"基準条件"}))}function Ae(t,e,n,{maximum:i=!1}={}){
let r=St(t),o=[];r.trial=n;for(let a of t.analysis.uncertainties??[]){let s=Y(W(r,ge(a),"parameter-sample-v1")),d=a.min;if(i)d=a.max;else if(a.max>a.min)if(a.distribution==="unifor\
m")d=a.min+s*(a.max-a.min);else{let c=a.max-a.min,f=(a.mode-a.min)/c;d=s<f?a.min+Math.sqrt(s*c*(a.mode-a.min)):a.max-Math.sqrt((1-s)*c*(a.max-a.mode))}ye(a.parameter).integer&&(d=Math.
round(d)),o.push({target:a.target,parameter:a.parameter,value:d})}for(let a of[...e.settings,...o])Et(r,a,a.value);if(r.groups=r.groups?.filter(a=>a.count!==0),r.behaviorAssignments&&
(r.behaviorAssignments=r.behaviorAssignments.map(a=>({...a,targets:a.targets.filter(s=>!s.startsWith("group:")||r.groups?.some(d=>d.id===s.slice(6)))})).filter(a=>a.targets.length||
r.mission?.type==="state"&&r.mission.assignmentId===a.id)),r.analysis){let a=s=>s.target==="scenario"?!!r.mission:s.target.startsWith("assignment:")?r.behaviorAssignments?.some(d=>d.
id===s.target.slice(11)):s.target.startsWith("group:")?r.groups?.some(d=>d.id===s.target.slice(6)):r.units.some(d=>d.id===s.target.slice(5));for(let s of["factors","uncertainties"])
r.analysis[s]=r.analysis[s]?.filter(a);r.analysis.groupId&&!r.groups?.some(s=>s.id===r.analysis.groupId)&&(delete r.analysis.groupId,delete r.analysis.counts)}return{scenario:r,sampled:o}}function tt(t){let e=t.mission;if(e?.type!=="state")return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=t.behaviors?.find(r=>r.id===n?.behaviorId);return n?i?.nodes?.
some(r=>r.id===e.nodeId)?[]:["計測対象の状態を選択してください。"]:["計測対象のタスクがありません。"]}var Ct=(t,e)=>t.join==="all"?e:t.join==="count"?t.requiredCount:1;function Ee(t,e,n,i=e.deadline){let r=t.filter(a=>a.time<=Math.min(i,e.deadline)).sort((a,s)=>a.time-s.time||a.unitId.
localeCompare(s.unitId)),o=Ct(e,n);return{stateTargetCount:n,stateReachedCount:r.length,stateEntries:r,success:n>0&&o>0&&r.length>=o,successTime:n>0&&o>0&&r.length>=o?r[o-1].time:null}}
var be=class{constructor(e,n){this.mission=e,this.members=new Set(n),this.first=new Map,this.cursor=0}update(e){for(;this.cursor<e.length;this.cursor++){let n=e[this.cursor];["init\
ialized","nodeChanged"].includes(n.type)&&n.nodeId===this.mission.nodeId&&n.time<=this.mission.deadline&&this.members.has(n.unitId)&&!this.first.has(n.unitId)&&this.first.set(n.unitId,
n.time)}return Ee([...this.first].map(([n,i])=>({unitId:n,time:i})),this.mission,this.members.size)}};var nt=t=>typeof t=="number"&&Number.isFinite(t);function it(t,e="unit",n=new Set){let i=[],r=t.communication,o=t.behavior;if(r!==void 0)if(!r||typeof r!="object"||Array.isArray(r))
i.push(e+": communicationはオブジェクトにしてください。");else{(typeof r.enabled!="boolean"||typeof r.terrainLOS!="boolean")&&i.push(e+": 通信のenabled・terrainLOSはboole\
anにしてください。");for(let[a,s,d]of[["range",.001,1e5],["delay",0,86400],["probability",0,1]])(!nt(r[a])||r[a]<s||r[a]>d)&&i.push(e+": communication."+a+"は"+s+"～"+d+"\
にしてください。")}if(o!==void 0){if(!o||typeof o!="object"||Array.isArray(o))return[...i,e+": behaviorはオブジェクトにしてください。"];if(typeof o.hold!="bo\
olean"&&i.push(e+": behavior.holdはbooleanにしてください。"),(!nt(o.preparation)||o.preparation<0||o.preparation>86400)&&i.push(e+": behavior.preparationは0～86400秒にしてください。"),
!Array.isArray(o.rules)||o.rules.length>16)i.push(e+": 行動ルールは最大16件にしてください。");else{let a=new Set;for(let s of o.rules){if(!s||typeof s!="object"){i.
push(e+": ルールはオブジェクトにしてください。");continue}(typeof s.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(s.id)||a.has(s.id))&&i.push(e+": ルールidは重複しない英数字・_・\
-にしてください。"),a.add(s.id),(!["detected","received","arrived"].includes(s.when)||!["send","depart"].includes(s.action)||!["any","waiting"].includes(s.state)||typeof s.
once!="boolean")&&i.push(e+": ルールの条件・動作・実行回数が不正です。"),s.action==="send"&&!n.has(s.receiverId)&&i.push(e+": 送信先の単体ユニットが見つかりません: "+
s.receiverId),s.action==="depart"&&!o.hold&&i.push(e+": 出発ルールには「指令まで待機」を設定してください。")}}}return i}var zt=["ground","surface","subsurface","air"],rt=["friendly","hostile","neutral"],ee=t=>typeof t=="number"&&Number.isFinite(t);function ot(t,e="unit"){let n=[],i=t.sensor;if(t.detectability!==
void 0&&(!ee(t.detectability)||t.detectability<0||t.detectability>10)&&n.push(e+": detectabilityは0～10にしてください。"),i!==void 0){if(!i||typeof i!="object"||Array.isArray(
i))return[...n,e+": sensorはオブジェクトにしてください。"];typeof i.enabled!="boolean"&&n.push(e+": sensor.enabledはbooleanにしてください。"),(!ee(i.range)||
i.range<=0||i.range>1e5)&&n.push(e+": sensor.rangeは0より大きく100000m以下にしてください。"),(!ee(i.probabilityPerMinute)||i.probabilityPerMinute<0||i.probabilityPerMinute>
1)&&n.push(e+": sensor.probabilityPerMinuteは0～1にしてください。"),(!Array.isArray(i.domains)||!i.domains.length||i.domains.some(r=>!zt.includes(r)))&&n.push(e+": sensor\
.domainsには対象領域を1つ以上指定してください。"),typeof i.terrainLOS!="boolean"&&n.push(e+": sensor.terrainLOSはbooleanにしてください。"),i.mountHeight!==
void 0&&(!ee(i.mountHeight)||i.mountHeight<0||i.mountHeight>1e3)&&n.push(e+": sensor.mountHeightは0～1000mにしてください。")}return n}function ke(t,e){if(t===void 0)return[];
let n=[];return!t||typeof t!="object"||Array.isArray(t)?["missionはオブジェクトにしてください。"]:(["detect","arrive","state"].includes(t.type)||n.push("mission.type\
はdetect・arrive・stateにしてください。"),t.type==="arrive"&&(!Array.isArray(t.responderIds)||!t.responderIds.length||t.responderIds.length>2e3||t.responderIds.some(i=>typeof i!=
"string")||new Set(t.responderIds).size!==t.responderIds.length)&&n.push("mission.responderIdsに到着を評価する単体ユニットIDを指定してください。"),t.type!==
"state"&&(!rt.includes(t.observerFaction)||!rt.includes(t.targetFaction)||t.observerFaction===t.targetFaction)&&n.push("観測側と対象側には異なる陣営を指定してください。"),
(t.type==="state"?["any","all","count"]:["any","all"]).includes(t.join)||n.push("mission.joinはany・all（状態計測ではcountも可）にしてください。"),t.type==="sta\
te"&&(typeof t.assignmentId!="string"||typeof t.nodeId!="string")&&n.push("計測するタスクと状態を選択してください。"),t.join==="count"&&(!Number.isInteger(t.requiredCount)||
t.requiredCount<1||t.requiredCount>2e3)&&n.push("到達を必要とする担当数は1～2000です。"),(!ee(t.deadline)||t.deadline<=0||t.deadline>e)&&n.push("mission.deadlineは0よ\
り大きく終了時刻以下にしてください。"),t.targetIds!==void 0&&(!Array.isArray(t.targetIds)||!t.targetIds.length||t.targetIds.length>2e3||t.targetIds.some(i=>typeof i!=
"string")||new Set(t.targetIds).size!==t.targetIds.length)&&n.push("mission.targetIdsは重複しない対象IDの配列にしてください。"),n)}function Ce(t,e){if(t===void 0)
return[];if(!t||typeof t!="object"||Array.isArray(t))return["analysisはオブジェクトにしてください。"];let n=[];return t.groupId!==void 0&&typeof t.groupId!="string"&&
n.push("analysis.groupIdは文字列にしてください。"),t.groupId&&(!Array.isArray(t.counts)||!t.counts.length||t.counts.length>12||t.counts.some(i=>!Number.isInteger(i)||i<
0||i>2e3)||new Set(t.counts).size!==t.counts.length)&&n.push("analysis.countsは重複しない0～2000の整数（最大12条件）にしてください。"),(!Number.isInteger(t.
trials)||t.trials<1||t.trials>2e3)&&n.push("analysis.trialsは1～2000にしてください。"),(!ee(t.step)||t.step<.1||t.step>300||Math.ceil(e/t.step)>1e5)&&n.push("判定間隔は0.1～300\
秒、シナリオ全体で10万区間以内にしてください。"),(!ee(t.requiredRate)||t.requiredRate<0||t.requiredRate>1)&&n.push("analysis.requiredRateは0～1にしてください。"),
n.push(...Qe(t,e)),n}var De=2e3,Tt=["ground","surface","subsurface","air"];var at=t=>JSON.parse(JSON.stringify(t)),J=t=>typeof t=="number"&&Number.isFinite(t),st=t=>t&&["x","y","z"].every(e=>J(t[e]));function se(t){let e=[];if(!t||typeof t!="object")throw new Error(
"シナリオはオブジェクトで指定してください。");[1,2,3].includes(t.version)||e.push("versionは1・2・3にしてください。"),t.unitsSystem!=="SI"&&e.push("\
unitsSystemはSI（m・s）にしてください。"),(typeof t.title!="string"||!t.title.trim()||t.title.length>160)&&e.push("titleは1～160文字で指定してください。"),
(!J(t.duration)||t.duration<=0||t.duration>86400)&&e.push("durationは0より大きく86400秒以下にしてください。");let n=t.terrain;!n||!Number.isInteger(n.columns)||!Number.
isInteger(n.rows)||n.columns<2||n.rows<2||n.columns>513||n.rows>513?e.push("terrainのcolumns・rowsは2～513の整数にしてください。"):((!J(n.spacing)||n.spacing<1||n.spacing>
1e4)&&e.push("terrain.spacingは1～10000mにしてください。"),n.spacingY!==void 0&&(!J(n.spacingY)||n.spacingY<1||n.spacingY>1e4)&&e.push("terrain.spacingYは1～10000mにしてください。"),
(!n.origin||!J(n.origin.x)||!J(n.origin.y))&&e.push("terrain.originのx・yが必要です。"),(!Array.isArray(n.elevations)||n.elevations.length!==n.columns*n.rows||n.elevations.
some(o=>!J(o)||o<-12e3||o>1e4))&&e.push("terrain.elevationsは格子数と同じ長さの標高配列（-12000～10000m）にしてください。"),J(n.seaLevel)||e.push("terrain.\
seaLevelが必要です。")),t.seed!==void 0&&(typeof t.seed!="string"||t.seed.length>100)&&e.push("seedは100文字以下の文字列にしてください。"),t.trial!==void 0&&
(!Number.isInteger(t.trial)||t.trial<0||t.trial>1e9)&&e.push("trialは0～1000000000の整数にしてください。");let i=t.groups??[],r=new Set;if(!Array.isArray(i)||i.length>
100)e.push("groupsは最大100件の配列にしてください。");else for(let o of i){if(!o||typeof o!="object"){e.push("groupはオブジェクトにしてください。");continue}
o.enabled!==void 0&&typeof o.enabled!="boolean"&&e.push("group.enabledはbooleanにしてください。"),(typeof o.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(o.id)||r.has(o.id))&&
e.push("group.idは重複しない英数字・_・-（50文字以下）にしてください。"),r.add(o.id),(typeof o.name!="string"||!o.name.trim()||o.name.length>100)&&e.push("\
group.nameは1～100文字にしてください。"),(!Number.isInteger(o.count)||o.count<1||o.count>De)&&e.push("group.countは1～2000にしてください。"),o.loopStartMode!==
void 0&&!["template","even","random"].includes(o.loopStartMode)&&e.push("group.loopStartModeはtemplate、even、randomにしてください。"),["grid","random"].includes(o.placement)||
e.push("group.placementはgridまたはrandomにしてください。");for(let a of["width","height"])(!J(o[a])||o[a]<0||o[a]>1e5)&&e.push("group."+a+"は0～100000mにしてください。")}
if(!Array.isArray(t.units)||t.units.length>De)e.push("unitsは最大2000件の配列にしてください。");else{let o=new Set,a=new Set(t.units.map(s=>s?.id));[...t.units,...Array.
isArray(i)?i.map(s=>s?.template):[]].forEach((s,d)=>{let c="units["+d+"]";if(!s||typeof s!="object"){e.push(c+": オブジェクトが必要です。");return}if((typeof s.id!="str\
ing"||!/^[a-zA-Z0-9_-]{1,80}$/.test(s.id)||d<t.units.length&&o.has(s.id))&&e.push(c+": idは重複しない英数字・_・-にしてください。"),d<t.units.length&&o.add(s.id),
(typeof s.name!="string"||!s.name.trim()||s.name.length>120)&&e.push(c+": nameは1～120文字にしてください。"),e.push(...ot(s,c),...it(s,c,a)),t.version===3&&s.behavior&&
e.push(c+": 旧行動ルールは読み込み時にノードへ変換してください。"),Tt.includes(s.domain)||e.push(c+": domainが不正です。"),["friendly","hostile","ne\
utral"].includes(s.faction)||e.push(c+": factionが不正です。"),s.enabled!==void 0&&typeof s.enabled!="boolean"&&e.push(c+": enabledはbooleanにしてください。"),typeof s.
manned!="boolean"&&e.push(c+": mannedはbooleanにしてください。"),(!J(s.speed)||s.speed<0||s.speed>1500)&&e.push(c+": speedは0～1500m/sにしてください。"),st(s.initial)||
e.push(c+": initialのx,y,zが必要です。"),["once","loop","pingpong"].includes(s.routeMode)||e.push(c+": routeModeが不正です。"),s.groupId!==void 0&&d<t.units.length&&e.
push(c+": groupIdは生成ユニット専用です。"),s.motion!==void 0)if(!s.motion||typeof s.motion!="object"||Array.isArray(s.motion))e.push(c+": motionはオブジェクトにしてください。");else
for(let[f,l,g]of[["horizontal",0,1e4],["vertical",0,3e3],["commonHorizontal",0,1e4],["scale",10,1e5],["startDelay",0,86400],["speedVariation",0,1],["loopStart",0,1]])s.motion[f]!==
void 0&&(!J(s.motion[f])||s.motion[f]<l||s.motion[f]>g)&&e.push(c+": motion."+f+"は"+l+"～"+g+"にしてください。");(!Array.isArray(s.route)||s.route.length>500||s.route.some(
f=>!st(f)))&&e.push(c+": routeは最大500件、各点にx,y,zが必要です。")})}if(Array.isArray(t.units)&&Array.isArray(i)&&!e.length){let o=t.units.length+i.reduce((a,s)=>a+
s.count,0);if(o>De)e.push("単体と群を合わせて最大2000ユニットにしてください。");else{let a=_e(t);new Set(a.map(s=>s.id)).size!==o&&e.push("生成ユニットのidが単体ユニットと重\
複しています。")}}if(e.push(...ke(t.mission,t.duration),...Ce(t.analysis,t.duration),...Fe(t),...tt(t)),t.mission?.type==="arrive"&&t.mission.responderIds?.some(o=>!t.units?.
some(a=>a.id===o))&&e.push("到着評価の対象となる単体ユニットが見つかりません。"),t.version===3&&!e.length)for(let o of[...t.analysis?.factors??[],...t.analysis?.
uncertainties??[]])try{Se(t,o)}catch(a){e.push(a.message)}if(e.length)throw new Error(e.slice(0,30).join(`
`));return Ge(at(t))}var Le=class{constructor(e){this.data=e,this.minX=e.origin.x,this.minY=e.origin.y,this.maxX=this.minX+(e.columns-1)*e.spacing,this.maxY=this.minY+(e.rows-1)*(e.
spacingY??e.spacing),this.cellSize=Math.min(e.spacing,e.spacingY??e.spacing)}contains(e,n){return J(e)&&J(n)&&e>=this.minX&&e<=this.maxX&&n>=this.minY&&n<=this.maxY}height(e,n){if(!this.
contains(e,n))return null;let i=this.data,r=(e-this.minX)/i.spacing,o=(n-this.minY)/(i.spacingY??i.spacing),a=Math.min(i.columns-2,Math.floor(r)),s=Math.min(i.rows-2,Math.floor(o)),
d=r-a,c=o-s,f=(l,g)=>i.elevations[(s+g)*i.columns+a+l];return(f(0,0)*(1-d)+f(1,0)*d)*(1-c)+(f(0,1)*(1-d)+f(1,1)*d)*c}project(e,n){let i={...e},r=this.height(i.x,i.y),o=this.data.seaLevel;
return r===null?{point:i,error:"地形データの範囲外です"}:n==="ground"&&(i.z=r,r<=o)?{point:i,error:"地上ユニットは陸上に配置してください"}:n==="surface"&&
(i.z=o,r>o-5)?{point:i,error:"水上ユニットには5m以上の水深が必要です"}:n==="subsurface"&&(i.z>o-1||i.z<r+5||r>=o)?{point:i,error:"水中ユニットは海面下かつ海底から5m以上離してください"}:
n==="air"&&i.z<=Math.max(r,o)+10?{point:i,error:"空中ユニットは地表・海面から10mより高くしてください"}:{point:i,error:null}}},ze=(t,e)=>Math.hypot(t.x-e.x,t.
y-e.y,t.z-e.z),ve=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function jt(t,e){let n=[0];for(let d=1;d<t.length;d++)n.push(n.at(-1)+ze(t[d-1],t[d]));let i=n.
at(-1);if(i===0)return t;let r=i*e,o=n.findIndex((d,c)=>c>0&&d>r),a=o<0?t.length-1:o,s=ve(t[a-1],t[a],(r-n[a-1])/(n[a]-n[a-1]));return[s,...t.slice(a,-1),...t.slice(0,a),{...s}]}var oe=class{constructor(e,{
deferPaths:n=!1}={}){let i=se(e);this.source=i,this.scenario={...i,units:_e(i)},this.nodeCount=0,this.terrain=new Le(this.scenario.terrain),this.paths=n?new Map:new Map(this.scenario.
units.filter(r=>r.enabled!==!1).map(r=>[r.id,this.compile(r)]))}compile(e){let n=this.terrain.project(e.initial,e.domain),i=[{...n.point,d:0}],r=e.motion??{},o=W(this.scenario,e.id,
"motion"),a=(r.startDelay??0)*Y(o+"|delay"),s=e.speed*(1+(Y(o+"|speed")*2-1)*(r.speedVariation??0)),d={delay:a,actualSpeed:s},c=e.routeMode==="loop"?(r.loopStart??0)%1:0,f=c>0&&e.route.
length>0;if(n.error&&!f)return{...d,nodes:i,length:0,error:n.error,errorAt:"初期位置",periodic:!1};let l=[n.point,...e.route.map(v=>this.terrain.project(v,e.domain).point)];e.route.
length&&e.routeMode==="loop"&&l.push(n.point);let g=l.slice(1).reduce((v,M,T)=>v+ze(l[T],M),0);if(g>0&&(r.horizontal??0)+(r.vertical??0)+(r.commonHorizontal??0)>0){let v=[n.point],
M=r.scale??2e3,T=Math.min(125,this.terrain.cellSize/4,M/8),I=0;for(let S=1;S<l.length;S++){let F=l[S-1],j=l[S],p=ze(F,j),R=Math.max(1,Math.ceil(p/T));if(R>2e4)throw new Error("航跡生成\
の区間が長すぎます。");for(let L=1;L<=R;L++){let te=I+p*L/R,ne=ve(F,j,L/R),ue=Math.min(1,te/M,(g-te)/M),ce=Math.max(0,ue),le=ce*ce*(3-2*ce),ie=Re(o,te,M),m=Re(W(this.scenario,
e.groupId??e.id,"common-motion"),te,M);if(ne.x+=le*(ie[0]*(r.horizontal??0)+m[0]*(r.commonHorizontal??0)),ne.y+=le*(ie[1]*(r.horizontal??0)+m[1]*(r.commonHorizontal??0)),["subsurfa\
ce","air"].includes(e.domain)&&(ne.z+=le*ie[2]*(r.vertical??0)),v.push(ne),v.length>1e5)throw new Error("航跡生成の点数が多すぎます。経路を短くするか変動間隔を大きくしてください。")}
I+=p}l=v}if(f){let v=[l[0]],M=Math.min(125,this.terrain.cellSize/4);for(let I=1;I<l.length;I++){let S=l[I-1],F=l[I],j=Math.max(1,Math.ceil(Math.hypot(F.x-S.x,F.y-S.y)/M));if(j>2e4)
return{...d,nodes:i,length:0,error:"経路区間が長すぎます",errorAt:"初期位置",periodic:!1};for(let p=1;p<=j;p++)if(v.push(this.terrain.project(ve(S,F,p/j),e.domain).point),
v.length>2000001)throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}l=jt(v,c);let T=this.terrain.project(l[0],e.domain);if(i=[{...T.point,d:0}],
T.error)return{...d,nodes:i,length:0,error:T.error,errorAt:"初期位置",periodic:!1}}let h=l.slice();e.route.length&&e.routeMode==="pingpong"&&l.push(...h.slice(0,-1).reverse());
let w=Math.min(125,this.terrain.cellSize/4);for(let v=1;v<l.length;v++){let M=l[v-1],T=l[v],I=Math.max(1,Math.ceil(Math.hypot(T.x-M.x,T.y-M.y)/w));if(I>2e4)return{...d,nodes:i,length:i.
at(-1).d,error:"経路区間が長すぎます",errorAt:"区間 "+v,periodic:!1};for(let S=1;S<=I;S++){let F=this.terrain.project(ve(M,T,S/I),e.domain);if(F.error)return{...d,nodes:i,
length:i.at(-1).d,error:F.error,errorAt:"区間 "+v,periodic:!1};let j=i.at(-1),p=j.d+ze(j,F.point);if(p>j.d&&(i.push({...F.point,d:p}),++this.nodeCount>2e6))throw new Error("経路全体の\
サンプル点数が上限200万点を超えました。")}}return{...d,nodes:i,length:i.at(-1).d,error:null,errorAt:null,periodic:e.routeMode!=="once"}}evaluate(e){let n=Math.min(
this.scenario.duration,Math.max(0,Number(e)||0));return{time:n,units:this.scenario.units.map(i=>this.evaluateUnit(i,n))}}evaluateUnit(e,n,i=!0){if(e.enabled===!1)return{id:e.id,position:{
...e.initial},status:"disabled",heading:0,distance:0,routeDistance:0,error:null,errorAt:null,actualSpeed:0,startDelay:0,eta:null};let r=Math.max(0,Number(n)||0),o=i?Math.min(this.scenario.
duration,r):r,a=this.paths.get(e.id),s=a.actualSpeed??e.speed,d=a.delay??0,c=s*Math.max(0,o-d),f=!a.periodic&&s>0&&o>=d+a.length/s?Math.max(c,a.length):c,l=a.periodic&&a.length>0?f%
a.length:Math.min(f,a.length),g=0,h=a.nodes.length-1;for(;g<h;){let I=Math.ceil((g+h)/2);a.nodes[I].d<=l?g=I:h=I-1}let w=a.nodes[g],v=a.nodes[Math.min(g+1,a.nodes.length-1)],M=ve(w,
v,v.d>w.d?(l-w.d)/(v.d-w.d):0);e.domain==="ground"&&(M.z=this.terrain.height(M.x,M.y)??M.z);let T=a.length===0?"idle":"moving";return a.error&&f>=a.length?T="blocked":!a.periodic&&
a.length>0&&f>=a.length?T="arrived":s===0?T="idle":o<d&&(T="waiting"),{id:e.id,position:M,status:T,heading:Math.atan2(v.x-w.x,v.y-w.y),distance:Math.min(f,a.periodic?f:a.length),routeDistance:a.
length,error:a.error,errorAt:a.errorAt,actualSpeed:s,startDelay:Number.isFinite(d)?d:null,eta:s>0&&Number.isFinite(d)?d+a.length/s:null}}routePoints(e){return this.paths.get(e)?.nodes||
[]}};function Ie(t){let e=se(t);if(e.version===3)return e;e.version=3,e.behaviors??=[],e.behaviorAssignments??=[];let n=e.recording?.step??e.analysis?.step??10;e.recording??={step:n,interval:n},
e.analysis&&(e.analysis={...Xe(e.analysis),step:n});for(let[i,r]of[...e.units.map(o=>["unit:"+o.id,o]),...(e.groups??[]).map(o=>["group:"+o.id,o.template])]){let o=r.behavior;if(o){
if(o.hold||o.rules.length){if(e.behaviorAssignments.some(l=>l.targets.includes(i)))throw Error("旧ルールとタスクが重複しています: "+i);let a=new Set;for(let l of o.
rules){if(a.has(l.when)||l.state!=="any"&&!(o.hold&&l.when==="received"))throw Error("自動変換できない旧ルールです。同じ条件の複数動作・状態条件はノードで再設計してください: "+
i);a.add(l.when)}let s="import-"+i.replace(":","-");if(e.behaviors.some(l=>l.id===s)||e.behaviorAssignments.some(l=>l.id===s))throw Error("変換先IDが重複しています: "+s);
let d=o.hold?"signal":"follow",c=[{id:d,kind:o.hold?"signal":"follow",x:320,y:70}],f=[];o.hold&&c.push({id:"follow",kind:"follow",x:1080,y:70}),o.rules.forEach((l,g)=>{let h=l.when===
"received"&&o.hold?"signal":"follow";l.action==="depart"?(c.push({id:l.id,kind:"wait",parameter:"preparation",seconds:o.preparation,x:680,y:70+g*150}),f.push({from:h,to:l.id,when:l.
when,once:l.once},{from:l.id,to:"follow",when:"elapsed"})):(c.push({id:l.id,kind:"report",receiverId:l.receiverId,x:680,y:70+g*150}),f.push({from:h,to:l.id,when:l.when,once:l.once},
{from:l.id,to:d,when:"sent",resume:!0},{from:l.id,to:d,when:"sendFailed",resume:!0}))}),e.behaviors.push({id:s,name:r.name+"の挙動",initial:d,triggers:[],nodes:c,edges:f}),e.behaviorAssignments.
push({id:s,name:r.name+"のタスク",behaviorId:s,targets:[i],spacing:"none",preparation:o.preparation});for(let l of[e.analysis?.factors,e.analysis?.uncertainties])for(let g of l??
[])g.target===i&&g.parameter==="behavior.preparation"&&(g.target="assignment:"+s)}delete r.behavior}}return se(e)}function Te(t,e,n){let i=Math.hypot(n.x-e.x,n.y-e.y),r=Math.max(1,Math.ceil(i/Math.min(125,t.cellSize/4)));for(let o=0;o<=r;o++){let a=o/r,s=e.x+(n.x-e.x)*a,d=e.y+(n.y-e.y)*a,c=e.z+
(n.z-e.z)*a,f=t.height(s,d);if(f===null||c<f-1e-6)return!1}return!0}function Ue(t,e,n,i){if(i<=0||n<=0||e>=t.range||t.probabilityPerMinute<=0)return 0;if(t.probabilityPerMinute>=1)
return 1;let r=-Math.log1p(-t.probabilityPerMinute)/60;return-Math.expm1(-r*i*n*(1-e/t.range)**2)}var Ye=(t,e)=>({...t,z:t.z+(e.sensor?.mountHeight??(e.domain==="ground"?2:0))}),Ot=(t,e,n)=>Math.
floor(t/n)+","+Math.floor(e/n);function dt(t,e){let n=new Map;for(let i of t){let r=Ot(i.position.x,i.position.y,e);n.has(r)||n.set(r,[]),n.get(r).push(i)}return n}function*ut(t,e,n){
let i=Math.floor(e.x/n),r=Math.floor(e.y/n);for(let o=-1;o<=1;o++)for(let a=-1;a<=1;a++)for(let s of t.get(i+a+","+(r+o))??[])yield s}var Pt=256*1048576;var Je=["idle","moving","arrived","blocked","waiting","standby","preparing"],lt=128*1048576,Q=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),ae=(t,e)=>(t%e+e)%e,xe=(t,e,n)=>({x:t.x+(e.
x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function we(t,e){let n=Math.min(t.length,Math.max(0,e)),i=t.nodes,r=0,o=i.length-1;for(;r<o;){let d=Math.ceil((r+o)/2);i[d].d<=n?r=d:
o=d-1}let a=i[r],s=i[Math.min(r+1,i.length-1)];return{point:xe(a,s,s.d>a.d?(n-a.d)/(s.d-a.d):0),segment:r,heading:Math.atan2(s.x-a.x,s.y-a.y)}}function pt(t,e){let n={point:t.nodes[0],
along:0,distance:1/0};for(let i=1;i<t.nodes.length;i++){let r=t.nodes[i-1],o=t.nodes[i],a=o.x-r.x,s=o.y-r.y,d=o.z-r.z,c=a*a+s*s+d*d,f=c?Math.max(0,Math.min(1,((e.x-r.x)*a+(e.y-r.y)*
s+(e.z-r.z)*d)/c)):0,l=xe(r,o,f),g=Q(e,l);g<n.distance&&(n={point:l,along:r.d+(o.d-r.d)*f,distance:g})}return n}var Z=class extends oe{constructor(e){super(Ie(e),{deferPaths:!0}),this.
frames=null,this.result=null,this.computeCount=0,this.nodeNames=[],this.assignments=this.source.behaviorAssignments,this.initialEvents=[];let n=new Map(this.source.behaviors.map(i=>[
i.id,i]));this.states=[],this.byId=new Map;for(let i of this.scenario.units.filter(r=>r.enabled!==!1).sort((r,o)=>r.id.localeCompare(o.id))){let r=this.assignments.find(g=>g.targets.
includes("unit:"+i.id)||i.groupId&&g.targets.includes("group:"+i.groupId)),o=r?he(n.get(r.behaviorId),r):null,a=o?.nodes.find(g=>g.id===o.initial),s=Me(this.source,r,a,i),c=r?.route?.
length>=2||a?.routeId?{...i,initial:s.points[0],route:s.points.slice(1),routeMode:a?.kind==="patrol"?"loop":s.mode,motion:{...i.motion,loopStart:0}}:i,f=this.compile(c);this.paths.
set(i.id,f);let l={unit:i,assignment:r,graph:o,path:f,basePath:f,pathCache:new Map,routeContexts:new Map,nearInside:new Map,node:null,nodeTime:0,position:{...f.nodes[0]},heading:0,
status:"idle",distance:0,progress:0,segment:-1,error:f.errorAt==="初期位置"?f.error:null,fired:new Set,triggerFired:new Set,triggerTimes:new Map,activated:!1,observation:null,trace:[],
routeStarted:null,routePaused:0};if(a?.joinMode==="nearest"){let g=this.terrain.project(i.initial,i.domain);l.position=g.point,g.error&&(l.error=g.error)}this.states.push(l),this.byId.
set(i.id,l);for(let g of o?.nodes??[])this.nodeNames.includes(o.id+":"+g.id)||this.nodeNames.push(o.id+":"+g.id)}this.inactiveUnits=this.scenario.units.filter(i=>i.enabled===!1).map(
i=>super.evaluateUnit(i,0));for(let i of this.assignments){let r=this.states.filter(o=>o.assignment===i);r.forEach((o,a)=>{o.initialPhase=ae((i.phase??0)+(i.spacing==="none"?o.unit.
motion?.loopStart??0:a/r.length),1),o.status=o.error?"blocked":"standby",o.graph.initial&&(o.activated=!0,this.enter(o,o.graph.initial,0,!0),this.initialEvents.push({type:"initiali\
zed",time:0,unitId:o.unit.id,nodeId:o.graph.initial}))})}for(let i of this.states)i.graph||Object.assign(i,super.evaluateUnit(i.unit,0))}enter(e,n,i,r=!1,o=!1){let a=e.node;if(a?.kind===
"follow"&&e.routeContexts.set(a.routeId??"default",{path:e.path,started:e.routeStarted,travel:e.routeTravel??0,offset:e.routeOffset??0,paused:i,join:e.join}),e.node=e.graph.nodes.find(
s=>s.id===n),e.nodeTime=i,e.sent=!1,e.elapsed=!1,e.destinationArrived=!1,e.join=null,e.nearInside=new Map([...e.nearInside].filter(([s])=>s.startsWith("trigger:"))),["follow","patr\
ol"].includes(e.node.kind)){let s=Me(this.source,e.assignment,e.node,e.unit),d=s.id+"|"+e.node.kind;if(r&&e.pathCache.set(d,e.path),!e.pathCache.has(d)){let c=!e.node.routeId;e.pathCache.
set(d,this.compile({...e.unit,initial:s.points[0],route:s.points.slice(1),routeMode:s.mode,motion:{...e.unit.motion,...c?{}:{loopStart:0}}}))}e.path=e.pathCache.get(d),this.paths.set(
e.unit.id,e.path)}if(e.error){e.status="blocked";return}if(e.status="idle",e.node.kind==="patrol"){if(r&&e.node.joinMode!=="nearest"){e.progress=(e.node.joinMode==="start"?0:e.initialPhase)*
e.path.length;let s=we(e.path,e.progress);e.position=s.point,e.heading=s.heading,e.segment=s.segment}else{let s=(e.node.joinMode??"nearest")==="nearest"?pt(e.path,e.position):we(e.
path,0);e.progress=s.along??0,e.join=s.point}e.readyAt=i+(r?e.path.delay:0),e.status=i<e.readyAt?"waiting":"moving"}else if(e.node.kind==="follow"){let s=o?e.routeContexts.get(e.node.
routeId??"default"):null;if(s&&s.path===e.path)e.routeStarted=s.started===null?null:s.started+i-s.paused,e.routeTravel=s.travel,e.routeOffset=s.offset,e.join=s.join;else{let d=e.node.
joinMode==="nearest"?pt(e.path,e.position):{point:e.path.nodes[0],along:0};e.routeOffset=d.along,e.routeTravel=d.along,e.routeArrived=!1,e.join=(!r||e.node.joinMode==="nearest")&&Q(
e.position,d.point)>1e-7?d.point:null,e.routeStarted=e.join?null:i-(e.path.actualSpeed?e.routeOffset/e.path.actualSpeed:0)-(e.routeOffset>0?e.path.delay:0)}e.status=e.join?"moving":
i<(e.routeStarted??i)+(r?e.path.delay:0)?"waiting":e.path.length&&e.path.actualSpeed?"moving":"idle"}else e.node.kind==="signal"?e.status="standby":e.node.kind==="wait"?e.status=e.
node.parameter==="preparation"?"preparing":"waiting":e.node.kind==="move"&&(e.status="moving")}activate(e,n,i,r,o){if(!e?.graph||e.status==="blocked")return!1;let a=Pe(e.graph).find(
c=>c.event===n&&(n!=="near"||X(c)===o?.conditionKey)&&(n!=="time"||Math.abs(this.nextTriggerTime(e,c)-i)<1e-8)&&(!e.triggerFired.has(c.id)||c.once===!1));if(!a)return!1;let s=e.unit.
id+"|trigger|"+a.id;if(o?.trace?.includes(s))return!1;if(o?(e.observation=o,e.trace=[...o.trace??[],s]):(e.observation=null,e.trace=[]),e.trace.length>64)throw Error("情報の中継が64段を超えま\
した。");e.triggerFired.add(a.id),e.triggerTimes.set(a.id,i);let d=e.node?.id;return e.activated=!0,this.enter(e,a.to,i),r.push({type:"triggered",time:i,unitId:e.unit.id,triggerId:a.
id,event:n,nodeId:a.to}),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d??null,nodeId:a.to}),e.node.parameter==="preparation"&&r.push({type:"preparing",time:i,unitId:e.unit.
id,nodeId:e.node.id}),e.node.kind==="follow"&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}nextTriggerTime(e,n){return e.triggerFired.has(n.id)?n.once===!1?
(e.triggerTimes.get(n.id)??0)+n.seconds:1/0:n.seconds}transition(e,n,i,r,o){if(!e?.graph||e.status==="blocked")return!1;if(this.activate(e,n,i,r,o))return!0;if(!e.node)return!1;let a=e.
graph.edges.find(c=>c.from===e.node.id&&c.when===n&&(n!=="near"||X(c)===o?.conditionKey));if(!a)return!1;let s=e.unit.id+"|"+a.from+"|"+X(a);if(a.once&&e.fired.has(s)||o?.trace?.includes(
s))return!1;if(a.once&&e.fired.add(s),o&&(e.observation=o,e.trace=[...o.trace??[],s]),e.trace.length>64)throw Error("情報の中継が64段を超えました。");e.node.kind==="f\
ollow"&&(e.pauseTime=i);let d=e.node.id;return this.enter(e,a.to,i,!1,a.resume),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d,nodeId:a.to}),e.node.parameter==="preparat\
ion"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&!a.resume&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}destination(e,n=e.
node,i){let r=me(this.source,e.assignment,n);return r?r.kind==="point"?r.point:i?.get(r.unitId)??this.byId.get(r.unitId)?.position??null:null}predict(e,n,i,r){if(e.status==="blocke\
d"||!e.node&&e.graph)return e.position;if(!e.graph||e.node.kind==="follow"&&!e.join){let c=e.graph?e.routeStarted??0:0;return oe.prototype.evaluateUnit.call(this,e.unit,Math.max(0,
n-c),!1).position}let o=Math.max(0,n-(this.currentTime??0));if(e.node.kind==="patrol"&&!e.join)return we(e.path,ae(e.progress+(i.get(e.unit.id)??e.path.actualSpeed)*Math.max(0,n-Math.
max(this.currentTime??0,e.readyAt)),e.path.length||1)).point;let a=e.join??(e.node.kind==="move"?this.destination(e,e.node,r):null);if(!a)return e.position;let s=Q(e.position,a),d=Math.
min(s,e.path.actualSpeed*o);return xe(e.position,a,s?d/s:1)}replayPath(e,n){if(!e.graph)return e.path;if(!e.replayRoutes){e.replayRoutes=[{time:0,node:e.graph.nodes.find(a=>a.id===
e.graph.initial)}];for(let a of this.result.actionEvents)a.unitId===e.unit.id&&a.type==="nodeChanged"&&e.replayRoutes.push({time:a.time,node:e.graph.nodes.find(s=>s.id===a.nodeId)});
e.replayRoutes=e.replayRoutes.filter(a=>["follow","patrol"].includes(a.node?.kind))}let i=e.replayRoutes.findLast(a=>a.time<=n)?.node;if(!i)return e.basePath;let r=Me(this.source,e.
assignment,i,e.unit),o=r.id+"|"+i.kind;return e.pathCache.has(o)||e.pathCache.set(o,this.compile({...e.unit,initial:r.points[0],route:r.points.slice(1),routeMode:r.mode,motion:{...e.
unit.motion,...i.routeId?{loopStart:0}:{}}})),e.pathCache.get(o)}stateSnapshot(e,n=e.path){return{id:e.unit.id,position:{x:e.position.x,y:e.position.y,z:e.position.z},heading:e.heading,
status:e.status,distance:e.distance,routeDistance:n.length,error:e.error,errorAt:n.errorAt,actualSpeed:n.actualSpeed,startDelay:n.delay,nodeId:e.node?.id,behaviorId:e.graph?.id,eta:null}}evaluate(e){
let n=Math.max(0,Math.min(this.source.duration,Number(e)||0));if(!this.frames)return{time:0,units:[...this.states.map(g=>this.stateSnapshot(g)),...this.inactiveUnits],actionsPending:!0,
recordingPending:!0};let i=0,r=this.frames.length-1;for(;i<r;){let g=Math.ceil((i+r)/2);this.frames[g].time<=n?i=g:r=g-1}let o=this.frames[i],a=this.frames[Math.min(i+1,this.frames.
length-1)],s=a.time>o.time?(n-o.time)/(a.time-o.time):0,d=this.states.map((g,h)=>{let w=h*5,v=o.values,M=a.values,T=this.nodeNames[o.nodes[h]-1],I=ae(M[w+3]-v[w+3]+Math.PI,Math.PI*
2)-Math.PI;return{...this.stateSnapshot(g,this.replayPath(g,n)),position:{x:v[w]+(M[w]-v[w])*s,y:v[w+1]+(M[w+1]-v[w+1])*s,z:v[w+2]+(M[w+2]-v[w+2])*s},heading:v[w+3]+I*s,distance:v[w+
4]+(M[w+4]-v[w+4])*s,status:Je[o.status[h]],nodeId:T?.split(":")[1],error:o.status[h]===3?"記録された地形制約停止":null,actualSpeed:a.time>o.time?Math.max(0,(M[w+4]-v[w+
4])/(a.time-o.time)):0}}),c=this.result,f=c.events.filter(g=>g.time<=n),l=this.source.mission;return{time:n,units:[...d,...this.inactiveUnits],actionEvents:c.actionEvents.filter(g=>g.
time<=n),mission:l?{...l.type==="state"?Ee(c.stateEntries,l,c.stateTargetCount,n):{},events:f,detectedCount:new Set(f.map(g=>g.targetId)).size,targetCount:c.targetCount,reachedCount:new Set(
c.actionEvents.filter(g=>g.type==="arrived"&&g.time<=n&&l.responderIds?.includes(g.unitId)).map(g=>g.unitId)).size,responderCount:c.responderCount,status:c.successTime!==null&&c.successTime<=
n?"success":n>=l.deadline?"failure":"pending",deadline:l.deadline}:void 0,recording:{frames:this.frames.length,bytes:this.recordBytes,computeCount:this.computeCount,step:this.source.
recording.step,interval:this.source.recording.interval},actionsPending:!1}}trailPoints(e,n,i=1e3){if(!this.frames)return[];let r=this.states.findIndex(f=>f.unit.id===e);if(r<0)return[];
let o=this.frames.filter(f=>f.time<=n),a=Math.max(1,Math.ceil(o.length/i)),s=o.filter((f,l)=>l%a===0||l===o.length-1).map(f=>({x:f.values[r*5],y:f.values[r*5+1],z:f.values[r*5+2]})),
d=this.frames.findLast(f=>f.time<=n),c=this.frames.find(f=>f.time>n)??d;if(d){let f=c.time>d.time?(n-d.time)/(c.time-d.time):0,l=r*5;s.push({x:d.values[l]+(c.values[l]-d.values[l])*
f,y:d.values[l+1]+(c.values[l+1]-d.values[l+1])*f,z:d.values[l+2]+(c.values[l+2]-d.values[l+2])*f})}return s}record(e,n){if(n.at(-1)?.time===e)return;let i=this.states.length,r=new Float32Array(
i*5),o=new Uint16Array(i),a=new Uint8Array(i);if(this.states.forEach((s,d)=>{r.set([s.position.x,s.position.y,s.position.z,s.heading,s.distance],d*5),o[d]=s.node?this.nodeNames.indexOf(
s.graph.id+":"+s.node.id)+1:0,a[d]=Je.indexOf(s.status)}),n.push({time:e,values:r,nodes:o,status:a}),n.length>100001||n.length*(i*23+8)>lt)throw Error("再生記録が128MiBを超えました。期間・個数・記録間隔\
を調整してください。")}get recordBytes(){return this.frames?.reduce((e,n)=>e+8+n.values.byteLength+n.nodes.byteLength+n.status.byteLength,0)??0}};function Be(t,e,n,i,r){let o=t.
terrain.project(n,e.unit.domain);if(o.error)return e.status="blocked",e.error=o.error,!1;let a=Q(e.position,o.point),s=Math.min(a,i*r),d=xe(e.position,o.point,a?s/a:1),c=Math.max(1,
Math.ceil(s/Math.min(125,t.terrain.cellSize/4)));for(let f=1;f<=c;f++){let l=t.terrain.project(xe(e.position,d,f/c),e.unit.domain);if(l.error)return e.status="blocked",e.error=l.error,
!1}return e.heading=Math.atan2(d.x-e.position.x,d.y-e.position.y),e.position=t.terrain.project(d,e.unit.domain).point,e.distance+=s,e.status=a<=s+1e-7?"arrived":"moving",e.status===
"arrived"}function*ft(t,e=t.source?.mission??t.scenario.mission,n,i={}){let r=t instanceof Z?t:new Z(t.source),o=i.horizon??e?.deadline??r.source.duration,a=i.record??!1,s=r.source.
recording.step,d=r.source.recording.interval;if(!Number.isFinite(o)||o<0||o>r.source.duration)throw Error("計算終了時刻が不正です。");if(r.computeCount)throw Error("計算済\
みです。新しい試行を作成してください。");r.computeCount++;let c=r.states,f=[...r.initialEvents],l=new Map,g=new Set,h=[],w=a?[]:null,v=c.filter(m=>m.unit.faction!==
"neutral"),M=e?.type==="state"?[]:e?.targetIds?e.targetIds.map(m=>r.byId.get(m)).filter(Boolean):c.filter(m=>e?m.unit.faction===e.targetFaction:m.unit.faction!=="neutral");if(e&&e.
type!=="state"&&e.targetIds?.some(m=>!r.scenario.units.some(x=>x.id===m&&x.faction===e.targetFaction))||e?.type==="detect"&&!r.scenario.units.some(m=>m.faction===e.targetFaction))throw Error(
"成功条件に合う対象がありません。");let T=e?.type==="arrive"?e.responderIds.filter(m=>r.byId.has(m)):[],I=e?.type==="state"?new be(e,c.filter(m=>m.assignment?.id===
e.assignmentId).map(m=>m.unit.id)):null,S={success:!1,successTime:null,targetCount:e?.type==="state"?v.length:M.length,detectedCount:0,responderCount:T.length,reachedCount:0,events:[],
actionEvents:f,invalidUnits:c.filter(m=>m.error).length,constrainedPaths:0},F=0,j=0,p=0,R=Math.max(1,...c.filter(m=>m.unit.sensor?.enabled).map(m=>m.unit.sensor.range)),L=(m,x,C,E={})=>(f.
push({type:x,time:C,unitId:m.unit.id,nodeId:m.node?.id,...E}),r.transition(m,x,C,f,E));function te(){let m=new Map;for(let x of r.assignments){let C=new Map;for(let E of c.filter(y=>y.
assignment===x&&y.node?.kind==="patrol"&&y.status!=="blocked"&&!y.join)){let y=E.node.routeId??"default";C.has(y)||C.set(y,[]),C.get(y).push(E)}for(let E of C.values()){E.sort((y,k)=>y.
progress/y.path.length-k.progress/k.path.length);for(let y=0;y<E.length;y++){let k=E[y],_=E[(y+1)%E.length],b=E.length===1?k.path.length:ae(_.progress/_.path.length-k.progress/k.path.
length,1)*k.path.length,z=x.spacing==="fixed"?x.spacingDistance??500:k.path.length/E.length,U=k.path.actualSpeed,B=U*(k.node.speedFraction??.7);m.set(k.unit.id,x.spacing==="none"||
E.length===1?B:Math.max(0,Math.min(U,B+(x.gain??.01)*(b-z))))}}}return m}function ne(m,x){let C=m.unit.communication,E=r.byId.get(m.node.receiverId??m.assignment.receiverId),y=E?Q(
m.position,E.position):1/0,k=m.observation,_=W(r.source,m.unit.id,"unified-report-v2")+"|"+JSON.stringify([m.node.id,k?.targetId,k?.originObserverId??k?.observerId??m.unit.id]),b=null;
C?.enabled?!E||E.error?b="受信先不在・配置不正":y>C.range?b="通信範囲外":C.terrainLOS&&!Te(r.terrain,m.position,E.position)?b="地形遮蔽":Y(_)>=C.probability&&(b=
"通信試行失敗"):b="通信無効",m.sent=!0;let z={receiverId:E?.unit.id,distance:Number.isFinite(y)?y:null,reason:b,targetId:k?.targetId,targetPosition:k?.targetPosition,observationTime:k?.
observationTime??k?.sampleTime??k?.time,originObserverId:k?.originObserverId??k?.observerId??m.unit.id,trace:m.trace,sourcePosition:{...m.position},receiverPosition:E?{...E.position}:
void 0};return b||h.push({...z,type:"received",time:x+C.delay,unitId:E.unit.id,senderId:m.unit.id}),L(m,b?"sendFailed":"sent",x,z)}function ue(m){return[...(m.graph?.triggers??[]).
filter(x=>x.event==="near").map(x=>({c:x,key:"trigger:"+x.id})),...(m.graph?.edges??[]).filter(x=>x.from===m.node?.id&&x.when==="near").map(x=>({c:x,key:"edge:"+x.from+"|"+X(x)}))]}
function ce(m,x){let C=!1;for(let{c:E,key:y}of ue(m)){let k=r.destination(m,E);if(!k)continue;let _=He(m.position,k,E.distanceMode),b=_<=E.distance+1e-6,z=m.nearInside.get(y)??!1;if(m.
nearInside.set(y,b),b&&!z&&!(y.startsWith("trigger:")&&E.once!==!1&&m.triggerFired.has(E.id))){let U={destinationId:E.destinationId,distance:_,distanceMode:E.distanceMode??"absolut\
e",conditionKey:X(E)};if(L(m,"near",x,U)){C=!0;break}}}return C}function le(m,x,C){let E=new Map(c.map(b=>[b.unit.id,{...b.position}])),y=new Set;for(let b of c)for(let{c:z}of ue(b)){
y.add(b);let U=me(r.source,b.assignment,z);U?.kind==="unit"&&r.byId.has(U.unitId)&&y.add(r.byId.get(U.unitId))}if(!y.size)return x;for(let b of y)if(b.status!=="blocked"&&(b.join&&
b.path.actualSpeed&&(x=Math.min(x,m+Q(b.position,b.join)/b.path.actualSpeed)),!b.join&&(!b.graph||["follow","patrol"].includes(b.node?.kind))&&b.path.actualSpeed&&b.path.length)){let z=b.
node?.kind==="patrol"?b.progress:ae(b.routeTravel??b.distance,b.path.length),U=b.path.nodes.find(B=>B.d>z+1e-7);U&&(x=Math.min(x,m+(U.d-z)/(C.get(b.unit.id)??b.path.actualSpeed)))}
let k=new Map(c.map(b=>[b.unit.id,r.predict(b,x,C,E)])),_=x;for(let b of c)for(let{c:z,key:U}of ue(b)){if(b.nearInside.get(U)||U.startsWith("trigger:")&&z.once!==!1&&b.triggerFired.
has(z.id))continue;let B=r.destination(b,z,E),u=r.destination(b,z,k);if(!B||!u)continue;let N=b.position,D=k.get(b.unit.id),A=[N.x-B.x,N.y-B.y,z.distanceMode==="horizontal"?0:N.z-B.
z],P=[D.x-u.x-A[0],D.y-u.y-A[1],z.distanceMode==="horizontal"?0:D.z-u.z-A[2]],q=P.reduce(($,V)=>$+V*V,0),K=2*A.reduce(($,V,yt)=>$+V*P[yt],0),re=A.reduce(($,V)=>$+V*V,0)-z.distance*
z.distance,pe=K*K-4*q*re;if(q>1e-12&&re>1e-6&&pe>=0){let $=(-K-Math.sqrt(pe))/(2*q);$>1e-9&&$<=1&&(_=Math.min(_,m+(x-m)*$))}}return _}function ie(m){let x=!1;for(let y of c)for(let k=0;k<
(y.graph?.triggers.length??0)&&r.activate(y,"time",m,f);k++)x=!0;let C=y=>{for(let k=0;k<64;k++){if(y.status==="blocked")return;let _=ce(y,m);if(_){x=!0;continue}if(y.node?.kind===
"report"&&!y.sent?_=ne(y,m):y.node?.kind==="wait"&&!y.elapsed&&m-y.nodeTime>=(y.node.parameter==="preparation"?y.assignment.preparation??y.node.seconds:y.node.seconds)&&(y.elapsed=
!0,_=L(y,"elapsed",m)),x=x||_,!_)return}throw Error("即時ノード遷移が64段を超えました。循環を見直してください。")};for(let y of c)C(y);let E=0;for(;;){if(h.
sort((_,b)=>_.time-b.time||_.unitId.localeCompare(b.unitId)),!h[0]||h[0].time>m)return x;if(++E>1e5||f.length>1e5)throw Error("情報イベントが10万件を超えました。");
let y=h.shift(),k=r.byId.get(y.unitId);f.push(y),k.observation=y,x=r.transition(k,"received",m,f,y)||x,C(k)}}ie(0),I&&Object.assign(S,I.update(f)),a&&r.record(0,w);for(let m=0;m<o;){
let x=Math.min(o,(Math.floor((m+1e-8)/s)+1)*s,e?.deadline>m?e.deadline:1/0),C=1/0;for(let u of h)u.time>m+1e-8&&(C=Math.min(C,u.time));for(let u of c)if(u.status!=="blocked"){if(u.
node?.kind==="wait"&&!u.elapsed){let N=u.node.parameter==="preparation"?u.assignment.preparation??u.node.seconds:u.node.seconds;u.nodeTime+N>m+1e-8&&(C=Math.min(C,u.nodeTime+N))}for(let N of u.
graph?.triggers??[])if(N.event==="time"){let D=r.nextTriggerTime(u,N);D>m+1e-8&&(C=Math.min(C,D))}if((!u.graph||u.node?.kind==="follow")&&!u.join&&!u.path.periodic&&u.path.length&&
u.path.actualSpeed&&!u.routeArrived){let N=(u.graph?u.routeStarted??0:0)+u.path.delay+u.path.length/u.path.actualSpeed;N>m+1e-8&&(C=Math.min(C,N))}if(u.join&&u.path.actualSpeed){let N=m+
Q(u.position,u.join)/u.path.actualSpeed;N>m+1e-8&&(C=Math.min(C,N))}if(u.node?.kind==="move"&&u.status!=="arrived"&&u.path.actualSpeed&&me(r.source,u.assignment,u.node)?.kind==="po\
int"){let N=m+Q(u.position,r.destination(u))/u.path.actualSpeed;N>m+1e-8&&(C=Math.min(C,N))}}r.currentTime=m;let E=te(),y=le(m,Math.min(x,C),E),k=y-m,_=new Map(c.map(u=>[u.unit.id,
{...u.position}])),b=new Map(c.map(u=>[u.unit.id,r.predict(u,y,E,_)])),z=!1;for(let u of c)if(u.status!=="blocked"&&!(u.graph&&!u.node)){if(u.node?.kind==="follow"&&u.join){Be(r,u,
u.join,u.path.actualSpeed,k)&&(u.join=null,u.routeStarted=y-(u.path.actualSpeed?u.routeOffset/u.path.actualSpeed:0)-(u.routeOffset>0?u.path.delay:0),u.routeTravel=u.routeOffset),z=
!0;continue}if(!u.graph||u.node.kind==="follow"){let N=u.status,D=u.segment,A=u.graph?u.routeStarted??0:0,P=oe.prototype.evaluateUnit.call(r,u.unit,Math.max(0,y-A),!1);if(u.graph){
let q=u.distance+Math.max(0,P.distance-(u.routeTravel??0));u.routeTravel=P.distance,Object.assign(u,P),u.distance=q}else Object.assign(u,P);u.segment=we(u.path,u.path.periodic?P.distance%
u.path.length:P.distance).segment,(N!==u.status||D!==u.segment)&&(z=!0),u.status==="arrived"&&!u.routeArrived&&(u.routeArrived=!0,z=L(u,"arrived",y)||z)}else if(u.node.kind==="patr\
ol"){if(y<=u.readyAt){u.status="waiting";continue}let N=y-Math.max(m,u.readyAt);if(u.join){Be(r,u,u.join,u.path.actualSpeed,N)&&(u.join=null),z=!0;continue}if(!u.path.length){u.status=
"blocked",u.error="周回経路の長さが0です。",z=!0;continue}let D=(E.get(u.unit.id)??u.path.actualSpeed)*N,A=u.progress+D;if(u.path.error&&A>=u.path.length){u.position={...u.
path.nodes.at(-1)},u.status="blocked",u.error=u.path.error,z=!0;continue}u.progress=ae(A,u.path.length);let P=we(u.path,u.progress);u.position=P.point,u.heading=P.heading,u.distance+=
D,u.status="moving",P.segment!==u.segment&&(z=!0,u.segment=P.segment)}else if(u.node.kind==="move"){let N=r.destination(u,u.node,b),D=me(r.source,u.assignment,u.node)?.kind==="unit";
if(!N){u.status="blocked",u.error="目的地が見つかりません。",z=!0;continue}(u.status!=="arrived"||D)&&Be(r,u,N,u.path.actualSpeed,k)&&u.status==="arrived"&&!u.destinationArrived&&
(u.destinationArrived=!0,z=!0,L(u,"arrived",y))}}if(Math.abs(y-x)<1e-8){let u=c.filter(A=>A.unit.sensor?.enabled&&A.status!=="blocked"&&A.node?.kind!=="stop"&&A.node?.sensor!==!1),
N=dt(u.map(A=>({unit:A.unit,position:Ye(A.position,A.unit),state:A})),R),D=[];for(let A of v){if(A.error&&A.path.errorAt==="初期位置"||A.unit.detectability===0)continue;let P=Ye(
A.position,{domain:A.unit.domain});for(let q of ut(N,P,R)){++F%256===0&&(yield{time:m,result:S});let K=q.state,re=K.unit.sensor,pe=K.unit.id+"|"+A.unit.id;if(K.unit.faction===A.unit.
faction||g.has(pe)||!re.domains.includes(A.unit.domain))continue;let $=Q(q.position,P),V=Ue(re,$,A.unit.detectability??1,y-p);V<=0||re.terrainLOS&&!Te(r.terrain,q.position,P)||Y(W(
r.source,K.unit.id,"unified-detect-v2")+"|"+JSON.stringify([A.unit.id,p,y]))<V&&(g.add(pe),D.push({type:"detected",time:y,sampleTime:y,observationTime:y,observerId:K.unit.id,unitId:K.
unit.id,targetId:A.unit.id,distance:$,observerPosition:{...q.position},targetPosition:{...P},trace:[]}))}}D.sort((A,P)=>A.unitId.localeCompare(P.unitId)||A.targetId.localeCompare(P.
targetId));for(let A of D){let P=r.byId.get(A.unitId);(!e||e.type==="state"||P.unit.faction===e.observerFaction&&M.some(q=>q.unit.id===A.targetId))&&!l.has(A.targetId)&&(l.set(A.targetId,
A),S.events.push(A)),P.observation=A,z=L(P,"detected",y,A)||z}p=y}if(z=ie(y)||z,f.length+h.length>1e5)throw Error("行動イベントが10万件を超えました。");S.detectedCount=
S.events.filter(u=>!e||u.time<=e.deadline).length,S.reachedCount=new Set(f.filter(u=>u.type==="arrived"&&T.includes(u.unitId)&&(!e||u.time<=e.deadline)).map(u=>u.unitId)).size,I&&Object.
assign(S,I.update(f));let U=e?.type==="arrive"?S.reachedCount:S.detectedCount,B=e?.join==="all"?e.type==="arrive"?T.length:M.length:1;if(e&&e.type!=="state"&&B>0&&y<=e.deadline&&U>=
B&&S.successTime===null&&(S.success=!0,S.successTime=y),a&&(z||y-j>=d-1e-8||y===o)&&(r.record(y,w),j=y),m=y,yield{time:y,result:S},!a&&!c.some(u=>u.graph)&&e?.type==="detect"&&S.detectedCount===
M.length)break}return S.constrainedPaths=c.filter(m=>m.status==="blocked").length,a&&(r.frames=w,r.result=S),S}var ht=t=>new Z(t);function*mt(t,e=t.scenario.mission,n=t.scenario.analysis?.step??10,i={}){if(!(t instanceof Z)&&t.source.version!==3&&n!==void 0){let r=Ie(t.source);r.recording={step:n,interval:n},
r.analysis&&(r.analysis.step=n),t=new Z(r)}return yield*ft(t,e,n,i)}function Ft(t,e){if(e===0)return{rate:null,low:null,high:null};let n=1.959963984540054,i=t/e,r=1+n*n/e,o=(i+n*n/(2*e))/r,a=n*Math.sqrt(i*(1-i)/e+n*n/(4*e*e))/r;return{rate:i,low:Math.
max(0,o-a),high:Math.min(1,o+a)}}function gt(t){let e=Ie(t),n=[...ke(e.mission,e.duration),...Ce(e.analysis,e.duration)];if((!e.mission||!e.analysis)&&n.push("成功条件と分析条件を設定してください。"),
n.length)throw new Error(n.join(`
`));let i=e.analysis,r=e.trial??0;if(r+i.trials-1>1e9)throw new Error("試行番号の上限を超えます。");let o=et(e);for(let a of o){for(let s of[...a.settings,...i.uncertainties??
[]])Se(e,s);se(Ae(e,a,r,{maximum:!0}).scenario)}return{scenario:e,analysis:i,startTrial:r,conditions:o}}function qe(t,e){let n=e.filter(a=>a.success).length,i=e.filter(a=>a.success).
map(a=>a.successTime).sort((a,s)=>a-s),r=i.length,o=r?r%2?i[(r-1)/2]:(i[r/2-1]+i[r/2])/2:null;return{count:t,total:e.length,successes:n,...Ft(n,e.length),median:o,invalidTrials:e.filter(
a=>a.invalidUnits>0).length,trials:e}}var de=0;self.onmessage=({data:t})=>{if(t.type==="cancel"){de++;return}t.type==="run"&&Rt(t,++de)};async function Rt(t,e){let n=performance.now();try{let{scenario:i,analysis:r,startTrial:o,
conditions:a}=gt(t.scenario),s=[],d=a.length*r.trials,c=0,f=0,l=performance.now();for(let g of a){let h=[];for(let w=0;w<r.trials;w++){if(e!==de)return;let v=o+w,{scenario:M,sampled:T}=Ae(
i,g,v),I=ht(M),S=mt(I,M.mission,r.step),F=S.next();for(;!F.done;){if(performance.now()-l>16&&(await new Promise(p=>setTimeout(p,0)),l=performance.now(),e!==de))return;F=S.next()}let j=F.
value;h.push({...M.mission?.type==="state"?{stateEntries:j.stateEntries,stateTargetCount:j.stateTargetCount,stateReachedCount:j.stateReachedCount}:{},reachedCount:j.reachedCount??0,
responderCount:j.responderCount??0,trial:v,sampled:T,success:j.success,successTime:j.successTime,detectedCount:j.detectedCount,targetCount:j.targetCount,invalidUnits:j.invalidUnits,
constrainedPaths:j.constrainedPaths}),c++,(performance.now()-f>120||w===r.trials-1)&&(f=performance.now(),self.postMessage({type:"progress",runId:t.runId,completed:c,planned:d,elapsedMs:performance.
now()-n,rows:[...s,{...qe(g.count,h),condition:g}]})),await new Promise(p=>setTimeout(p,0)),l=performance.now()}s.push({...qe(g.count,h),condition:g})}e===de&&self.postMessage({type:"\
complete",runId:t.runId,completed:c,planned:d,elapsedMs:performance.now()-n,rows:s})}catch(i){e===de&&self.postMessage({type:"error",runId:t.runId,message:i.message})}}})();
