/* SimSim portable 20261006-terrain-grid-17-9a15c60f8b6a. Generated by npm run build:portable. */
(()=>{var Pt={number:"数値",route:"経路",destination:"目的地",unit:"単体ユニット"},it={routeId:"route",destinationId:"destination",receiverId:"unit",seconds:"number",speedFraction:"\
number",distance:"number"},ne=t=>!!t&&typeof t=="object"&&!Array.isArray(t)&&Object.keys(t).length===1&&typeof t.$param=="string";function be(t,e,n){if(!ne(t))return t;let i=Array.
isArray(e?.parameters)?e.parameters.find(r=>r?.id===t.$param):null;return Object.hasOwn(n?.parameters??{},t.$param)?n.parameters[t.$param]:i?.default}function xe(t,e){if(!t)return t;
let n=i=>i&&typeof i=="object"?Object.fromEntries(Object.entries(i).map(([r,o])=>[r,be(o,t,e)])):i;return{...t,nodes:t.nodes.map(n),edges:t.edges.map(n),triggers:(t.triggers??[]).map(
n)}}function Le(t,e,n){if(!Array.isArray(e.nodes)||!Array.isArray(e.edges)||e.triggers!==void 0&&!Array.isArray(e.triggers))return["挙動のノード・条件の形式が不正です。"];
let i=[],r=e.parameters??[],o=new Set;if(!Array.isArray(r)||r.length>64)return["担当時に指定する値は最大64件の配列です。"];let a=(s,d)=>s.type==="number"?Number.
isFinite(d):typeof d=="string"&&(s.type==="route"?t.routes:s.type==="destination"?t.destinations:t.units)?.some?.(u=>u.id===d);for(let s of r){if(!s||!/^[a-zA-Z0-9_-]{1,80}$/.test(
s.id??"")||o.has(s.id)||typeof s.name!="string"||!s.name.trim()||s.name.length>120||!Object.hasOwn(Pt,s.type)){i.push("担当値のID・名前・種類が不正または重複しています。");
continue}o.add(s.id),s.unit!==void 0&&(s.type!=="number"||!["s","m","ratio"].includes(s.unit))&&i.push("担当値の単位が不正です。"),Object.hasOwn(s,"default")&&!a(s,s.default)&&
i.push("担当値「"+s.name+"」の既定値が不正です。"),n&&!a(s,be({$param:s.id},e,n))&&i.push("タスク「"+n.name+"」で「"+s.name+"」を指定してください。")}
for(let s of[...e.nodes,...e.edges,...e.triggers??[]].filter(d=>d&&typeof d=="object"))for(let[d,u]of Object.entries(s))if(u&&typeof u=="object"&&(Object.hasOwn(u,"$param")||it[d])){
let f=ne(u)?r.find(g=>g?.id===u.$param):null,p={seconds:"s",distance:"m",speedFraction:"ratio"}[d];(!f||f.type!==it[d]||p&&f.unit&&f.unit!==p)&&i.push("担当値の参照・種類・単位が不正です: "+
d)}return n?.parameters!==void 0&&(!n.parameters||typeof n.parameters!="object"||Array.isArray(n.parameters)||Object.keys(n.parameters).some(s=>!o.has(s)))&&i.push("タスクの担当値に未定義の項目が\
あります。"),i}var rt=Number.isFinite,Z=class{constructor(e){this.data=e,this.minX=e.origin.x,this.minY=e.origin.y,this.maxX=this.minX+(e.columns-1)*e.spacing,this.maxY=this.minY+(e.rows-1)*(e.spacingY??
e.spacing),this.cellSize=Math.min(e.spacing,e.spacingY??e.spacing)}contains(e,n){return rt(e)&&rt(n)&&e>=this.minX&&e<=this.maxX&&n>=this.minY&&n<=this.maxY}height(e,n){if(!this.contains(
e,n))return null;let i=this.data,r=(e-this.minX)/i.spacing,o=(n-this.minY)/(i.spacingY??i.spacing),a=Math.min(i.columns-2,Math.floor(r)),s=Math.min(i.rows-2,Math.floor(o)),d=r-a,u=o-
s,f=(p,g)=>i.elevations[(s+g)*i.columns+a+p];return(f(0,0)*(1-d)+f(1,0)*d)*(1-u)+(f(0,1)*(1-d)+f(1,1)*d)*u}project(e,n){let i={...e},r=this.height(i.x,i.y),o=this.data.seaLevel;return r===
null?{point:i,error:"地形データの範囲外です"}:n==="ground"&&(i.z=r,r<=o)?{point:i,error:"地上ユニットは陸上に配置してください"}:n==="surface"&&(i.z=o,r>
o-5)?{point:i,error:"水上ユニットには5m以上の水深が必要です"}:n==="subsurface"&&(i.z>o-1||i.z<r+5||r>=o)?{point:i,error:"水中ユニットは海面下かつ海底から5m以上離してください"}:
n==="air"&&i.z<=Math.max(r,o)+10?{point:i,error:"空中ユニットは地表・海面から10mより高くしてください"}:{point:i,error:null}}};var Nt=["ground","surface","subsurface","air"],Te=Number.isFinite,Ce=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n}),de=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z);
function fe(t){return!t||typeof t!="object"||Array.isArray(t)||!Nt.includes(t.domain)||t.clearance!==void 0&&(!Te(t.clearance)||t.clearance<0||t.clearance>1e4)?["経路検査の領域・地表／海底からの余裕\
（0～10000m）が不正です。"]:[]}function Ue(t,e="once"){let n=fe(t);return!t||n.length||((!Array.isArray(t.via)||t.via.length<(e==="loop"?3:2)||t.via.length>100||t.via.some(
i=>!i||!["x","y"].every(r=>Te(i[r])&&Math.abs(i[r])<=1e6)))&&n.push("自動生成の必須経由地点は2～100点（周回は3点以上）の東西・南北座標です。"),["ai\
r","subsurface"].includes(t.domain)&&(!Te(t.height)||t.height<-1e6||t.height>1e6)&&n.push("自動生成する高度・深度のz座標を指定してください。"),t.height!==void 0&&
(!Te(t.height)||Math.abs(t.height)>1e6)&&n.push("高度・深度は数値で指定してください。")),n}function Ft(t,e,n){let i=t.height(e.x,e.y),r=t.data.seaLevel;return i===
null?-1/0:n==="ground"?i-r:n==="surface"?r-i-5:n==="subsurface"?Math.min(e.z-i-5,r-e.z-1):e.z-Math.max(i,r)-10}function pe(t,e,n){let i=Ft(t,e,n.domain),r=n.clearance??0;if(i<r-1e-7||
["ground","air"].includes(n.domain)&&i<=0){let o=t.project(e,n.domain);return{point:{...e},reason:o.error??"地表・海底／海面からの余裕 "+r+"mを満たしていません。",
margin:i}}return null}function we(t,e,n,i){let r=t instanceof Z?t:new Z(t),o=pe(r,e,i),a=pe(r,n,i);if(o)return o;if(a)return a;let s=[0,1],d=r.data;for(let[u,f,p,g]of[["x",d.columns,
d.spacing,d.origin.x],["y",d.rows,d.spacingY??d.spacing,d.origin.y]]){let m=n[u]-e[u];if(!m)continue;let v=Math.min(e[u],n[u]),x=Math.max(e[u],n[u]);for(let b=Math.max(1,Math.ceil(
(v-g)/p));b<=Math.min(f-2,Math.floor((x-g)/p));b++){let z=(g+b*p-e[u])/m;z>0&&z<1&&s.push(z)}}s.sort((u,f)=>u-f);for(let u=1;u<s.length;u++){let f=s[u-1],p=s[u];if(p-f<1e-12)continue;
let g=Ce(e,n,f),m=Ce(e,n,p),v=Ce(e,n,(f+p)/2),x=r.height(g.x,g.y),b=r.height(m.x,m.y),z=r.height(v.x,v.y),w=2*(x+b-2*z),S=b-x-w,j=[0,1];if(Math.abs(w)>1e-12)for(let O of[-S,m.z-g.z-
S]){let l=O/(2*w);l>0&&l<1&&j.push(l)}for(let O of j){let l=pe(r,Ce(e,n,f+(p-f)*O),i);if(l)return l}}return null}function Rt(t,e,n,{loop:i=!1}={}){let r=fe(n);if(r.length)throw Error(
r[0]);let o=t instanceof Z?t:new Z(t),a=[];if(!Array.isArray(e)||!e.length)return{ok:!0,issues:a};if(e.length===1){let s=pe(o,e[0],n);s&&a.push({segment:0,from:e[0],to:e[0],...s})}
for(let s=1;s<e.length+(i?1:0);s++){let d=e[s-1],u=e[s%e.length],f=we(o,d,u,n);f&&a.push({segment:s-1,from:{...d},to:{...u},...f})}return{ok:!a.length,issues:a}}var Ye=class{constructor(){
this.values=[]}push(e){let n=this.values.length;for(this.values.push(e);n;){let i=n-1>>1;if(this.values[i].score<=e.score)break;this.values[n]=this.values[i],n=i}this.values[n]=e}pop(){
let e=this.values[0],n=this.values.pop();if(this.values.length){let i=0;for(;i*2+1<this.values.length;){let r=i*2+1;if(r+1<this.values.length&&this.values[r+1].score<this.values[r].
score&&r++,this.values[r].score>=n.score)break;this.values[i]=this.values[r],i=r}this.values[i]=n}return e}};function Dt(t,e,n,i,r){if(!we(t,e,n,i))return[{...e},{...n}];let{nx:o,ny:a,
sx:s,sy:d,height:u}=r,f=o*a,p=new Array(f),g=new Float64Array(f).fill(1/0),m=new Int32Array(f).fill(-1),v=new Uint8Array(f),x=new Ye,b=I=>{if(p[I]!==void 0)return p[I];let _={x:t.minX+
I%o*s,y:t.minY+Math.floor(I/o)*d,z:u},H=t.project(_,i.domain);return p[I]=pe(t,_,i)?null:H.point},z=I=>{let _=Math.round((I.x-t.minX)/s),H=Math.round((I.y-t.minY)/d),$=[];for(let U=-2;U<=
2;U++)for(let q=-2;q<=2;q++){let G=_+q,J=H+U;if(G<0||G>=o||J<0||J>=a)continue;let h=J*o+G,M=b(h);M&&!we(t,I,M,i)&&$.push(h)}return $},w=new Set(z(n));if(!w.size)throw Error("目的地付近に\
接続できる通行可能な経路がありません。地点・高度／深度・余裕を調整してください。");for(let I of z(e))g[I]=de(e,b(I)),x.push({i:I,score:g[I]+
de(b(I),n)});let S=-1;for(;x.values.length;){let{i:I}=x.pop();if(v[I])continue;if(v[I]=1,w.has(I)){S=I;break}let _=I%o,H=Math.floor(I/o),$=b(I);for(let U=-1;U<=1;U++)for(let q=-1;q<=
1;q++){if(!q&&!U)continue;let G=_+q,J=H+U;if(G<0||G>=o||J<0||J>=a)continue;let h=J*o+G;if(v[h])continue;let M=b(h);if(!M)continue;let T=g[I]+de($,M);T>=g[h]||we(t,$,M,i)||(m[h]=I,g[h]=
T,x.push({i:h,score:T+de(M,n)}))}}if(S<0)throw Error("この領域・高度／深度・余裕では経路を生成できませんでした。通れる海峡・陸地がつながっているか、必須地点を確認してください。");
let j=[{...n}];for(let I=S;I>=0;I=m[I])j.push(b(I));j.push({...e}),j.reverse();let O=[j[0]],l=0;for(;l<j.length-1;){let I=j.length-1;for(;I>l+1&&we(t,j[l],j[I],i);)I--;O.push(j[I]),
l=I}return O}function _t(t,e,{mode:n="once"}={}){let i=Ue(e,n);if(i.length)throw Error(i.join(`
`));let r=t instanceof Z?t:new Z(t),o={domain:e.domain,clearance:e.clearance??0},a=e.height??r.data.seaLevel,s=e.via.map((b,z)=>{let w={x:b.x,y:b.y,z:a},S=pe(r,w,o);if(S)throw Error(
"必須地点 "+(z+1)+"："+S.reason);return r.project(w,e.domain).point});if(s.every(b=>de(b,s[0])<1e-6))throw Error("異なる出発地点・目的地を指定してください。");
let d=r.maxX-r.minX,u=r.maxY-r.minY,f=Math.max(Math.min(r.data.spacing,r.data.spacingY??r.data.spacing)/4,Math.max(d,u)/256),p=Math.max(2,Math.ceil(d/f)+1),g=Math.max(2,Math.ceil(u/
f)+1),m={nx:p,ny:g,sx:d/(p-1),sy:u/(g-1),height:a},v=[s[0]];for(let b=1;b<s.length+(n==="loop"?1:0);b++)de(v.at(-1),s[b%s.length])<1e-8||v.push(...Dt(r,v.at(-1),s[b%s.length],o,m).
slice(1));if(n==="loop"&&de(v[0],v.at(-1))<1e-6&&v.pop(),v.length>500)throw Error("生成経路が500点を超えました。必須地点を減らしてください。");if(v.length<
(n==="loop"?3:2))throw Error("周回は異なる必須地点を3点以上指定してください。");if(!Rt(r,v,o,{loop:n==="loop"}).ok)throw Error("生成経路の検査に失敗しました。条件を調整してください。");
return{points:v,navigation:o}}function ot(t){for(let e of t.routes??[])if(e.generate)try{let n=_t(t.terrain,e.generate,{mode:e.mode??"once"});Object.assign(e,n),delete e.generate}catch(n){
throw Error("経路「"+e.name+"」："+n.message)}return t}function je(t,e,n,i){let r=t.behaviors?.find(s=>s.id===e?.behaviorId),o=be(n?.routeId,r,e),a=o?t.routes?.find(s=>s.id===o):null;return{id:a?.id??"default",points:a?.points??e?.route??
[i.initial,...i.route],mode:n?.kind==="patrol"?"loop":a?.mode??e?.routeMode??i.routeMode}}function re(t,e,n){let i=be(n?.destinationId,t.behaviors?.find(r=>r.id===e?.behaviorId),e);
return i?t.destinations?.find(r=>r.id===i):e?.base?{kind:"point",point:e.base}:null}function oe(t){let e=t.when??t.event;return e==="near"?[e,t.destinationId,t.distance,t.distanceMode??
"absolute"].map(n=>ne(n)?JSON.stringify(n):n).join("|"):e==="time"?e+"|"+(ne(t.seconds)?JSON.stringify(t.seconds):t.seconds):e}var st=(t,e,n="absolute")=>Math.hypot(t.x-e.x,t.y-e.y,
n==="horizontal"?0:t.z-e.z);function at(t){let e=[],n=(r,o,a)=>Number.isFinite(r)&&r>=o&&r<=a,i=r=>r&&["x","y","z"].every(o=>n(r[o],-1e6,1e6));for(let[r,o]of[["routes",128],["desti\
nations",256]]){let a=t[r]??[],s=new Set;if(!Array.isArray(a)||a.length>o){e.push(r==="routes"?"経路は最大128件の配列です。":"目的地は最大256件の配列です。");
continue}for(let d of a){if(!d||!/^[a-zA-Z0-9_-]{1,80}$/.test(d.id??"")||s.has(d.id)||typeof d.name!="string"||!d.name.trim()||d.name.length>120){e.push("経路・目的地のIDまたは名前が不正・重複しています。");
continue}s.add(d.id),r==="routes"?(d.generate!==void 0?(d.points!==void 0&&e.push("経路にはpointsかgenerateのどちらか一方を指定してください。"),e.push(...Ue(d.
generate,d.mode??"once"))):(!Array.isArray(d.points)||d.points.length<2||d.points.length>500||d.points.some(u=>!i(u)))&&e.push("経路は2～500点の座標で指定してください。"),
d.navigation!==void 0&&e.push(...fe(d.navigation)),["once","loop","pingpong"].includes(d.mode??"once")||e.push("経路の繰り返し方式が不正です。")):d.kind==="point"?i(
d.point)||e.push("目的地の地点座標が不正です。"):d.kind==="unit"?t.units?.some(u=>u.id===d.unitId)||e.push("目的地のユニットがありません。"):d.kind!=="\
received"&&e.push("目的地は地点・ユニット・受信した目標位置を指定してください。")}}return e}function qe(t,e,n=!1){let i=[];return!(n&&ne(e.destinationId))&&
(!Array.isArray(t.destinations)||!t.destinations.some(r=>r?.id===e.destinationId))&&i.push("接近条件の目的地を選択してください。"),!(n&&ne(e.distance))&&(!Number.
isFinite(e.distance)||e.distance<0||e.distance>1e6)&&i.push("接近距離は0～1000000mです。"),["horizontal","absolute"].includes(e.distanceMode??"absolute")||i.push("距離の種類は水平\
距離または絶対距離です。"),i}var Lt={follow:"経路を進む",patrol:"協調して周回",signal:"情報を待つ",report:"報告",move:"目的に向かって進む",wait:"時間待ち",stop:"終了"},Yt={received:"\
情報受信",time:"時間経過",detected:"対象探知",near:"指定距離まで近づく"};function dt(t){return t.initial??t.entry??(Array.isArray(t.triggers)?t.triggers.find(e=>e?.
event==="scenarioStart")?.to:void 0)}function Be(t){return(t.triggers??[]).filter(e=>e?.event!=="scenarioStart")}function ut(t){for(let e of t.behaviors??[]){let n=dt(e);n!==void 0&&
(e.initial=n),e.triggers=Be(e);for(let i of e.triggers)delete i.policy;for(let i of e.nodes)i.kind==="return"&&(i.kind="move");delete e.entry}return t}var Ut={follow:["detected","received","arrived","near"],patrol:["detected","received","near"],signal:["received","detected","near"],report:["sent","sendFailed","near"],move:["arriv\
ed","received","detected","near"],return:["arrived","received","detected","near"],wait:["elapsed","received","detected","near"],stop:[]};var Q=(t,e,n)=>Number.isFinite(t)&&t>=e&&t<=n,Je=t=>t&&["x","y","z"].every(e=>Q(t[e],-1e6,1e6));function Ge(t,e=!1){let n=at(t),i=t.behaviors??[],r=t.behaviorAssignments??[];if(!Array.
isArray(i)||i.length>50)return["挙動は最大50件の配列です。"];if(!Array.isArray(r)||r.length>100)return["タスクは最大100件の配列です。"];let o=Array.isArray(
t.routes)?t.routes:[],a=Array.isArray(t.destinations)?t.destinations:[],s=new Set,d=new Set,u=new Set;for(let m of i){if(!m||!/^[a-zA-Z0-9_-]{1,80}$/.test(m.id??"")||s.has(m.id)){n.
push("挙動IDが不正または重複しています。");continue}if(s.add(m.id),(typeof m.name!="string"||!m.name.trim()||m.name.length>120)&&n.push("挙動名は1～120文字です。"),
!Array.isArray(m.nodes)||!m.nodes.length||m.nodes.length>64||!Array.isArray(m.edges)||m.edges.length>128){n.push("挙動は1～64ノード、最大128接続です。");continue}e||
n.push(...Le(t,m));let v=(l,I,_)=>!e&&ne(l)||Q(l,I,_),x=l=>!ne(l),b=new Map,z=new Set;for(let l of m.nodes){if(!l||!/^[a-zA-Z0-9_-]{1,80}$/.test(l.id??"")||b.has(l.id)||!(Lt[l.kind]||
l.kind==="return")){n.push("ノードID・種類が不正です。");continue}if(b.set(l.id,l),l.routeId!==void 0&&(!["follow","patrol"].includes(l.kind)||x(l.routeId)&&!o.some(I=>I?.
id===l.routeId))&&n.push("状態ノードの経路参照が不正です。"),l.destinationId!==void 0&&(!["move","return"].includes(l.kind)||x(l.destinationId)&&!a.some(I=>I?.id===
l.destinationId))&&n.push("状態ノードの目的地参照が不正です。"),l.kind==="patrol"&&l.routeId&&x(l.routeId)&&o.find(I=>I?.id===l.routeId)?.points?.length<3&&n.push(
"周回経路は3点以上必要です。"),l.kind==="patrol"&&l.routeId&&x(l.routeId)){let I=o.find(_=>_?.id===l.routeId);I?.generate&&I.mode!=="loop"&&n.push("協調して周回する自動生成経路はmode\
をloopにしてください。")}l.kind==="wait"&&!v(l.seconds,0,86400)&&n.push("待機時間は0～86400秒です。"),l.kind==="patrol"&&!v(l.speedFraction??.7,.05,1)&&n.push("巡\
回速度比は0.05～1です。"),l.kind==="report"&&!l.receiverId&&!l.receiverRole&&n.push("報告先または報告先の役割を指定してください。"),l.receiverId&&x(l.
receiverId)&&!t.units?.some(I=>I.id===l.receiverId)&&n.push("報告先の単体ユニットがありません: "+l.receiverId),l.joinMode!==void 0&&(!["follow","patrol"].includes(l.
kind)||!["start","nearest"].includes(l.joinMode))&&n.push("経路への入り方は最初から／最短地点からを選択してください。"),l.heightMode!==void 0&&(l.kind!==
"move"||!["keep","target"].includes(l.heightMode))&&n.push("移動の高度・深度は維持する／目的地に合わせるを選択してください。"),l.sensor!==void 0&&typeof l.
sensor!="boolean"&&n.push("ノードのsensorはbooleanです。"),(l.x!==void 0&&!Q(l.x,0,4e3)||l.y!==void 0&&!Q(l.y,0,4e3))&&n.push("ノード位置が不正です。")}let w=dt(
m),S=m.triggers??[],j=new Set,O=new Set;if(w!==void 0&&!b.has(w)&&n.push("初期状態の参照先がありません。"),(m.initial!==void 0&&m.entry!==void 0&&m.initial!==m.entry||
m.triggers?.some?.(l=>l?.event==="scenarioStart"&&l.to!==w))&&n.push("初期状態の指定が重複しています。"),!Array.isArray(S)||S.length>32)n.push("イベントノードは最大32件の配列です。");else if(w===
void 0&&!S.length)n.push("初期状態またはイベントノードを指定してください。");else for(let l of S){(!l||!/^[a-zA-Z0-9_-]{1,80}$/.test(l.id??"")||j.has(l.id)||
!(Object.hasOwn(Yt,l.event)||l.event==="scenarioStart")||!b.has(l.to))&&n.push("イベントノードのID・種類・接続先が不正です。"),j.add(l?.id);let I=l?oe(l):"";O.
has(I)&&n.push("同じイベント・時間のイベントノードは一つだけ指定できます。"),O.add(I),l?.event==="time"&&(!v(l.seconds,0,86400)||l.once===!1&&l.seconds===
0)&&n.push("時間イベントは0～86400秒、繰り返す場合は0より大きい秒数です。"),l?.policy!==void 0&&!["idle","interrupt"].includes(l.policy)&&n.push("起動方法はid\
le・interruptです。"),l?.once!==void 0&&typeof l.once!="boolean"&&n.push("イベントノードのonceはbooleanです。"),l?.event==="near"&&n.push(...qe(t,l,!e)),(l?.x!==void 0&&
!Q(l.x,0,4e3)||l?.y!==void 0&&!Q(l.y,0,4e3))&&n.push("イベントノードの位置が不正です。")}for(let l of m.edges){let I=l?.from+"|"+(l?oe(l):""),_=b.get(l?.from);(!l||
!_||!b.has(l.to)||!(Ut[_.kind]??[]).includes(l.when)||z.has(I))&&n.push("接続条件が始点ノードに対応しないか、接続が不正・重複しています。"),l?.once!==
void 0&&typeof l.once!="boolean"&&n.push("接続のonceはbooleanです。"),l?.when==="near"&&n.push(...qe(t,l,!e)),z.add(I)}}for(let m of r){if(!m||!/^[a-zA-Z0-9_-]{1,80}$/.test(
m.id??"")||d.has(m.id)){n.push("タスクIDが不正または重複しています。");continue}d.add(m.id),(typeof m.name!="string"||!m.name.trim()||m.name.length>120)&&n.push("タ\
スク名は1～120文字です。");let v=i.find(w=>w.id===m.behaviorId);if(v||n.push("タスクの挙動がありません。"),!Array.isArray(m.targets)||!m.targets.length&&!(t.
mission?.type==="state"&&t.mission.assignmentId===m.id)||m.targets.length>100){n.push("タスクの担当を選んでください。");continue}for(let w of m.targets){let S=typeof w==
"string"?w.split(":")[0]:"",j=typeof w=="string"?w.slice(S.length+1):"";(!(S==="unit"?t.units?.find(l=>l.id===j):S==="group"&&t.groups?.find(l=>l.id===j)?.template)||u.has(w))&&n.push(
"タスクの担当が不正または重複しています。"),u.add(w)}if(v){let w=Le(t,v,m);if(n.push(...w),!w.length&&v.parameters?.length){let S=xe(v,m);n.push(...Ge({...t,behaviors:[
S],behaviorAssignments:[]},!0).map(j=>"タスク「"+m.name+"」: "+j))}}let x=v&&Array.isArray(v.nodes)&&Array.isArray(v.edges)?xe(v,m):null,b=x?.nodes.some(w=>w.kind==="patrol"&&
!w.routeId),z=x?.nodes.some(w=>["return","move"].includes(w.kind)&&!w.destinationId);b&&(!Array.isArray(m.route)||m.route.length<3)&&n.push("周回タスクは3点以上の共有経路が必要です。"),
m.route!==void 0&&(!Array.isArray(m.route)||m.route.length>500||m.route.some(w=>!Je(w)))&&n.push("タスクの経路が不正です。"),z&&!Je(m.base)&&n.push("目的に向かって進む状態の目的地を選択し\
てください。"),m.base!==void 0&&!Je(m.base)&&n.push("帰投地点が不正です。"),m.routeMode!==void 0&&!["once","loop","pingpong"].includes(m.routeMode)&&n.push("タスクの経路方\
式が不正です。"),["even","fixed","none"].includes(m.spacing??"none")||n.push("間隔方式が不正です。"),(!Q(m.spacingDistance??500,0,1e5)||!Q(m.gain??.01,0,1)||!Q(m.preparation??
0,0,86400)||!Q(m.phase??0,0,1))&&n.push("タスクの間隔・調整係数・準備時間・開始割合が不正です。"),x?.nodes.some(w=>w.receiverRole&&!w.receiverId)&&!t.units?.
some(w=>w.id===m.receiverId)&&n.push("タスクの報告先を選んでください。")}let f=t.recording??{},p=f.step??t.analysis?.step??10,g=f.interval??p;return(!Q(p,.1,300)||!Q(
g,.1,300)||g<p||Math.abs(g/p-Math.round(g/p))>1e-8||t.duration/p>1e5)&&n.push("計算刻み0.1～300秒、記録間隔は刻みの整数倍・300秒以下、最大10万ステップです。"),
t.version===3&&t.analysis&&t.analysis.step!==p&&n.push("分析と記録の計算刻みを一致させてください。"),n}function ct(t,e){let n=t.units?.find(r=>r.id===e),i=n?.groupId??t.groups?.find(r=>e?.slice(0,e.lastIndexOf("__"))===r.id)?.id;return t.behaviorAssignments?.find(r=>r.targets.includes(
"unit:"+e)||i&&r.targets.includes("group:"+i))}function B(t){let e=2166136261;for(let n=0;n<t.length;n++)e^=t.charCodeAt(n),e=Math.imul(e,16777619);return e^=e>>>16,e=Math.imul(e,2146121005),e^=e>>>15,e=Math.imul(e,2221713035),
e^=e>>>16,(e>>>0)/4294967296}var qt=t=>t*t*(3-2*t);function He(t,e,n){let i=Math.floor(e/n),r=qt(e/n-i),o=d=>{let u=B(t+"|angle|"+d)*Math.PI*2,f=Math.sqrt(B(t+"|radius|"+d));return[
Math.cos(u)*f,Math.sin(u)*f,B(t+"|z|"+d)*2-1]},a=o(i),s=o(i+1);return a.map((d,u)=>d+(s[u]-d)*r)}function ie(t,e,n){return"simsim-rng-v1|"+JSON.stringify([t.seed??"SimSim",t.trial??
0,e,n])}function $e(t){let e=t.units.map(n=>({...n}));for(let n of t.groups??[]){let i=Math.ceil(Math.sqrt(n.count)),r=Math.ceil(n.count/i);for(let o=0;o<n.count;o++){let a=n.id+"_\
_"+(o+1),s=ie(t,a,"deployment"),d=n.placement==="random"?B(s+"|x"):(o%i+.5)/i,u=n.placement==="random"?B(s+"|y"):(Math.floor(o/i)+.5)/r,f=(d-.5)*n.width,p=(u-.5)*n.height,g=x=>({...x,
x:x.x+f,y:x.y+p}),m=n.loopStartMode??"template",v=n.template.routeMode==="loop"&&m!=="template"?{...n.template.motion,loopStart:((n.template.motion?.loopStart??0)+(m==="even"?o/n.count:
B(ie(t,a,"loop-start-placement-v1"))))%1}:n.template.motion;e.push({...n.template,...v?{motion:v}:{},enabled:n.enabled!==!1,id:a,name:(n.name+" "+(o+1)).slice(0,120),groupId:n.id,initial:g(
n.template.initial),route:n.template.route.map(g)})}}return e}var F=(t,e,n,i,r,o,a={})=>({key:t,label:e,family:n,path:i,min:r,max:o,scale:1,scope:"entity",...a}),Jt=[F("rate.movement.speed","移動速度","Rate","speed",0,1500,{unit:"m/s",default:0}),
F("extent.sense.radius","最大探知距離","Extent","sensor.range",.001,1e5,{unit:"km",scale:1e3,sensor:!0}),F("interaction.detection.probability","距離0で1分の探知確率",
"Interaction","sensor.probabilityPerMinute",0,1,{unit:"%",scale:.01,sensor:!0}),F("extent.communication.radius","最大通信距離","Extent","communication.range",.001,1e5,{unit:"\
km",scale:1e3,communication:!0}),F("interaction.communication.delay","通信遅延","Interaction","communication.delay",0,86400,{unit:"s",communication:!0}),F("interaction.communic\
ation.probability","通信成功確率","Interaction","communication.probability",0,1,{unit:"%",scale:.01,communication:!0}),F("behavior.preparation","出発準備時間","Behavior",
"preparation",0,86400,{unit:"s",scope:"assignment",preparation:!0,default:0}),F("extent.signature.coefficient","被探知係数","Extent","detectability",0,10,{unit:"倍",default:1}),
F("state.position.x","配置・経路の中心 x","State","initial.x",-1e6,1e6,{unit:"km",scale:1e3,translate:"x"}),F("state.position.y","配置・経路の中心 y","State","initi\
al.y",-1e6,1e6,{unit:"km",scale:1e3,translate:"y"}),F("state.position.z","高度・深度 z","State","initial.z",-2e4,1e5,{unit:"m",translate:"z",vertical:!0}),F("extent.sense.moun\
tHeight","センサー取付高","Extent","sensor.mountHeight",0,1e3,{unit:"m",sensor:!0,default:0}),F("state.route.phase","周回の出発点","State","motion.loopStart",0,1,{unit:"\
%",scale:.01,default:0,loopOnly:!0}),F("motion.horizontal","個体の水平ずれ上限","Motion","motion.horizontal",0,1e4,{unit:"m",default:0}),F("motion.commonHorizontal","群共通の水\
平ずれ上限","Motion","motion.commonHorizontal",0,1e4,{unit:"m",default:0}),F("motion.vertical","上下ずれ上限","Motion","motion.vertical",0,3e3,{unit:"m",default:0,vertical:!0}),
F("motion.scale","航跡の変動間隔","Motion","motion.scale",10,1e5,{unit:"m",default:2e3}),F("motion.startDelay","出発遅れ上限","Motion","motion.startDelay",0,86400,{unit:"\
s",default:0}),F("motion.speedVariation","個体速度のばらつき","Motion","motion.speedVariation",0,1,{unit:"±%",scale:.01,default:0}),F("capacity.population","群の個数",
"Capacity","count",0,2e3,{unit:"個",scope:"group",integer:!0}),F("extent.deployment.width","配置幅 x","Extent","width",0,1e5,{unit:"km",scale:1e3,scope:"group"}),F("extent.depl\
oyment.height","配置幅 y","Extent","height",0,1e5,{unit:"km",scale:1e3,scope:"group"}),F("task.route.x","共有経路の基準 x","State","route.0.x",-1e6,1e6,{unit:"km",scale:1e3,
scope:"assignment",routeAxis:"x"}),F("task.route.y","共有経路の基準 y","State","route.0.y",-1e6,1e6,{unit:"km",scale:1e3,scope:"assignment",routeAxis:"y"}),F("task.route.z",
"共有経路の高度・深度","State","route.0.z",-2e4,1e5,{unit:"m",scope:"assignment",routeAxis:"z"}),F("task.route.phase","共有周回の出発点","State","phase",0,1,{unit:"\
%",scale:.01,scope:"assignment",default:0,patrol:!0}),F("coordination.spacing","協調する指定間隔","Behavior","spacingDistance",0,1e5,{unit:"m",scope:"assignment",fixedSpacing:!0,
default:500}),F("coordination.gain","間隔の調整係数","Behavior","gain",0,1,{unit:"1/s",scope:"assignment",default:.01}),F("mission.deadline","成功条件の期限","Mission",
"mission.deadline",1e-6,86400,{unit:"min",scale:60,scope:"scenario"})],Me=t=>Jt.find(e=>e.key===t),Ie=t=>JSON.stringify([t.target,t.parameter]);function lt(t){let e=JSON.parse(JSON.
stringify(t));return e.factors=[...t.groupId?[{target:"group:"+t.groupId,parameter:"capacity.population",values:[...t.counts].sort((n,i)=>n-i)}]:[],...e.factors??[]],delete e.groupId,
delete e.counts,e}var Bt=t=>JSON.parse(JSON.stringify(t));function pt(t,e,n){if(e==="scenario"){if(n.scope!=="scenario"||!t.mission)throw new Error("成功条件を設定してください。");
return t}let i=e?.indexOf(":")??-1,r=e?.slice(0,i),o=e?.slice(i+1),a=r==="unit"?t.units?.find(d=>d.id===o):r==="group"?t.groups?.find(d=>d.id===o):r==="assignment"?t.behaviorAssignments?.
find(d=>d.id===o):null;if(!a||n.scope==="scenario"||n.scope==="group"&&r!=="group")throw new Error("変数の対象が見つかりません: "+e);if(n.scope==="assignment"!=(r==="a\
ssignment"))throw new Error("変数の対象が一致しません。");let s=r==="group"&&n.scope==="entity"?a.template:a;if(r!=="assignment"&&ct(t,r==="group"?o+"__1":o)?.route?.length&&
(n.translate||n.loopOnly||n.key.startsWith("extent.deployment.")))throw new Error("共有経路の位置・開始割合はタスク側の変数を選んでください。");if(n.loopOnly&&
s.routeMode!=="loop")throw new Error("周回の出発点は周回経路の対象に指定してください。");if(n.communication&&!s.communication?.enabled)throw new Error("通信変数\
の対象で通信を有効にしてください。");if(n.behavior&&!s.behavior)throw new Error("条件付き行動の設定がありません。");if(n.sensor&&!s.sensor)throw new Error(
"探知変数の対象にセンサーがありません。");return s}var Gt=(t,e)=>e.split(".").reduce((n,i)=>n?.[i],t);function Oe(t,e){let n=Me(e.parameter);if(!n)throw new Error(
"未対応の変数です。");let i=pt(t,e.target,n);return Gt(i,n.path)??(n.key==="extent.sense.mountHeight"&&i.domain==="ground"?2:n.default)}function Ht(t,e,n){let i=Me(e.parameter),
r=pt(t,e.target,i),o=i.path.split(".");if(i.routeAxis){let s=n-r.route[0][i.routeAxis];for(let d of r.route)d[i.routeAxis]+=s;return}if(i.translate){let s=n-r.initial[i.translate];
for(let d of r.route??[])d[i.translate]+=s}let a=r;for(let s of o.slice(0,-1))a[s]===void 0&&(a[s]={}),a=a[s];a[o.at(-1)]=n}function $t(t,e,n){let i=Me(e.parameter),r=e.target;return e.target.startsWith("group:")&&(r=t.groups?.find(o=>o.id===e.target.slice(6))?.name??r),e.target.startsWith("assignment:")&&
(r=t.behaviorAssignments?.find(o=>o.id===e.target.slice(11))?.name??r),e.target.startsWith("unit:")&&(r=t.units?.find(o=>o.id===e.target.slice(5))?.name??r),r+" / "+i.label+" = "+Number(
(n/i.scale).toFixed(5))+" "+i.unit}function ft(t,e){let n=[],i=new Set;t.groupId&&i.add(Ie({target:"group:"+t.groupId,parameter:"capacity.population"}));for(let[o,a]of[["factors",t.
factors??[]],["uncertainties",t.uncertainties??[]]]){let s=o==="factors"?9:8;if(!Array.isArray(a)||a.length>s){n.push(o+"は最大"+s+"変数にしてください。");continue}for(let d of a){
let u=Me(d?.parameter),f=Ie(d??{});if(!u||typeof d.target!="string"){n.push("未対応の変数または対象です。");continue}i.has(f)&&n.push("同じ変数を重複して指定できません。"),
i.add(f);let p=u.key==="mission.deadline"?Math.min(u.max,e):u.max,g=m=>typeof m=="number"&&Number.isFinite(m)&&m>=u.min&&m<=p&&(!u.integer||Number.isInteger(m));o==="factors"?(!Array.
isArray(d.values)||!d.values.length||d.values.length>12||d.values.some(m=>!g(m))||new Set(d.values).size!==d.values.length)&&n.push(u.label+": 比較値は範囲内で重複しない数値を1～12個指定してください。"):
(!["uniform","triangular"].includes(d.distribution)||!g(d.min)||!g(d.max)||d.min>d.max||d.distribution==="triangular"&&(!g(d.mode)||d.mode<d.min||d.mode>d.max))&&n.push(u.label+": \
分布の範囲・最頻値が不正です。")}}let r=(t.groupId?t.counts?.length??0:1)*(Array.isArray(t.factors)?t.factors.reduce((o,a)=>o*(a?.values?.length??0),1):1);return r>24&&
n.push("比較値の組合せは最大24条件にしてください。"),r*t.trials>1e4&&n.push("条件数×試行数は10000以下にしてください。"),n}function ht(t){let e=t.
analysis,n=e.groupId?[...e.counts].sort((i,r)=>i-r).map(i=>({count:i,settings:[{target:"group:"+e.groupId,parameter:"capacity.population",value:i}]})):[{settings:[]}];for(let i of e.
factors??[])n=n.flatMap(r=>i.values.map(o=>({...r,settings:[...r.settings,{target:i.target,parameter:i.parameter,value:o}]})));return n.map((i,r)=>({...i,id:JSON.stringify(i.settings.
map(o=>[Ie(o),o.value]).sort((o,a)=>o[0]<a[0]?-1:o[0]>a[0]?1:0)),index:r+1,label:i.settings.map(o=>$t(t,o,o.value)).join(" / ")||"基準条件"}))}function Pe(t,e,n,{maximum:i=!1}={}){
let r=Bt(t),o=[];r.trial=n;for(let a of t.analysis.uncertainties??[]){let s=B(ie(r,Ie(a),"parameter-sample-v1")),d=a.min;if(i)d=a.max;else if(a.max>a.min)if(a.distribution==="unifo\
rm")d=a.min+s*(a.max-a.min);else{let u=a.max-a.min,f=(a.mode-a.min)/u;d=s<f?a.min+Math.sqrt(s*u*(a.mode-a.min)):a.max-Math.sqrt((1-s)*u*(a.max-a.mode))}Me(a.parameter).integer&&(d=
Math.round(d)),o.push({target:a.target,parameter:a.parameter,value:d})}for(let a of[...e.settings,...o])Ht(r,a,a.value);if(r.groups=r.groups?.filter(a=>a.count!==0),r.behaviorAssignments&&
(r.behaviorAssignments=r.behaviorAssignments.map(a=>({...a,targets:a.targets.filter(s=>!s.startsWith("group:")||r.groups?.some(d=>d.id===s.slice(6)))})).filter(a=>a.targets.length||
r.mission?.type==="state"&&r.mission.assignmentId===a.id)),r.analysis){let a=s=>s.target==="scenario"?!!r.mission:s.target.startsWith("assignment:")?r.behaviorAssignments?.some(d=>d.
id===s.target.slice(11)):s.target.startsWith("group:")?r.groups?.some(d=>d.id===s.target.slice(6)):r.units.some(d=>d.id===s.target.slice(5));for(let s of["factors","uncertainties"])
r.analysis[s]=r.analysis[s]?.filter(a);r.analysis.groupId&&!r.groups?.some(s=>s.id===r.analysis.groupId)&&(delete r.analysis.groupId,delete r.analysis.counts)}return{scenario:r,sampled:o}}function mt(t){let e=t.mission;if(e?.type!=="state")return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=t.behaviors?.find(r=>r.id===n?.behaviorId);return n?i?.nodes?.
some(r=>r.id===e.nodeId)?[]:["計測対象の状態を選択してください。"]:["計測対象のタスクがありません。"]}function Ke(t,e=t.mission){if(e?.type!=="state")
return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=[];for(let r of n?.targets??[])if(r.startsWith("unit:")){let o=t.units.find(a=>a.id===r.slice(5));o&&o.enabled!==
!1&&i.push(o.id)}else{let o=t.groups?.find(a=>a.id===r.slice(6));if(o&&o.enabled!==!1)for(let a=1;a<=o.count;a++)i.push(o.id+"__"+a)}return i.sort()}var Kt=(t,e)=>t.join==="all"?e:
t.join==="count"?t.requiredCount:1;function Ne(t,e,n,i=e.deadline){let r=t.filter(a=>a.time<=Math.min(i,e.deadline)).sort((a,s)=>a.time-s.time||a.unitId.localeCompare(s.unitId)),o=Kt(
e,n);return{stateTargetCount:n,stateReachedCount:r.length,stateEntries:r,success:n>0&&o>0&&r.length>=o,successTime:n>0&&o>0&&r.length>=o?r[o-1].time:null}}var ue=class{constructor(e,n){
this.mission=e,this.members=new Set(n),this.first=new Map,this.cursor=0}update(e){for(;this.cursor<e.length;this.cursor++){let n=e[this.cursor];["initialized","nodeChanged"].includes(
n.type)&&n.nodeId===this.mission.nodeId&&n.time<=this.mission.deadline&&this.members.has(n.unitId)&&!this.first.has(n.unitId)&&this.first.set(n.unitId,n.time)}return Ne([...this.first].
map(([n,i])=>({unitId:n,time:i})),this.mission,this.members.size)}};function yt(t){if(t.measurements===void 0)return[];if(!Array.isArray(t.measurements)||t.measurements.length>12)return["measurementsは最大12件の配列にしてください。"];
let e=[],n=new Set;for(let i of t.measurements){if(!i||typeof i!="object"){e.push("計測点はオブジェクトにしてください。");continue}let r=t.behaviorAssignments?.find(
a=>a.id===i.assignmentId),o=t.behaviors?.find(a=>a.id===r?.behaviorId);(typeof i.id!="string"||!/^[A-Za-z0-9_-]{1,64}$/.test(i.id)||n.has(i.id))&&e.push("計測点のidは重複しない英数字・_・-（64文字以内\
）です。"),(typeof i.name!="string"||!i.name.trim()||i.name.length>120)&&e.push("計測点のnameは1～120文字です。"),(i.type!=="state"||!o?.nodes?.some(a=>a.id===i.nodeId))&&
e.push("計測点のtypeはstate、assignmentId・nodeIdは存在するタスク・状態を指定してください。"),(!["any","all","count"].includes(i.join)||i.join==="count"&&
(!Number.isInteger(i.requiredCount)||i.requiredCount<1||i.requiredCount>2e3))&&e.push("計測点のjoinはany・all・count、requiredCountは1～2000です。"),(!Number.isFinite(
i.deadline)||i.deadline<=0||i.deadline>t.duration)&&e.push("計測点のdeadlineは0より大きく終了時刻以下にしてください。"),i.previousId!==void 0&&!n.has(i.previousId)&&
e.push("所要時間の基準previousIdには、この計測点より前に登録した計測点を指定してください。"),n.add(i.id)}return e}function Ve(t,e,n=t.duration){
return(t.measurements??[]).map(i=>({id:i.id,...new ue({...i,deadline:Math.min(n,i.deadline)},Ke(t,i)).update(e)}))}var vt=t=>typeof t=="number"&&Number.isFinite(t);function bt(t,e="unit",n=new Set){let i=[],r=t.communication,o=t.behavior;if(r!==void 0)if(!r||typeof r!="object"||Array.isArray(r))
i.push(e+": communicationはオブジェクトにしてください。");else{(typeof r.enabled!="boolean"||typeof r.terrainLOS!="boolean")&&i.push(e+": 通信のenabled・terrainLOSはboole\
anにしてください。");for(let[a,s,d]of[["range",.001,1e5],["delay",0,86400],["probability",0,1]])(!vt(r[a])||r[a]<s||r[a]>d)&&i.push(e+": communication."+a+"は"+s+"～"+d+"\
にしてください。")}if(o!==void 0){if(!o||typeof o!="object"||Array.isArray(o))return[...i,e+": behaviorはオブジェクトにしてください。"];if(typeof o.hold!="bo\
olean"&&i.push(e+": behavior.holdはbooleanにしてください。"),(!vt(o.preparation)||o.preparation<0||o.preparation>86400)&&i.push(e+": behavior.preparationは0～86400秒にしてください。"),
!Array.isArray(o.rules)||o.rules.length>16)i.push(e+": 行動ルールは最大16件にしてください。");else{let a=new Set;for(let s of o.rules){if(!s||typeof s!="object"){i.
push(e+": ルールはオブジェクトにしてください。");continue}(typeof s.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(s.id)||a.has(s.id))&&i.push(e+": ルールidは重複しない英数字・_・\
-にしてください。"),a.add(s.id),(!["detected","received","arrived"].includes(s.when)||!["send","depart"].includes(s.action)||!["any","waiting"].includes(s.state)||typeof s.
once!="boolean")&&i.push(e+": ルールの条件・動作・実行回数が不正です。"),s.action==="send"&&!n.has(s.receiverId)&&i.push(e+": 送信先の単体ユニットが見つかりません: "+
s.receiverId),s.action==="depart"&&!o.hold&&i.push(e+": 出発ルールには「指令まで待機」を設定してください。")}}}return i}var Vt=["ground","surface","subsurface","air"],xt=["friendly","hostile","neutral"],ce=t=>typeof t=="number"&&Number.isFinite(t);function wt(t,e="unit"){let n=[],i=t.sensor;if(t.detectability!==
void 0&&(!ce(t.detectability)||t.detectability<0||t.detectability>10)&&n.push(e+": detectabilityは0～10にしてください。"),i!==void 0){if(!i||typeof i!="object"||Array.isArray(
i))return[...n,e+": sensorはオブジェクトにしてください。"];typeof i.enabled!="boolean"&&n.push(e+": sensor.enabledはbooleanにしてください。"),(!ce(i.range)||
i.range<=0||i.range>1e5)&&n.push(e+": sensor.rangeは0より大きく100000m以下にしてください。"),(!ce(i.probabilityPerMinute)||i.probabilityPerMinute<0||i.probabilityPerMinute>
1)&&n.push(e+": sensor.probabilityPerMinuteは0～1にしてください。"),(!Array.isArray(i.domains)||!i.domains.length||i.domains.some(r=>!Vt.includes(r)))&&n.push(e+": sensor\
.domainsには対象領域を1つ以上指定してください。"),typeof i.terrainLOS!="boolean"&&n.push(e+": sensor.terrainLOSはbooleanにしてください。"),i.mountHeight!==
void 0&&(!ce(i.mountHeight)||i.mountHeight<0||i.mountHeight>1e3)&&n.push(e+": sensor.mountHeightは0～1000mにしてください。")}return n}function Fe(t,e){if(t===void 0)return[];
let n=[];return!t||typeof t!="object"||Array.isArray(t)?["missionはオブジェクトにしてください。"]:(["detect","arrive","state"].includes(t.type)||n.push("mission.type\
はdetect・arrive・stateにしてください。"),t.type==="arrive"&&(!Array.isArray(t.responderIds)||!t.responderIds.length||t.responderIds.length>2e3||t.responderIds.some(i=>typeof i!=
"string")||new Set(t.responderIds).size!==t.responderIds.length)&&n.push("mission.responderIdsに到着を評価する単体ユニットIDを指定してください。"),t.type!==
"state"&&(!xt.includes(t.observerFaction)||!xt.includes(t.targetFaction)||t.observerFaction===t.targetFaction)&&n.push("観測側と対象側には異なる陣営を指定してください。"),
(t.type==="state"?["any","all","count"]:["any","all"]).includes(t.join)||n.push("mission.joinはany・all（状態計測ではcountも可）にしてください。"),t.type==="sta\
te"&&(typeof t.assignmentId!="string"||typeof t.nodeId!="string")&&n.push("計測するタスクと状態を選択してください。"),t.join==="count"&&(!Number.isInteger(t.requiredCount)||
t.requiredCount<1||t.requiredCount>2e3)&&n.push("到達を必要とする担当数は1～2000です。"),(!ce(t.deadline)||t.deadline<=0||t.deadline>e)&&n.push("mission.deadlineは0よ\
り大きく終了時刻以下にしてください。"),t.targetIds!==void 0&&(!Array.isArray(t.targetIds)||!t.targetIds.length||t.targetIds.length>2e3||t.targetIds.some(i=>typeof i!=
"string")||new Set(t.targetIds).size!==t.targetIds.length)&&n.push("mission.targetIdsは重複しない対象IDの配列にしてください。"),n)}function Re(t,e){if(t===void 0)
return[];if(!t||typeof t!="object"||Array.isArray(t))return["analysisはオブジェクトにしてください。"];let n=[];return t.groupId!==void 0&&typeof t.groupId!="string"&&
n.push("analysis.groupIdは文字列にしてください。"),t.groupId&&(!Array.isArray(t.counts)||!t.counts.length||t.counts.length>12||t.counts.some(i=>!Number.isInteger(i)||i<
0||i>2e3)||new Set(t.counts).size!==t.counts.length)&&n.push("analysis.countsは重複しない0～2000の整数（最大12条件）にしてください。"),(!Number.isInteger(t.
trials)||t.trials<1||t.trials>2e3)&&n.push("analysis.trialsは1～2000にしてください。"),(!ce(t.step)||t.step<.1||t.step>300||Math.ceil(e/t.step)>1e5)&&n.push("判定間隔は0.1～300\
秒、シナリオ全体で10万区間以内にしてください。"),(!ce(t.requiredRate)||t.requiredRate<0||t.requiredRate>1)&&n.push("analysis.requiredRateは0～1にしてください。"),
n.push(...ft(t,e)),n}var Xe=2e3,Xt=["ground","surface","subsurface","air"];var Mt=t=>JSON.parse(JSON.stringify(t)),ee=t=>typeof t=="number"&&Number.isFinite(t),It=t=>t&&["x","y","z"].every(e=>ee(t[e]));function me(t){let e=[];if(!t||typeof t!="object")throw new Error(
"シナリオはオブジェクトで指定してください。");[1,2,3].includes(t.version)||e.push("versionは1・2・3にしてください。"),t.unitsSystem!=="SI"&&e.push("\
unitsSystemはSI（m・s）にしてください。"),(typeof t.title!="string"||!t.title.trim()||t.title.length>160)&&e.push("titleは1～160文字で指定してください。"),
(!ee(t.duration)||t.duration<=0||t.duration>86400)&&e.push("durationは0より大きく86400秒以下にしてください。");let n=t.terrain;!n||!Number.isInteger(n.columns)||!Number.
isInteger(n.rows)||n.columns<2||n.rows<2||n.columns>513||n.rows>513?e.push("terrainのcolumns・rowsは2～513の整数にしてください。"):((!ee(n.spacing)||n.spacing<1||n.spacing>
1e4)&&e.push("terrain.spacingは1～10000mにしてください。"),n.spacingY!==void 0&&(!ee(n.spacingY)||n.spacingY<1||n.spacingY>1e4)&&e.push("terrain.spacingYは1～10000mにしてください。"),
(!n.origin||!ee(n.origin.x)||!ee(n.origin.y))&&e.push("terrain.originのx・yが必要です。"),(!Array.isArray(n.elevations)||n.elevations.length!==n.columns*n.rows||n.elevations.
some(o=>!ee(o)||o<-12e3||o>1e4))&&e.push("terrain.elevationsは格子数と同じ長さの標高配列（-12000～10000m）にしてください。"),ee(n.seaLevel)||e.push("terrai\
n.seaLevelが必要です。")),t.seed!==void 0&&(typeof t.seed!="string"||t.seed.length>100)&&e.push("seedは100文字以下の文字列にしてください。"),t.trial!==void 0&&
(!Number.isInteger(t.trial)||t.trial<0||t.trial>1e9)&&e.push("trialは0～1000000000の整数にしてください。");let i=t.groups??[],r=new Set;if(!Array.isArray(i)||i.length>
100)e.push("groupsは最大100件の配列にしてください。");else for(let o of i){if(!o||typeof o!="object"){e.push("groupはオブジェクトにしてください。");continue}
o.enabled!==void 0&&typeof o.enabled!="boolean"&&e.push("group.enabledはbooleanにしてください。"),(typeof o.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(o.id)||r.has(o.id))&&
e.push("group.idは重複しない英数字・_・-（50文字以下）にしてください。"),r.add(o.id),(typeof o.name!="string"||!o.name.trim()||o.name.length>100)&&e.push("\
group.nameは1～100文字にしてください。"),(!Number.isInteger(o.count)||o.count<1||o.count>Xe)&&e.push("group.countは1～2000にしてください。"),o.loopStartMode!==
void 0&&!["template","even","random"].includes(o.loopStartMode)&&e.push("group.loopStartModeはtemplate、even、randomにしてください。"),["grid","random"].includes(o.placement)||
e.push("group.placementはgridまたはrandomにしてください。");for(let a of["width","height"])(!ee(o[a])||o[a]<0||o[a]>1e5)&&e.push("group."+a+"は0～100000mにしてください。")}
if(!Array.isArray(t.units)||t.units.length>Xe)e.push("unitsは最大2000件の配列にしてください。");else{let o=new Set,a=new Set(t.units.map(s=>s?.id));[...t.units,...Array.
isArray(i)?i.map(s=>s?.template):[]].forEach((s,d)=>{let u="units["+d+"]";if(!s||typeof s!="object"){e.push(u+": オブジェクトが必要です。");return}if((typeof s.id!="str\
ing"||!/^[a-zA-Z0-9_-]{1,80}$/.test(s.id)||d<t.units.length&&o.has(s.id))&&e.push(u+": idは重複しない英数字・_・-にしてください。"),d<t.units.length&&o.add(s.id),
(typeof s.name!="string"||!s.name.trim()||s.name.length>120)&&e.push(u+": nameは1～120文字にしてください。"),e.push(...wt(s,u),...bt(s,u,a)),t.version===3&&s.behavior&&
e.push(u+": 旧行動ルールは読み込み時にノードへ変換してください。"),s.navigation!==void 0&&e.push(...fe(s.navigation)),Xt.includes(s.domain)||e.push(u+": d\
omainが不正です。"),["friendly","hostile","neutral"].includes(s.faction)||e.push(u+": factionが不正です。"),s.enabled!==void 0&&typeof s.enabled!="boolean"&&e.push(u+":\
 enabledはbooleanにしてください。"),typeof s.manned!="boolean"&&e.push(u+": mannedはbooleanにしてください。"),(!ee(s.speed)||s.speed<0||s.speed>1500)&&e.push(u+":\
 speedは0～1500m/sにしてください。"),It(s.initial)||e.push(u+": initialのx,y,zが必要です。"),["once","loop","pingpong"].includes(s.routeMode)||e.push(u+": routeMod\
eが不正です。"),s.groupId!==void 0&&d<t.units.length&&e.push(u+": groupIdは生成ユニット専用です。"),s.motion!==void 0)if(!s.motion||typeof s.motion!="object"||Array.
isArray(s.motion))e.push(u+": motionはオブジェクトにしてください。");else for(let[f,p,g]of[["horizontal",0,1e4],["vertical",0,3e3],["commonHorizontal",0,1e4],["scale",
10,1e5],["startDelay",0,86400],["speedVariation",0,1],["loopStart",0,1]])s.motion[f]!==void 0&&(!ee(s.motion[f])||s.motion[f]<p||s.motion[f]>g)&&e.push(u+": motion."+f+"は"+p+"～"+
g+"にしてください。");(!Array.isArray(s.route)||s.route.length>500||s.route.some(f=>!It(f)))&&e.push(u+": routeは最大500件、各点にx,y,zが必要です。")})}if(Array.
isArray(t.units)&&Array.isArray(i)&&!e.length){let o=t.units.length+i.reduce((a,s)=>a+s.count,0);if(o>Xe)e.push("単体と群を合わせて最大2000ユニットにしてください。");else{
let a=$e(t);new Set(a.map(s=>s.id)).size!==o&&e.push("生成ユニットのidが単体ユニットと重複しています。")}}if(e.push(...Fe(t.mission,t.duration),...Re(t.analysis,
t.duration),...Ge(t),...mt(t),...yt(t)),t.mission?.type==="arrive"&&t.mission.responderIds?.some(o=>!t.units?.some(a=>a.id===o))&&e.push("到着評価の対象となる単体ユニットが見つかりません。"),
t.version===3&&!e.length)for(let o of[...t.analysis?.factors??[],...t.analysis?.uncertainties??[]])try{Oe(t,o)}catch(a){e.push(a.message)}if(e.length)throw new Error(e.slice(0,30).
join(`
`));return ot(ut(Mt(t)))}var De=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),Ae=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function Wt(t,e){let n=[0];for(let d=1;d<
t.length;d++)n.push(n.at(-1)+De(t[d-1],t[d]));let i=n.at(-1);if(i===0)return t;let r=i*e,o=n.findIndex((d,u)=>u>0&&d>r),a=o<0?t.length-1:o,s=Ae(t[a-1],t[a],(r-n[a-1])/(n[a]-n[a-1]));
return[s,...t.slice(a,-1),...t.slice(0,a),{...s}]}var he=class{constructor(e,{deferPaths:n=!1}={}){let i=me(e);this.source=i,this.scenario={...i,units:$e(i)},this.nodeCount=0,this.
terrain=new Z(this.scenario.terrain),this.paths=n?new Map:new Map(this.scenario.units.filter(r=>r.enabled!==!1).map(r=>[r.id,this.compile(r)]))}compile(e){let n=this.terrain.project(
e.initial,e.domain),i=[{...n.point,d:0}],r=e.motion??{},o=ie(this.scenario,e.id,"motion"),a=(r.startDelay??0)*B(o+"|delay"),s=e.speed*(1+(B(o+"|speed")*2-1)*(r.speedVariation??0)),
d={delay:a,actualSpeed:s},u=e.routeMode==="loop"?(r.loopStart??0)%1:0,f=u>0&&e.route.length>0;if(n.error&&!f)return{...d,nodes:i,length:0,error:n.error,errorAt:"初期位置",periodic:!1};
let p=[n.point,...e.route.map(x=>this.terrain.project(x,e.domain).point)];e.route.length&&e.routeMode==="loop"&&p.push(n.point);let g=p.slice(1).reduce((x,b,z)=>x+De(p[z],b),0);if(g>
0&&(r.horizontal??0)+(r.vertical??0)+(r.commonHorizontal??0)>0){let x=[n.point],b=r.scale??2e3,z=Math.min(125,this.terrain.cellSize/4,b/8),w=0;for(let S=1;S<p.length;S++){let j=p[S-
1],O=p[S],l=De(j,O),I=Math.max(1,Math.ceil(l/z));if(I>2e4)throw new Error("航跡生成の区間が長すぎます。");for(let _=1;_<=I;_++){let H=w+l*_/I,$=Ae(j,O,_/I),U=Math.min(
1,H/b,(g-H)/b),q=Math.max(0,U),G=q*q*(3-2*q),J=He(o,H,b),h=He(ie(this.scenario,e.groupId??e.id,"common-motion"),H,b);if($.x+=G*(J[0]*(r.horizontal??0)+h[0]*(r.commonHorizontal??0)),
$.y+=G*(J[1]*(r.horizontal??0)+h[1]*(r.commonHorizontal??0)),["subsurface","air"].includes(e.domain)&&($.z+=G*J[2]*(r.vertical??0)),x.push($),x.length>1e5)throw new Error("航跡生成の点数が\
多すぎます。経路を短くするか変動間隔を大きくしてください。")}w+=l}p=x}if(f){let x=[p[0]],b=Math.min(125,this.terrain.cellSize/4);for(let w=1;w<p.length;w++){
let S=p[w-1],j=p[w],O=Math.max(1,Math.ceil(Math.hypot(j.x-S.x,j.y-S.y)/b));if(O>2e4)return{...d,nodes:i,length:0,error:"経路区間が長すぎます",errorAt:"初期位置",periodic:!1};
for(let l=1;l<=O;l++)if(x.push(this.terrain.project(Ae(S,j,l/O),e.domain).point),x.length>2000001)throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}
p=Wt(x,u);let z=this.terrain.project(p[0],e.domain);if(i=[{...z.point,d:0}],z.error)return{...d,nodes:i,length:0,error:z.error,errorAt:"初期位置",periodic:!1}}let m=p.slice();e.
route.length&&e.routeMode==="pingpong"&&p.push(...m.slice(0,-1).reverse());let v=Math.min(125,this.terrain.cellSize/4);for(let x=1;x<p.length;x++){let b=p[x-1],z=p[x],w=Math.max(1,
Math.ceil(Math.hypot(z.x-b.x,z.y-b.y)/v));if(w>2e4)return{...d,nodes:i,length:i.at(-1).d,error:"経路区間が長すぎます",errorAt:"区間 "+x,periodic:!1};for(let S=1;S<=w;S++){
let j=this.terrain.project(Ae(b,z,S/w),e.domain);if(j.error)return{...d,nodes:i,length:i.at(-1).d,error:j.error,errorAt:"区間 "+x,periodic:!1};let O=i.at(-1),l=O.d+De(O,j.point);
if(l>O.d&&(i.push({...j.point,d:l}),++this.nodeCount>2e6))throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}}return{...d,nodes:i,length:i.
at(-1).d,error:null,errorAt:null,periodic:e.routeMode!=="once"}}evaluate(e){let n=Math.min(this.scenario.duration,Math.max(0,Number(e)||0));return{time:n,units:this.scenario.units.
map(i=>this.evaluateUnit(i,n))}}evaluateUnit(e,n,i=!0){if(e.enabled===!1)return{id:e.id,position:{...e.initial},status:"disabled",heading:0,distance:0,routeDistance:0,error:null,errorAt:null,
actualSpeed:0,startDelay:0,eta:null};let r=Math.max(0,Number(n)||0),o=i?Math.min(this.scenario.duration,r):r,a=this.paths.get(e.id),s=a.actualSpeed??e.speed,d=a.delay??0,u=s*Math.max(
0,o-d),f=!a.periodic&&s>0&&o>=d+a.length/s?Math.max(u,a.length):u,p=a.periodic&&a.length>0?f%a.length:Math.min(f,a.length),g=0,m=a.nodes.length-1;for(;g<m;){let w=Math.ceil((g+m)/2);
a.nodes[w].d<=p?g=w:m=w-1}let v=a.nodes[g],x=a.nodes[Math.min(g+1,a.nodes.length-1)],b=Ae(v,x,x.d>v.d?(p-v.d)/(x.d-v.d):0);e.domain==="ground"&&(b.z=this.terrain.height(b.x,b.y)??b.
z);let z=a.length===0?"idle":"moving";return a.error&&f>=a.length?z="blocked":!a.periodic&&a.length>0&&f>=a.length?z="arrived":s===0?z="idle":o<d&&(z="waiting"),{id:e.id,position:b,
status:z,heading:Math.atan2(x.x-v.x,x.y-v.y),distance:Math.min(f,a.periodic?f:a.length),routeDistance:a.length,error:a.error,errorAt:a.errorAt,actualSpeed:s,startDelay:Number.isFinite(
d)?d:null,eta:s>0&&Number.isFinite(d)?d+a.length/s:null}}routePoints(e){return this.paths.get(e)?.nodes||[]}};function Se(t){let e=me(t);if(e.version===3)return e;e.version=3,e.behaviors??=[],e.behaviorAssignments??=[];let n=e.recording?.step??e.analysis?.step??10;e.recording??={step:n,interval:n},
e.analysis&&(e.analysis={...lt(e.analysis),step:n});for(let[i,r]of[...e.units.map(o=>["unit:"+o.id,o]),...(e.groups??[]).map(o=>["group:"+o.id,o.template])]){let o=r.behavior;if(o){
if(o.hold||o.rules.length){if(e.behaviorAssignments.some(p=>p.targets.includes(i)))throw Error("旧ルールとタスクが重複しています: "+i);let a=new Set;for(let p of o.
rules){if(a.has(p.when)||p.state!=="any"&&!(o.hold&&p.when==="received"))throw Error("自動変換できない旧ルールです。同じ条件の複数動作・状態条件はノードで再設計してください: "+
i);a.add(p.when)}let s="import-"+i.replace(":","-");if(e.behaviors.some(p=>p.id===s)||e.behaviorAssignments.some(p=>p.id===s))throw Error("変換先IDが重複しています: "+s);
let d=o.hold?"signal":"follow",u=[{id:d,kind:o.hold?"signal":"follow",x:320,y:70}],f=[];o.hold&&u.push({id:"follow",kind:"follow",x:1080,y:70}),o.rules.forEach((p,g)=>{let m=p.when===
"received"&&o.hold?"signal":"follow";p.action==="depart"?(u.push({id:p.id,kind:"wait",parameter:"preparation",seconds:o.preparation,x:680,y:70+g*150}),f.push({from:m,to:p.id,when:p.
when,once:p.once},{from:p.id,to:"follow",when:"elapsed"})):(u.push({id:p.id,kind:"report",receiverId:p.receiverId,x:680,y:70+g*150}),f.push({from:m,to:p.id,when:p.when,once:p.once},
{from:p.id,to:d,when:"sent",resume:!0},{from:p.id,to:d,when:"sendFailed",resume:!0}))}),e.behaviors.push({id:s,name:r.name+"の挙動",initial:d,triggers:[],nodes:u,edges:f}),e.behaviorAssignments.
push({id:s,name:r.name+"のタスク",behaviorId:s,targets:[i],spacing:"none",preparation:o.preparation});for(let p of[e.analysis?.factors,e.analysis?.uncertainties])for(let g of p??
[])g.target===i&&g.parameter==="behavior.preparation"&&(g.target="assignment:"+s)}delete r.behavior}}return me(e)}function _e(t,e,n){let i=Math.hypot(n.x-e.x,n.y-e.y),r=Math.max(1,Math.ceil(i/Math.min(125,t.cellSize/4)));for(let o=0;o<=r;o++){let a=o/r,s=e.x+(n.x-e.x)*a,d=e.y+(n.y-e.y)*a,u=e.z+
(n.z-e.z)*a,f=t.height(s,d);if(f===null||u<f-1e-6)return!1}return!0}function We(t,e,n,i){if(i<=0||n<=0||e>=t.range||t.probabilityPerMinute<=0)return 0;if(t.probabilityPerMinute>=1)
return 1;let r=-Math.log1p(-t.probabilityPerMinute)/60;return-Math.expm1(-r*i*n*(1-e/t.range)**2)}var Ze=(t,e)=>({...t,z:t.z+(e.sensor?.mountHeight??(e.domain==="ground"?2:0))}),Zt=(t,e,n)=>Math.
floor(t/n)+","+Math.floor(e/n);function At(t,e){let n=new Map;for(let i of t){let r=Zt(i.position.x,i.position.y,e);n.has(r)||n.set(r,[]),n.get(r).push(i)}return n}function*St(t,e,n){
let i=Math.floor(e.x/n),r=Math.floor(e.y/n);for(let o=-1;o<=1;o++)for(let a=-1;a<=1;a++)for(let s of t.get(i+a+","+(r+o))??[])yield s}var en=256*1048576;var Qe=["idle","moving","arrived","blocked","waiting","standby","preparing"],kt=128*1048576,ae=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),ge=(t,e)=>(t%e+e)%e,ke=(t,e,n)=>({x:t.x+(e.
x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function Ee(t,e){let n=Math.min(t.length,Math.max(0,e)),i=t.nodes,r=0,o=i.length-1;for(;r<o;){let d=Math.ceil((r+o)/2);i[d].d<=n?r=d:
o=d-1}let a=i[r],s=i[Math.min(r+1,i.length-1)];return{point:ke(a,s,s.d>a.d?(n-a.d)/(s.d-a.d):0),segment:r,heading:Math.atan2(s.x-a.x,s.y-a.y)}}function zt(t,e){let n={point:t.nodes[0],
along:0,distance:1/0};for(let i=1;i<t.nodes.length;i++){let r=t.nodes[i-1],o=t.nodes[i],a=o.x-r.x,s=o.y-r.y,d=o.z-r.z,u=a*a+s*s+d*d,f=u?Math.max(0,Math.min(1,((e.x-r.x)*a+(e.y-r.y)*
s+(e.z-r.z)*d)/u)):0,p=ke(r,o,f),g=ae(e,p);g<n.distance&&(n={point:p,along:r.d+(o.d-r.d)*f,distance:g})}return n}var se=class extends he{constructor(e){super(Se(e),{deferPaths:!0}),
this.frames=null,this.result=null,this.computeCount=0,this.nodeNames=[],this.assignments=this.source.behaviorAssignments,this.initialEvents=[];let n=new Map(this.source.behaviors.map(
i=>[i.id,i]));this.states=[],this.byId=new Map;for(let i of this.scenario.units.filter(r=>r.enabled!==!1).sort((r,o)=>r.id.localeCompare(o.id))){let r=this.assignments.find(g=>g.targets.
includes("unit:"+i.id)||i.groupId&&g.targets.includes("group:"+i.groupId)),o=r?xe(n.get(r.behaviorId),r):null,a=o?.nodes.find(g=>g.id===o.initial),s=je(this.source,r,a,i),u=r?.route?.
length>=2||a?.routeId?{...i,initial:s.points[0],route:s.points.slice(1),routeMode:a?.kind==="patrol"?"loop":s.mode,motion:{...i.motion,loopStart:0}}:i,f=this.compile(u);this.paths.
set(i.id,f);let p={unit:i,assignment:r,graph:o,path:f,basePath:f,pathCache:new Map,routeContexts:new Map,nearInside:new Map,node:null,nodeTime:0,position:{...f.nodes[0]},heading:0,
status:"idle",distance:0,progress:0,segment:-1,error:f.errorAt==="初期位置"?f.error:null,fired:new Set,triggerFired:new Set,triggerTimes:new Map,activated:!1,observation:null,latestObservation:null,
receivedPosition:null,moveGoal:null,moveHeight:null,trace:[],routeStarted:null,routePaused:0};if(a?.joinMode==="nearest"){let g=this.terrain.project(i.initial,i.domain);p.position=
g.point,g.error&&(p.error=g.error)}this.states.push(p),this.byId.set(i.id,p);for(let g of o?.nodes??[])this.nodeNames.includes(o.id+":"+g.id)||this.nodeNames.push(o.id+":"+g.id)}this.
inactiveUnits=this.scenario.units.filter(i=>i.enabled===!1).map(i=>super.evaluateUnit(i,0));for(let i of this.assignments){let r=this.states.filter(o=>o.assignment===i);r.forEach((o,a)=>{
o.initialPhase=ge((i.phase??0)+(i.spacing==="none"?o.unit.motion?.loopStart??0:a/r.length),1),o.status=o.error?"blocked":"standby",o.graph.initial&&(o.activated=!0,this.enter(o,o.graph.
initial,0,!0),this.initialEvents.push({type:"initialized",time:0,unitId:o.unit.id,nodeId:o.graph.initial}))})}for(let i of this.states)i.graph||Object.assign(i,super.evaluateUnit(i.
unit,0))}enter(e,n,i,r=!1,o=!1){let a=e.node;if(a?.kind==="follow"&&e.routeContexts.set(a.routeId??"default",{path:e.path,started:e.routeStarted,travel:e.routeTravel??0,offset:e.routeOffset??
0,paused:i,join:e.join}),e.node=e.graph.nodes.find(s=>s.id===n),a&&e.error&&(e.error=this.terrain.project(e.position,e.unit.domain).error),e.moveHeight=e.position.z,e.moveGoal=e.node.
kind==="move"&&re(this.source,e.assignment,e.node)?.kind==="received"&&e.receivedPosition?{...e.receivedPosition.targetPosition}:null,e.nodeTime=i,e.sent=!1,e.elapsed=!1,e.destinationArrived=
!1,e.join=null,e.nearInside=new Map([...e.nearInside].filter(([s])=>s.startsWith("trigger:"))),["follow","patrol"].includes(e.node.kind)){let s=je(this.source,e.assignment,e.node,e.
unit),d=s.id+"|"+e.node.kind;if(r&&e.pathCache.set(d,e.path),!e.pathCache.has(d)){let u=!e.node.routeId;e.pathCache.set(d,this.compile({...e.unit,initial:s.points[0],route:s.points.
slice(1),routeMode:s.mode,motion:{...e.unit.motion,...u?{}:{loopStart:0}}}))}e.path=e.pathCache.get(d),this.paths.set(e.unit.id,e.path)}if(e.error){e.status="blocked";return}if(e.status=
"idle",e.node.kind==="patrol"){if(r&&e.node.joinMode!=="nearest"){e.progress=(e.node.joinMode==="start"?0:e.initialPhase)*e.path.length;let s=Ee(e.path,e.progress);e.position=s.point,
e.heading=s.heading,e.segment=s.segment}else{let s=(e.node.joinMode??"nearest")==="nearest"?zt(e.path,e.position):Ee(e.path,0);e.progress=s.along??0,e.join=s.point}e.readyAt=i+(r?e.
path.delay:0),e.status=i<e.readyAt?"waiting":"moving"}else if(e.node.kind==="follow"){let s=o?e.routeContexts.get(e.node.routeId??"default"):null;if(s&&s.path===e.path)e.routeStarted=
s.started===null?null:s.started+i-s.paused,e.routeTravel=s.travel,e.routeOffset=s.offset,e.join=s.join;else{let d=e.node.joinMode==="nearest"?zt(e.path,e.position):{point:e.path.nodes[0],
along:0};e.routeOffset=d.along,e.routeTravel=d.along,e.routeArrived=!1,e.join=(!r||e.node.joinMode==="nearest")&&ae(e.position,d.point)>1e-7?d.point:null,e.routeStarted=e.join?null:
i-(e.path.actualSpeed?e.routeOffset/e.path.actualSpeed:0)-(e.routeOffset>0?e.path.delay:0)}e.status=e.join?"moving":i<(e.routeStarted??i)+(r?e.path.delay:0)?"waiting":e.path.length&&
e.path.actualSpeed?"moving":"idle"}else e.node.kind==="signal"?e.status="standby":e.node.kind==="wait"?e.status=e.node.parameter==="preparation"?"preparing":"waiting":e.node.kind===
"move"&&(e.status=re(this.source,e.assignment,e.node)?.kind==="received"&&!e.moveGoal?"standby":"moving")}activate(e,n,i,r,o){if(!e?.graph||e.status==="blocked"&&n!=="received")return!1;
let a=Be(e.graph).find(u=>u.event===n&&(n!=="near"||oe(u)===o?.conditionKey)&&(n!=="time"||Math.abs(this.nextTriggerTime(e,u)-i)<1e-8)&&(!e.triggerFired.has(u.id)||u.once===!1));if(!a)
return!1;let s=e.unit.id+"|trigger|"+a.id;if(o?.trace?.includes(s))return!1;if(o?(e.observation=o,e.trace=[...o.trace??[],s]):(e.observation=null,e.trace=[]),e.trace.length>64)throw Error(
"情報の中継が64段を超えました。");e.triggerFired.add(a.id),e.triggerTimes.set(a.id,i);let d=e.node?.id;return e.activated=!0,this.enter(e,a.to,i),r.push({type:"trigge\
red",time:i,unitId:e.unit.id,triggerId:a.id,event:n,nodeId:a.to}),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d??null,nodeId:a.to}),e.node.parameter==="preparation"&&r.
push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}nextTriggerTime(e,n){
return e.triggerFired.has(n.id)?n.once===!1?(e.triggerTimes.get(n.id)??0)+n.seconds:1/0:n.seconds}transition(e,n,i,r,o){if(!e?.graph||e.status==="blocked"&&n!=="received")return!1;
if(this.activate(e,n,i,r,o))return!0;if(!e.node)return!1;let a=e.graph.edges.find(u=>u.from===e.node.id&&u.when===n&&(n!=="near"||oe(u)===o?.conditionKey));if(!a)return!1;let s=e.unit.
id+"|"+a.from+"|"+oe(a);if(a.once&&e.fired.has(s)||o?.trace?.includes(s))return!1;if(a.once&&e.fired.add(s),o&&(e.observation=o,e.trace=[...o.trace??[],s]),e.trace.length>64)throw Error(
"情報の中継が64段を超えました。");e.node.kind==="follow"&&(e.pauseTime=i);let d=e.node.id;return this.enter(e,a.to,i,!1,a.resume),r.push({type:"nodeChanged",time:i,unitId:e.
unit.id,from:d,nodeId:a.to}),e.node.parameter==="preparation"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&!a.resume&&r.push({type:"\
departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}destination(e,n=e.node,i){let r=re(this.source,e.assignment,n);return r?r.kind==="received"?e.node?.kind==="move"&&re(this.source,
e.assignment,e.node)?.id===r.id?e.moveGoal:e.receivedPosition?.targetPosition??null:r.kind==="point"?r.point:i?.get(r.unitId)??this.byId.get(r.unitId)?.position??null:null}movementDestination(e,n){
let i=this.destination(e,e.node,n),r=re(this.source,e.assignment,e.node);return i?(e.node.heightMode??(r?.kind==="point"?"target":"keep"))==="keep"?{...i,z:e.moveHeight??e.position.
z}:i:null}predict(e,n,i,r){if(e.status==="blocked"||!e.node&&e.graph)return e.position;if(!e.graph||e.node.kind==="follow"&&!e.join){let f=e.graph?e.routeStarted??0:0;return he.prototype.
evaluateUnit.call(this,e.unit,Math.max(0,n-f),!1).position}let o=Math.max(0,n-(this.currentTime??0));if(e.node.kind==="patrol"&&!e.join)return Ee(e.path,ge(e.progress+(i.get(e.unit.
id)??e.path.actualSpeed)*Math.max(0,n-Math.max(this.currentTime??0,e.readyAt)),e.path.length||1)).point;let a=e.join??(e.node.kind==="move"?this.movementDestination(e,r):null);if(!a)
return e.position;let s=this.terrain.project(a,e.unit.domain);if(s.error)return e.position;let d=ae(e.position,s.point),u=Math.min(d,e.path.actualSpeed*o);return ke(e.position,s.point,
d?u/d:1)}replayPath(e,n){if(!e.graph)return e.path;if(!e.replayRoutes){e.replayRoutes=[{time:0,node:e.graph.nodes.find(a=>a.id===e.graph.initial)}];for(let a of this.result.actionEvents)
a.unitId===e.unit.id&&a.type==="nodeChanged"&&e.replayRoutes.push({time:a.time,node:e.graph.nodes.find(s=>s.id===a.nodeId)});e.replayRoutes=e.replayRoutes.filter(a=>["follow","patr\
ol"].includes(a.node?.kind))}let i=e.replayRoutes.findLast(a=>a.time<=n)?.node;if(!i)return e.basePath;let r=je(this.source,e.assignment,i,e.unit),o=r.id+"|"+i.kind;return e.pathCache.
has(o)||e.pathCache.set(o,this.compile({...e.unit,initial:r.points[0],route:r.points.slice(1),routeMode:r.mode,motion:{...e.unit.motion,...i.routeId?{loopStart:0}:{}}})),e.pathCache.
get(o)}stateSnapshot(e,n=e.path){return{id:e.unit.id,position:{x:e.position.x,y:e.position.y,z:e.position.z},heading:e.heading,status:e.status,distance:e.distance,routeDistance:n.length,
error:e.error,errorAt:n.errorAt,actualSpeed:n.actualSpeed,startDelay:n.delay,nodeId:e.node?.id,behaviorId:e.graph?.id,eta:null}}evaluate(e){let n=Math.max(0,Math.min(this.source.duration,
Number(e)||0));if(!this.frames)return{time:0,units:[...this.states.map(g=>this.stateSnapshot(g)),...this.inactiveUnits],actionsPending:!0,recordingPending:!0};let i=0,r=this.frames.
length-1;for(;i<r;){let g=Math.ceil((i+r)/2);this.frames[g].time<=n?i=g:r=g-1}let o=this.frames[i],a=this.frames[Math.min(i+1,this.frames.length-1)],s=a.time>o.time?(n-o.time)/(a.time-
o.time):0,d=this.states.map((g,m)=>{let v=m*5,x=o.values,b=a.values,z=this.nodeNames[o.nodes[m]-1],w=ge(b[v+3]-x[v+3]+Math.PI,Math.PI*2)-Math.PI;return{...this.stateSnapshot(g,this.
replayPath(g,n)),position:{x:x[v]+(b[v]-x[v])*s,y:x[v+1]+(b[v+1]-x[v+1])*s,z:x[v+2]+(b[v+2]-x[v+2])*s},heading:x[v+3]+w*s,distance:x[v+4]+(b[v+4]-x[v+4])*s,status:Qe[o.status[m]],nodeId:z?.
split(":")[1],error:o.status[m]===3?"記録された地形制約停止":null,actualSpeed:a.time>o.time?Math.max(0,(b[v+4]-x[v+4])/(a.time-o.time)):0}}),u=this.result,f=u.events.filter(
g=>g.time<=n),p=this.source.mission;return{time:n,units:[...d,...this.inactiveUnits],actionEvents:u.actionEvents.filter(g=>g.time<=n),mission:p?{...p.type==="state"?Ne(u.stateEntries,
p,u.stateTargetCount,n):{},events:f,detectedCount:new Set(f.map(g=>g.targetId)).size,targetCount:u.targetCount,reachedCount:new Set(u.actionEvents.filter(g=>g.type==="arrived"&&g.time<=
n&&p.responderIds?.includes(g.unitId)).map(g=>g.unitId)).size,responderCount:u.responderCount,status:u.successTime!==null&&u.successTime<=n?"success":n>=p.deadline?"failure":"pendi\
ng",deadline:p.deadline}:void 0,recording:{frames:this.frames.length,bytes:this.recordBytes,computeCount:this.computeCount,step:this.source.recording.step,interval:this.source.recording.
interval},actionsPending:!1}}trailPoints(e,n,i=1e3){if(!this.frames)return[];let r=this.states.findIndex(f=>f.unit.id===e);if(r<0)return[];let o=this.frames.filter(f=>f.time<=n),a=Math.
max(1,Math.ceil(o.length/i)),s=o.filter((f,p)=>p%a===0||p===o.length-1).map(f=>({x:f.values[r*5],y:f.values[r*5+1],z:f.values[r*5+2]})),d=this.frames.findLast(f=>f.time<=n),u=this.
frames.find(f=>f.time>n)??d;if(d){let f=u.time>d.time?(n-d.time)/(u.time-d.time):0,p=r*5;s.push({x:d.values[p]+(u.values[p]-d.values[p])*f,y:d.values[p+1]+(u.values[p+1]-d.values[p+
1])*f,z:d.values[p+2]+(u.values[p+2]-d.values[p+2])*f})}return s}record(e,n){if(n.at(-1)?.time===e)return;let i=this.states.length,r=new Float32Array(i*5),o=new Uint16Array(i),a=new Uint8Array(
i);if(this.states.forEach((s,d)=>{r.set([s.position.x,s.position.y,s.position.z,s.heading,s.distance],d*5),o[d]=s.node?this.nodeNames.indexOf(s.graph.id+":"+s.node.id)+1:0,a[d]=Qe.
indexOf(s.status)}),n.push({time:e,values:r,nodes:o,status:a}),n.length>100001||n.length*(i*23+8)>kt)throw Error("再生記録が128MiBを超えました。期間・個数・記録間隔を調整してください。")}get recordBytes(){
return this.frames?.reduce((e,n)=>e+8+n.values.byteLength+n.nodes.byteLength+n.status.byteLength,0)??0}};function et(t,e,n,i,r){let o=t.terrain.project(n,e.unit.domain);if(o.error)
return e.status="blocked",e.error=o.error,!1;let a=ae(e.position,o.point),s=Math.min(a,i*r),d=ke(e.position,o.point,a?s/a:1),u=Math.max(1,Math.ceil(s/Math.min(125,t.terrain.cellSize/
4)));for(let f=1;f<=u;f++){let p=t.terrain.project(ke(e.position,d,f/u),e.unit.domain);if(p.error)return e.status="blocked",e.error=p.error,!1}return e.heading=Math.atan2(d.x-e.position.
x,d.y-e.position.y),e.position=t.terrain.project(d,e.unit.domain).point,e.distance+=s,e.status=a<=s+1e-7?"arrived":"moving",e.status==="arrived"}function*Ct(t,e=t.source?.mission??
t.scenario.mission,n,i={}){let r=t instanceof se?t:new se(t.source),o=i.horizon??(r.source.measurements?.length?r.source.duration:e?.deadline??r.source.duration),a=i.record??!1,s=r.
source.recording.step,d=r.source.recording.interval;if(!Number.isFinite(o)||o<0||o>r.source.duration)throw Error("計算終了時刻が不正です。");if(r.computeCount)throw Error(
"計算済みです。新しい試行を作成してください。");r.computeCount++;let u=r.states,f=[...r.initialEvents],p=new Map,g=new Set,m=[],v=a?[]:null,x=u.filter(h=>h.unit.
faction!=="neutral"),b=e?.type==="state"?[]:e?.targetIds?e.targetIds.map(h=>r.byId.get(h)).filter(Boolean):u.filter(h=>e?h.unit.faction===e.targetFaction:h.unit.faction!=="neutral");
if(e&&e.type!=="state"&&e.targetIds?.some(h=>!r.scenario.units.some(M=>M.id===h&&M.faction===e.targetFaction))||e?.type==="detect"&&!r.scenario.units.some(h=>h.faction===e.targetFaction))
throw Error("成功条件に合う対象がありません。");let z=e?.type==="arrive"?e.responderIds.filter(h=>r.byId.has(h)):[],w=e?.type==="state"?new ue(e,u.filter(h=>h.assignment?.
id===e.assignmentId).map(h=>h.unit.id)):null,S={success:!1,successTime:null,targetCount:e?.type==="state"?x.length:b.length,detectedCount:0,responderCount:z.length,reachedCount:0,events:[],
actionEvents:f,invalidUnits:u.filter(h=>h.error).length,constrainedPaths:0},j=0,O=0,l=0,I=Math.max(1,...u.filter(h=>h.unit.sensor?.enabled).map(h=>h.unit.sensor.range)),_=(h,M,T,C={})=>(f.
push({type:M,time:T,unitId:h.unit.id,nodeId:h.node?.id,...C}),r.transition(h,M,T,f,C));function H(){let h=new Map;for(let M of r.assignments){let T=new Map;for(let C of u.filter(y=>y.
assignment===M&&y.node?.kind==="patrol"&&y.status!=="blocked"&&!y.join)){let y=C.node.routeId??"default";T.has(y)||T.set(y,[]),T.get(y).push(C)}for(let C of T.values()){C.sort((y,E)=>y.
progress/y.path.length-E.progress/E.path.length);for(let y=0;y<C.length;y++){let E=C[y],N=C[(y+1)%C.length],A=C.length===1?E.path.length:ge(N.progress/N.path.length-E.progress/E.path.
length,1)*E.path.length,P=M.spacing==="fixed"?M.spacingDistance??500:E.path.length/C.length,Y=E.path.actualSpeed,K=Y*(E.node.speedFraction??.7);h.set(E.unit.id,M.spacing==="none"||
C.length===1?K:Math.max(0,Math.min(Y,K+(M.gain??.01)*(A-P))))}}}return h}function $(h,M){let T=h.unit.communication,C=r.byId.get(h.node.receiverId??h.assignment.receiverId),y=C?ae(
h.position,C.position):1/0,E=h.observation?.type==="received"&&h.observation.targetPosition?h.observation:h.latestObservation??(h.observation?.targetPosition?h.observation:null),N=ie(
r.source,h.unit.id,"unified-report-v2")+"|"+JSON.stringify([h.node.id,E?.targetId,E?.originObserverId??E?.observerId??h.unit.id]),A=null;T?.enabled?C?y>T.range?A="通信範囲外":
T.terrainLOS&&!_e(r.terrain,h.position,C.position)?A="地形遮蔽":B(N)>=T.probability&&(A="通信試行失敗"):A="受信先不在（無効・計算対象外）":A="通信無効",
h.sent=!0;let P={receiverId:C?.unit.id,distance:Number.isFinite(y)?y:null,reason:A,targetId:E?.targetId,targetPosition:E?.targetPosition?{...E.targetPosition}:void 0,observationTime:E?.
observationTime??E?.sampleTime??E?.time,originObserverId:E?.originObserverId??E?.observerId??h.unit.id,trace:[...h.trace],sourcePosition:{...h.position},receiverPosition:C?{...C.position}:
void 0};return A||m.push({...P,type:"received",time:M+T.delay,unitId:C.unit.id,senderId:h.unit.id}),_(h,A?"sendFailed":"sent",M,P)}function U(h){return[...(h.graph?.triggers??[]).filter(
M=>M.event==="near").map(M=>({c:M,key:"trigger:"+M.id})),...(h.graph?.edges??[]).filter(M=>M.from===h.node?.id&&M.when==="near").map(M=>({c:M,key:"edge:"+M.from+"|"+oe(M)}))]}function q(h,M){
let T=!1;for(let{c:C,key:y}of U(h)){let E=r.destination(h,C);if(!E)continue;let N=st(h.position,E,C.distanceMode),A=N<=C.distance+1e-6,P=h.nearInside.get(y)??!1;if(h.nearInside.set(
y,A),A&&!P&&!(y.startsWith("trigger:")&&C.once!==!1&&h.triggerFired.has(C.id))){let Y={destinationId:C.destinationId,distance:N,distanceMode:C.distanceMode??"absolute",conditionKey:oe(
C)};if(_(h,"near",M,Y)){T=!0;break}}}return T}function G(h,M,T){let C=new Map(u.map(A=>[A.unit.id,{...A.position}])),y=new Set;for(let A of u)for(let{c:P}of U(A)){y.add(A);let Y=re(
r.source,A.assignment,P);Y?.kind==="unit"&&r.byId.has(Y.unitId)&&y.add(r.byId.get(Y.unitId))}if(!y.size)return M;for(let A of y)if(A.status!=="blocked"&&(A.join&&A.path.actualSpeed&&
(M=Math.min(M,h+ae(A.position,A.join)/A.path.actualSpeed)),!A.join&&(!A.graph||["follow","patrol"].includes(A.node?.kind))&&A.path.actualSpeed&&A.path.length)){let P=A.node?.kind===
"patrol"?A.progress:ge(A.routeTravel??A.distance,A.path.length),Y=A.path.nodes.find(K=>K.d>P+1e-7);Y&&(M=Math.min(M,h+(Y.d-P)/(T.get(A.unit.id)??A.path.actualSpeed)))}let E=new Map(
u.map(A=>[A.unit.id,r.predict(A,M,T,C)])),N=M;for(let A of u)for(let{c:P,key:Y}of U(A)){if(A.nearInside.get(Y)||Y.startsWith("trigger:")&&P.once!==!1&&A.triggerFired.has(P.id))continue;
let K=r.destination(A,P,C),c=r.destination(A,P,E);if(!K||!c)continue;let R=A.position,L=E.get(A.unit.id),k=[R.x-K.x,R.y-K.y,P.distanceMode==="horizontal"?0:R.z-K.z],D=[L.x-c.x-k[0],
L.y-c.y-k[1],P.distanceMode==="horizontal"?0:L.z-c.z-k[2]],V=D.reduce((W,te)=>W+te*te,0),X=2*k.reduce((W,te,ze)=>W+te*D[ze],0),le=k.reduce((W,te)=>W+te*te,0)-P.distance*P.distance,
ve=X*X-4*V*le;if(V>1e-12&&le>1e-6&&ve>=0){let W=(-X-Math.sqrt(ve))/(2*V);W>1e-9&&W<=1&&(N=Math.min(N,h+(M-h)*W))}}return N}function J(h){let M=!1;for(let y of u)for(let E=0;E<(y.graph?.
triggers.length??0)&&r.activate(y,"time",h,f);E++)M=!0;let T=y=>{for(let E=0;E<64;E++){if(y.status==="blocked")return;let N=q(y,h);if(N){M=!0;continue}if(y.node?.kind==="report"&&!y.
sent?N=$(y,h):y.node?.kind==="wait"&&!y.elapsed&&h-y.nodeTime>=(y.node.parameter==="preparation"?y.assignment.preparation??y.node.seconds:y.node.seconds)&&(y.elapsed=!0,N=_(y,"elap\
sed",h)),M=M||N,!N)return}throw Error("即時ノード遷移が64段を超えました。循環を見直してください。")};for(let y of u)T(y);let C=0;for(;;){if(m.sort((N,A)=>N.
time-A.time||N.unitId.localeCompare(A.unitId)),!m[0]||m[0].time>h)return M;if(++C>1e5||f.length>1e5)throw Error("情報イベントが10万件を超えました。");let y=m.shift(),
E=r.byId.get(y.unitId);if(f.push(y),E.observation=y,y.targetPosition&&["x","y","z"].every(N=>Number.isFinite(y.targetPosition[N]))){let N=E.receivedPosition;(!N||N.targetId!==y.targetId||
(y.observationTime??y.time)>=(N.observationTime??N.time))&&(E.receivedPosition={...y,targetPosition:{...y.targetPosition}},E.latestObservation=E.receivedPosition)}M=r.transition(E,
"received",h,f,y)||M,T(E)}}J(0),w&&Object.assign(S,w.update(f)),a&&r.record(0,v);for(let h=0;h<o;){let M=Math.min(o,(Math.floor((h+1e-8)/s)+1)*s,e?.deadline>h?e.deadline:1/0),T=1/0;
for(let c of m)c.time>h+1e-8&&(T=Math.min(T,c.time));for(let c of u)if(c.status!=="blocked"){if(c.node?.kind==="wait"&&!c.elapsed){let R=c.node.parameter==="preparation"?c.assignment.
preparation??c.node.seconds:c.node.seconds;c.nodeTime+R>h+1e-8&&(T=Math.min(T,c.nodeTime+R))}for(let R of c.graph?.triggers??[])if(R.event==="time"){let L=r.nextTriggerTime(c,R);L>
h+1e-8&&(T=Math.min(T,L))}if((!c.graph||c.node?.kind==="follow")&&!c.join&&!c.path.periodic&&c.path.length&&c.path.actualSpeed&&!c.routeArrived){let R=(c.graph?c.routeStarted??0:0)+
c.path.delay+c.path.length/c.path.actualSpeed;R>h+1e-8&&(T=Math.min(T,R))}if(c.join&&c.path.actualSpeed){let R=h+ae(c.position,c.join)/c.path.actualSpeed;R>h+1e-8&&(T=Math.min(T,R))}
if(c.node?.kind==="move"&&c.status!=="arrived"&&c.path.actualSpeed&&["point","received"].includes(re(r.source,c.assignment,c.node)?.kind)&&r.movementDestination(c)){let R=h+ae(c.position,
r.terrain.project(r.movementDestination(c),c.unit.domain).point)/c.path.actualSpeed;R>h+1e-8&&(T=Math.min(T,R))}}r.currentTime=h;let C=H(),y=G(h,Math.min(M,T),C),E=y-h,N=new Map(u.
map(c=>[c.unit.id,{...c.position}])),A=new Map(u.map(c=>[c.unit.id,r.predict(c,y,C,N)])),P=!1;for(let c of u)if(c.status!=="blocked"&&!(c.graph&&!c.node)){if(c.node?.kind==="follow"&&
c.join){et(r,c,c.join,c.path.actualSpeed,E)&&(c.join=null,c.routeStarted=y-(c.path.actualSpeed?c.routeOffset/c.path.actualSpeed:0)-(c.routeOffset>0?c.path.delay:0),c.routeTravel=c.
routeOffset),P=!0;continue}if(!c.graph||c.node.kind==="follow"){let R=c.status,L=c.segment,k=c.graph?c.routeStarted??0:0,D=he.prototype.evaluateUnit.call(r,c.unit,Math.max(0,y-k),!1);
if(c.graph){let V=c.distance+Math.max(0,D.distance-(c.routeTravel??0));c.routeTravel=D.distance,Object.assign(c,D),c.distance=V}else Object.assign(c,D);c.segment=Ee(c.path,c.path.periodic?
D.distance%c.path.length:D.distance).segment,(R!==c.status||L!==c.segment)&&(P=!0),c.status==="arrived"&&!c.routeArrived&&(c.routeArrived=!0,P=_(c,"arrived",y)||P)}else if(c.node.kind===
"patrol"){if(y<=c.readyAt){c.status="waiting";continue}let R=y-Math.max(h,c.readyAt);if(c.join){et(r,c,c.join,c.path.actualSpeed,R)&&(c.join=null),P=!0;continue}if(!c.path.length){
c.status="blocked",c.error="周回経路の長さが0です。",P=!0;continue}let L=(C.get(c.unit.id)??c.path.actualSpeed)*R,k=c.progress+L;if(c.path.error&&k>=c.path.length){c.position=
{...c.path.nodes.at(-1)},c.status="blocked",c.error=c.path.error,P=!0;continue}c.progress=ge(k,c.path.length);let D=Ee(c.path,c.progress);c.position=D.point,c.heading=D.heading,c.distance+=
L,c.status="moving",D.segment!==c.segment&&(P=!0,c.segment=D.segment)}else if(c.node.kind==="move"){let R=r.movementDestination(c,A),L=re(r.source,c.assignment,c.node)?.kind,k=L===
"unit";if(!R){if(L==="received"){c.status="standby";continue}c.status="blocked",c.error="目的地が見つかりません。",P=!0;continue}(c.status!=="arrived"||k)&&et(r,c,R,c.path.
actualSpeed,E)&&c.status==="arrived"&&!c.destinationArrived&&(c.destinationArrived=!0,P=!0,_(c,"arrived",y))}}if(Math.abs(y-M)<1e-8){let c=u.filter(k=>k.unit.sensor?.enabled&&k.status!==
"blocked"&&k.node?.kind!=="stop"&&k.node?.sensor!==!1),R=At(c.map(k=>({unit:k.unit,position:Ze(k.position,k.unit),state:k})),I),L=[];for(let k of x){if(k.error&&k.path.errorAt==="初\
期位置"||k.unit.detectability===0)continue;let D=Ze(k.position,{domain:k.unit.domain});for(let V of St(R,D,I)){++j%256===0&&(yield{time:h,result:S});let X=V.state,le=X.unit.sensor,
ve=X.unit.id+"|"+k.unit.id;if(X.unit.faction===k.unit.faction||!le.domains.includes(k.unit.domain))continue;let W=ae(V.position,D),te=We(le,W,k.unit.detectability??1,y-l);if(!(te<=
0||le.terrainLOS&&!_e(r.terrain,V.position,D))&&B(ie(r.source,X.unit.id,"unified-detect-v2")+"|"+JSON.stringify([k.unit.id,l,y]))<te){let ze={type:"detected",time:y,sampleTime:y,observationTime:y,
observerId:X.unit.id,unitId:X.unit.id,targetId:k.unit.id,distance:W,observerPosition:{...V.position},targetPosition:{...D},trace:[]};X.latestObservation=ze,(!g.has(ve)||X.graph?.triggers.
some(nt=>nt.event==="detected"&&nt.once===!1))&&L.push(ze),g.add(ve)}}}L.sort((k,D)=>k.unitId.localeCompare(D.unitId)||k.targetId.localeCompare(D.targetId));for(let k of L){let D=r.
byId.get(k.unitId);(!e||e.type==="state"||D.unit.faction===e.observerFaction&&b.some(V=>V.unit.id===k.targetId))&&!p.has(k.targetId)&&(p.set(k.targetId,k),S.events.push(k)),D.observation=
k,P=_(D,"detected",y,k)||P}l=y}if(P=J(y)||P,f.length+m.length>1e5)throw Error("行動イベントが10万件を超えました。");S.detectedCount=S.events.filter(c=>!e||c.time<=e.
deadline).length,S.reachedCount=new Set(f.filter(c=>c.type==="arrived"&&z.includes(c.unitId)&&(!e||c.time<=e.deadline)).map(c=>c.unitId)).size,w&&Object.assign(S,w.update(f));let Y=e?.
type==="arrive"?S.reachedCount:S.detectedCount,K=e?.join==="all"?e.type==="arrive"?z.length:b.length:1;if(e&&e.type!=="state"&&K>0&&y<=e.deadline&&Y>=K&&S.successTime===null&&(S.success=
!0,S.successTime=y),a&&(P||y-O>=d-1e-8||y===o)&&(r.record(y,v),O=y),h=y,yield{time:y,result:S},!r.source.measurements?.length&&!a&&!u.some(c=>c.graph)&&e?.type==="detect"&&S.detectedCount===
b.length)break}return r.source.measurements?.length&&(S.measurements=Ve(r.source,f,o)),S.constrainedPaths=u.filter(h=>h.status==="blocked").length,a&&(r.frames=v,r.result=S),S}var Tt=t=>new se(
t);function*jt(t,e=t.scenario.mission,n=t.scenario.analysis?.step??10,i={}){if(!(t instanceof se)&&t.source.version!==3&&n!==void 0){let r=Se(t.source);r.recording={step:n,interval:n},
r.analysis&&(r.analysis.step=n),t=new se(r)}return yield*Ct(t,e,n,i)}function tn(t,e){if(e===0)return{rate:null,low:null,high:null};let n=1.959963984540054,i=t/e,r=1+n*n/e,o=(i+n*n/(2*e))/r,a=n*Math.sqrt(i*(1-i)/e+n*n/(4*e*e))/r;return{rate:i,low:Math.
max(0,o-a),high:Math.min(1,o+a)}}function Ot(t){let e=Se(t),n=[...Fe(e.mission,e.duration),...Re(e.analysis,e.duration)];if((!e.mission||!e.analysis)&&n.push("成功条件と分析条件を設定してください。"),
n.length)throw new Error(n.join(`
`));let i=e.analysis,r=e.trial??0;if(r+i.trials-1>1e9)throw new Error("試行番号の上限を超えます。");let o=ht(e);for(let a of o){for(let s of[...a.settings,...i.uncertainties??
[]])Oe(e,s);me(Pe(e,a,r,{maximum:!0}).scenario)}return{scenario:e,analysis:i,startTrial:r,conditions:o}}function tt(t,e){let n=e.filter(a=>a.success).length,i=e.filter(a=>a.success).
map(a=>a.successTime).sort((a,s)=>a-s),r=i.length,o=r?r%2?i[(r-1)/2]:(i[r/2-1]+i[r/2])/2:null;return{count:t,total:e.length,successes:n,...tn(n,e.length),median:o,invalidTrials:e.filter(
a=>a.invalidUnits>0).length,trials:e}}var ye=0;self.onmessage=({data:t})=>{if(t.type==="cancel"){ye++;return}t.type==="run"&&nn(t,++ye)};async function nn(t,e){let n=performance.now();try{let{scenario:i,analysis:r,startTrial:o,
conditions:a}=Ot(t.scenario),s=[],d=a.length*r.trials,u=0,f=0,p=performance.now();for(let g of a){let m=[];for(let v=0;v<r.trials;v++){if(e!==ye)return;let x=o+v,{scenario:b,sampled:z}=Pe(
i,g,x),w=Tt(b),S=jt(w,b.mission,r.step),j=S.next();for(;!j.done;){if(performance.now()-p>16&&(await new Promise(l=>setTimeout(l,0)),p=performance.now(),e!==ye))return;j=S.next()}let O=j.
value;m.push({...O.measurements?{measurements:O.measurements}:{},...b.mission?.type==="state"?{stateEntries:O.stateEntries,stateTargetCount:O.stateTargetCount,stateReachedCount:O.stateReachedCount}:
{},reachedCount:O.reachedCount??0,responderCount:O.responderCount??0,trial:x,sampled:z,success:O.success,successTime:O.successTime,detectedCount:O.detectedCount,targetCount:O.targetCount,
invalidUnits:O.invalidUnits,constrainedPaths:O.constrainedPaths}),u++,(performance.now()-f>120||v===r.trials-1)&&(f=performance.now(),self.postMessage({type:"progress",runId:t.runId,
completed:u,planned:d,elapsedMs:performance.now()-n,rows:[...s,{...tt(g.count,m),condition:g}]})),await new Promise(l=>setTimeout(l,0)),p=performance.now()}s.push({...tt(g.count,m),
condition:g})}e===ye&&self.postMessage({type:"complete",runId:t.runId,completed:u,planned:d,elapsedMs:performance.now()-n,rows:s})}catch(i){e===ye&&self.postMessage({type:"error",runId:t.
runId,message:i.message})}}})();
