/* SimSim portable 20261007-plan-switch-25-0e9cff0967fc. Generated by npm run build:portable. */
(()=>{var Xt="20261007-plan-switch-25",mt="20261007-plan-switch-25-0e9cff0967fc",vn="v"+Xt.replace(/^(\d{4})(\d{2})(\d{2})-.*-(\d+)$/,"$1.$2.$3.$4");function gt(t){let e=t.mission;if(e?.type!=="state")return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=t.behaviors?.find(r=>r.id===n?.behaviorId);return n?i?.nodes?.
some(r=>r.id===e.nodeId)?[]:["計測対象の状態を選択してください。"]:["計測対象のタスクがありません。"]}function Ae(t,e=t.mission){if(e?.type!=="state")
return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=[];for(let r of n?.targets??[])if(r.startsWith("unit:")){let o=t.units.find(a=>a.id===r.slice(5));o&&o.enabled!==
!1&&i.push(o.id)}else{let o=t.groups?.find(a=>a.id===r.slice(6));if(o&&o.enabled!==!1)for(let a=1;a<=o.count;a++)i.push(o.id+"__"+a)}return i.sort()}var Kt=(t,e)=>t.join==="all"?e:
t.join==="count"?t.requiredCount:1;function _e(t,e,n,i=e.deadline){let r=t.filter(a=>a.time<=Math.min(i,e.deadline)).sort((a,s)=>a.time-s.time||a.unitId.localeCompare(s.unitId)),o=Kt(
e,n);return{stateTargetCount:n,stateReachedCount:r.length,stateEntries:r,success:n>0&&o>0&&r.length>=o,successTime:n>0&&o>0&&r.length>=o?r[o-1].time:null}}var ue=class{constructor(e,n){
this.mission=e,this.members=new Set(n),this.first=new Map,this.cursor=0}update(e){for(;this.cursor<e.length;this.cursor++){let n=e[this.cursor];["initialized","nodeChanged"].includes(
n.type)&&n.nodeId===this.mission.nodeId&&n.time<=this.mission.deadline&&this.members.has(n.unitId)&&!this.first.has(n.unitId)&&this.first.set(n.unitId,n.time)}return _e([...this.first].
map(([n,i])=>({unitId:n,time:i})),this.mission,this.members.size)}};function De(t,e){let n=t.mission;if(n?.type!=="state")return;let i=new Set(Ae(t)),r=e.stateEntries;if(e.stateTargetCount!==
i.size||!Array.isArray(r)||r.length>i.size||new Set(r.map(a=>a?.unitId)).size!==r.length||r.some(a=>!a||!i.has(a.unitId)||!Number.isFinite(a.time)||a.time<0||a.time>n.deadline))throw Error(
"状態到達の対象・初回到達時刻が不正です。");let o=_e(r,n,i.size);if(e.stateReachedCount!==o.stateReachedCount||e.success!==o.success||e.successTime!==o.successTime)
throw Error("状態到達数・成立時刻と計測条件が一致していません。")}function yt(t){if(t.measurements===void 0)return[];if(!Array.isArray(t.measurements)||t.measurements.length>12)return["measurementsは最大12件の配列にしてください。"];
let e=[],n=new Set;for(let i of t.measurements){if(!i||typeof i!="object"){e.push("計測点はオブジェクトにしてください。");continue}let r=t.behaviorAssignments?.find(
a=>a.id===i.assignmentId),o=t.behaviors?.find(a=>a.id===r?.behaviorId);(typeof i.id!="string"||!/^[A-Za-z0-9_-]{1,64}$/.test(i.id)||n.has(i.id))&&e.push("計測点のidは重複しない英数字・_・-（64文字以内\
）です。"),(typeof i.name!="string"||!i.name.trim()||i.name.length>120)&&e.push("計測点のnameは1～120文字です。"),(i.type!=="state"||!o?.nodes?.some(a=>a.id===i.nodeId))&&
e.push("計測点のtypeはstate、assignmentId・nodeIdは存在するタスク・状態を指定してください。"),(!["any","all","count"].includes(i.join)||i.join==="count"&&
(!Number.isInteger(i.requiredCount)||i.requiredCount<1||i.requiredCount>2e3))&&e.push("計測点のjoinはany・all・count、requiredCountは1～2000です。"),(!Number.isFinite(
i.deadline)||i.deadline<=0||i.deadline>t.duration)&&e.push("計測点のdeadlineは0より大きく終了時刻以下にしてください。"),i.previousId!==void 0&&!n.has(i.previousId)&&
e.push("所要時間の基準previousIdには、この計測点より前に登録した計測点を指定してください。"),n.add(i.id)}return e}function Re(t,e,n=t.duration){
return(t.measurements??[]).map(i=>({id:i.id,...new ue({...i,deadline:Math.min(n,i.deadline)},Ae(t,i)).update(e)}))}function vt(t,e){if(t.measurements?.length){if(!Array.isArray(e)||
e.length!==t.measurements.length)throw Error("計測点の結果数が一致しません。");for(let[n,i]of t.measurements.entries()){if(e[n]?.id!==i.id)throw Error("計測点の結果IDが一致しま\
せん。");De({...t,mission:i},e[n])}}}var Zt={number:"数値",route:"経路",destination:"目的地",unit:"単体ユニット"},bt={routeId:"route",destinationId:"destination",receiverId:"unit",seconds:"number",speedFraction:"\
number",distance:"number"},re=t=>!!t&&typeof t=="object"&&!Array.isArray(t)&&Object.keys(t).length===1&&typeof t.$param=="string";function Se(t,e,n){if(!re(t))return t;let i=Array.
isArray(e?.parameters)?e.parameters.find(r=>r?.id===t.$param):null;return Object.hasOwn(n?.parameters??{},t.$param)?n.parameters[t.$param]:i?.default}function Ee(t,e){if(!t)return t;
let n=i=>i&&typeof i=="object"?Object.fromEntries(Object.entries(i).map(([r,o])=>[r,Se(o,t,e)])):i;return{...t,nodes:t.nodes.map(n),edges:t.edges.map(n),triggers:(t.triggers??[]).map(
n)}}function We(t,e,n){if(!Array.isArray(e.nodes)||!Array.isArray(e.edges)||e.triggers!==void 0&&!Array.isArray(e.triggers))return["挙動のノード・条件の形式が不正です。"];
let i=[],r=e.parameters??[],o=new Set;if(!Array.isArray(r)||r.length>64)return["担当時に指定する値は最大64件の配列です。"];let a=(s,d)=>s.type==="number"?Number.
isFinite(d):typeof d=="string"&&(s.type==="route"?t.routes:s.type==="destination"?t.destinations:t.units)?.some?.(u=>u.id===d);for(let s of r){if(!s||!/^[a-zA-Z0-9_-]{1,80}$/.test(
s.id??"")||o.has(s.id)||typeof s.name!="string"||!s.name.trim()||s.name.length>120||!Object.hasOwn(Zt,s.type)){i.push("担当値のID・名前・種類が不正または重複しています。");
continue}o.add(s.id),s.unit!==void 0&&(s.type!=="number"||!["s","m","ratio"].includes(s.unit))&&i.push("担当値の単位が不正です。"),Object.hasOwn(s,"default")&&!a(s,s.default)&&
i.push("担当値「"+s.name+"」の既定値が不正です。"),n&&!a(s,Se({$param:s.id},e,n))&&i.push("タスク「"+n.name+"」で「"+s.name+"」を指定してください。")}
for(let s of[...e.nodes,...e.edges,...e.triggers??[]].filter(d=>d&&typeof d=="object"))for(let[d,u]of Object.entries(s))if(u&&typeof u=="object"&&(Object.hasOwn(u,"$param")||bt[d])){
let l=re(u)?r.find(g=>g?.id===u.$param):null,p={seconds:"s",distance:"m",speedFraction:"ratio"}[d];(!l||l.type!==bt[d]||p&&l.unit&&l.unit!==p)&&i.push("担当値の参照・種類・単位が不正です: "+
d)}return n?.parameters!==void 0&&(!n.parameters||typeof n.parameters!="object"||Array.isArray(n.parameters)||Object.keys(n.parameters).some(s=>!o.has(s)))&&i.push("タスクの担当値に未定義の項目が\
あります。"),i}var xt=Number.isFinite,Q=class{constructor(e){this.data=e,this.minX=e.origin.x,this.minY=e.origin.y,this.maxX=this.minX+(e.columns-1)*e.spacing,this.maxY=this.minY+(e.rows-1)*(e.spacingY??
e.spacing),this.cellSize=Math.min(e.spacing,e.spacingY??e.spacing)}contains(e,n){return xt(e)&&xt(n)&&e>=this.minX&&e<=this.maxX&&n>=this.minY&&n<=this.maxY}height(e,n){if(!this.contains(
e,n))return null;let i=this.data,r=(e-this.minX)/i.spacing,o=(n-this.minY)/(i.spacingY??i.spacing),a=Math.min(i.columns-2,Math.floor(r)),s=Math.min(i.rows-2,Math.floor(o)),d=r-a,u=o-
s,l=(p,g)=>i.elevations[(s+g)*i.columns+a+p];return(l(0,0)*(1-d)+l(1,0)*d)*(1-u)+(l(0,1)*(1-d)+l(1,1)*d)*u}project(e,n){let i={...e},r=this.height(i.x,i.y),o=this.data.seaLevel;return r===
null?{point:i,error:"地形データの範囲外です"}:n==="ground"&&(i.z=r,r<=o)?{point:i,error:"地上ユニットは陸上に配置してください"}:n==="surface"&&(i.z=o,r>
o-5)?{point:i,error:"水上ユニットには5m以上の水深が必要です"}:n==="subsurface"&&(i.z>o-1||i.z<r+5||r>=o)?{point:i,error:"水中ユニットは海面下かつ海底から5m以上離してください"}:
n==="air"&&i.z<=Math.max(r,o)+10?{point:i,error:"空中ユニットは地表・海面から10mより高くしてください"}:{point:i,error:null}}};var Qt=["ground","surface","subsurface","air"],Be=Number.isFinite,Le=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n}),le=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z);
function ye(t){return!t||typeof t!="object"||Array.isArray(t)||!Qt.includes(t.domain)||t.clearance!==void 0&&(!Be(t.clearance)||t.clearance<0||t.clearance>1e4)?["経路検査の領域・地表／海底からの余裕\
（0～10000m）が不正です。"]:[]}function Ke(t,e="once"){let n=ye(t);return!t||n.length||((!Array.isArray(t.via)||t.via.length<(e==="loop"?3:2)||t.via.length>100||t.via.some(
i=>!i||!["x","y"].every(r=>Be(i[r])&&Math.abs(i[r])<=1e6)))&&n.push("自動生成の必須経由地点は2～100点（周回は3点以上）の東西・南北座標です。"),["ai\
r","subsurface"].includes(t.domain)&&(!Be(t.height)||t.height<-1e6||t.height>1e6)&&n.push("自動生成する高度・深度のz座標を指定してください。"),t.height!==void 0&&
(!Be(t.height)||Math.abs(t.height)>1e6)&&n.push("高度・深度は数値で指定してください。")),n}function en(t,e,n){let i=t.height(e.x,e.y),r=t.data.seaLevel;return i===
null?-1/0:n==="ground"?i-r:n==="surface"?r-i-5:n==="subsurface"?Math.min(e.z-i-5,r-e.z-1):e.z-Math.max(i,r)-10}function ge(t,e,n){let i=en(t,e,n.domain),r=n.clearance??0;if(i<r-1e-7||
["ground","air"].includes(n.domain)&&i<=0){let o=t.project(e,n.domain);return{point:{...e},reason:o.error??"地表・海底／海面からの余裕 "+r+"mを満たしていません。",
margin:i}}return null}function ke(t,e,n,i){let r=t instanceof Q?t:new Q(t),o=ge(r,e,i),a=ge(r,n,i);if(o)return o;if(a)return a;let s=[0,1],d=r.data;for(let[u,l,p,g]of[["x",d.columns,
d.spacing,d.origin.x],["y",d.rows,d.spacingY??d.spacing,d.origin.y]]){let m=n[u]-e[u];if(!m)continue;let v=Math.min(e[u],n[u]),b=Math.max(e[u],n[u]);for(let x=Math.max(1,Math.ceil(
(v-g)/p));x<=Math.min(l-2,Math.floor((b-g)/p));x++){let T=(g+x*p-e[u])/m;T>0&&T<1&&s.push(T)}}s.sort((u,l)=>u-l);for(let u=1;u<s.length;u++){let l=s[u-1],p=s[u];if(p-l<1e-12)continue;
let g=Le(e,n,l),m=Le(e,n,p),v=Le(e,n,(l+p)/2),b=r.height(g.x,g.y),x=r.height(m.x,m.y),T=r.height(v.x,v.y),I=2*(b+x-2*T),S=x-b-I,N=[0,1];if(Math.abs(I)>1e-12)for(let R of[-S,m.z-g.z-
S]){let f=R/(2*I);f>0&&f<1&&N.push(f)}for(let R of N){let f=ge(r,Le(e,n,l+(p-l)*R),i);if(f)return f}}return null}function tn(t,e,n,{loop:i=!1}={}){let r=ye(n);if(r.length)throw Error(
r[0]);let o=t instanceof Q?t:new Q(t),a=[];if(!Array.isArray(e)||!e.length)return{ok:!0,issues:a};if(e.length===1){let s=ge(o,e[0],n);s&&a.push({segment:0,from:e[0],to:e[0],...s})}
for(let s=1;s<e.length+(i?1:0);s++){let d=e[s-1],u=e[s%e.length],l=ke(o,d,u,n);l&&a.push({segment:s-1,from:{...d},to:{...u},...l})}return{ok:!a.length,issues:a}}var Xe=class{constructor(){
this.values=[]}push(e){let n=this.values.length;for(this.values.push(e);n;){let i=n-1>>1;if(this.values[i].score<=e.score)break;this.values[n]=this.values[i],n=i}this.values[n]=e}pop(){
let e=this.values[0],n=this.values.pop();if(this.values.length){let i=0;for(;i*2+1<this.values.length;){let r=i*2+1;if(r+1<this.values.length&&this.values[r+1].score<this.values[r].
score&&r++,this.values[r].score>=n.score)break;this.values[i]=this.values[r],i=r}this.values[i]=n}return e}};function nn(t,e,n,i,r){if(!ke(t,e,n,i))return[{...e},{...n}];let{nx:o,ny:a,
sx:s,sy:d,height:u}=r,l=o*a,p=new Array(l),g=new Float64Array(l).fill(1/0),m=new Int32Array(l).fill(-1),v=new Uint8Array(l),b=new Xe,x=w=>{if(p[w]!==void 0)return p[w];let D={x:t.minX+
w%o*s,y:t.minY+Math.floor(w/o)*d,z:u},V=t.project(D,i.domain);return p[w]=ge(t,D,i)?null:V.point},T=w=>{let D=Math.round((w.x-t.minX)/s),V=Math.round((w.y-t.minY)/d),W=[];for(let J=-2;J<=
2;J++)for(let q=-2;q<=2;q++){let H=D+q,$=V+J;if(H<0||H>=o||$<0||$>=a)continue;let h=$*o+H,A=x(h);A&&!ke(t,w,A,i)&&W.push(h)}return W},I=new Set(T(n));if(!I.size)throw Error("目的地付近に\
接続できる通行可能な経路がありません。地点・高度／深度・余裕を調整してください。");for(let w of T(e))g[w]=le(e,x(w)),b.push({i:w,score:g[w]+
le(x(w),n)});let S=-1;for(;b.values.length;){let{i:w}=b.pop();if(v[w])continue;if(v[w]=1,I.has(w)){S=w;break}let D=w%o,V=Math.floor(w/o),W=x(w);for(let J=-1;J<=1;J++)for(let q=-1;q<=
1;q++){if(!q&&!J)continue;let H=D+q,$=V+J;if(H<0||H>=o||$<0||$>=a)continue;let h=$*o+H;if(v[h])continue;let A=x(h);if(!A)continue;let j=g[w]+le(W,A);j>=g[h]||ke(t,W,A,i)||(m[h]=w,g[h]=
j,b.push({i:h,score:j+le(A,n)}))}}if(S<0)throw Error("この領域・高度／深度・余裕では経路を生成できませんでした。通れる海峡・陸地がつながっているか、必須地点を確認してください。");
let N=[{...n}];for(let w=S;w>=0;w=m[w])N.push(x(w));N.push({...e}),N.reverse();let R=[N[0]],f=0;for(;f<N.length-1;){let w=N.length-1;for(;w>f+1&&ke(t,N[f],N[w],i);)w--;R.push(N[w]),
f=w}return R}function rn(t,e,{mode:n="once"}={}){let i=Ke(e,n);if(i.length)throw Error(i.join(`
`));let r=t instanceof Q?t:new Q(t),o={domain:e.domain,clearance:e.clearance??0},a=e.height??r.data.seaLevel,s=e.via.map((x,T)=>{let I={x:x.x,y:x.y,z:a},S=ge(r,I,o);if(S)throw Error(
"必須地点 "+(T+1)+"："+S.reason);return r.project(I,e.domain).point});if(s.every(x=>le(x,s[0])<1e-6))throw Error("異なる出発地点・目的地を指定してください。");
let d=r.maxX-r.minX,u=r.maxY-r.minY,l=Math.max(Math.min(r.data.spacing,r.data.spacingY??r.data.spacing)/4,Math.max(d,u)/256),p=Math.max(2,Math.ceil(d/l)+1),g=Math.max(2,Math.ceil(u/
l)+1),m={nx:p,ny:g,sx:d/(p-1),sy:u/(g-1),height:a},v=[s[0]];for(let x=1;x<s.length+(n==="loop"?1:0);x++)le(v.at(-1),s[x%s.length])<1e-8||v.push(...nn(r,v.at(-1),s[x%s.length],o,m).
slice(1));if(n==="loop"&&le(v[0],v.at(-1))<1e-6&&v.pop(),v.length>500)throw Error("生成経路が500点を超えました。必須地点を減らしてください。");if(v.length<
(n==="loop"?3:2))throw Error("周回は異なる必須地点を3点以上指定してください。");if(!tn(r,v,o,{loop:n==="loop"}).ok)throw Error("生成経路の検査に失敗しました。条件を調整してください。");
return{points:v,navigation:o}}function It(t){for(let e of t.routes??[])if(e.generate)try{let n=rn(t.terrain,e.generate,{mode:e.mode??"once"});Object.assign(e,n),delete e.generate}catch(n){
throw Error("経路「"+e.name+"」："+n.message)}return t}function Ue(t,e,n,i){let r=t.behaviors?.find(s=>s.id===e?.behaviorId),o=Se(n?.routeId,r,e),a=o?t.routes?.find(s=>s.id===o):null;return{id:a?.id??"default",points:a?.points??e?.route??
[i.initial,...i.route],mode:n?.kind==="patrol"?"loop":a?.mode??e?.routeMode??i.routeMode}}function se(t,e,n){let i=Se(n?.destinationId,t.behaviors?.find(r=>r.id===e?.behaviorId),e);
return i?t.destinations?.find(r=>r.id===i):e?.base?{kind:"point",point:e.base}:null}function ae(t){let e=t.when??t.event;return e==="near"?[e,t.destinationId,t.distance,t.distanceMode??
"absolute"].map(n=>re(n)?JSON.stringify(n):n).join("|"):e==="time"?e+"|"+(re(t.seconds)?JSON.stringify(t.seconds):t.seconds):e}var wt=(t,e,n="absolute")=>Math.hypot(t.x-e.x,t.y-e.y,
n==="horizontal"?0:t.z-e.z);function Mt(t){let e=[],n=(r,o,a)=>Number.isFinite(r)&&r>=o&&r<=a,i=r=>r&&["x","y","z"].every(o=>n(r[o],-1e6,1e6));for(let[r,o]of[["routes",128],["desti\
nations",256]]){let a=t[r]??[],s=new Set;if(!Array.isArray(a)||a.length>o){e.push(r==="routes"?"経路は最大128件の配列です。":"目的地は最大256件の配列です。");
continue}for(let d of a){if(!d||!/^[a-zA-Z0-9_-]{1,80}$/.test(d.id??"")||s.has(d.id)||typeof d.name!="string"||!d.name.trim()||d.name.length>120){e.push("経路・目的地のIDまたは名前が不正・重複しています。");
continue}s.add(d.id),r==="routes"?(d.generate!==void 0?(d.points!==void 0&&e.push("経路にはpointsかgenerateのどちらか一方を指定してください。"),e.push(...Ke(d.
generate,d.mode??"once"))):(!Array.isArray(d.points)||d.points.length<2||d.points.length>500||d.points.some(u=>!i(u)))&&e.push("経路は2～500点の座標で指定してください。"),
d.navigation!==void 0&&e.push(...ye(d.navigation)),["once","loop","pingpong"].includes(d.mode??"once")||e.push("経路の繰り返し方式が不正です。")):d.kind==="point"?i(
d.point)||e.push("目的地の地点座標が不正です。"):d.kind==="unit"?t.units?.some(u=>u.id===d.unitId)||e.push("目的地のユニットがありません。"):d.kind!=="\
received"&&e.push("目的地は地点・ユニット・取得した目標位置（探知・受信）を指定してください。")}}return e}function Ze(t,e,n=!1){let i=[];return!(n&&
re(e.destinationId))&&(!Array.isArray(t.destinations)||!t.destinations.some(r=>r?.id===e.destinationId))&&i.push("接近条件の目的地を選択してください。"),!(n&&re(e.
distance))&&(!Number.isFinite(e.distance)||e.distance<0||e.distance>1e6)&&i.push("接近距離は0～1000000mです。"),["horizontal","absolute"].includes(e.distanceMode??"absolut\
e")||i.push("距離の種類は水平距離または絶対距離です。"),i}var on={follow:"経路を進む",patrol:"協調して周回",signal:"情報を待つ",report:"報告",move:"目的に向かって進む",wait:"時間待ち",stop:"終了"},sn={received:"\
情報受信",time:"時間経過",detected:"対象探知",near:"指定距離まで近づく"};function At(t){return t.initial??t.entry??(Array.isArray(t.triggers)?t.triggers.find(e=>e?.
event==="scenarioStart")?.to:void 0)}function et(t){return(t.triggers??[]).filter(e=>e?.event!=="scenarioStart")}function St(t){for(let e of t.behaviors??[]){let n=At(e);n!==void 0&&
(e.initial=n),e.triggers=et(e);for(let i of e.triggers)delete i.policy;for(let i of e.nodes)i.kind==="return"&&(i.kind="move");delete e.entry}return t}var an={follow:["detected","received","arrived","near"],patrol:["detected","received","near"],signal:["received","detected","near"],report:["sent","sendFailed","near"],move:["arriv\
ed","received","detected","near"],return:["arrived","received","detected","near"],wait:["elapsed","received","detected","near"],stop:[]};var ee=(t,e,n)=>Number.isFinite(t)&&t>=e&&t<=n,Qe=t=>t&&["x","y","z"].every(e=>ee(t[e],-1e6,1e6));function tt(t,e=!1){let n=Mt(t),i=t.behaviors??[],r=t.behaviorAssignments??[];if(!Array.
isArray(i)||i.length>50)return["挙動は最大50件の配列です。"];if(!Array.isArray(r)||r.length>100)return["タスクは最大100件の配列です。"];let o=Array.isArray(
t.routes)?t.routes:[],a=Array.isArray(t.destinations)?t.destinations:[],s=new Set,d=new Set,u=new Set;for(let m of i){if(!m||!/^[a-zA-Z0-9_-]{1,80}$/.test(m.id??"")||s.has(m.id)){n.
push("挙動IDが不正または重複しています。");continue}if(s.add(m.id),(typeof m.name!="string"||!m.name.trim()||m.name.length>120)&&n.push("挙動名は1～120文字です。"),
!Array.isArray(m.nodes)||!m.nodes.length||m.nodes.length>64||!Array.isArray(m.edges)||m.edges.length>128){n.push("挙動は1～64ノード、最大128接続です。");continue}e||
n.push(...We(t,m));let v=(f,w,D)=>!e&&re(f)||ee(f,w,D),b=f=>!re(f),x=new Map,T=new Set;for(let f of m.nodes){if(!f||!/^[a-zA-Z0-9_-]{1,80}$/.test(f.id??"")||x.has(f.id)||!(on[f.kind]||
f.kind==="return")){n.push("ノードID・種類が不正です。");continue}if(x.set(f.id,f),f.routeId!==void 0&&(!["follow","patrol"].includes(f.kind)||b(f.routeId)&&!o.some(w=>w?.
id===f.routeId))&&n.push("状態ノードの経路参照が不正です。"),f.destinationId!==void 0&&(!["move","return"].includes(f.kind)||b(f.destinationId)&&!a.some(w=>w?.id===
f.destinationId))&&n.push("状態ノードの目的地参照が不正です。"),f.kind==="patrol"&&f.routeId&&b(f.routeId)&&o.find(w=>w?.id===f.routeId)?.points?.length<3&&n.push(
"周回経路は3点以上必要です。"),f.kind==="patrol"&&f.routeId&&b(f.routeId)){let w=o.find(D=>D?.id===f.routeId);w?.generate&&w.mode!=="loop"&&n.push("協調して周回する自動生成経路はmode\
をloopにしてください。")}f.kind==="wait"&&!v(f.seconds,0,86400)&&n.push("待機時間は0～86400秒です。"),f.kind==="patrol"&&!v(f.speedFraction??.7,.05,1)&&n.push("巡\
回速度比は0.05～1です。"),f.kind==="report"&&!f.receiverId&&!f.receiverRole&&n.push("報告先または報告先の役割を指定してください。"),f.receiverId&&b(f.
receiverId)&&!t.units?.some(w=>w.id===f.receiverId)&&n.push("報告先の単体ユニットがありません: "+f.receiverId),f.joinMode!==void 0&&(!["follow","patrol"].includes(f.
kind)||!["start","nearest"].includes(f.joinMode))&&n.push("経路への入り方は最初から／最短地点からを選択してください。"),f.heightMode!==void 0&&(f.kind!==
"move"||!["keep","target"].includes(f.heightMode))&&n.push("移動の高度・深度は維持する／目的地に合わせるを選択してください。"),f.sensor!==void 0&&typeof f.
sensor!="boolean"&&n.push("ノードのsensorはbooleanです。"),(f.x!==void 0&&!ee(f.x,0,4e3)||f.y!==void 0&&!ee(f.y,0,4e3))&&n.push("ノード位置が不正です。")}let I=At(
m),S=m.triggers??[],N=new Set,R=new Set;if(I!==void 0&&!x.has(I)&&n.push("初期状態の参照先がありません。"),(m.initial!==void 0&&m.entry!==void 0&&m.initial!==m.entry||
m.triggers?.some?.(f=>f?.event==="scenarioStart"&&f.to!==I))&&n.push("初期状態の指定が重複しています。"),!Array.isArray(S)||S.length>32)n.push("イベントノードは最大32件の配列です。");else if(I===
void 0&&!S.length)n.push("初期状態またはイベントノードを指定してください。");else for(let f of S){(!f||!/^[a-zA-Z0-9_-]{1,80}$/.test(f.id??"")||N.has(f.id)||
!(Object.hasOwn(sn,f.event)||f.event==="scenarioStart")||!x.has(f.to))&&n.push("イベントノードのID・種類・接続先が不正です。"),N.add(f?.id);let w=f?ae(f):"";R.
has(w)&&n.push("同じイベント・時間のイベントノードは一つだけ指定できます。"),R.add(w),f?.event==="time"&&(!v(f.seconds,0,86400)||f.once===!1&&f.seconds===
0)&&n.push("時間イベントは0～86400秒、繰り返す場合は0より大きい秒数です。"),f?.policy!==void 0&&!["idle","interrupt"].includes(f.policy)&&n.push("起動方法はid\
le・interruptです。"),f?.once!==void 0&&typeof f.once!="boolean"&&n.push("イベントノードのonceはbooleanです。"),f?.event==="near"&&n.push(...Ze(t,f,!e)),(f?.x!==void 0&&
!ee(f.x,0,4e3)||f?.y!==void 0&&!ee(f.y,0,4e3))&&n.push("イベントノードの位置が不正です。")}for(let f of m.edges){let w=f?.from+"|"+(f?ae(f):""),D=x.get(f?.from);(!f||
!D||!x.has(f.to)||!(an[D.kind]??[]).includes(f.when)||T.has(w))&&n.push("接続条件が始点ノードに対応しないか、接続が不正・重複しています。"),f?.once!==
void 0&&typeof f.once!="boolean"&&n.push("接続のonceはbooleanです。"),f?.when==="near"&&n.push(...Ze(t,f,!e)),T.add(w)}}for(let m of r){if(!m||!/^[a-zA-Z0-9_-]{1,80}$/.test(
m.id??"")||d.has(m.id)){n.push("タスクIDが不正または重複しています。");continue}d.add(m.id),(typeof m.name!="string"||!m.name.trim()||m.name.length>120)&&n.push("タ\
スク名は1～120文字です。");let v=i.find(I=>I.id===m.behaviorId);if(v||n.push("タスクの挙動がありません。"),!Array.isArray(m.targets)||!m.targets.length&&!(t.
mission?.type==="state"&&t.mission.assignmentId===m.id)&&!t.measurements?.some(I=>I.assignmentId===m.id)||m.targets.length>100){n.push("タスクの担当を選んでください。");
continue}for(let I of m.targets){let S=typeof I=="string"?I.split(":")[0]:"",N=typeof I=="string"?I.slice(S.length+1):"";(!(S==="unit"?t.units?.find(f=>f.id===N):S==="group"&&t.groups?.
find(f=>f.id===N)?.template)||u.has(I))&&n.push("タスクの担当が不正または重複しています。"),u.add(I)}if(v){let I=We(t,v,m);if(n.push(...I),!I.length&&v.parameters?.
length){let S=Ee(v,m);n.push(...tt({...t,behaviors:[S],behaviorAssignments:[]},!0).map(N=>"タスク「"+m.name+"」: "+N))}}let b=v&&Array.isArray(v.nodes)&&Array.isArray(v.edges)?
Ee(v,m):null,x=b?.nodes.some(I=>I.kind==="patrol"&&!I.routeId),T=b?.nodes.some(I=>["return","move"].includes(I.kind)&&!I.destinationId);x&&(!Array.isArray(m.route)||m.route.length<
3)&&n.push("周回タスクは3点以上の共有経路が必要です。"),m.route!==void 0&&(!Array.isArray(m.route)||m.route.length>500||m.route.some(I=>!Qe(I)))&&n.push("タスクの経路\
が不正です。"),T&&!Qe(m.base)&&n.push("目的に向かって進む状態の目的地を選択してください。"),m.base!==void 0&&!Qe(m.base)&&n.push("帰投地点が不正です。"),
m.routeMode!==void 0&&!["once","loop","pingpong"].includes(m.routeMode)&&n.push("タスクの経路方式が不正です。"),["even","fixed","none"].includes(m.spacing??"none")||n.
push("間隔方式が不正です。"),(!ee(m.spacingDistance??500,0,1e5)||!ee(m.gain??.01,0,1)||!ee(m.preparation??0,0,86400)||!ee(m.phase??0,0,1))&&n.push("タスクの間隔・調整係数・準備時間・開始割合が\
不正です。"),b?.nodes.some(I=>I.receiverRole&&!I.receiverId)&&!t.units?.some(I=>I.id===m.receiverId)&&n.push("タスクの報告先を選んでください。")}let l=t.recording??
{},p=l.step??t.analysis?.step??10,g=l.interval??p;return(!ee(p,.1,300)||!ee(g,.1,300)||g<p||Math.abs(g/p-Math.round(g/p))>1e-8||t.duration/p>1e5)&&n.push("計算刻み0.1～300秒、記録間隔は刻みの整数倍・\
300秒以下、最大10万ステップです。"),t.version===3&&t.analysis&&t.analysis.step!==p&&n.push("分析と記録の計算刻みを一致させてください。"),n}function nt(t,e){let n=t.units?.find(r=>r.id===e),i=n?.groupId??t.groups?.find(r=>e?.slice(0,e.lastIndexOf("__"))===r.id)?.id;return t.behaviorAssignments?.find(r=>r.targets.includes(
"unit:"+e)||i&&r.targets.includes("group:"+i))}function G(t){let e=2166136261;for(let n=0;n<t.length;n++)e^=t.charCodeAt(n),e=Math.imul(e,16777619);return e^=e>>>16,e=Math.imul(e,2146121005),e^=e>>>15,e=Math.imul(e,2221713035),
e^=e>>>16,(e>>>0)/4294967296}var dn=t=>t*t*(3-2*t);function it(t,e,n){let i=Math.floor(e/n),r=dn(e/n-i),o=d=>{let u=G(t+"|angle|"+d)*Math.PI*2,l=Math.sqrt(G(t+"|radius|"+d));return[
Math.cos(u)*l,Math.sin(u)*l,G(t+"|z|"+d)*2-1]},a=o(i),s=o(i+1);return a.map((d,u)=>d+(s[u]-d)*r)}function de(t,e,n){return"simsim-rng-v1|"+JSON.stringify([t.seed??"SimSim",t.trial??
0,e,n])}function rt(t){let e=t.units.map(n=>({...n}));for(let n of t.groups??[]){let i=Math.ceil(Math.sqrt(n.count)),r=Math.ceil(n.count/i);for(let o=0;o<n.count;o++){let a=n.id+"_\
_"+(o+1),s=de(t,a,"deployment"),d=n.placement==="random"?G(s+"|x"):(o%i+.5)/i,u=n.placement==="random"?G(s+"|y"):(Math.floor(o/i)+.5)/r,l=(d-.5)*n.width,p=(u-.5)*n.height,g=b=>({...b,
x:b.x+l,y:b.y+p}),m=n.loopStartMode??"template",v=n.template.routeMode==="loop"&&m!=="template"?{...n.template.motion,loopStart:((n.template.motion?.loopStart??0)+(m==="even"?o/n.count:
G(de(t,a,"loop-start-placement-v1"))))%1}:n.template.motion;e.push({...n.template,...v?{motion:v}:{},enabled:n.enabled!==!1,id:a,name:(n.name+" "+(o+1)).slice(0,120),groupId:n.id,initial:g(
n.template.initial),route:n.template.route.map(g)})}}return e}var C=(t,e,n,i,r,o,a={})=>({key:t,label:e,family:n,path:i,min:r,max:o,scale:1,scope:"entity",...a}),Ye=[C("rate.movement.speed","移動速度","Rate","speed",0,1500,{unit:"m/s",default:0}),
C("extent.sense.radius","最大探知距離","Extent","sensor.range",.001,1e5,{unit:"km",scale:1e3,sensor:!0}),C("interaction.detection.probability","距離0で1分の探知確率",
"Interaction","sensor.probabilityPerMinute",0,1,{unit:"%",scale:.01,sensor:!0}),C("extent.communication.radius","最大通信距離","Extent","communication.range",.001,1e5,{unit:"\
km",scale:1e3,communication:!0}),C("interaction.communication.delay","通信遅延","Interaction","communication.delay",0,86400,{unit:"s",communication:!0}),C("interaction.communic\
ation.probability","通信成功確率","Interaction","communication.probability",0,1,{unit:"%",scale:.01,communication:!0}),C("behavior.preparation","出発準備時間","Behavior",
"preparation",0,86400,{unit:"s",scope:"assignment",preparation:!0,default:0}),C("extent.signature.coefficient","被探知係数","Extent","detectability",0,10,{unit:"倍",default:1}),
C("state.position.x","配置・経路の中心 x","State","initial.x",-1e6,1e6,{unit:"km",scale:1e3,translate:"x"}),C("state.position.y","配置・経路の中心 y","State","initi\
al.y",-1e6,1e6,{unit:"km",scale:1e3,translate:"y"}),C("state.position.z","高度・深度 z","State","initial.z",-2e4,1e5,{unit:"m",translate:"z",vertical:!0}),C("extent.sense.moun\
tHeight","センサー取付高","Extent","sensor.mountHeight",0,1e3,{unit:"m",sensor:!0,default:0}),C("state.route.phase","周回の出発点","State","motion.loopStart",0,1,{unit:"\
%",scale:.01,default:0,loopOnly:!0}),C("motion.horizontal","個体の水平ずれ上限","Motion","motion.horizontal",0,1e4,{unit:"m",default:0}),C("motion.commonHorizontal","群共通の水\
平ずれ上限","Motion","motion.commonHorizontal",0,1e4,{unit:"m",default:0}),C("motion.vertical","上下ずれ上限","Motion","motion.vertical",0,3e3,{unit:"m",default:0,vertical:!0}),
C("motion.scale","航跡の変動間隔","Motion","motion.scale",10,1e5,{unit:"m",default:2e3}),C("motion.startDelay","出発遅れ上限","Motion","motion.startDelay",0,86400,{unit:"\
s",default:0}),C("motion.speedVariation","個体速度のばらつき","Motion","motion.speedVariation",0,1,{unit:"±%",scale:.01,default:0}),C("capacity.population","群の個数",
"Capacity","count",0,2e3,{unit:"個",scope:"group",integer:!0}),C("extent.deployment.width","配置幅 x","Extent","width",0,1e5,{unit:"km",scale:1e3,scope:"group"}),C("extent.depl\
oyment.height","配置幅 y","Extent","height",0,1e5,{unit:"km",scale:1e3,scope:"group"}),C("task.route.x","共有経路の基準 x","State","route.0.x",-1e6,1e6,{unit:"km",scale:1e3,
scope:"assignment",routeAxis:"x"}),C("task.route.y","共有経路の基準 y","State","route.0.y",-1e6,1e6,{unit:"km",scale:1e3,scope:"assignment",routeAxis:"y"}),C("task.route.z",
"共有経路の高度・深度","State","route.0.z",-2e4,1e5,{unit:"m",scope:"assignment",routeAxis:"z"}),C("task.route.phase","共有周回の出発点","State","phase",0,1,{unit:"\
%",scale:.01,scope:"assignment",default:0,patrol:!0}),C("coordination.spacing","協調する指定間隔","Behavior","spacingDistance",0,1e5,{unit:"m",scope:"assignment",fixedSpacing:!0,
default:500}),C("coordination.gain","間隔の調整係数","Behavior","gain",0,1,{unit:"1/s",scope:"assignment",default:.01}),C("mission.deadline","成功条件の期限","Mission",
"mission.deadline",1e-6,86400,{unit:"min",scale:60,scope:"scenario"})];function ze(t){let e=Ye.find(a=>a.key===t);if(e)return e;let n=/^behavior\.(node|trigger)\.([A-Za-z0-9_-]{1,80})\.(seconds|speedFraction)$/.
exec(t??"");if(!n||n[1]==="trigger"&&n[3]!=="seconds")return;let[,i,r,o]=n;return C(t,(i==="trigger"?"イベント ":"状態 ")+r+" · "+(o==="seconds"?"待機・発火時間":"周回速\
度割合"),"Behavior",o,o==="speedFraction"?.05:0,o==="speedFraction"?1:86400,{scope:"behavior",unit:o==="seconds"?"s":"%",scale:o==="seconds"?1:.01,default:o==="speedFraction"?.7:
void 0,collection:i==="node"?"nodes":"triggers",itemId:r})}var pe=t=>JSON.stringify([t.target,t.parameter]);function Et(t){let e=JSON.parse(JSON.stringify(t));return e.factors=[...t.groupId?[{target:"group:"+t.groupId,parameter:"capacity.p\
opulation",values:[...t.counts].sort((n,i)=>n-i)}]:[],...e.factors??[]],delete e.groupId,delete e.counts,e}function un(t,e,n){if(e==="scenario"){if(n.scope!=="scenario"||!t.mission)throw new Error("成功条件を設定してください。");return t}let i=e?.indexOf(":")??-1,r=e?.slice(
0,i),o=e?.slice(i+1),a=r==="unit"?t.units?.find(d=>d.id===o):r==="group"?t.groups?.find(d=>d.id===o):r==="assignment"?t.behaviorAssignments?.find(d=>d.id===o):r==="behavior"?t.behaviors?.
find(d=>d.id===o):null;if(!a||n.scope==="scenario"||n.scope==="group"&&r!=="group")throw new Error("変数の対象が見つかりません: "+e);if(n.scope==="behavior"){let d=r===
"behavior"?a[n.collection]?.find(u=>u.id===n.itemId):null;if(!d||(n.collection==="triggers"?d.event!=="time":n.path==="seconds"?d.kind!=="wait"||d.parameter==="preparation":d.kind!==
"patrol")||d[n.path]!==void 0&&typeof d[n.path]!="number")throw Error("ノードの数値設定がありません。");return d}if(r==="behavior")throw Error("変数の対象が一致しません。");
if(n.scope==="assignment"!=(r==="assignment"))throw new Error("変数の対象が一致しません。");let s=r==="group"&&n.scope==="entity"?a.template:a;if(r!=="assignment"&&nt(
t,r==="group"?o+"__1":o)?.route?.length&&(n.translate||n.loopOnly||n.key.startsWith("extent.deployment.")))throw new Error("共有経路の位置・開始割合はタスク側の変数を選んでください。");
if(n.loopOnly&&s.routeMode!=="loop")throw new Error("周回の出発点は周回経路の対象に指定してください。");if(n.communication&&!s.communication?.enabled)throw new Error(
"通信変数の対象で通信を有効にしてください。");if(n.behavior&&!s.behavior)throw new Error("条件付き行動の設定がありません。");if(n.sensor&&!s.sensor)
throw new Error("探知変数の対象にセンサーがありません。");return s}var cn=(t,e)=>e.split(".").reduce((n,i)=>n?.[i],t);function Je(t,e){let n=ze(e.parameter);if(!n)
throw new Error("未対応の変数です。");let i=un(t,e.target,n);return cn(i,n.path)??(n.key==="extent.sense.mountHeight"&&i.domain==="ground"?2:n.default)}function kt(t){let e=[],n=(i,r,o,a)=>{let s=nt(t,a==="group"?i.slice(6)+"__1":i.slice(5));for(let d of Ye)s?.route?.length&&(d.translate||d.loopOnly||d.key.startsWith("extent.deplo\
yment."))||d.scope==="assignment"||d.loopOnly&&o.routeMode!=="loop"||d.scope==="scenario"||d.scope==="group"&&a!=="group"||d.sensor&&!o.sensor?.enabled||d.communication&&!o.communication?.
enabled||d.behavior&&!o.behavior||d.vertical&&["ground","surface"].includes(o.domain)||e.push({target:i,targetLabel:(a==="group"?"群: ":"ユニット: ")+r,parameter:d.key,label:r+
" · "+d.family+" · "+d.label+" ("+d.unit+")"})};for(let i of t.units??[])n("unit:"+i.id,i.name,i,"unit");for(let i of t.groups??[])n("group:"+i.id,i.name,i.template,"group");for(let i of t.
behaviorAssignments??[])for(let r of Ye.filter(o=>o.scope==="assignment"&&(!o.fixedSpacing||i.spacing==="fixed")&&(!o.routeAxis||i.route?.length)&&(!o.patrol||t.behaviors?.find(a=>a.
id===i.behaviorId)?.nodes.some(a=>a.kind==="patrol"))&&(!o.preparation||t.behaviors?.find(a=>a.id===i.behaviorId)?.nodes.some(a=>a.parameter==="preparation"))))e.push({target:"assi\
gnment:"+i.id,targetLabel:"協調: "+i.name,parameter:r.key,label:i.name+" · "+r.label+" ("+r.unit+")"});for(let i of t.behaviors??[])for(let[r,o]of[["node",i.nodes],["trigger",i.
triggers]])for(let a of o??[]){let s=r==="trigger"&&a.event==="time"||r==="node"&&a.kind==="wait"&&a.parameter!=="preparation"?"seconds":r==="node"&&a.kind==="patrol"?"speedFractio\
n":null;if(!s||a[s]!==void 0&&typeof a[s]!="number")continue;let d="behavior."+r+"."+a.id+"."+s,u=ze(d);e.push({target:"behavior:"+i.id,targetLabel:"挙動: "+i.name+"（使用する全タスク）",
parameter:d,label:i.name+" · "+u.label+" ("+u.unit+")"})}if(t.mission)for(let i of Ye.filter(r=>r.scope==="scenario"))e.push({target:"scenario",targetLabel:"シナリオ・ミッション",
parameter:i.key,label:i.label+" ("+i.unit+")"});return e}function zt(t,e){let n=[],i=new Set;t.groupId&&i.add(pe({target:"group:"+t.groupId,parameter:"capacity.population"}));for(let[o,a]of[["factors",t.factors??[]],["uncertainties",t.uncertainties??
[]]]){let s=o==="factors"?9:8;if(!Array.isArray(a)||a.length>s){n.push(o+"は最大"+s+"変数にしてください。");continue}for(let d of a){let u=ze(d?.parameter),l=pe(d??{});
if(!u||typeof d.target!="string"){n.push("未対応の変数または対象です。");continue}i.has(l)&&n.push("同じ変数を重複して指定できません。"),i.add(l);let p=u.
key==="mission.deadline"?Math.min(u.max,e):u.max,g=m=>typeof m=="number"&&Number.isFinite(m)&&m>=u.min&&m<=p&&(!u.integer||Number.isInteger(m));o==="factors"?(!Array.isArray(d.values)||
!d.values.length||d.values.length>12||d.values.some(m=>!g(m))||new Set(d.values).size!==d.values.length)&&n.push(u.label+": 比較値は範囲内で重複しない数値を1～12個指定してください。"):
(!["uniform","triangular"].includes(d.distribution)||!g(d.min)||!g(d.max)||d.min>d.max||d.distribution==="triangular"&&(!g(d.mode)||d.mode<d.min||d.mode>d.max))&&n.push(u.label+": \
分布の範囲・最頻値が不正です。")}}let r=(t.groupId?t.counts?.length??0:1)*(Array.isArray(t.factors)?t.factors.reduce((o,a)=>o*(a?.values?.length??0),1):1);return r>24&&
n.push("比較値の組合せは最大24条件にしてください。"),!["sensitivity","plans"].includes(t.mode)&&r*t.trials>1e4&&n.push("条件数×試行数は10000以下にしてください。"),
n}var ln=32;function jt(t){let e=t.mission?[{id:"mission.rate",label:"ミッションの成立率",kind:"rate"},{id:"mission.time",label:"ミッションの成立時刻",kind:"time"}]:
[];for(let n of t.measurements??[])for(let i of["rate","time","duration"])e.push({id:"point."+n.id+"."+i,label:n.name+" · "+{rate:"到達率",time:"成立時刻",duration:"起点からの所要\
時間"}[i],kind:i,measurementId:n.id});return e}function pn(t){let e=new Set((t.analysis?.uncertainties??[]).map(pe));return kt(t).filter(n=>{if(n.target==="scenario"||e.has(pe(n))||
n.target.startsWith("unit:")&&t.units.find(i=>i.id===n.target.slice(5))?.enabled===!1||n.target.startsWith("group:")&&t.groups.find(i=>i.id===n.target.slice(6))?.enabled===!1)return!1;
try{return Number.isFinite(Je(t,n))}catch{return!1}})}function Tt(t){let e=t.analysis,n=e?.sensitivity,i=[];if(e?.mode!==void 0&&!["comparison","sensitivity","plans"].includes(e.mode)&&i.push("分析の種類はcomparison・sensitivity・plansです。"),
n===void 0)return i;if(!n||typeof n!="object"||Array.isArray(n))return[...i,"感度分析の設定はオブジェクトにしてください。"];if(jt(t).some(a=>a.id===n.metric)||
i.push("感度分析の評価指標を選択してください。"),!Array.isArray(n.candidates)||n.candidates.length>ln)return[...i,"感度分析は最大32項目です。"];let r=new Set(
pn(t).map(pe)),o=new Set;for(let a of n.candidates){let s=ze(a?.parameter),d=pe(a??{});if(!s||!r.has(d)){i.push("感度分析の対象・性能が不在、無効、または試行のばらつきと重複しています。");
continue}o.has(d)&&i.push("感度分析の項目は重複できません。"),o.add(d);let u=l=>Number.isFinite(l)&&l>=s.min&&l<=s.max&&(!s.integer||Number.isInteger(l));(!u(a.low)||
!u(a.high)||a.low>a.high)&&i.push(s.label+": 小さい値・大きい値を範囲内で指定してください。")}return i}var qe=["units","groups","behaviors","behaviorAssignments","routes","destinations"],Ot=t=>JSON.parse(JSON.stringify(t));function Nt(t,e){return{...Ot(t),...Ot(e.operation)}}function Pt(t){let e=t.analysis?.plans;if(e===void 0)return[];if(!e||typeof e!="object"||Array.isArray(e))return["運用案の設定はオブジェクト\
にしてください。"];let n=[];if(typeof e.metric!="string"&&n.push("運用案の評価指標を選択してください。"),!Array.isArray(e.items)||e.items.length>8)return[
...n,"運用案は最大8件です。"];let i=new Set;for(let o of e.items)(!o||typeof o.id!="string"||!/^[A-Za-z0-9_-]{1,80}$/.test(o.id)||i.has(o.id))&&n.push("運用案IDは重複しない英数字・_・-\
にしてください。"),i.add(o?.id),(typeof o?.name!="string"||!o.name.trim()||o.name.length>120)&&n.push("運用案名は1～120文字にしてください。"),(!o?.operation||
typeof o.operation!="object"||Array.isArray(o.operation)||Object.keys(o.operation).some(a=>!qe.includes(a))||qe.some(a=>!Array.isArray(o.operation[a])))&&n.push("運用案には配置・経路・挙動の配列を保\
存してください。");let r=e.editor;if(r!==void 0){let o=a=>typeof a=="string"&&(a===""||/^[A-Za-z0-9_-]{1,80}$/.test(a));if(!r||typeof r!="object"||Array.isArray(r)||!o(r.activeId)||
!Array.isArray(r.drafts)||r.drafts.length>16)n.push("運用案の編集保持は有効な案IDと最大16件の配列にしてください。");else{let a=new Set;for(let s of r.drafts)
(!s||!o(s.id)||a.has(s.id)||typeof s.name!="string"||!s.name.trim()||s.name.length>120)&&n.push("保持する運用案のID・名前が不正です。"),a.add(s?.id),(!s?.operation||
typeof s.operation!="object"||Array.isArray(s.operation)||Object.keys(s.operation).some(d=>!qe.includes(d))||qe.some(d=>!Array.isArray(s.operation[d])))&&n.push("編集中の運用案には配置・経路・挙動の\
配列を保持してください。");r.activeId&&!i.has(r.activeId)&&!a.has(r.activeId)&&n.push("編集中の運用案がありません。")}}return e.items.length&&!i.has(e.baselineId)&&
n.push("基準となる運用案を選択してください。"),n}var Ct=t=>typeof t=="number"&&Number.isFinite(t);function Ft(t,e="unit",n=new Set){let i=[],r=t.communication,o=t.behavior;if(r!==void 0)if(!r||typeof r!="object"||Array.isArray(r))
i.push(e+": communicationはオブジェクトにしてください。");else{(typeof r.enabled!="boolean"||typeof r.terrainLOS!="boolean")&&i.push(e+": 通信のenabled・terrainLOSはboole\
anにしてください。");for(let[a,s,d]of[["range",.001,1e5],["delay",0,86400],["probability",0,1]])(!Ct(r[a])||r[a]<s||r[a]>d)&&i.push(e+": communication."+a+"は"+s+"～"+d+"\
にしてください。")}if(o!==void 0){if(!o||typeof o!="object"||Array.isArray(o))return[...i,e+": behaviorはオブジェクトにしてください。"];if(typeof o.hold!="bo\
olean"&&i.push(e+": behavior.holdはbooleanにしてください。"),(!Ct(o.preparation)||o.preparation<0||o.preparation>86400)&&i.push(e+": behavior.preparationは0～86400秒にしてください。"),
!Array.isArray(o.rules)||o.rules.length>16)i.push(e+": 行動ルールは最大16件にしてください。");else{let a=new Set;for(let s of o.rules){if(!s||typeof s!="object"){i.
push(e+": ルールはオブジェクトにしてください。");continue}(typeof s.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(s.id)||a.has(s.id))&&i.push(e+": ルールidは重複しない英数字・_・\
-にしてください。"),a.add(s.id),(!["detected","received","arrived"].includes(s.when)||!["send","depart"].includes(s.action)||!["any","waiting"].includes(s.state)||typeof s.
once!="boolean")&&i.push(e+": ルールの条件・動作・実行回数が不正です。"),s.action==="send"&&!n.has(s.receiverId)&&i.push(e+": 送信先の単体ユニットが見つかりません: "+
s.receiverId),s.action==="depart"&&!o.hold&&i.push(e+": 出発ルールには「指令まで待機」を設定してください。")}}}return i}var fn=["ground","surface","subsurface","air"],_t=["friendly","hostile","neutral"],fe=t=>typeof t=="number"&&Number.isFinite(t);function Dt(t,e="unit"){let n=[],i=t.sensor;if(t.detectability!==
void 0&&(!fe(t.detectability)||t.detectability<0||t.detectability>10)&&n.push(e+": detectabilityは0～10にしてください。"),i!==void 0){if(!i||typeof i!="object"||Array.isArray(
i))return[...n,e+": sensorはオブジェクトにしてください。"];typeof i.enabled!="boolean"&&n.push(e+": sensor.enabledはbooleanにしてください。"),(!fe(i.range)||
i.range<=0||i.range>1e5)&&n.push(e+": sensor.rangeは0より大きく100000m以下にしてください。"),(!fe(i.probabilityPerMinute)||i.probabilityPerMinute<0||i.probabilityPerMinute>
1)&&n.push(e+": sensor.probabilityPerMinuteは0～1にしてください。"),(!Array.isArray(i.domains)||!i.domains.length||i.domains.some(r=>!fn.includes(r)))&&n.push(e+": sensor\
.domainsには対象領域を1つ以上指定してください。"),typeof i.terrainLOS!="boolean"&&n.push(e+": sensor.terrainLOSはbooleanにしてください。"),i.mountHeight!==
void 0&&(!fe(i.mountHeight)||i.mountHeight<0||i.mountHeight>1e3)&&n.push(e+": sensor.mountHeightは0～1000mにしてください。")}return n}function Rt(t,e){if(t===void 0)return[];
let n=[];return!t||typeof t!="object"||Array.isArray(t)?["missionはオブジェクトにしてください。"]:(["detect","arrive","state"].includes(t.type)||n.push("mission.type\
はdetect・arrive・stateにしてください。"),t.type==="arrive"&&(!Array.isArray(t.responderIds)||!t.responderIds.length||t.responderIds.length>2e3||t.responderIds.some(i=>typeof i!=
"string")||new Set(t.responderIds).size!==t.responderIds.length)&&n.push("mission.responderIdsに到着を評価する単体ユニットIDを指定してください。"),t.type!==
"state"&&(!_t.includes(t.observerFaction)||!_t.includes(t.targetFaction)||t.observerFaction===t.targetFaction)&&n.push("観測側と対象側には異なる陣営を指定してください。"),
(t.type==="state"?["any","all","count"]:["any","all"]).includes(t.join)||n.push("mission.joinはany・all（状態計測ではcountも可）にしてください。"),t.type==="sta\
te"&&(typeof t.assignmentId!="string"||typeof t.nodeId!="string")&&n.push("計測するタスクと状態を選択してください。"),t.join==="count"&&(!Number.isInteger(t.requiredCount)||
t.requiredCount<1||t.requiredCount>2e3)&&n.push("到達を必要とする担当数は1～2000です。"),(!fe(t.deadline)||t.deadline<=0||t.deadline>e)&&n.push("mission.deadlineは0よ\
り大きく終了時刻以下にしてください。"),t.targetIds!==void 0&&(!Array.isArray(t.targetIds)||!t.targetIds.length||t.targetIds.length>2e3||t.targetIds.some(i=>typeof i!=
"string")||new Set(t.targetIds).size!==t.targetIds.length)&&n.push("mission.targetIdsは重複しない対象IDの配列にしてください。"),n)}function Lt(t,e){if(t===void 0)
return[];if(!t||typeof t!="object"||Array.isArray(t))return["analysisはオブジェクトにしてください。"];let n=[];return t.groupId!==void 0&&typeof t.groupId!="string"&&
n.push("analysis.groupIdは文字列にしてください。"),t.groupId&&(!Array.isArray(t.counts)||!t.counts.length||t.counts.length>12||t.counts.some(i=>!Number.isInteger(i)||i<
0||i>2e3)||new Set(t.counts).size!==t.counts.length)&&n.push("analysis.countsは重複しない0～2000の整数（最大12条件）にしてください。"),(!Number.isInteger(t.
trials)||t.trials<1||t.trials>2e3)&&n.push("analysis.trialsは1～2000にしてください。"),(!fe(t.step)||t.step<.1||t.step>300||Math.ceil(e/t.step)>1e5)&&n.push("判定間隔は0.1～300\
秒、シナリオ全体で10万区間以内にしてください。"),(!fe(t.requiredRate)||t.requiredRate<0||t.requiredRate>1)&&n.push("analysis.requiredRateは0～1にしてください。"),
n.push(...zt(t,e)),n}var ot=2e3,hn=["ground","surface","subsurface","air"];var He=t=>JSON.parse(JSON.stringify(t)),ne=t=>typeof t=="number"&&Number.isFinite(t),Bt=t=>t&&["x","y","z"].every(e=>ne(t[e]));function Te(t){let e=[];if(!t||typeof t!="object")throw new Error(
"シナリオはオブジェクトで指定してください。");[1,2,3].includes(t.version)||e.push("versionは1・2・3にしてください。"),t.unitsSystem!=="SI"&&e.push("\
unitsSystemはSI（m・s）にしてください。"),(typeof t.title!="string"||!t.title.trim()||t.title.length>160)&&e.push("titleは1～160文字で指定してください。"),
(!ne(t.duration)||t.duration<=0||t.duration>86400)&&e.push("durationは0より大きく86400秒以下にしてください。");let n=t.terrain;!n||!Number.isInteger(n.columns)||!Number.
isInteger(n.rows)||n.columns<2||n.rows<2||n.columns>513||n.rows>513?e.push("terrainのcolumns・rowsは2～513の整数にしてください。"):((!ne(n.spacing)||n.spacing<1||n.spacing>
1e4)&&e.push("terrain.spacingは1～10000mにしてください。"),n.spacingY!==void 0&&(!ne(n.spacingY)||n.spacingY<1||n.spacingY>1e4)&&e.push("terrain.spacingYは1～10000mにしてください。"),
(!n.origin||!ne(n.origin.x)||!ne(n.origin.y))&&e.push("terrain.originのx・yが必要です。"),(!Array.isArray(n.elevations)||n.elevations.length!==n.columns*n.rows||n.elevations.
some(o=>!ne(o)||o<-12e3||o>1e4))&&e.push("terrain.elevationsは格子数と同じ長さの標高配列（-12000～10000m）にしてください。"),ne(n.seaLevel)||e.push("terrai\
n.seaLevelが必要です。")),t.seed!==void 0&&(typeof t.seed!="string"||t.seed.length>100)&&e.push("seedは100文字以下の文字列にしてください。"),t.trial!==void 0&&
(!Number.isInteger(t.trial)||t.trial<0||t.trial>1e9)&&e.push("trialは0～1000000000の整数にしてください。");let i=t.groups??[],r=new Set;if(!Array.isArray(i)||i.length>
100)e.push("groupsは最大100件の配列にしてください。");else for(let o of i){if(!o||typeof o!="object"){e.push("groupはオブジェクトにしてください。");continue}
o.enabled!==void 0&&typeof o.enabled!="boolean"&&e.push("group.enabledはbooleanにしてください。"),(typeof o.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(o.id)||r.has(o.id))&&
e.push("group.idは重複しない英数字・_・-（50文字以下）にしてください。"),r.add(o.id),(typeof o.name!="string"||!o.name.trim()||o.name.length>100)&&e.push("\
group.nameは1～100文字にしてください。"),(!Number.isInteger(o.count)||o.count<1||o.count>ot)&&e.push("group.countは1～2000にしてください。"),o.loopStartMode!==
void 0&&!["template","even","random"].includes(o.loopStartMode)&&e.push("group.loopStartModeはtemplate、even、randomにしてください。"),["grid","random"].includes(o.placement)||
e.push("group.placementはgridまたはrandomにしてください。");for(let a of["width","height"])(!ne(o[a])||o[a]<0||o[a]>1e5)&&e.push("group."+a+"は0～100000mにしてください。")}
if(!Array.isArray(t.units)||t.units.length>ot)e.push("unitsは最大2000件の配列にしてください。");else{let o=new Set,a=new Set(t.units.map(s=>s?.id));[...t.units,...Array.
isArray(i)?i.map(s=>s?.template):[]].forEach((s,d)=>{let u="units["+d+"]";if(!s||typeof s!="object"){e.push(u+": オブジェクトが必要です。");return}if((typeof s.id!="str\
ing"||!/^[a-zA-Z0-9_-]{1,80}$/.test(s.id)||d<t.units.length&&o.has(s.id))&&e.push(u+": idは重複しない英数字・_・-にしてください。"),d<t.units.length&&o.add(s.id),
(typeof s.name!="string"||!s.name.trim()||s.name.length>120)&&e.push(u+": nameは1～120文字にしてください。"),e.push(...Dt(s,u),...Ft(s,u,a)),t.version===3&&s.behavior&&
e.push(u+": 旧行動ルールは読み込み時にノードへ変換してください。"),s.navigation!==void 0&&e.push(...ye(s.navigation)),hn.includes(s.domain)||e.push(u+": d\
omainが不正です。"),["friendly","hostile","neutral"].includes(s.faction)||e.push(u+": factionが不正です。"),s.enabled!==void 0&&typeof s.enabled!="boolean"&&e.push(u+":\
 enabledはbooleanにしてください。"),typeof s.manned!="boolean"&&e.push(u+": mannedはbooleanにしてください。"),(!ne(s.speed)||s.speed<0||s.speed>1500)&&e.push(u+":\
 speedは0～1500m/sにしてください。"),Bt(s.initial)||e.push(u+": initialのx,y,zが必要です。"),["once","loop","pingpong"].includes(s.routeMode)||e.push(u+": routeMod\
eが不正です。"),s.groupId!==void 0&&d<t.units.length&&e.push(u+": groupIdは生成ユニット専用です。"),s.motion!==void 0)if(!s.motion||typeof s.motion!="object"||Array.
isArray(s.motion))e.push(u+": motionはオブジェクトにしてください。");else for(let[l,p,g]of[["horizontal",0,1e4],["vertical",0,3e3],["commonHorizontal",0,1e4],["scale",
10,1e5],["startDelay",0,86400],["speedVariation",0,1],["loopStart",0,1]])s.motion[l]!==void 0&&(!ne(s.motion[l])||s.motion[l]<p||s.motion[l]>g)&&e.push(u+": motion."+l+"は"+p+"～"+
g+"にしてください。");(!Array.isArray(s.route)||s.route.length>500||s.route.some(l=>!Bt(l)))&&e.push(u+": routeは最大500件、各点にx,y,zが必要です。")})}if(Array.
isArray(t.units)&&Array.isArray(i)&&!e.length){let o=t.units.length+i.reduce((a,s)=>a+s.count,0);if(o>ot)e.push("単体と群を合わせて最大2000ユニットにしてください。");else{
let a=rt(t);new Set(a.map(s=>s.id)).size!==o&&e.push("生成ユニットのidが単体ユニットと重複しています。")}}if(e.push(...Rt(t.mission,t.duration),...Lt(t.analysis,
t.duration),...tt(t),...gt(t),...yt(t)),t.mission?.type==="arrive"&&t.mission.responderIds?.some(o=>!t.units?.some(a=>a.id===o))&&e.push("到着評価の対象となる単体ユニットが見つかりません。"),
t.version===3&&!e.length)for(let o of[...t.analysis?.factors??[],...t.analysis?.uncertainties??[]])try{Je(t,o)}catch(a){e.push(a.message)}if(e.length||e.push(...Tt(t)),e.length||e.
push(...Pt(t)),!e.length&&t.analysis?.plans)for(let o of[...t.analysis.plans.items,...t.analysis.plans.editor?.drafts??[]])try{let a=Nt(t,o);delete a.analysis,delete a.mission,delete a.
measurements,Te(a)}catch(a){e.push("運用案「"+o.name+"」: "+a.message)}if(e.length)throw new Error(e.slice(0,30).join(`
`));return It(St(He(t)))}var $e=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),je=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function mn(t,e){let n=[0];for(let d=1;d<
t.length;d++)n.push(n.at(-1)+$e(t[d-1],t[d]));let i=n.at(-1);if(i===0)return t;let r=i*e,o=n.findIndex((d,u)=>u>0&&d>r),a=o<0?t.length-1:o,s=je(t[a-1],t[a],(r-n[a-1])/(n[a]-n[a-1]));
return[s,...t.slice(a,-1),...t.slice(0,a),{...s}]}var ve=class{constructor(e,{deferPaths:n=!1}={}){let i=Te(e);this.source=i,this.scenario={...i,units:rt(i)},this.nodeCount=0,this.
terrain=new Q(this.scenario.terrain),this.paths=n?new Map:new Map(this.scenario.units.filter(r=>r.enabled!==!1).map(r=>[r.id,this.compile(r)]))}compile(e){let n=this.terrain.project(
e.initial,e.domain),i=[{...n.point,d:0}],r=e.motion??{},o=de(this.scenario,e.id,"motion"),a=(r.startDelay??0)*G(o+"|delay"),s=e.speed*(1+(G(o+"|speed")*2-1)*(r.speedVariation??0)),
d={delay:a,actualSpeed:s},u=e.routeMode==="loop"?(r.loopStart??0)%1:0,l=u>0&&e.route.length>0;if(n.error&&!l)return{...d,nodes:i,length:0,error:n.error,errorAt:"初期位置",periodic:!1};
let p=[n.point,...e.route.map(b=>this.terrain.project(b,e.domain).point)];e.route.length&&e.routeMode==="loop"&&p.push(n.point);let g=p.slice(1).reduce((b,x,T)=>b+$e(p[T],x),0);if(g>
0&&(r.horizontal??0)+(r.vertical??0)+(r.commonHorizontal??0)>0){let b=[n.point],x=r.scale??2e3,T=Math.min(125,this.terrain.cellSize/4,x/8),I=0;for(let S=1;S<p.length;S++){let N=p[S-
1],R=p[S],f=$e(N,R),w=Math.max(1,Math.ceil(f/T));if(w>2e4)throw new Error("航跡生成の区間が長すぎます。");for(let D=1;D<=w;D++){let V=I+f*D/w,W=je(N,R,D/w),J=Math.min(
1,V/x,(g-V)/x),q=Math.max(0,J),H=q*q*(3-2*q),$=it(o,V,x),h=it(de(this.scenario,e.groupId??e.id,"common-motion"),V,x);if(W.x+=H*($[0]*(r.horizontal??0)+h[0]*(r.commonHorizontal??0)),
W.y+=H*($[1]*(r.horizontal??0)+h[1]*(r.commonHorizontal??0)),["subsurface","air"].includes(e.domain)&&(W.z+=H*$[2]*(r.vertical??0)),b.push(W),b.length>1e5)throw new Error("航跡生成の点数が\
多すぎます。経路を短くするか変動間隔を大きくしてください。")}I+=f}p=b}if(l){let b=[p[0]],x=Math.min(125,this.terrain.cellSize/4);for(let I=1;I<p.length;I++){
let S=p[I-1],N=p[I],R=Math.max(1,Math.ceil(Math.hypot(N.x-S.x,N.y-S.y)/x));if(R>2e4)return{...d,nodes:i,length:0,error:"経路区間が長すぎます",errorAt:"初期位置",periodic:!1};
for(let f=1;f<=R;f++)if(b.push(this.terrain.project(je(S,N,f/R),e.domain).point),b.length>2000001)throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}
p=mn(b,u);let T=this.terrain.project(p[0],e.domain);if(i=[{...T.point,d:0}],T.error)return{...d,nodes:i,length:0,error:T.error,errorAt:"初期位置",periodic:!1}}let m=p.slice();e.
route.length&&e.routeMode==="pingpong"&&p.push(...m.slice(0,-1).reverse());let v=Math.min(125,this.terrain.cellSize/4);for(let b=1;b<p.length;b++){let x=p[b-1],T=p[b],I=Math.max(1,
Math.ceil(Math.hypot(T.x-x.x,T.y-x.y)/v));if(I>2e4)return{...d,nodes:i,length:i.at(-1).d,error:"経路区間が長すぎます",errorAt:"区間 "+b,periodic:!1};for(let S=1;S<=I;S++){
let N=this.terrain.project(je(x,T,S/I),e.domain);if(N.error)return{...d,nodes:i,length:i.at(-1).d,error:N.error,errorAt:"区間 "+b,periodic:!1};let R=i.at(-1),f=R.d+$e(R,N.point);
if(f>R.d&&(i.push({...N.point,d:f}),++this.nodeCount>2e6))throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}}return{...d,nodes:i,length:i.
at(-1).d,error:null,errorAt:null,periodic:e.routeMode!=="once"}}evaluate(e){let n=Math.min(this.scenario.duration,Math.max(0,Number(e)||0));return{time:n,units:this.scenario.units.
map(i=>this.evaluateUnit(i,n))}}evaluateUnit(e,n,i=!0){if(e.enabled===!1)return{id:e.id,position:{...e.initial},status:"disabled",heading:0,distance:0,routeDistance:0,error:null,errorAt:null,
actualSpeed:0,startDelay:0,eta:null};let r=Math.max(0,Number(n)||0),o=i?Math.min(this.scenario.duration,r):r,a=this.paths.get(e.id),s=a.actualSpeed??e.speed,d=a.delay??0,u=s*Math.max(
0,o-d),l=!a.periodic&&s>0&&o>=d+a.length/s?Math.max(u,a.length):u,p=a.periodic&&a.length>0?l%a.length:Math.min(l,a.length),g=0,m=a.nodes.length-1;for(;g<m;){let I=Math.ceil((g+m)/2);
a.nodes[I].d<=p?g=I:m=I-1}let v=a.nodes[g],b=a.nodes[Math.min(g+1,a.nodes.length-1)],x=je(v,b,b.d>v.d?(p-v.d)/(b.d-v.d):0);e.domain==="ground"&&(x.z=this.terrain.height(x.x,x.y)??x.
z);let T=a.length===0?"idle":"moving";return a.error&&l>=a.length?T="blocked":!a.periodic&&a.length>0&&l>=a.length?T="arrived":s===0?T="idle":o<d&&(T="waiting"),{id:e.id,position:x,
status:T,heading:Math.atan2(b.x-v.x,b.y-v.y),distance:Math.min(l,a.periodic?l:a.length),routeDistance:a.length,error:a.error,errorAt:a.errorAt,actualSpeed:s,startDelay:Number.isFinite(
d)?d:null,eta:s>0&&Number.isFinite(d)?d+a.length/s:null}}routePoints(e){return this.paths.get(e)?.nodes||[]}};function Ut(t){let e=Te(t);if(e.version===3)return e;e.version=3,e.behaviors??=[],e.behaviorAssignments??=[];let n=e.recording?.step??e.analysis?.step??10;e.recording??={step:n,interval:n},
e.analysis&&(e.analysis={...Et(e.analysis),step:n});for(let[i,r]of[...e.units.map(o=>["unit:"+o.id,o]),...(e.groups??[]).map(o=>["group:"+o.id,o.template])]){let o=r.behavior;if(o){
if(o.hold||o.rules.length){if(e.behaviorAssignments.some(p=>p.targets.includes(i)))throw Error("旧ルールとタスクが重複しています: "+i);let a=new Set;for(let p of o.
rules){if(a.has(p.when)||p.state!=="any"&&!(o.hold&&p.when==="received"))throw Error("自動変換できない旧ルールです。同じ条件の複数動作・状態条件はノードで再設計してください: "+
i);a.add(p.when)}let s="import-"+i.replace(":","-");if(e.behaviors.some(p=>p.id===s)||e.behaviorAssignments.some(p=>p.id===s))throw Error("変換先IDが重複しています: "+s);
let d=o.hold?"signal":"follow",u=[{id:d,kind:o.hold?"signal":"follow",x:320,y:70}],l=[];o.hold&&u.push({id:"follow",kind:"follow",x:1080,y:70}),o.rules.forEach((p,g)=>{let m=p.when===
"received"&&o.hold?"signal":"follow";p.action==="depart"?(u.push({id:p.id,kind:"wait",parameter:"preparation",seconds:o.preparation,x:680,y:70+g*150}),l.push({from:m,to:p.id,when:p.
when,once:p.once},{from:p.id,to:"follow",when:"elapsed"})):(u.push({id:p.id,kind:"report",receiverId:p.receiverId,x:680,y:70+g*150}),l.push({from:m,to:p.id,when:p.when,once:p.once},
{from:p.id,to:d,when:"sent",resume:!0},{from:p.id,to:d,when:"sendFailed",resume:!0}))}),e.behaviors.push({id:s,name:r.name+"の挙動",initial:d,triggers:[],nodes:u,edges:l}),e.behaviorAssignments.
push({id:s,name:r.name+"のタスク",behaviorId:s,targets:[i],spacing:"none",preparation:o.preparation});for(let p of[e.analysis?.factors,e.analysis?.uncertainties])for(let g of p??
[])g.target===i&&g.parameter==="behavior.preparation"&&(g.target="assignment:"+s)}delete r.behavior}}return Te(e)}function st(t,e,n){let i=Math.hypot(n.x-e.x,n.y-e.y),r=Math.max(1,Math.ceil(i/Math.min(125,t.cellSize/4)));for(let o=0;o<=r;o++){let a=o/r,s=e.x+(n.x-e.x)*a,d=e.y+(n.y-e.y)*a,u=e.z+
(n.z-e.z)*a,l=t.height(s,d);if(l===null||u<l-1e-6)return!1}return!0}function Yt(t,e,n,i){if(i<=0||n<=0||e>=t.range||t.probabilityPerMinute<=0)return 0;if(t.probabilityPerMinute>=1)
return 1;let r=-Math.log1p(-t.probabilityPerMinute)/60;return-Math.expm1(-r*i*n*(1-e/t.range)**2)}var at=(t,e)=>({...t,z:t.z+(e.sensor?.mountHeight??(e.domain==="ground"?2:0))}),gn=(t,e,n)=>Math.
floor(t/n)+","+Math.floor(e/n);function Jt(t,e){let n=new Map;for(let i of t){let r=gn(i.position.x,i.position.y,e);n.has(r)||n.set(r,[]),n.get(r).push(i)}return n}function*qt(t,e,n){
let i=Math.floor(e.x/n),r=Math.floor(e.y/n);for(let o=-1;o<=1;o++)for(let a=-1;a<=1;a++)for(let s of t.get(i+a+","+(r+o))??[])yield s}var $t=256*1048576,dt=t=>{let e=new Uint8Array(t.buffer,t.byteOffset,t.byteLength),n="";for(let i=0;i<e.length;i+=8192)n+=String.fromCharCode(...e.subarray(i,i+8192));return btoa(n)},
ut=(t,e,n)=>{if(typeof t!="string"||t.length>Math.ceil(n*e.BYTES_PER_ELEMENT/3)*4+4)throw Error("記録配列の長さが不正です。");let i=atob(t);if(i.length!==n*e.BYTES_PER_ELEMENT)
throw Error("記録配列の長さが不正です。");let r=new Uint8Array(i.length);for(let o=0;o<i.length;o++)r[o]=i.charCodeAt(o);return new e(r.buffer)};function ct(t){if(!t.frames)
throw Error("計算・記録を先に実行してください。");let e={type:"SimSim-recording",version:2,model:Ge,source:He(t.source),unitIds:t.states.map(n=>n.unit.id),nodeNames:t.
nodeNames,result:t.result,frames:t.frames.map(n=>({time:n.time,values:dt(n.values),nodes:dt(n.nodes),status:dt(n.status)}))};if(new TextEncoder().encode(JSON.stringify(e)).byteLength>
$t)throw Error("保存形式で256MiBを超えます。期間・個数を減らしてください。");return e}var Oe=t=>t&&["x","y","z"].every(e=>Number.isFinite(t[e])),yn=new Set(
["detected","sent","sendFailed","received","arrived","elapsed","nodeChanged","departed","preparing","initialized","triggered","near"]);function lt(t){if(t?.type!=="SimSim-recording"||
t.version!==2||t.model!==Ge||!Array.isArray(t.frames)||!t.frames.length)throw Error("対応していない記録モデルです。旧版の記録は元の版で再生してください。");
let e=new he(t.source),n=e.states.length;if(t.source.version!==3||JSON.stringify(t.unitIds)!==JSON.stringify(e.states.map(o=>o.unit.id))||JSON.stringify(t.nodeNames)!==JSON.stringify(
e.nodeNames))throw Error("記録対象・ノード・シナリオ版が一致しません。");if(t.frames.length*(n*23+8)>pt||t.frames.length>100001)throw Error("再生記録が上限を超えています。");
let i=-1;if(e.frames=t.frames.map((o,a)=>{if(!Number.isFinite(o.time)||o.time<=i||o.time>e.source.duration||a===0&&o.time!==0)throw Error("記録時刻が不正です。");i=o.time;
let s=ut(o.values,Float32Array,n*5),d=ut(o.nodes,Uint16Array,n),u=ut(o.status,Uint8Array,n);if(s.some(l=>!Number.isFinite(l))||u.some(l=>l>=be.length))throw Error("記録値が不正です。");
return d.forEach((l,p)=>{let g=e.states[p],m=e.nodeNames[l-1];if(g.graph&&l===0&&![be.indexOf("standby"),be.indexOf("blocked")].includes(u[p]))throw Error("起動前の記録状態が不正です。");
if(g.graph?l!==0&&(!m||!g.graph.nodes.some(v=>g.graph.id+":"+v.id===m)):l!==0)throw Error("記録ノードが担当の挙動と一致しません。")}),{time:o.time,values:s,nodes:d,
status:u}}),i!==e.source.duration)throw Error("終了時刻までの記録がありません。");let r=t.result;if(!r||typeof r.success!="boolean"||!Array.isArray(r.events)||!Array.
isArray(r.actionEvents)||r.events.length+r.actionEvents.length>2e5||r.successTime!==null&&(!Number.isFinite(r.successTime)||r.successTime<0||r.successTime>e.source.duration)||r.success!==
(r.successTime!==null))throw Error("記録の評価・イベントが不正です。");for(let[o,a]of[["targetCount",0],["detectedCount",0],["responderCount",0],["reachedCount",0],
["invalidUnits",0],["constrainedPaths",0]])if(!Number.isInteger(r[o])||r[o]<a||r[o]>2e3)throw Error("記録の件数が不正です。");for(let o of[r.events,r.actionEvents]){let a=-1;
for(let s of o){if(!s||!yn.has(s.type)||!Number.isFinite(s.time)||s.time<a||s.time<0||s.time>e.source.duration||!e.byId.has(s.unitId))throw Error("イベントの種類・参照・時刻が不正です。");
a=s.time;for(let u of["targetId","receiverId","senderId","observerId"])if(s[u]!==void 0&&!e.byId.has(s[u]))throw Error("イベントの参照先がありません。");for(let u of[
"targetPosition","sourcePosition","receiverPosition","observerPosition"])if(s[u]!==void 0&&!Oe(s[u]))throw Error("イベントの位置が不正です。");if(s.type==="detected"&&
(!s.targetId||!Oe(s.targetPosition)||!Oe(s.observerPosition)))throw Error("探知情報が不正です。");if(s.type==="received"&&(!s.senderId||!Oe(s.sourcePosition)||!Oe(s.receiverPosition)))
throw Error("受信情報が不正です。");let d=e.byId.get(s.unitId);if(s.type==="near"&&(!e.source.destinations?.some(u=>u.id===s.destinationId)||!Number.isFinite(s.distance)||
s.distance<0||!["horizontal","absolute"].includes(s.distanceMode)))throw Error("接近イベントの記録が不正です。");if(s.type==="initialized"&&(s.time!==0||d.graph?.initial!==
s.nodeId))throw Error("初期状態の記録が不正です。");if(s.type==="triggered"&&!d.graph?.triggers.some(u=>u.id===s.triggerId&&u.event===s.event&&u.to===s.nodeId)&&!(s.event===
"scenarioStart"&&s.time===0&&d.graph?.initial===s.nodeId&&t.source.behaviors?.find(u=>u.id===d.graph.id)?.triggers?.some(u=>u.id===s.triggerId&&u.event==="scenarioStart"&&u.to===s.
nodeId)))throw Error("起動イベントの条件が不正です。");if(s.nodeId!==void 0&&!d.graph?.nodes.some(u=>u.id===s.nodeId))throw Error("イベントのノードが不正です。")}}
if(e.source.mission?.type==="state"){De(e.source,r);let o=new ue(e.source.mission,Ae(e.source)).update(r.actionEvents);if(JSON.stringify(o.stateEntries)!==JSON.stringify(r.stateEntries)||
o.successTime!==r.successTime)throw Error("状態の初回到達記録がイベント履歴と一致しません。")}if(e.source.measurements?.length&&(vt(e.source,r.measurements),
JSON.stringify(Re(e.source,r.actionEvents))!==JSON.stringify(r.measurements)))throw Error("計測点の到達記録がイベント履歴と一致しません。");e.result=He(r);for(let o of[
e.result.events,e.result.actionEvents])for(let a of o)a.type==="triggered"&&a.event==="scenarioStart"&&(a.type="initialized",delete a.event,delete a.triggerId);return e}var Ge="trigger-behavior-v3",be=["idle","moving","arrived","blocked","waiting","standby","preparing"],pt=128*1048576,oe=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),Ne=(t,e)=>(t%e+e)%
e,Ce=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function Pe(t,e){let n=Math.min(t.length,Math.max(0,e)),i=t.nodes,r=0,o=i.length-1;for(;r<o;){let d=Math.ceil(
(r+o)/2);i[d].d<=n?r=d:o=d-1}let a=i[r],s=i[Math.min(r+1,i.length-1)];return{point:Ce(a,s,s.d>a.d?(n-a.d)/(s.d-a.d):0),segment:r,heading:Math.atan2(s.x-a.x,s.y-a.y)}}function Ht(t,e){
let n={point:t.nodes[0],along:0,distance:1/0};for(let i=1;i<t.nodes.length;i++){let r=t.nodes[i-1],o=t.nodes[i],a=o.x-r.x,s=o.y-r.y,d=o.z-r.z,u=a*a+s*s+d*d,l=u?Math.max(0,Math.min(
1,((e.x-r.x)*a+(e.y-r.y)*s+(e.z-r.z)*d)/u)):0,p=Ce(r,o,l),g=oe(e,p);g<n.distance&&(n={point:p,along:r.d+(o.d-r.d)*l,distance:g})}return n}var he=class extends ve{constructor(e){super(
Ut(e),{deferPaths:!0}),this.frames=null,this.result=null,this.computeCount=0,this.nodeNames=[],this.assignments=this.source.behaviorAssignments,this.initialEvents=[];let n=new Map(
this.source.behaviors.map(i=>[i.id,i]));this.states=[],this.byId=new Map;for(let i of this.scenario.units.filter(r=>r.enabled!==!1).sort((r,o)=>r.id.localeCompare(o.id))){let r=this.
assignments.find(g=>g.targets.includes("unit:"+i.id)||i.groupId&&g.targets.includes("group:"+i.groupId)),o=r?Ee(n.get(r.behaviorId),r):null,a=o?.nodes.find(g=>g.id===o.initial),s=Ue(
this.source,r,a,i),u=r?.route?.length>=2||a?.routeId?{...i,initial:s.points[0],route:s.points.slice(1),routeMode:a?.kind==="patrol"?"loop":s.mode,motion:{...i.motion,loopStart:0}}:
i,l=this.compile(u);this.paths.set(i.id,l);let p={unit:i,assignment:r,graph:o,path:l,basePath:l,pathCache:new Map,routeContexts:new Map,nearInside:new Map,node:null,nodeTime:0,position:{
...l.nodes[0]},heading:0,status:"idle",distance:0,progress:0,segment:-1,error:l.errorAt==="初期位置"?l.error:null,fired:new Set,triggerFired:new Set,triggerTimes:new Map,activated:!1,
observation:null,latestObservation:null,receivedPosition:null,moveGoal:null,moveHeight:null,trace:[],routeStarted:null,routePaused:0};if(a?.joinMode==="nearest"){let g=this.terrain.
project(i.initial,i.domain);p.position=g.point,g.error&&(p.error=g.error)}this.states.push(p),this.byId.set(i.id,p);for(let g of o?.nodes??[])this.nodeNames.includes(o.id+":"+g.id)||
this.nodeNames.push(o.id+":"+g.id)}this.inactiveUnits=this.scenario.units.filter(i=>i.enabled===!1).map(i=>super.evaluateUnit(i,0));for(let i of this.assignments){let r=this.states.
filter(o=>o.assignment===i);r.forEach((o,a)=>{o.initialPhase=Ne((i.phase??0)+(i.spacing==="none"?o.unit.motion?.loopStart??0:a/r.length),1),o.status=o.error?"blocked":"standby",o.graph.
initial&&(o.activated=!0,this.enter(o,o.graph.initial,0,!0),this.initialEvents.push({type:"initialized",time:0,unitId:o.unit.id,nodeId:o.graph.initial}))})}for(let i of this.states)
i.graph||Object.assign(i,super.evaluateUnit(i.unit,0))}enter(e,n,i,r=!1,o=!1,a=null){let s=e.node;s?.kind==="follow"&&e.routeContexts.set(s.routeId??"default",{path:e.path,started:e.
routeStarted,travel:e.routeTravel??0,offset:e.routeOffset??0,paused:i,join:e.join}),e.node=e.graph.nodes.find(u=>u.id===n),s&&e.error&&(e.error=this.terrain.project(e.position,e.unit.
domain).error),e.moveHeight=e.position.z;let d=this.observedPosition(e,a);if(e.moveGoal=e.node.kind==="move"&&se(this.source,e.assignment,e.node)?.kind==="received"&&d?{...d}:null,
e.nodeTime=i,e.sent=!1,e.elapsed=!1,e.destinationArrived=!1,e.join=null,e.nearInside=new Map([...e.nearInside].filter(([u])=>u.startsWith("trigger:"))),["follow","patrol"].includes(
e.node.kind)){let u=Ue(this.source,e.assignment,e.node,e.unit),l=u.id+"|"+e.node.kind;if(r&&e.pathCache.set(l,e.path),!e.pathCache.has(l)){let p=!e.node.routeId;e.pathCache.set(l,this.
compile({...e.unit,initial:u.points[0],route:u.points.slice(1),routeMode:u.mode,motion:{...e.unit.motion,...p?{}:{loopStart:0}}}))}e.path=e.pathCache.get(l),this.paths.set(e.unit.id,
e.path)}if(e.error){e.status="blocked";return}if(e.status="idle",e.node.kind==="patrol"){if(r&&e.node.joinMode!=="nearest"){e.progress=(e.node.joinMode==="start"?0:e.initialPhase)*
e.path.length;let u=Pe(e.path,e.progress);e.position=u.point,e.heading=u.heading,e.segment=u.segment}else{let u=(e.node.joinMode??"nearest")==="nearest"?Ht(e.path,e.position):Pe(e.
path,0);e.progress=u.along??0,e.join=oe(e.position,u.point)>1e-7?u.point:null}e.readyAt=i+(r?e.path.delay:0),e.status=i<e.readyAt?"waiting":"moving"}else if(e.node.kind==="follow"){
let u=o?e.routeContexts.get(e.node.routeId??"default"):null;if(u&&u.path===e.path)e.routeStarted=u.started===null?null:u.started+i-u.paused,e.routeTravel=u.travel,e.routeOffset=u.offset,
e.join=u.join;else{let l=e.node.joinMode==="nearest"?Ht(e.path,e.position):{point:e.path.nodes[0],along:0};e.routeOffset=l.along,e.routeTravel=l.along,e.routeArrived=!1,e.join=(!r||
e.node.joinMode==="nearest")&&oe(e.position,l.point)>1e-7?l.point:null,e.routeStarted=e.join?null:i-(e.path.actualSpeed?e.routeOffset/e.path.actualSpeed:0)-(e.routeOffset>0?e.path.
delay:0)}e.status=e.join?"moving":i<(e.routeStarted??i)+(r?e.path.delay:0)?"waiting":e.path.length&&e.path.actualSpeed?"moving":"idle"}else e.node.kind==="signal"?e.status="standby":
e.node.kind==="wait"?e.status=e.node.parameter==="preparation"?"preparing":"waiting":e.node.kind==="move"&&(e.status=se(this.source,e.assignment,e.node)?.kind==="received"&&!e.moveGoal?
"standby":"moving")}activate(e,n,i,r,o){if(!e?.graph||e.status==="blocked"&&n!=="received")return!1;let a=et(e.graph).find(u=>u.event===n&&(n!=="near"||ae(u)===o?.conditionKey)&&(n!==
"time"||Math.abs(this.nextTriggerTime(e,u)-i)<1e-8)&&(!e.triggerFired.has(u.id)||u.once===!1));if(!a)return!1;let s=e.unit.id+"|trigger|"+a.id;if(o?.trace?.includes(s))return!1;if(o?
(e.observation=o,e.trace=[...o.trace??[],s]):(e.observation=null,e.trace=[]),e.trace.length>64)throw Error("情報の中継が64段を超えました。");e.triggerFired.add(a.id),
e.triggerTimes.set(a.id,i);let d=e.node?.id;return e.activated=!0,this.enter(e,a.to,i,!1,!1,o),r.push({type:"triggered",time:i,unitId:e.unit.id,triggerId:a.id,event:n,nodeId:a.to}),
r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d??null,nodeId:a.to}),e.node.parameter==="preparation"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),
e.node.kind==="follow"&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}nextTriggerTime(e,n){return e.triggerFired.has(n.id)?n.once===!1?(e.triggerTimes.get(n.
id)??0)+n.seconds:1/0:n.seconds}transition(e,n,i,r,o){if(!e?.graph||e.status==="blocked"&&n!=="received")return!1;if(this.activate(e,n,i,r,o))return!0;if(!e.node)return!1;let a=e.graph.
edges.find(u=>u.from===e.node.id&&u.when===n&&(n!=="near"||ae(u)===o?.conditionKey));if(!a)return!1;let s=e.unit.id+"|"+a.from+"|"+ae(a);if(a.once&&e.fired.has(s)||o?.trace?.includes(
s))return!1;if(a.once&&e.fired.add(s),o&&(e.observation=o,e.trace=[...o.trace??[],s]),e.trace.length>64)throw Error("情報の中継が64段を超えました。");e.node.kind==="f\
ollow"&&(e.pauseTime=i);let d=e.node.id;return this.enter(e,a.to,i,!1,a.resume,o),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d,nodeId:a.to}),e.node.parameter==="prepar\
ation"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&!a.resume&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}rememberObservation(e,n){
let i=e.latestObservation,r=o=>o.observationTime??o.sampleTime??o.time;(!i||i.targetId!==n.targetId||r(n)>=r(i))&&(e.latestObservation=n)}observedPosition(e,n){let i=e.latestObservation??
e.receivedPosition,r=a=>a.observationTime??a.sampleTime??a.time;return(n?.targetPosition&&!(i?.targetId===n.targetId&&r(i)>r(n))?n:i)?.targetPosition??null}destination(e,n=e.node,i){
let r=se(this.source,e.assignment,n);return r?r.kind==="received"?e.node?.kind==="move"&&se(this.source,e.assignment,e.node)?.id===r.id?e.moveGoal:this.observedPosition(e):r.kind===
"point"?r.point:i?.get(r.unitId)??this.byId.get(r.unitId)?.position??null:null}movementDestination(e,n){let i=this.destination(e,e.node,n),r=se(this.source,e.assignment,e.node);return i?
(e.node.heightMode??(r?.kind==="point"?"target":"keep"))==="keep"?{...i,z:e.moveHeight??e.position.z}:i:null}predict(e,n,i,r){if(e.status==="blocked"||!e.node&&e.graph)return e.position;
if(!e.graph||e.node.kind==="follow"&&!e.join){let l=e.graph?e.routeStarted??0:0;return ve.prototype.evaluateUnit.call(this,e.unit,Math.max(0,n-l),!1).position}let o=Math.max(0,n-(this.
currentTime??0));if(e.node.kind==="patrol"&&!e.join)return Pe(e.path,Ne(e.progress+(i.get(e.unit.id)??e.path.actualSpeed)*Math.max(0,n-Math.max(this.currentTime??0,e.readyAt)),e.path.
length||1)).point;let a=e.join??(e.node.kind==="move"?this.movementDestination(e,r):null);if(!a)return e.position;let s=this.terrain.project(a,e.unit.domain);if(s.error)return e.position;
let d=oe(e.position,s.point),u=Math.min(d,e.path.actualSpeed*o);return Ce(e.position,s.point,d?u/d:1)}replayPath(e,n){if(!e.graph)return e.path;if(!e.replayRoutes){e.replayRoutes=[
{time:0,node:e.graph.nodes.find(a=>a.id===e.graph.initial)}];for(let a of this.result.actionEvents)a.unitId===e.unit.id&&a.type==="nodeChanged"&&e.replayRoutes.push({time:a.time,node:e.
graph.nodes.find(s=>s.id===a.nodeId)});e.replayRoutes=e.replayRoutes.filter(a=>["follow","patrol"].includes(a.node?.kind))}let i=e.replayRoutes.findLast(a=>a.time<=n)?.node;if(!i)return e.
basePath;let r=Ue(this.source,e.assignment,i,e.unit),o=r.id+"|"+i.kind;return e.pathCache.has(o)||e.pathCache.set(o,this.compile({...e.unit,initial:r.points[0],route:r.points.slice(
1),routeMode:r.mode,motion:{...e.unit.motion,...i.routeId?{loopStart:0}:{}}})),e.pathCache.get(o)}stateSnapshot(e,n=e.path){return{id:e.unit.id,position:{x:e.position.x,y:e.position.
y,z:e.position.z},heading:e.heading,status:e.status,distance:e.distance,routeDistance:n.length,error:e.error,errorAt:n.errorAt,actualSpeed:n.actualSpeed,startDelay:n.delay,nodeId:e.
node?.id,behaviorId:e.graph?.id,eta:null}}evaluate(e){let n=Math.max(0,Math.min(this.source.duration,Number(e)||0));if(!this.frames)return{time:0,units:[...this.states.map(g=>this.
stateSnapshot(g)),...this.inactiveUnits],actionsPending:!0,recordingPending:!0};let i=0,r=this.frames.length-1;for(;i<r;){let g=Math.ceil((i+r)/2);this.frames[g].time<=n?i=g:r=g-1}
let o=this.frames[i],a=this.frames[Math.min(i+1,this.frames.length-1)],s=a.time>o.time?(n-o.time)/(a.time-o.time):0,d=this.states.map((g,m)=>{let v=m*5,b=o.values,x=a.values,T=this.
nodeNames[o.nodes[m]-1],I=Ne(x[v+3]-b[v+3]+Math.PI,Math.PI*2)-Math.PI;return{...this.stateSnapshot(g,this.replayPath(g,n)),position:{x:b[v]+(x[v]-b[v])*s,y:b[v+1]+(x[v+1]-b[v+1])*s,
z:b[v+2]+(x[v+2]-b[v+2])*s},heading:b[v+3]+I*s,distance:b[v+4]+(x[v+4]-b[v+4])*s,status:be[o.status[m]],nodeId:T?.split(":")[1],error:o.status[m]===3?"記録された地形制約停止":
null,actualSpeed:a.time>o.time?Math.max(0,(x[v+4]-b[v+4])/(a.time-o.time)):0}}),u=this.result,l=u.events.filter(g=>g.time<=n),p=this.source.mission;return{time:n,units:[...d,...this.
inactiveUnits],actionEvents:u.actionEvents.filter(g=>g.time<=n),mission:p?{...p.type==="state"?_e(u.stateEntries,p,u.stateTargetCount,n):{},events:l,detectedCount:new Set(l.map(g=>g.
targetId)).size,targetCount:u.targetCount,reachedCount:new Set(u.actionEvents.filter(g=>g.type==="arrived"&&g.time<=n&&p.responderIds?.includes(g.unitId)).map(g=>g.unitId)).size,responderCount:u.
responderCount,status:u.successTime!==null&&u.successTime<=n?"success":n>=p.deadline?"failure":"pending",deadline:p.deadline}:void 0,recording:{frames:this.frames.length,bytes:this.
recordBytes,computeCount:this.computeCount,step:this.source.recording.step,interval:this.source.recording.interval},actionsPending:!1}}trailPoints(e,n,i=1e3){if(!this.frames)return[];
let r=this.states.findIndex(l=>l.unit.id===e);if(r<0)return[];let o=this.frames.filter(l=>l.time<=n),a=Math.max(1,Math.ceil(o.length/i)),s=o.filter((l,p)=>p%a===0||p===o.length-1).
map(l=>({x:l.values[r*5],y:l.values[r*5+1],z:l.values[r*5+2]})),d=this.frames.findLast(l=>l.time<=n),u=this.frames.find(l=>l.time>n)??d;if(d){let l=u.time>d.time?(n-d.time)/(u.time-
d.time):0,p=r*5;s.push({x:d.values[p]+(u.values[p]-d.values[p])*l,y:d.values[p+1]+(u.values[p+1]-d.values[p+1])*l,z:d.values[p+2]+(u.values[p+2]-d.values[p+2])*l})}return s}record(e,n){
if(n.at(-1)?.time===e)return;let i=this.states.length,r=new Float32Array(i*5),o=new Uint16Array(i),a=new Uint8Array(i);if(this.states.forEach((s,d)=>{r.set([s.position.x,s.position.
y,s.position.z,s.heading,s.distance],d*5),o[d]=s.node?this.nodeNames.indexOf(s.graph.id+":"+s.node.id)+1:0,a[d]=be.indexOf(s.status)}),n.push({time:e,values:r,nodes:o,status:a}),n.
length>100001||n.length*(i*23+8)>pt)throw Error("再生記録が128MiBを超えました。期間・個数・記録間隔を調整してください。")}get recordBytes(){return this.
frames?.reduce((e,n)=>e+8+n.values.byteLength+n.nodes.byteLength+n.status.byteLength,0)??0}};function ft(t,e,n,i,r){let o=t.terrain.project(n,e.unit.domain);if(o.error)return e.status=
"blocked",e.error=o.error,!1;let a=oe(e.position,o.point),s=Math.min(a,i*r),d=Ce(e.position,o.point,a?s/a:1),u=Math.max(1,Math.ceil(s/Math.min(125,t.terrain.cellSize/4)));for(let l=1;l<=
u;l++){let p=t.terrain.project(Ce(e.position,d,l/u),e.unit.domain);if(p.error)return e.status="blocked",e.error=p.error,!1}return e.heading=Math.atan2(d.x-e.position.x,d.y-e.position.
y),e.position=t.terrain.project(d,e.unit.domain).point,e.distance+=s,e.status=a<=s+1e-7?"arrived":"moving",e.status==="arrived"}function*Gt(t,e=t.source?.mission??t.scenario.mission,n,i={}){
let r=t instanceof he?t:new he(t.source),o=i.horizon??(r.source.measurements?.length?r.source.duration:e?.deadline??r.source.duration),a=i.record??!1,s=r.source.recording.step,d=r.
source.recording.interval;if(!Number.isFinite(o)||o<0||o>r.source.duration)throw Error("計算終了時刻が不正です。");if(r.computeCount)throw Error("計算済みです。新しい試行を作成してください。");
r.computeCount++;let u=r.states,l=[...r.initialEvents],p=new Map,g=new Set,m=[],v=a?[]:null,b=u.filter(h=>h.unit.faction!=="neutral"),x=e?.type==="state"?[]:e?.targetIds?e.targetIds.
map(h=>r.byId.get(h)).filter(Boolean):u.filter(h=>e?h.unit.faction===e.targetFaction:h.unit.faction!=="neutral");if(e&&e.type!=="state"&&e.targetIds?.some(h=>!r.scenario.units.some(
A=>A.id===h&&A.faction===e.targetFaction))||e?.type==="detect"&&!r.scenario.units.some(h=>h.faction===e.targetFaction))throw Error("成功条件に合う対象がありません。");
let T=e?.type==="arrive"?e.responderIds.filter(h=>r.byId.has(h)):[],I=e?.type==="state"?new ue(e,u.filter(h=>h.assignment?.id===e.assignmentId).map(h=>h.unit.id)):null,S={success:!1,
successTime:null,targetCount:e?.type==="state"?b.length:x.length,detectedCount:0,responderCount:T.length,reachedCount:0,events:[],actionEvents:l,invalidUnits:u.filter(h=>h.error).length,
constrainedPaths:0},N=0,R=0,f=0,w=Math.max(1,...u.filter(h=>h.unit.sensor?.enabled).map(h=>h.unit.sensor.range)),D=(h,A,j,z={})=>(l.push({type:A,time:j,unitId:h.unit.id,nodeId:h.node?.
id,...z}),r.transition(h,A,j,l,z));function V(){let h=new Map;for(let A of r.assignments){let j=new Map;for(let z of u.filter(y=>y.assignment===A&&y.node?.kind==="patrol"&&y.status!==
"blocked"&&!y.join)){let y=z.node.routeId??"default";j.has(y)||j.set(y,[]),j.get(y).push(z)}for(let z of j.values()){z.sort((y,E)=>y.progress/y.path.length-E.progress/E.path.length||
y.unit.id.localeCompare(E.unit.id));for(let y=0;y<z.length;y++){let E=z[y],F=z[(y+1)%z.length],M=E.path.actualSpeed,O=M*(E.node.speedFraction??.7),U=O;if(A.spacing!=="none"&&z.length>
1){let te=(F.progress/F.path.length-E.progress/E.path.length+(y===z.length-1?1:0))*E.path.length,c=A.spacing==="fixed"?A.spacingDistance??500:E.path.length/z.length,P=(A.gain??.01)*
(te-c),B=P<0?O*.5:M-O;B>0&&(U+=B*Math.tanh(P/B))}h.set(E.unit.id,U)}}}return h}function W(h,A){let j=h.unit.communication,z=r.byId.get(h.node.receiverId??h.assignment.receiverId),y=z?
oe(h.position,z.position):1/0,E=h.observation?.type==="received"&&h.observation.targetPosition?h.observation:h.latestObservation??(h.observation?.targetPosition?h.observation:null),
F=de(r.source,h.unit.id,"unified-report-v2")+"|"+JSON.stringify([h.node.id,E?.targetId,E?.originObserverId??E?.observerId??h.unit.id]),M=null;j?.enabled?z?y>j.range?M="通信範囲外":
j.terrainLOS&&!st(r.terrain,h.position,z.position)?M="地形遮蔽":G(F)>=j.probability&&(M="通信試行失敗"):M="受信先不在（無効・計算対象外）":M="通信無効",
h.sent=!0;let O={receiverId:z?.unit.id,distance:Number.isFinite(y)?y:null,reason:M,targetId:E?.targetId,targetPosition:E?.targetPosition?{...E.targetPosition}:void 0,observationTime:E?.
observationTime??E?.sampleTime??E?.time,originObserverId:E?.originObserverId??E?.observerId??h.unit.id,trace:[...h.trace],sourcePosition:{...h.position},receiverPosition:z?{...z.position}:
void 0};return M||m.push({...O,type:"received",time:A+j.delay,unitId:z.unit.id,senderId:h.unit.id}),D(h,M?"sendFailed":"sent",A,O)}function J(h){return[...(h.graph?.triggers??[]).filter(
A=>A.event==="near").map(A=>({c:A,key:"trigger:"+A.id})),...(h.graph?.edges??[]).filter(A=>A.from===h.node?.id&&A.when==="near").map(A=>({c:A,key:"edge:"+A.from+"|"+ae(A)}))]}function q(h,A){
let j=!1;for(let{c:z,key:y}of J(h)){let E=r.destination(h,z);if(!E)continue;let F=wt(h.position,E,z.distanceMode),M=F<=z.distance+1e-6,O=h.nearInside.get(y)??!1;if(h.nearInside.set(
y,M),M&&!O&&!(y.startsWith("trigger:")&&z.once!==!1&&h.triggerFired.has(z.id))){let U={destinationId:z.destinationId,distance:F,distanceMode:z.distanceMode??"absolute",conditionKey:ae(
z)};if(D(h,"near",A,U)){j=!0;break}}}return j}function H(h,A,j){let z=new Map(u.map(M=>[M.unit.id,{...M.position}])),y=new Set;for(let M of u)for(let{c:O}of J(M)){y.add(M);let U=se(
r.source,M.assignment,O);U?.kind==="unit"&&r.byId.has(U.unitId)&&y.add(r.byId.get(U.unitId))}if(!y.size)return A;for(let M of y)if(M.status!=="blocked"&&(M.join&&M.path.actualSpeed&&
(A=Math.min(A,h+oe(M.position,M.join)/M.path.actualSpeed)),!M.join&&(!M.graph||["follow","patrol"].includes(M.node?.kind))&&M.path.actualSpeed&&M.path.length)){let O=M.node?.kind===
"patrol"?M.progress:Ne(M.routeTravel??M.distance,M.path.length),U=M.path.nodes.find(te=>te.d>O+1e-7);U&&(A=Math.min(A,h+(U.d-O)/(j.get(M.unit.id)??M.path.actualSpeed)))}let E=new Map(
u.map(M=>[M.unit.id,r.predict(M,A,j,z)])),F=A;for(let M of u)for(let{c:O,key:U}of J(M)){if(M.nearInside.get(U)||U.startsWith("trigger:")&&O.once!==!1&&M.triggerFired.has(O.id))continue;
let te=r.destination(M,O,z),c=r.destination(M,O,E);if(!te||!c)continue;let P=M.position,B=E.get(M.unit.id),k=[P.x-te.x,P.y-te.y,O.distanceMode==="horizontal"?0:P.z-te.z],_=[B.x-c.x-
k[0],B.y-c.y-k[1],O.distanceMode==="horizontal"?0:B.z-c.z-k[2]],X=_.reduce((Z,ie)=>Z+ie*ie,0),K=2*k.reduce((Z,ie,Fe)=>Z+ie*_[Fe],0),me=k.reduce((Z,ie)=>Z+ie*ie,0)-O.distance*O.distance,
Me=K*K-4*X*me;if(X>1e-12&&me>1e-6&&Me>=0){let Z=(-K-Math.sqrt(Me))/(2*X);Z>1e-9&&Z<=1&&(F=Math.min(F,h+(A-h)*Z))}}return F}function $(h){let A=!1;for(let y of u)for(let E=0;E<(y.graph?.
triggers.length??0)&&r.activate(y,"time",h,l);E++)A=!0;let j=y=>{for(let E=0;E<64;E++){if(y.status==="blocked")return;let F=q(y,h);if(F){A=!0;continue}if(y.node?.kind==="report"&&!y.
sent?F=W(y,h):y.node?.kind==="wait"&&!y.elapsed&&h-y.nodeTime>=(y.node.parameter==="preparation"?y.assignment.preparation??y.node.seconds:y.node.seconds)&&(y.elapsed=!0,F=D(y,"elap\
sed",h)),A=A||F,!F)return}throw Error("即時ノード遷移が64段を超えました。循環を見直してください。")};for(let y of u)j(y);let z=0;for(;;){if(m.sort((F,M)=>F.
time-M.time||F.unitId.localeCompare(M.unitId)),!m[0]||m[0].time>h)return A;if(++z>1e5||l.length>1e5)throw Error("情報イベントが10万件を超えました。");let y=m.shift(),
E=r.byId.get(y.unitId);if(l.push(y),E.observation=y,y.targetPosition&&["x","y","z"].every(F=>Number.isFinite(y.targetPosition[F]))){let F=E.receivedPosition;(!F||F.targetId!==y.targetId||
(y.observationTime??y.time)>=(F.observationTime??F.time))&&(E.receivedPosition={...y,targetPosition:{...y.targetPosition}},r.rememberObservation(E,E.receivedPosition))}A=r.transition(
E,"received",h,l,y)||A,j(E)}}$(0),I&&Object.assign(S,I.update(l)),a&&r.record(0,v);for(let h=0;h<o;){let A=Math.min(o,(Math.floor((h+1e-8)/s)+1)*s,e?.deadline>h?e.deadline:1/0),j=1/0;
for(let c of m)c.time>h+1e-8&&(j=Math.min(j,c.time));for(let c of u)if(c.status!=="blocked"){if(c.node?.kind==="wait"&&!c.elapsed){let P=c.node.parameter==="preparation"?c.assignment.
preparation??c.node.seconds:c.node.seconds;c.nodeTime+P>h+1e-8&&(j=Math.min(j,c.nodeTime+P))}for(let P of c.graph?.triggers??[])if(P.event==="time"){let B=r.nextTriggerTime(c,P);B>
h+1e-8&&(j=Math.min(j,B))}if((!c.graph||c.node?.kind==="follow")&&!c.join&&!c.path.periodic&&c.path.length&&c.path.actualSpeed&&!c.routeArrived){let P=(c.graph?c.routeStarted??0:0)+
c.path.delay+c.path.length/c.path.actualSpeed;P>h+1e-8&&(j=Math.min(j,P))}if(c.join&&c.path.actualSpeed){let P=h+oe(c.position,c.join)/c.path.actualSpeed;P>h+1e-8&&(j=Math.min(j,P))}
if(c.node?.kind==="move"&&c.status!=="arrived"&&c.path.actualSpeed&&["point","received"].includes(se(r.source,c.assignment,c.node)?.kind)&&r.movementDestination(c)){let P=h+oe(c.position,
r.terrain.project(r.movementDestination(c),c.unit.domain).point)/c.path.actualSpeed;P>h+1e-8&&(j=Math.min(j,P))}}r.currentTime=h;let z=V(),y=H(h,Math.min(A,j),z),E=y-h,F=new Map(u.
map(c=>[c.unit.id,{...c.position}])),M=new Map(u.map(c=>[c.unit.id,r.predict(c,y,z,F)])),O=!1;for(let c of u)if(c.status!=="blocked"&&!(c.graph&&!c.node)){if(c.node?.kind==="follow"&&
c.join){ft(r,c,c.join,c.path.actualSpeed,E)&&(c.join=null,c.routeStarted=y-(c.path.actualSpeed?c.routeOffset/c.path.actualSpeed:0)-(c.routeOffset>0?c.path.delay:0),c.routeTravel=c.
routeOffset),O=!0;continue}if(!c.graph||c.node.kind==="follow"){let P=c.status,B=c.segment,k=c.graph?c.routeStarted??0:0,_=ve.prototype.evaluateUnit.call(r,c.unit,Math.max(0,y-k),!1);
if(c.graph){let X=c.distance+Math.max(0,_.distance-(c.routeTravel??0));c.routeTravel=_.distance,Object.assign(c,_),c.distance=X}else Object.assign(c,_);c.segment=Pe(c.path,c.path.periodic?
_.distance%c.path.length:_.distance).segment,(P!==c.status||B!==c.segment)&&(O=!0),c.status==="arrived"&&!c.routeArrived&&(c.routeArrived=!0,O=D(c,"arrived",y)||O)}else if(c.node.kind===
"patrol"){if(y<=c.readyAt){c.status="waiting";continue}let P=y-Math.max(h,c.readyAt);if(c.join){ft(r,c,c.join,c.path.actualSpeed,P)&&(c.join=null),O=!0;continue}if(!c.path.length){
c.status="blocked",c.error="周回経路の長さが0です。",O=!0;continue}let B=(z.get(c.unit.id)??c.path.actualSpeed)*P,k=c.progress+B;if(c.path.error&&k>=c.path.length){c.position=
{...c.path.nodes.at(-1)},c.status="blocked",c.error=c.path.error,O=!0;continue}c.progress=Ne(k,c.path.length);let _=Pe(c.path,c.progress);c.position=_.point,c.heading=_.heading,c.distance+=
B,c.status="moving",_.segment!==c.segment&&(O=!0,c.segment=_.segment)}else if(c.node.kind==="move"){let P=r.movementDestination(c,M),B=se(r.source,c.assignment,c.node)?.kind,k=B===
"unit";if(!P){if(B==="received"){c.status="standby";continue}c.status="blocked",c.error="目的地が見つかりません。",O=!0;continue}(c.status!=="arrived"||k)&&ft(r,c,P,c.path.
actualSpeed,E)&&c.status==="arrived"&&!c.destinationArrived&&(c.destinationArrived=!0,O=!0,D(c,"arrived",y))}}if(Math.abs(y-A)<1e-8){let c=u.filter(k=>k.unit.sensor?.enabled&&k.status!==
"blocked"&&k.node?.kind!=="stop"&&k.node?.sensor!==!1),P=Jt(c.map(k=>({unit:k.unit,position:at(k.position,k.unit),state:k})),w),B=[];for(let k of b){if(k.error&&k.path.errorAt==="初\
期位置"||k.unit.detectability===0)continue;let _=at(k.position,{domain:k.unit.domain});for(let X of qt(P,_,w)){++N%256===0&&(yield{time:h,result:S});let K=X.state,me=K.unit.sensor,
Me=K.unit.id+"|"+k.unit.id;if(K.unit.faction===k.unit.faction||!me.domains.includes(k.unit.domain))continue;let Z=oe(X.position,_),ie=Yt(me,Z,k.unit.detectability??1,y-f);if(!(ie<=
0||me.terrainLOS&&!st(r.terrain,X.position,_))&&G(de(r.source,K.unit.id,"unified-detect-v2")+"|"+JSON.stringify([k.unit.id,f,y]))<ie){let Fe={type:"detected",time:y,sampleTime:y,observationTime:y,
observerId:K.unit.id,unitId:K.unit.id,targetId:k.unit.id,distance:Z,observerPosition:{...X.position},targetPosition:{..._},trace:[]};r.rememberObservation(K,Fe),(!g.has(Me)||K.graph?.
triggers.some(ht=>ht.event==="detected"&&ht.once===!1))&&B.push(Fe),g.add(Me)}}}B.sort((k,_)=>k.unitId.localeCompare(_.unitId)||k.targetId.localeCompare(_.targetId));for(let k of B){
let _=r.byId.get(k.unitId);(!e||e.type==="state"||_.unit.faction===e.observerFaction&&x.some(X=>X.unit.id===k.targetId))&&!p.has(k.targetId)&&(p.set(k.targetId,k),S.events.push(k)),
_.observation=k,O=D(_,"detected",y,k)||O}f=y}if(O=$(y)||O,l.length+m.length>1e5)throw Error("行動イベントが10万件を超えました。");S.detectedCount=S.events.filter(c=>!e||
c.time<=e.deadline).length,S.reachedCount=new Set(l.filter(c=>c.type==="arrived"&&T.includes(c.unitId)&&(!e||c.time<=e.deadline)).map(c=>c.unitId)).size,I&&Object.assign(S,I.update(
l));let U=e?.type==="arrive"?S.reachedCount:S.detectedCount,te=e?.join==="all"?e.type==="arrive"?T.length:x.length:1;if(e&&e.type!=="state"&&te>0&&y<=e.deadline&&U>=te&&S.successTime===
null&&(S.success=!0,S.successTime=y),a&&(O||y-R>=d-1e-8||y===o)&&(r.record(y,v),R=y),h=y,yield{time:y,result:S},!r.source.measurements?.length&&!a&&!u.some(c=>c.graph)&&e?.type==="\
detect"&&S.detectedCount===x.length)break}return r.source.measurements?.length&&(S.measurements=Re(r.source,l,o)),S.constrainedPaths=u.filter(h=>h.status==="blocked").length,a&&(r.
frames=v,r.result=S),S}var Ve=t=>new he(t);var L,Y,Ie=0,ce="idle",we=null;function Wt(){L.frames&&self.postMessage({type:"recordingHistory",revision:Y.revision,history:{duration:L.source.duration,unitIds:L.states.map(t=>t.unit.
id),events:L.result.actionEvents}})}function xe(){if(!L||!Y)return;let t=L.evaluate(L.frames?Y.time:0);if(L.frames&&Y.showTrails){let e=L.states.length<=80?L.states.map(n=>n.unit.id):
[Y.selected];t.trails=Object.fromEntries(e.filter(Boolean).map(n=>[n,L.trailPoints(n,t.time)]))}t.executionState=ce,t.recordingRunning=ce==="running",t.recordingPending=!L.frames,t.
actionsPending=!L.frames,we&&(t.missionError=we),self.postMessage({type:"snapshot",revision:Y.revision,request:Y.request,snapshot:t})}self.onmessage=({data:t})=>{if(t.type==="ping"){
self.postMessage({type:"pong",build:mt});return}try{if(t.type==="scenario"){let e=++Ie;Y=t,we=null,L=t.recording?lt(t.recording):Ve(t.scenario),ce=L.frames?"ready":"idle",Wt(),xe(),
t.autoRecord&&!L.frames&&Vt(e)}else if(t.revision===Y?.revision)if(Y={...Y,...t,scenario:Y.scenario},t.type==="calculate"){let e=++Ie;L=Ve(Y.scenario),Y.time=0,we=null,Vt(e)}else t.
type==="cancelRecording"?(Ie++,ce="cancelled",L=Ve(Y.scenario),xe()):t.type==="exportRecording"?self.postMessage({type:"recordingExport",revision:t.revision,payload:ct(L)}):xe()}catch(e){
ce="failed",we=e.message,xe(),self.postMessage({type:"error",revision:t.revision,message:e.message})}};async function Vt(t){ce="running",xe();try{let e=Gt(L,L.source.mission,void 0,
{horizon:L.source.duration,record:!0}),n=e.next(),i=performance.now(),r=0;for(;!n.done;){if(performance.now()-i>16&&(await new Promise(o=>setTimeout(o,0)),i=performance.now(),t!==Ie))
return;performance.now()-r>150&&(r=performance.now(),self.postMessage({type:"recordingProgress",revision:Y.revision,time:n.value.time,duration:L.source.duration})),n=e.next()}if(t!==
Ie)return;ce="ready",Wt()}catch(e){if(t!==Ie)return;ce="failed",we=e.message}xe()}})();
