/* SimSim portable 20261006-empty-task-11-d7ebd0714e7a. Generated by npm run build:portable. */
(()=>{function Xe(t){let e=t.mission;if(e?.type!=="state")return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=t.behaviors?.find(r=>r.id===n?.behaviorId);return n?i?.nodes?.
some(r=>r.id===e.nodeId)?[]:["計測対象の状態を選択してください。"]:["計測対象のタスクがありません。"]}function Ce(t,e=t.mission){if(e?.type!=="state")
return[];let n=t.behaviorAssignments?.find(r=>r.id===e.assignmentId),i=[];for(let r of n?.targets??[])if(r.startsWith("unit:")){let o=t.units.find(a=>a.id===r.slice(5));o&&o.enabled!==
!1&&i.push(o.id)}else{let o=t.groups?.find(a=>a.id===r.slice(6));if(o&&o.enabled!==!1)for(let a=1;a<=o.count;a++)i.push(o.id+"__"+a)}return i.sort()}var Et=(t,e)=>t.join==="all"?e:
t.join==="count"?t.requiredCount:1;function Ee(t,e,n,i=e.deadline){let r=t.filter(a=>a.time<=Math.min(i,e.deadline)).sort((a,s)=>a.time-s.time||a.unitId.localeCompare(s.unitId)),o=Et(
e,n);return{stateTargetCount:n,stateReachedCount:r.length,stateEntries:r,success:n>0&&o>0&&r.length>=o,successTime:n>0&&o>0&&r.length>=o?r[o-1].time:null}}var de=class{constructor(e,n){
this.mission=e,this.members=new Set(n),this.first=new Map,this.cursor=0}update(e){for(;this.cursor<e.length;this.cursor++){let n=e[this.cursor];["initialized","nodeChanged"].includes(
n.type)&&n.nodeId===this.mission.nodeId&&n.time<=this.mission.deadline&&this.members.has(n.unitId)&&!this.first.has(n.unitId)&&this.first.set(n.unitId,n.time)}return Ee([...this.first].
map(([n,i])=>({unitId:n,time:i})),this.mission,this.members.size)}};function Ze(t,e){let n=t.mission;if(n?.type!=="state")return;let i=new Set(Ce(t)),r=e.stateEntries;if(e.stateTargetCount!==
i.size||!Array.isArray(r)||r.length>i.size||new Set(r.map(a=>a?.unitId)).size!==r.length||r.some(a=>!a||!i.has(a.unitId)||!Number.isFinite(a.time)||a.time<0||a.time>n.deadline))throw Error(
"状態到達の対象・初回到達時刻が不正です。");let o=Ee(r,n,i.size);if(e.stateReachedCount!==o.stateReachedCount||e.success!==o.success||e.successTime!==o.successTime)
throw Error("状態到達数・成立時刻と計測条件が一致していません。")}var kt={number:"数値",route:"経路",destination:"目的地",unit:"単体ユニット"},Qe={routeId:"route",destinationId:"destination",receiverId:"unit",seconds:"number",speedFraction:"\
number",distance:"number"},X=t=>!!t&&typeof t=="object"&&!Array.isArray(t)&&Object.keys(t).length===1&&typeof t.$param=="string";function ve(t,e,n){if(!X(t))return t;let i=Array.isArray(
e?.parameters)?e.parameters.find(r=>r?.id===t.$param):null;return Object.hasOwn(n?.parameters??{},t.$param)?n.parameters[t.$param]:i?.default}function Ie(t,e){if(!t)return t;let n=i=>i&&
typeof i=="object"?Object.fromEntries(Object.entries(i).map(([r,o])=>[r,ve(o,t,e)])):i;return{...t,nodes:t.nodes.map(n),edges:t.edges.map(n),triggers:(t.triggers??[]).map(n)}}function Pe(t,e,n){
if(!Array.isArray(e.nodes)||!Array.isArray(e.edges)||e.triggers!==void 0&&!Array.isArray(e.triggers))return["挙動のノード・条件の形式が不正です。"];let i=[],r=e.parameters??
[],o=new Set;if(!Array.isArray(r)||r.length>64)return["担当時に指定する値は最大64件の配列です。"];let a=(s,d)=>s.type==="number"?Number.isFinite(d):typeof d=="st\
ring"&&(s.type==="route"?t.routes:s.type==="destination"?t.destinations:t.units)?.some?.(c=>c.id===d);for(let s of r){if(!s||!/^[a-zA-Z0-9_-]{1,80}$/.test(s.id??"")||o.has(s.id)||typeof s.
name!="string"||!s.name.trim()||s.name.length>120||!Object.hasOwn(kt,s.type)){i.push("担当値のID・名前・種類が不正または重複しています。");continue}o.add(s.
id),s.unit!==void 0&&(s.type!=="number"||!["s","m","ratio"].includes(s.unit))&&i.push("担当値の単位が不正です。"),Object.hasOwn(s,"default")&&!a(s,s.default)&&i.push("担\
当値「"+s.name+"」の既定値が不正です。"),n&&!a(s,ve({$param:s.id},e,n))&&i.push("タスク「"+n.name+"」で「"+s.name+"」を指定してください。")}for(let s of[
...e.nodes,...e.edges,...e.triggers??[]].filter(d=>d&&typeof d=="object"))for(let[d,c]of Object.entries(s))if(c&&typeof c=="object"&&(Object.hasOwn(c,"$param")||Qe[d])){let f=X(c)?
r.find(y=>y?.id===c.$param):null,l={seconds:"s",distance:"m",speedFraction:"ratio"}[d];(!f||f.type!==Qe[d]||l&&f.unit&&f.unit!==l)&&i.push("担当値の参照・種類・単位が不正です: "+
d)}return n?.parameters!==void 0&&(!n.parameters||typeof n.parameters!="object"||Array.isArray(n.parameters)||Object.keys(n.parameters).some(s=>!o.has(s)))&&i.push("タスクの担当値に未定義の項目が\
あります。"),i}function ke(t,e,n,i){let r=t.behaviors?.find(s=>s.id===e?.behaviorId),o=ve(n?.routeId,r,e),a=o?t.routes?.find(s=>s.id===o):null;return{id:a?.id??"default",points:a?.points??e?.route??
[i.initial,...i.route],mode:n?.kind==="patrol"?"loop":a?.mode??e?.routeMode??i.routeMode}}function xe(t,e,n){let i=ve(n?.destinationId,t.behaviors?.find(r=>r.id===e?.behaviorId),e);
return i?t.destinations?.find(r=>r.id===i):e?.base?{kind:"point",point:e.base}:null}function Z(t){let e=t.when??t.event;return e==="near"?[e,t.destinationId,t.distance,t.distanceMode??
"absolute"].map(n=>X(n)?JSON.stringify(n):n).join("|"):e==="time"?e+"|"+(X(t.seconds)?JSON.stringify(t.seconds):t.seconds):e}var et=(t,e,n="absolute")=>Math.hypot(t.x-e.x,t.y-e.y,n===
"horizontal"?0:t.z-e.z);function tt(t){let e=[],n=(r,o,a)=>Number.isFinite(r)&&r>=o&&r<=a,i=r=>r&&["x","y","z"].every(o=>n(r[o],-1e6,1e6));for(let[r,o]of[["routes",128],["destinati\
ons",256]]){let a=t[r]??[],s=new Set;if(!Array.isArray(a)||a.length>o){e.push(r==="routes"?"経路は最大128件の配列です。":"目的地は最大256件の配列です。");continue}
for(let d of a){if(!d||!/^[a-zA-Z0-9_-]{1,80}$/.test(d.id??"")||s.has(d.id)||typeof d.name!="string"||!d.name.trim()||d.name.length>120){e.push("経路・目的地のIDまたは名前が不正・重複しています。");
continue}s.add(d.id),r==="routes"?((!Array.isArray(d.points)||d.points.length<2||d.points.length>500||d.points.some(c=>!i(c)))&&e.push("経路は2～500点の座標で指定してください。"),
["once","loop","pingpong"].includes(d.mode??"once")||e.push("経路の繰り返し方式が不正です。")):d.kind==="point"?i(d.point)||e.push("目的地の地点座標が不正です。"):
d.kind==="unit"?t.units?.some(c=>c.id===d.unitId)||e.push("目的地のユニットがありません。"):e.push("目的地は地点またはユニットを指定してください。")}}
return e}function Fe(t,e,n=!1){let i=[];return!(n&&X(e.destinationId))&&(!Array.isArray(t.destinations)||!t.destinations.some(r=>r?.id===e.destinationId))&&i.push("接近条件の目的地を選択してくださ\
い。"),!(n&&X(e.distance))&&(!Number.isFinite(e.distance)||e.distance<0||e.distance>1e6)&&i.push("接近距離は0～1000000mです。"),["horizontal","absolute"].includes(e.distanceMode??
"absolute")||i.push("距離の種類は水平距離または絶対距離です。"),i}var zt={follow:"経路を進む",patrol:"協調して周回",signal:"情報を待つ",report:"報告",move:"目的に向かって進む",wait:"時間待ち",stop:"終了"},jt={received:"\
情報受信",time:"時間経過",detected:"対象探知",near:"指定距離まで近づく"};function nt(t){return t.initial??t.entry??(Array.isArray(t.triggers)?t.triggers.find(e=>e?.
event==="scenarioStart")?.to:void 0)}function _e(t){return(t.triggers??[]).filter(e=>e?.event!=="scenarioStart")}function it(t){for(let e of t.behaviors??[]){let n=nt(e);n!==void 0&&
(e.initial=n),e.triggers=_e(e);for(let i of e.triggers)delete i.policy;for(let i of e.nodes)i.kind==="return"&&(i.kind="move");delete e.entry}return t}var Ot={follow:["detected","received","arrived","near"],patrol:["detected","received","near"],signal:["received","detected","near"],report:["sent","sendFailed","near"],move:["arriv\
ed","received","detected","near"],return:["arrived","received","detected","near"],wait:["elapsed","received","detected","near"],stop:[]};var V=(t,e,n)=>Number.isFinite(t)&&t>=e&&t<=n,Re=t=>t&&["x","y","z"].every(e=>V(t[e],-1e6,1e6));function De(t,e=!1){let n=tt(t),i=t.behaviors??[],r=t.behaviorAssignments??[];if(!Array.
isArray(i)||i.length>50)return["挙動は最大50件の配列です。"];if(!Array.isArray(r)||r.length>100)return["タスクは最大100件の配列です。"];let o=Array.isArray(
t.routes)?t.routes:[],a=Array.isArray(t.destinations)?t.destinations:[],s=new Set,d=new Set,c=new Set;for(let h of i){if(!h||!/^[a-zA-Z0-9_-]{1,80}$/.test(h.id??"")||s.has(h.id)){n.
push("挙動IDが不正または重複しています。");continue}if(s.add(h.id),(typeof h.name!="string"||!h.name.trim()||h.name.length>120)&&n.push("挙動名は1～120文字です。"),
!Array.isArray(h.nodes)||!h.nodes.length||h.nodes.length>64||!Array.isArray(h.edges)||h.edges.length>128){n.push("挙動は1～64ノード、最大128接続です。");continue}e||
n.push(...Pe(t,h));let x=(p,P,Y)=>!e&&X(p)||V(p,P,Y),v=p=>!X(p),k=new Map,T=new Set;for(let p of h.nodes){if(!p||!/^[a-zA-Z0-9_-]{1,80}$/.test(p.id??"")||k.has(p.id)||!(zt[p.kind]||
p.kind==="return")){n.push("ノードID・種類が不正です。");continue}k.set(p.id,p),p.routeId!==void 0&&(!["follow","patrol"].includes(p.kind)||v(p.routeId)&&!o.some(P=>P?.
id===p.routeId))&&n.push("状態ノードの経路参照が不正です。"),p.destinationId!==void 0&&(!["move","return"].includes(p.kind)||v(p.destinationId)&&!a.some(P=>P?.id===
p.destinationId))&&n.push("状態ノードの目的地参照が不正です。"),p.kind==="patrol"&&p.routeId&&v(p.routeId)&&o.find(P=>P?.id===p.routeId)?.points?.length<3&&n.push(
"周回経路は3点以上必要です。"),p.kind==="wait"&&!x(p.seconds,0,86400)&&n.push("待機時間は0～86400秒です。"),p.kind==="patrol"&&!x(p.speedFraction??.7,.05,1)&&
n.push("巡回速度比は0.05～1です。"),p.kind==="report"&&!p.receiverId&&!p.receiverRole&&n.push("報告先または報告先の役割を指定してください。"),p.receiverId&&
v(p.receiverId)&&!t.units?.some(P=>P.id===p.receiverId)&&n.push("報告先の単体ユニットがありません: "+p.receiverId),p.joinMode!==void 0&&(!["follow","patrol"].includes(
p.kind)||!["start","nearest"].includes(p.joinMode))&&n.push("経路への入り方は最初から／最短地点からを選択してください。"),p.sensor!==void 0&&typeof p.sensor!=
"boolean"&&n.push("ノードのsensorはbooleanです。"),(p.x!==void 0&&!V(p.x,0,4e3)||p.y!==void 0&&!V(p.y,0,4e3))&&n.push("ノード位置が不正です。")}let I=nt(h),S=h.triggers??
[],R=new Set,D=new Set;if(I!==void 0&&!k.has(I)&&n.push("初期状態の参照先がありません。"),(h.initial!==void 0&&h.entry!==void 0&&h.initial!==h.entry||h.triggers?.some?.(
p=>p?.event==="scenarioStart"&&p.to!==I))&&n.push("初期状態の指定が重複しています。"),!Array.isArray(S)||S.length>32)n.push("イベントノードは最大32件の配列です。");else if(I===
void 0&&!S.length)n.push("初期状態またはイベントノードを指定してください。");else for(let p of S){(!p||!/^[a-zA-Z0-9_-]{1,80}$/.test(p.id??"")||R.has(p.id)||
!(Object.hasOwn(jt,p.event)||p.event==="scenarioStart")||!k.has(p.to))&&n.push("イベントノードのID・種類・接続先が不正です。"),R.add(p?.id);let P=p?Z(p):"";D.has(
P)&&n.push("同じイベント・時間のイベントノードは一つだけ指定できます。"),D.add(P),p?.event==="time"&&(!x(p.seconds,0,86400)||p.once===!1&&p.seconds===0)&&
n.push("時間イベントは0～86400秒、繰り返す場合は0より大きい秒数です。"),p?.policy!==void 0&&!["idle","interrupt"].includes(p.policy)&&n.push("起動方法はidle・i\
nterruptです。"),p?.once!==void 0&&typeof p.once!="boolean"&&n.push("イベントノードのonceはbooleanです。"),p?.event==="near"&&n.push(...Fe(t,p,!e)),(p?.x!==void 0&&!V(
p.x,0,4e3)||p?.y!==void 0&&!V(p.y,0,4e3))&&n.push("イベントノードの位置が不正です。")}for(let p of h.edges){let P=p?.from+"|"+(p?Z(p):""),Y=k.get(p?.from);(!p||!Y||
!k.has(p.to)||!(Ot[Y.kind]??[]).includes(p.when)||T.has(P))&&n.push("接続条件が始点ノードに対応しないか、接続が不正・重複しています。"),p?.once!==void 0&&
typeof p.once!="boolean"&&n.push("接続のonceはbooleanです。"),p?.when==="near"&&n.push(...Fe(t,p,!e)),T.add(P)}}for(let h of r){if(!h||!/^[a-zA-Z0-9_-]{1,80}$/.test(h.id??"")||
d.has(h.id)){n.push("タスクIDが不正または重複しています。");continue}d.add(h.id),(typeof h.name!="string"||!h.name.trim()||h.name.length>120)&&n.push("タスク名は1～120文字\
です。");let x=i.find(I=>I.id===h.behaviorId);if(x||n.push("タスクの挙動がありません。"),!Array.isArray(h.targets)||!h.targets.length&&!(t.mission?.type==="state"&&
t.mission.assignmentId===h.id)||h.targets.length>100){n.push("タスクの担当を選んでください。");continue}for(let I of h.targets){let S=typeof I=="string"?I.split(":")[0]:
"",R=typeof I=="string"?I.slice(S.length+1):"";(!(S==="unit"?t.units?.find(p=>p.id===R):S==="group"&&t.groups?.find(p=>p.id===R)?.template)||c.has(I))&&n.push("タスクの担当が不正または重複しています。"),
c.add(I)}if(x){let I=Pe(t,x,h);if(n.push(...I),!I.length&&x.parameters?.length){let S=Ie(x,h);n.push(...De({...t,behaviors:[S],behaviorAssignments:[]},!0).map(R=>"タスク「"+h.name+
"」: "+R))}}let v=x&&Array.isArray(x.nodes)&&Array.isArray(x.edges)?Ie(x,h):null,k=v?.nodes.some(I=>I.kind==="patrol"&&!I.routeId),T=v?.nodes.some(I=>["return","move"].includes(I.
kind)&&!I.destinationId);k&&(!Array.isArray(h.route)||h.route.length<3)&&n.push("周回タスクは3点以上の共有経路が必要です。"),h.route!==void 0&&(!Array.isArray(h.
route)||h.route.length>500||h.route.some(I=>!Re(I)))&&n.push("タスクの経路が不正です。"),T&&!Re(h.base)&&n.push("目的に向かって進む状態の目的地を選択してください。"),
h.base!==void 0&&!Re(h.base)&&n.push("帰投地点が不正です。"),h.routeMode!==void 0&&!["once","loop","pingpong"].includes(h.routeMode)&&n.push("タスクの経路方式が不正です。"),
["even","fixed","none"].includes(h.spacing??"none")||n.push("間隔方式が不正です。"),(!V(h.spacingDistance??500,0,1e5)||!V(h.gain??.01,0,1)||!V(h.preparation??0,0,86400)||
!V(h.phase??0,0,1))&&n.push("タスクの間隔・調整係数・準備時間・開始割合が不正です。"),v?.nodes.some(I=>I.receiverRole&&!I.receiverId)&&!t.units?.some(I=>I.
id===h.receiverId)&&n.push("タスクの報告先を選んでください。")}let f=t.recording??{},l=f.step??t.analysis?.step??10,y=f.interval??l;return(!V(l,.1,300)||!V(y,.1,300)||
y<l||Math.abs(y/l-Math.round(y/l))>1e-8||t.duration/l>1e5)&&n.push("計算刻み0.1～300秒、記録間隔は刻みの整数倍・300秒以下、最大10万ステップです。"),
t.version===3&&t.analysis&&t.analysis.step!==l&&n.push("分析と記録の計算刻みを一致させてください。"),n}function rt(t,e){let n=t.units?.find(r=>r.id===e),i=n?.groupId??t.groups?.find(r=>e?.slice(0,e.lastIndexOf("__"))===r.id)?.id;return t.behaviorAssignments?.find(r=>r.targets.includes(
"unit:"+e)||i&&r.targets.includes("group:"+i))}function B(t){let e=2166136261;for(let n=0;n<t.length;n++)e^=t.charCodeAt(n),e=Math.imul(e,16777619);return e^=e>>>16,e=Math.imul(e,2146121005),e^=e>>>15,e=Math.imul(e,2221713035),
e^=e>>>16,(e>>>0)/4294967296}var Tt=t=>t*t*(3-2*t);function Le(t,e,n){let i=Math.floor(e/n),r=Tt(e/n-i),o=d=>{let c=B(t+"|angle|"+d)*Math.PI*2,f=Math.sqrt(B(t+"|radius|"+d));return[
Math.cos(c)*f,Math.sin(c)*f,B(t+"|z|"+d)*2-1]},a=o(i),s=o(i+1);return a.map((d,c)=>d+(s[c]-d)*r)}function Q(t,e,n){return"simsim-rng-v1|"+JSON.stringify([t.seed??"SimSim",t.trial??
0,e,n])}function Ye(t){let e=t.units.map(n=>({...n}));for(let n of t.groups??[]){let i=Math.ceil(Math.sqrt(n.count)),r=Math.ceil(n.count/i);for(let o=0;o<n.count;o++){let a=n.id+"_\
_"+(o+1),s=Q(t,a,"deployment"),d=n.placement==="random"?B(s+"|x"):(o%i+.5)/i,c=n.placement==="random"?B(s+"|y"):(Math.floor(o/i)+.5)/r,f=(d-.5)*n.width,l=(c-.5)*n.height,y=v=>({...v,
x:v.x+f,y:v.y+l}),h=n.loopStartMode??"template",x=n.template.routeMode==="loop"&&h!=="template"?{...n.template.motion,loopStart:((n.template.motion?.loopStart??0)+(h==="even"?o/n.count:
B(Q(t,a,"loop-start-placement-v1"))))%1}:n.template.motion;e.push({...n.template,...x?{motion:x}:{},enabled:n.enabled!==!1,id:a,name:(n.name+" "+(o+1)).slice(0,120),groupId:n.id,initial:y(
n.template.initial),route:n.template.route.map(y)})}}return e}var O=(t,e,n,i,r,o,a={})=>({key:t,label:e,family:n,path:i,min:r,max:o,scale:1,scope:"entity",...a}),Nt=[O("rate.movement.speed","移動速度","Rate","speed",0,1500,{unit:"m/s",default:0}),
O("extent.sense.radius","最大探知距離","Extent","sensor.range",.001,1e5,{unit:"km",scale:1e3,sensor:!0}),O("interaction.detection.probability","距離0で1分の探知確率",
"Interaction","sensor.probabilityPerMinute",0,1,{unit:"%",scale:.01,sensor:!0}),O("extent.communication.radius","最大通信距離","Extent","communication.range",.001,1e5,{unit:"\
km",scale:1e3,communication:!0}),O("interaction.communication.delay","通信遅延","Interaction","communication.delay",0,86400,{unit:"s",communication:!0}),O("interaction.communic\
ation.probability","通信成功確率","Interaction","communication.probability",0,1,{unit:"%",scale:.01,communication:!0}),O("behavior.preparation","出発準備時間","Behavior",
"preparation",0,86400,{unit:"s",scope:"assignment",preparation:!0,default:0}),O("extent.signature.coefficient","被探知係数","Extent","detectability",0,10,{unit:"倍",default:1}),
O("state.position.x","配置・経路の中心 x","State","initial.x",-1e6,1e6,{unit:"km",scale:1e3,translate:"x"}),O("state.position.y","配置・経路の中心 y","State","initi\
al.y",-1e6,1e6,{unit:"km",scale:1e3,translate:"y"}),O("state.position.z","高度・深度 z","State","initial.z",-2e4,1e5,{unit:"m",translate:"z",vertical:!0}),O("extent.sense.moun\
tHeight","センサー取付高","Extent","sensor.mountHeight",0,1e3,{unit:"m",sensor:!0,default:0}),O("state.route.phase","周回の出発点","State","motion.loopStart",0,1,{unit:"\
%",scale:.01,default:0,loopOnly:!0}),O("motion.horizontal","個体の水平ずれ上限","Motion","motion.horizontal",0,1e4,{unit:"m",default:0}),O("motion.commonHorizontal","群共通の水\
平ずれ上限","Motion","motion.commonHorizontal",0,1e4,{unit:"m",default:0}),O("motion.vertical","上下ずれ上限","Motion","motion.vertical",0,3e3,{unit:"m",default:0,vertical:!0}),
O("motion.scale","航跡の変動間隔","Motion","motion.scale",10,1e5,{unit:"m",default:2e3}),O("motion.startDelay","出発遅れ上限","Motion","motion.startDelay",0,86400,{unit:"\
s",default:0}),O("motion.speedVariation","個体速度のばらつき","Motion","motion.speedVariation",0,1,{unit:"±%",scale:.01,default:0}),O("capacity.population","群の個数",
"Capacity","count",0,2e3,{unit:"個",scope:"group",integer:!0}),O("extent.deployment.width","配置幅 x","Extent","width",0,1e5,{unit:"km",scale:1e3,scope:"group"}),O("extent.depl\
oyment.height","配置幅 y","Extent","height",0,1e5,{unit:"km",scale:1e3,scope:"group"}),O("task.route.x","共有経路の基準 x","State","route.0.x",-1e6,1e6,{unit:"km",scale:1e3,
scope:"assignment",routeAxis:"x"}),O("task.route.y","共有経路の基準 y","State","route.0.y",-1e6,1e6,{unit:"km",scale:1e3,scope:"assignment",routeAxis:"y"}),O("task.route.z",
"共有経路の高度・深度","State","route.0.z",-2e4,1e5,{unit:"m",scope:"assignment",routeAxis:"z"}),O("task.route.phase","共有周回の出発点","State","phase",0,1,{unit:"\
%",scale:.01,scope:"assignment",default:0,patrol:!0}),O("coordination.spacing","協調する指定間隔","Behavior","spacingDistance",0,1e5,{unit:"m",scope:"assignment",fixedSpacing:!0,
default:500}),O("coordination.gain","間隔の調整係数","Behavior","gain",0,1,{unit:"1/s",scope:"assignment",default:.01}),O("mission.deadline","成功条件の期限","Mission",
"mission.deadline",1e-6,86400,{unit:"min",scale:60,scope:"scenario"})],st=t=>Nt.find(e=>e.key===t),ot=t=>JSON.stringify([t.target,t.parameter]);function at(t){let e=JSON.parse(JSON.
stringify(t));return e.factors=[...t.groupId?[{target:"group:"+t.groupId,parameter:"capacity.population",values:[...t.counts].sort((n,i)=>n-i)}]:[],...e.factors??[]],delete e.groupId,
delete e.counts,e}function Ct(t,e,n){if(e==="scenario"){if(n.scope!=="scenario"||!t.mission)throw new Error("成功条件を設定してください。");return t}let i=e?.indexOf(":")??-1,r=e?.slice(
0,i),o=e?.slice(i+1),a=r==="unit"?t.units?.find(d=>d.id===o):r==="group"?t.groups?.find(d=>d.id===o):r==="assignment"?t.behaviorAssignments?.find(d=>d.id===o):null;if(!a||n.scope===
"scenario"||n.scope==="group"&&r!=="group")throw new Error("変数の対象が見つかりません: "+e);if(n.scope==="assignment"!=(r==="assignment"))throw new Error("変数の対象が一致しませ\
ん。");let s=r==="group"&&n.scope==="entity"?a.template:a;if(r!=="assignment"&&rt(t,r==="group"?o+"__1":o)?.route?.length&&(n.translate||n.loopOnly||n.key.startsWith("extent.depl\
oyment.")))throw new Error("共有経路の位置・開始割合はタスク側の変数を選んでください。");if(n.loopOnly&&s.routeMode!=="loop")throw new Error("周回の出発点は周回\
経路の対象に指定してください。");if(n.communication&&!s.communication?.enabled)throw new Error("通信変数の対象で通信を有効にしてください。");if(n.
behavior&&!s.behavior)throw new Error("条件付き行動の設定がありません。");if(n.sensor&&!s.sensor)throw new Error("探知変数の対象にセンサーがありません。");
return s}var Pt=(t,e)=>e.split(".").reduce((n,i)=>n?.[i],t);function dt(t,e){let n=st(e.parameter);if(!n)throw new Error("未対応の変数です。");let i=Ct(t,e.target,n);return Pt(
i,n.path)??(n.key==="extent.sense.mountHeight"&&i.domain==="ground"?2:n.default)}function ut(t,e){let n=[],i=new Set;t.groupId&&i.add(ot({target:"group:"+t.groupId,parameter:"capacity.population"}));for(let[o,a]of[["factors",t.factors??[]],["uncertainties",t.uncertainties??
[]]]){let s=o==="factors"?9:8;if(!Array.isArray(a)||a.length>s){n.push(o+"は最大"+s+"変数にしてください。");continue}for(let d of a){let c=st(d?.parameter),f=ot(d??{});
if(!c||typeof d.target!="string"){n.push("未対応の変数または対象です。");continue}i.has(f)&&n.push("同じ変数を重複して指定できません。"),i.add(f);let l=c.
key==="mission.deadline"?Math.min(c.max,e):c.max,y=h=>typeof h=="number"&&Number.isFinite(h)&&h>=c.min&&h<=l&&(!c.integer||Number.isInteger(h));o==="factors"?(!Array.isArray(d.values)||
!d.values.length||d.values.length>12||d.values.some(h=>!y(h))||new Set(d.values).size!==d.values.length)&&n.push(c.label+": 比較値は範囲内で重複しない数値を1～12個指定してください。"):
(!["uniform","triangular"].includes(d.distribution)||!y(d.min)||!y(d.max)||d.min>d.max||d.distribution==="triangular"&&(!y(d.mode)||d.mode<d.min||d.mode>d.max))&&n.push(c.label+": \
分布の範囲・最頻値が不正です。")}}let r=(t.groupId?t.counts?.length??0:1)*(Array.isArray(t.factors)?t.factors.reduce((o,a)=>o*(a?.values?.length??0),1):1);return r>24&&
n.push("比較値の組合せは最大24条件にしてください。"),r*t.trials>1e4&&n.push("条件数×試行数は10000以下にしてください。"),n}var ct=t=>typeof t=="number"&&Number.isFinite(t);function lt(t,e="unit",n=new Set){let i=[],r=t.communication,o=t.behavior;if(r!==void 0)if(!r||typeof r!="object"||Array.isArray(r))
i.push(e+": communicationはオブジェクトにしてください。");else{(typeof r.enabled!="boolean"||typeof r.terrainLOS!="boolean")&&i.push(e+": 通信のenabled・terrainLOSはboole\
anにしてください。");for(let[a,s,d]of[["range",.001,1e5],["delay",0,86400],["probability",0,1]])(!ct(r[a])||r[a]<s||r[a]>d)&&i.push(e+": communication."+a+"は"+s+"～"+d+"\
にしてください。")}if(o!==void 0){if(!o||typeof o!="object"||Array.isArray(o))return[...i,e+": behaviorはオブジェクトにしてください。"];if(typeof o.hold!="bo\
olean"&&i.push(e+": behavior.holdはbooleanにしてください。"),(!ct(o.preparation)||o.preparation<0||o.preparation>86400)&&i.push(e+": behavior.preparationは0～86400秒にしてください。"),
!Array.isArray(o.rules)||o.rules.length>16)i.push(e+": 行動ルールは最大16件にしてください。");else{let a=new Set;for(let s of o.rules){if(!s||typeof s!="object"){i.
push(e+": ルールはオブジェクトにしてください。");continue}(typeof s.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(s.id)||a.has(s.id))&&i.push(e+": ルールidは重複しない英数字・_・\
-にしてください。"),a.add(s.id),(!["detected","received","arrived"].includes(s.when)||!["send","depart"].includes(s.action)||!["any","waiting"].includes(s.state)||typeof s.
once!="boolean")&&i.push(e+": ルールの条件・動作・実行回数が不正です。"),s.action==="send"&&!n.has(s.receiverId)&&i.push(e+": 送信先の単体ユニットが見つかりません: "+
s.receiverId),s.action==="depart"&&!o.hold&&i.push(e+": 出発ルールには「指令まで待機」を設定してください。")}}}return i}var Ft=["ground","surface","subsurface","air"],pt=["friendly","hostile","neutral"],ne=t=>typeof t=="number"&&Number.isFinite(t);function ft(t,e="unit"){let n=[],i=t.sensor;if(t.detectability!==
void 0&&(!ne(t.detectability)||t.detectability<0||t.detectability>10)&&n.push(e+": detectabilityは0～10にしてください。"),i!==void 0){if(!i||typeof i!="object"||Array.isArray(
i))return[...n,e+": sensorはオブジェクトにしてください。"];typeof i.enabled!="boolean"&&n.push(e+": sensor.enabledはbooleanにしてください。"),(!ne(i.range)||
i.range<=0||i.range>1e5)&&n.push(e+": sensor.rangeは0より大きく100000m以下にしてください。"),(!ne(i.probabilityPerMinute)||i.probabilityPerMinute<0||i.probabilityPerMinute>
1)&&n.push(e+": sensor.probabilityPerMinuteは0～1にしてください。"),(!Array.isArray(i.domains)||!i.domains.length||i.domains.some(r=>!Ft.includes(r)))&&n.push(e+": sensor\
.domainsには対象領域を1つ以上指定してください。"),typeof i.terrainLOS!="boolean"&&n.push(e+": sensor.terrainLOSはbooleanにしてください。"),i.mountHeight!==
void 0&&(!ne(i.mountHeight)||i.mountHeight<0||i.mountHeight>1e3)&&n.push(e+": sensor.mountHeightは0～1000mにしてください。")}return n}function ht(t,e){if(t===void 0)return[];
let n=[];return!t||typeof t!="object"||Array.isArray(t)?["missionはオブジェクトにしてください。"]:(["detect","arrive","state"].includes(t.type)||n.push("mission.type\
はdetect・arrive・stateにしてください。"),t.type==="arrive"&&(!Array.isArray(t.responderIds)||!t.responderIds.length||t.responderIds.length>2e3||t.responderIds.some(i=>typeof i!=
"string")||new Set(t.responderIds).size!==t.responderIds.length)&&n.push("mission.responderIdsに到着を評価する単体ユニットIDを指定してください。"),t.type!==
"state"&&(!pt.includes(t.observerFaction)||!pt.includes(t.targetFaction)||t.observerFaction===t.targetFaction)&&n.push("観測側と対象側には異なる陣営を指定してください。"),
(t.type==="state"?["any","all","count"]:["any","all"]).includes(t.join)||n.push("mission.joinはany・all（状態計測ではcountも可）にしてください。"),t.type==="sta\
te"&&(typeof t.assignmentId!="string"||typeof t.nodeId!="string")&&n.push("計測するタスクと状態を選択してください。"),t.join==="count"&&(!Number.isInteger(t.requiredCount)||
t.requiredCount<1||t.requiredCount>2e3)&&n.push("到達を必要とする担当数は1～2000です。"),(!ne(t.deadline)||t.deadline<=0||t.deadline>e)&&n.push("mission.deadlineは0よ\
り大きく終了時刻以下にしてください。"),t.targetIds!==void 0&&(!Array.isArray(t.targetIds)||!t.targetIds.length||t.targetIds.length>2e3||t.targetIds.some(i=>typeof i!=
"string")||new Set(t.targetIds).size!==t.targetIds.length)&&n.push("mission.targetIdsは重複しない対象IDの配列にしてください。"),n)}function mt(t,e){if(t===void 0)
return[];if(!t||typeof t!="object"||Array.isArray(t))return["analysisはオブジェクトにしてください。"];let n=[];return t.groupId!==void 0&&typeof t.groupId!="string"&&
n.push("analysis.groupIdは文字列にしてください。"),t.groupId&&(!Array.isArray(t.counts)||!t.counts.length||t.counts.length>12||t.counts.some(i=>!Number.isInteger(i)||i<
0||i>2e3)||new Set(t.counts).size!==t.counts.length)&&n.push("analysis.countsは重複しない0～2000の整数（最大12条件）にしてください。"),(!Number.isInteger(t.
trials)||t.trials<1||t.trials>2e3)&&n.push("analysis.trialsは1～2000にしてください。"),(!ne(t.step)||t.step<.1||t.step>300||Math.ceil(e/t.step)>1e5)&&n.push("判定間隔は0.1～300\
秒、シナリオ全体で10万区間以内にしてください。"),(!ne(t.requiredRate)||t.requiredRate<0||t.requiredRate>1)&&n.push("analysis.requiredRateは0～1にしてください。"),
n.push(...ut(t,e)),n}var Ue=2e3,Rt=["ground","surface","subsurface","air"];var je=t=>JSON.parse(JSON.stringify(t)),q=t=>typeof t=="number"&&Number.isFinite(t),gt=t=>t&&["x","y","z"].every(e=>q(t[e]));function Oe(t){let e=[];if(!t||typeof t!="object")throw new Error(
"シナリオはオブジェクトで指定してください。");[1,2,3].includes(t.version)||e.push("versionは1・2・3にしてください。"),t.unitsSystem!=="SI"&&e.push("\
unitsSystemはSI（m・s）にしてください。"),(typeof t.title!="string"||!t.title.trim()||t.title.length>160)&&e.push("titleは1～160文字で指定してください。"),
(!q(t.duration)||t.duration<=0||t.duration>86400)&&e.push("durationは0より大きく86400秒以下にしてください。");let n=t.terrain;!n||!Number.isInteger(n.columns)||!Number.
isInteger(n.rows)||n.columns<2||n.rows<2||n.columns>513||n.rows>513?e.push("terrainのcolumns・rowsは2～513の整数にしてください。"):((!q(n.spacing)||n.spacing<1||n.spacing>
1e4)&&e.push("terrain.spacingは1～10000mにしてください。"),n.spacingY!==void 0&&(!q(n.spacingY)||n.spacingY<1||n.spacingY>1e4)&&e.push("terrain.spacingYは1～10000mにしてください。"),
(!n.origin||!q(n.origin.x)||!q(n.origin.y))&&e.push("terrain.originのx・yが必要です。"),(!Array.isArray(n.elevations)||n.elevations.length!==n.columns*n.rows||n.elevations.
some(o=>!q(o)||o<-12e3||o>1e4))&&e.push("terrain.elevationsは格子数と同じ長さの標高配列（-12000～10000m）にしてください。"),q(n.seaLevel)||e.push("terrain.\
seaLevelが必要です。")),t.seed!==void 0&&(typeof t.seed!="string"||t.seed.length>100)&&e.push("seedは100文字以下の文字列にしてください。"),t.trial!==void 0&&
(!Number.isInteger(t.trial)||t.trial<0||t.trial>1e9)&&e.push("trialは0～1000000000の整数にしてください。");let i=t.groups??[],r=new Set;if(!Array.isArray(i)||i.length>
100)e.push("groupsは最大100件の配列にしてください。");else for(let o of i){if(!o||typeof o!="object"){e.push("groupはオブジェクトにしてください。");continue}
o.enabled!==void 0&&typeof o.enabled!="boolean"&&e.push("group.enabledはbooleanにしてください。"),(typeof o.id!="string"||!/^[a-zA-Z0-9_-]{1,50}$/.test(o.id)||r.has(o.id))&&
e.push("group.idは重複しない英数字・_・-（50文字以下）にしてください。"),r.add(o.id),(typeof o.name!="string"||!o.name.trim()||o.name.length>100)&&e.push("\
group.nameは1～100文字にしてください。"),(!Number.isInteger(o.count)||o.count<1||o.count>Ue)&&e.push("group.countは1～2000にしてください。"),o.loopStartMode!==
void 0&&!["template","even","random"].includes(o.loopStartMode)&&e.push("group.loopStartModeはtemplate、even、randomにしてください。"),["grid","random"].includes(o.placement)||
e.push("group.placementはgridまたはrandomにしてください。");for(let a of["width","height"])(!q(o[a])||o[a]<0||o[a]>1e5)&&e.push("group."+a+"は0～100000mにしてください。")}
if(!Array.isArray(t.units)||t.units.length>Ue)e.push("unitsは最大2000件の配列にしてください。");else{let o=new Set,a=new Set(t.units.map(s=>s?.id));[...t.units,...Array.
isArray(i)?i.map(s=>s?.template):[]].forEach((s,d)=>{let c="units["+d+"]";if(!s||typeof s!="object"){e.push(c+": オブジェクトが必要です。");return}if((typeof s.id!="str\
ing"||!/^[a-zA-Z0-9_-]{1,80}$/.test(s.id)||d<t.units.length&&o.has(s.id))&&e.push(c+": idは重複しない英数字・_・-にしてください。"),d<t.units.length&&o.add(s.id),
(typeof s.name!="string"||!s.name.trim()||s.name.length>120)&&e.push(c+": nameは1～120文字にしてください。"),e.push(...ft(s,c),...lt(s,c,a)),t.version===3&&s.behavior&&
e.push(c+": 旧行動ルールは読み込み時にノードへ変換してください。"),Rt.includes(s.domain)||e.push(c+": domainが不正です。"),["friendly","hostile","ne\
utral"].includes(s.faction)||e.push(c+": factionが不正です。"),s.enabled!==void 0&&typeof s.enabled!="boolean"&&e.push(c+": enabledはbooleanにしてください。"),typeof s.
manned!="boolean"&&e.push(c+": mannedはbooleanにしてください。"),(!q(s.speed)||s.speed<0||s.speed>1500)&&e.push(c+": speedは0～1500m/sにしてください。"),gt(s.initial)||
e.push(c+": initialのx,y,zが必要です。"),["once","loop","pingpong"].includes(s.routeMode)||e.push(c+": routeModeが不正です。"),s.groupId!==void 0&&d<t.units.length&&e.
push(c+": groupIdは生成ユニット専用です。"),s.motion!==void 0)if(!s.motion||typeof s.motion!="object"||Array.isArray(s.motion))e.push(c+": motionはオブジェクトにしてください。");else
for(let[f,l,y]of[["horizontal",0,1e4],["vertical",0,3e3],["commonHorizontal",0,1e4],["scale",10,1e5],["startDelay",0,86400],["speedVariation",0,1],["loopStart",0,1]])s.motion[f]!==
void 0&&(!q(s.motion[f])||s.motion[f]<l||s.motion[f]>y)&&e.push(c+": motion."+f+"は"+l+"～"+y+"にしてください。");(!Array.isArray(s.route)||s.route.length>500||s.route.some(
f=>!gt(f)))&&e.push(c+": routeは最大500件、各点にx,y,zが必要です。")})}if(Array.isArray(t.units)&&Array.isArray(i)&&!e.length){let o=t.units.length+i.reduce((a,s)=>a+
s.count,0);if(o>Ue)e.push("単体と群を合わせて最大2000ユニットにしてください。");else{let a=Ye(t);new Set(a.map(s=>s.id)).size!==o&&e.push("生成ユニットのidが単体ユニットと重\
複しています。")}}if(e.push(...ht(t.mission,t.duration),...mt(t.analysis,t.duration),...De(t),...Xe(t)),t.mission?.type==="arrive"&&t.mission.responderIds?.some(o=>!t.units?.
some(a=>a.id===o))&&e.push("到着評価の対象となる単体ユニットが見つかりません。"),t.version===3&&!e.length)for(let o of[...t.analysis?.factors??[],...t.analysis?.
uncertainties??[]])try{dt(t,o)}catch(a){e.push(a.message)}if(e.length)throw new Error(e.slice(0,30).join(`
`));return it(je(t))}var Je=class{constructor(e){this.data=e,this.minX=e.origin.x,this.minY=e.origin.y,this.maxX=this.minX+(e.columns-1)*e.spacing,this.maxY=this.minY+(e.rows-1)*(e.
spacingY??e.spacing),this.cellSize=Math.min(e.spacing,e.spacingY??e.spacing)}contains(e,n){return q(e)&&q(n)&&e>=this.minX&&e<=this.maxX&&n>=this.minY&&n<=this.maxY}height(e,n){if(!this.
contains(e,n))return null;let i=this.data,r=(e-this.minX)/i.spacing,o=(n-this.minY)/(i.spacingY??i.spacing),a=Math.min(i.columns-2,Math.floor(r)),s=Math.min(i.rows-2,Math.floor(o)),
d=r-a,c=o-s,f=(l,y)=>i.elevations[(s+y)*i.columns+a+l];return(f(0,0)*(1-d)+f(1,0)*d)*(1-c)+(f(0,1)*(1-d)+f(1,1)*d)*c}project(e,n){let i={...e},r=this.height(i.x,i.y),o=this.data.seaLevel;
return r===null?{point:i,error:"地形データの範囲外です"}:n==="ground"&&(i.z=r,r<=o)?{point:i,error:"地上ユニットは陸上に配置してください"}:n==="surface"&&
(i.z=o,r>o-5)?{point:i,error:"水上ユニットには5m以上の水深が必要です"}:n==="subsurface"&&(i.z>o-1||i.z<r+5||r>=o)?{point:i,error:"水中ユニットは海面下かつ海底から5m以上離してください"}:
n==="air"&&i.z<=Math.max(r,o)+10?{point:i,error:"空中ユニットは地表・海面から10mより高くしてください"}:{point:i,error:null}}},ze=(t,e)=>Math.hypot(t.x-e.x,t.
y-e.y,t.z-e.z),we=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function _t(t,e){let n=[0];for(let d=1;d<t.length;d++)n.push(n.at(-1)+ze(t[d-1],t[d]));let i=n.
at(-1);if(i===0)return t;let r=i*e,o=n.findIndex((d,c)=>c>0&&d>r),a=o<0?t.length-1:o,s=we(t[a-1],t[a],(r-n[a-1])/(n[a]-n[a-1]));return[s,...t.slice(a,-1),...t.slice(0,a),{...s}]}var ue=class{constructor(e,{
deferPaths:n=!1}={}){let i=Oe(e);this.source=i,this.scenario={...i,units:Ye(i)},this.nodeCount=0,this.terrain=new Je(this.scenario.terrain),this.paths=n?new Map:new Map(this.scenario.
units.filter(r=>r.enabled!==!1).map(r=>[r.id,this.compile(r)]))}compile(e){let n=this.terrain.project(e.initial,e.domain),i=[{...n.point,d:0}],r=e.motion??{},o=Q(this.scenario,e.id,
"motion"),a=(r.startDelay??0)*B(o+"|delay"),s=e.speed*(1+(B(o+"|speed")*2-1)*(r.speedVariation??0)),d={delay:a,actualSpeed:s},c=e.routeMode==="loop"?(r.loopStart??0)%1:0,f=c>0&&e.route.
length>0;if(n.error&&!f)return{...d,nodes:i,length:0,error:n.error,errorAt:"初期位置",periodic:!1};let l=[n.point,...e.route.map(v=>this.terrain.project(v,e.domain).point)];e.route.
length&&e.routeMode==="loop"&&l.push(n.point);let y=l.slice(1).reduce((v,k,T)=>v+ze(l[T],k),0);if(y>0&&(r.horizontal??0)+(r.vertical??0)+(r.commonHorizontal??0)>0){let v=[n.point],
k=r.scale??2e3,T=Math.min(125,this.terrain.cellSize/4,k/8),I=0;for(let S=1;S<l.length;S++){let R=l[S-1],D=l[S],p=ze(R,D),P=Math.max(1,Math.ceil(p/T));if(P>2e4)throw new Error("航跡生成\
の区間が長すぎます。");for(let Y=1;Y<=P;Y++){let re=I+p*Y/P,oe=we(R,D,Y/P),me=Math.min(1,re/k,(y-re)/k),ge=Math.max(0,me),ye=ge*ge*(3-2*ge),se=Le(o,re,k),m=Le(Q(this.scenario,
e.groupId??e.id,"common-motion"),re,k);if(oe.x+=ye*(se[0]*(r.horizontal??0)+m[0]*(r.commonHorizontal??0)),oe.y+=ye*(se[1]*(r.horizontal??0)+m[1]*(r.commonHorizontal??0)),["subsurfa\
ce","air"].includes(e.domain)&&(oe.z+=ye*se[2]*(r.vertical??0)),v.push(oe),v.length>1e5)throw new Error("航跡生成の点数が多すぎます。経路を短くするか変動間隔を大きくしてください。")}
I+=p}l=v}if(f){let v=[l[0]],k=Math.min(125,this.terrain.cellSize/4);for(let I=1;I<l.length;I++){let S=l[I-1],R=l[I],D=Math.max(1,Math.ceil(Math.hypot(R.x-S.x,R.y-S.y)/k));if(D>2e4)
return{...d,nodes:i,length:0,error:"経路区間が長すぎます",errorAt:"初期位置",periodic:!1};for(let p=1;p<=D;p++)if(v.push(this.terrain.project(we(S,R,p/D),e.domain).point),
v.length>2000001)throw new Error("経路全体のサンプル点数が上限200万点を超えました。")}l=_t(v,c);let T=this.terrain.project(l[0],e.domain);if(i=[{...T.point,d:0}],
T.error)return{...d,nodes:i,length:0,error:T.error,errorAt:"初期位置",periodic:!1}}let h=l.slice();e.route.length&&e.routeMode==="pingpong"&&l.push(...h.slice(0,-1).reverse());
let x=Math.min(125,this.terrain.cellSize/4);for(let v=1;v<l.length;v++){let k=l[v-1],T=l[v],I=Math.max(1,Math.ceil(Math.hypot(T.x-k.x,T.y-k.y)/x));if(I>2e4)return{...d,nodes:i,length:i.
at(-1).d,error:"経路区間が長すぎます",errorAt:"区間 "+v,periodic:!1};for(let S=1;S<=I;S++){let R=this.terrain.project(we(k,T,S/I),e.domain);if(R.error)return{...d,nodes:i,
length:i.at(-1).d,error:R.error,errorAt:"区間 "+v,periodic:!1};let D=i.at(-1),p=D.d+ze(D,R.point);if(p>D.d&&(i.push({...R.point,d:p}),++this.nodeCount>2e6))throw new Error("経路全体の\
サンプル点数が上限200万点を超えました。")}}return{...d,nodes:i,length:i.at(-1).d,error:null,errorAt:null,periodic:e.routeMode!=="once"}}evaluate(e){let n=Math.min(
this.scenario.duration,Math.max(0,Number(e)||0));return{time:n,units:this.scenario.units.map(i=>this.evaluateUnit(i,n))}}evaluateUnit(e,n,i=!0){if(e.enabled===!1)return{id:e.id,position:{
...e.initial},status:"disabled",heading:0,distance:0,routeDistance:0,error:null,errorAt:null,actualSpeed:0,startDelay:0,eta:null};let r=Math.max(0,Number(n)||0),o=i?Math.min(this.scenario.
duration,r):r,a=this.paths.get(e.id),s=a.actualSpeed??e.speed,d=a.delay??0,c=s*Math.max(0,o-d),f=!a.periodic&&s>0&&o>=d+a.length/s?Math.max(c,a.length):c,l=a.periodic&&a.length>0?f%
a.length:Math.min(f,a.length),y=0,h=a.nodes.length-1;for(;y<h;){let I=Math.ceil((y+h)/2);a.nodes[I].d<=l?y=I:h=I-1}let x=a.nodes[y],v=a.nodes[Math.min(y+1,a.nodes.length-1)],k=we(x,
v,v.d>x.d?(l-x.d)/(v.d-x.d):0);e.domain==="ground"&&(k.z=this.terrain.height(k.x,k.y)??k.z);let T=a.length===0?"idle":"moving";return a.error&&f>=a.length?T="blocked":!a.periodic&&
a.length>0&&f>=a.length?T="arrived":s===0?T="idle":o<d&&(T="waiting"),{id:e.id,position:k,status:T,heading:Math.atan2(v.x-x.x,v.y-x.y),distance:Math.min(f,a.periodic?f:a.length),routeDistance:a.
length,error:a.error,errorAt:a.errorAt,actualSpeed:s,startDelay:Number.isFinite(d)?d:null,eta:s>0&&Number.isFinite(d)?d+a.length/s:null}}routePoints(e){return this.paths.get(e)?.nodes||
[]}};function yt(t){let e=Oe(t);if(e.version===3)return e;e.version=3,e.behaviors??=[],e.behaviorAssignments??=[];let n=e.recording?.step??e.analysis?.step??10;e.recording??={step:n,interval:n},
e.analysis&&(e.analysis={...at(e.analysis),step:n});for(let[i,r]of[...e.units.map(o=>["unit:"+o.id,o]),...(e.groups??[]).map(o=>["group:"+o.id,o.template])]){let o=r.behavior;if(o){
if(o.hold||o.rules.length){if(e.behaviorAssignments.some(l=>l.targets.includes(i)))throw Error("旧ルールとタスクが重複しています: "+i);let a=new Set;for(let l of o.
rules){if(a.has(l.when)||l.state!=="any"&&!(o.hold&&l.when==="received"))throw Error("自動変換できない旧ルールです。同じ条件の複数動作・状態条件はノードで再設計してください: "+
i);a.add(l.when)}let s="import-"+i.replace(":","-");if(e.behaviors.some(l=>l.id===s)||e.behaviorAssignments.some(l=>l.id===s))throw Error("変換先IDが重複しています: "+s);
let d=o.hold?"signal":"follow",c=[{id:d,kind:o.hold?"signal":"follow",x:320,y:70}],f=[];o.hold&&c.push({id:"follow",kind:"follow",x:1080,y:70}),o.rules.forEach((l,y)=>{let h=l.when===
"received"&&o.hold?"signal":"follow";l.action==="depart"?(c.push({id:l.id,kind:"wait",parameter:"preparation",seconds:o.preparation,x:680,y:70+y*150}),f.push({from:h,to:l.id,when:l.
when,once:l.once},{from:l.id,to:"follow",when:"elapsed"})):(c.push({id:l.id,kind:"report",receiverId:l.receiverId,x:680,y:70+y*150}),f.push({from:h,to:l.id,when:l.when,once:l.once},
{from:l.id,to:d,when:"sent",resume:!0},{from:l.id,to:d,when:"sendFailed",resume:!0}))}),e.behaviors.push({id:s,name:r.name+"の挙動",initial:d,triggers:[],nodes:c,edges:f}),e.behaviorAssignments.
push({id:s,name:r.name+"のタスク",behaviorId:s,targets:[i],spacing:"none",preparation:o.preparation});for(let l of[e.analysis?.factors,e.analysis?.uncertainties])for(let y of l??
[])y.target===i&&y.parameter==="behavior.preparation"&&(y.target="assignment:"+s)}delete r.behavior}}return Oe(e)}function Be(t,e,n){let i=Math.hypot(n.x-e.x,n.y-e.y),r=Math.max(1,Math.ceil(i/Math.min(125,t.cellSize/4)));for(let o=0;o<=r;o++){let a=o/r,s=e.x+(n.x-e.x)*a,d=e.y+(n.y-e.y)*a,c=e.z+
(n.z-e.z)*a,f=t.height(s,d);if(f===null||c<f-1e-6)return!1}return!0}function bt(t,e,n,i){if(i<=0||n<=0||e>=t.range||t.probabilityPerMinute<=0)return 0;if(t.probabilityPerMinute>=1)
return 1;let r=-Math.log1p(-t.probabilityPerMinute)/60;return-Math.expm1(-r*i*n*(1-e/t.range)**2)}var qe=(t,e)=>({...t,z:t.z+(e.sensor?.mountHeight??(e.domain==="ground"?2:0))}),Dt=(t,e,n)=>Math.
floor(t/n)+","+Math.floor(e/n);function vt(t,e){let n=new Map;for(let i of t){let r=Dt(i.position.x,i.position.y,e);n.has(r)||n.set(r,[]),n.get(r).push(i)}return n}function*It(t,e,n){
let i=Math.floor(e.x/n),r=Math.floor(e.y/n);for(let o=-1;o<=1;o++)for(let a=-1;a<=1;a++)for(let s of t.get(i+a+","+(r+o))??[])yield s}var xt=256*1048576,$e=t=>{let e=new Uint8Array(t.buffer,t.byteOffset,t.byteLength),n="";for(let i=0;i<e.length;i+=8192)n+=String.fromCharCode(...e.subarray(i,i+8192));return btoa(n)},
He=(t,e,n)=>{if(typeof t!="string"||t.length>Math.ceil(n*e.BYTES_PER_ELEMENT/3)*4+4)throw Error("記録配列の長さが不正です。");let i=atob(t);if(i.length!==n*e.BYTES_PER_ELEMENT)
throw Error("記録配列の長さが不正です。");let r=new Uint8Array(i.length);for(let o=0;o<i.length;o++)r[o]=i.charCodeAt(o);return new e(r.buffer)};function Ke(t){if(!t.frames)
throw Error("計算・記録を先に実行してください。");let e={type:"SimSim-recording",version:2,model:Te,source:je(t.source),unitIds:t.states.map(n=>n.unit.id),nodeNames:t.
nodeNames,result:t.result,frames:t.frames.map(n=>({time:n.time,values:$e(n.values),nodes:$e(n.nodes),status:$e(n.status)}))};if(new TextEncoder().encode(JSON.stringify(e)).byteLength>
xt)throw Error("保存形式で256MiBを超えます。期間・個数を減らしてください。");return e}var Me=t=>t&&["x","y","z"].every(e=>Number.isFinite(t[e])),Lt=new Set(
["detected","sent","sendFailed","received","arrived","elapsed","nodeChanged","departed","preparing","initialized","triggered","near"]);function Ve(t){if(t?.type!=="SimSim-recording"||
t.version!==2||t.model!==Te||!Array.isArray(t.frames)||!t.frames.length)throw Error("対応していない記録モデルです。旧版の記録は元の版で再生してください。");
let e=new ie(t.source),n=e.states.length;if(t.source.version!==3||JSON.stringify(t.unitIds)!==JSON.stringify(e.states.map(o=>o.unit.id))||JSON.stringify(t.nodeNames)!==JSON.stringify(
e.nodeNames))throw Error("記録対象・ノード・シナリオ版が一致しません。");if(t.frames.length*(n*23+8)>Ge||t.frames.length>100001)throw Error("再生記録が上限を超えています。");
let i=-1;if(e.frames=t.frames.map((o,a)=>{if(!Number.isFinite(o.time)||o.time<=i||o.time>e.source.duration||a===0&&o.time!==0)throw Error("記録時刻が不正です。");i=o.time;
let s=He(o.values,Float32Array,n*5),d=He(o.nodes,Uint16Array,n),c=He(o.status,Uint8Array,n);if(s.some(f=>!Number.isFinite(f))||c.some(f=>f>=ce.length))throw Error("記録値が不正です。");
return d.forEach((f,l)=>{let y=e.states[l],h=e.nodeNames[f-1];if(y.graph&&f===0&&![ce.indexOf("standby"),ce.indexOf("blocked")].includes(c[l]))throw Error("起動前の記録状態が不正です。");
if(y.graph?f!==0&&(!h||!y.graph.nodes.some(x=>y.graph.id+":"+x.id===h)):f!==0)throw Error("記録ノードが担当の挙動と一致しません。")}),{time:o.time,values:s,nodes:d,
status:c}}),i!==e.source.duration)throw Error("終了時刻までの記録がありません。");let r=t.result;if(!r||typeof r.success!="boolean"||!Array.isArray(r.events)||!Array.
isArray(r.actionEvents)||r.events.length+r.actionEvents.length>2e5||r.successTime!==null&&(!Number.isFinite(r.successTime)||r.successTime<0||r.successTime>e.source.duration)||r.success!==
(r.successTime!==null))throw Error("記録の評価・イベントが不正です。");for(let[o,a]of[["targetCount",0],["detectedCount",0],["responderCount",0],["reachedCount",0],
["invalidUnits",0],["constrainedPaths",0]])if(!Number.isInteger(r[o])||r[o]<a||r[o]>2e3)throw Error("記録の件数が不正です。");for(let o of[r.events,r.actionEvents]){let a=-1;
for(let s of o){if(!s||!Lt.has(s.type)||!Number.isFinite(s.time)||s.time<a||s.time<0||s.time>e.source.duration||!e.byId.has(s.unitId))throw Error("イベントの種類・参照・時刻が不正です。");
a=s.time;for(let c of["targetId","receiverId","senderId","observerId"])if(s[c]!==void 0&&!e.byId.has(s[c]))throw Error("イベントの参照先がありません。");for(let c of[
"targetPosition","sourcePosition","receiverPosition","observerPosition"])if(s[c]!==void 0&&!Me(s[c]))throw Error("イベントの位置が不正です。");if(s.type==="detected"&&
(!s.targetId||!Me(s.targetPosition)||!Me(s.observerPosition)))throw Error("探知情報が不正です。");if(s.type==="received"&&(!s.senderId||!Me(s.sourcePosition)||!Me(s.receiverPosition)))
throw Error("受信情報が不正です。");let d=e.byId.get(s.unitId);if(s.type==="near"&&(!e.source.destinations?.some(c=>c.id===s.destinationId)||!Number.isFinite(s.distance)||
s.distance<0||!["horizontal","absolute"].includes(s.distanceMode)))throw Error("接近イベントの記録が不正です。");if(s.type==="initialized"&&(s.time!==0||d.graph?.initial!==
s.nodeId))throw Error("初期状態の記録が不正です。");if(s.type==="triggered"&&!d.graph?.triggers.some(c=>c.id===s.triggerId&&c.event===s.event&&c.to===s.nodeId)&&!(s.event===
"scenarioStart"&&s.time===0&&d.graph?.initial===s.nodeId&&t.source.behaviors?.find(c=>c.id===d.graph.id)?.triggers?.some(c=>c.id===s.triggerId&&c.event==="scenarioStart"&&c.to===s.
nodeId)))throw Error("起動イベントの条件が不正です。");if(s.nodeId!==void 0&&!d.graph?.nodes.some(c=>c.id===s.nodeId))throw Error("イベントのノードが不正です。")}}
if(e.source.mission?.type==="state"){Ze(e.source,r);let o=new de(e.source.mission,Ce(e.source)).update(r.actionEvents);if(JSON.stringify(o.stateEntries)!==JSON.stringify(r.stateEntries)||
o.successTime!==r.successTime)throw Error("状態の初回到達記録がイベント履歴と一致しません。")}e.result=je(r);for(let o of[e.result.events,e.result.actionEvents])
for(let a of o)a.type==="triggered"&&a.event==="scenarioStart"&&(a.type="initialized",delete a.event,delete a.triggerId);return e}var Te="trigger-behavior-v3",ce=["idle","moving","arrived","blocked","waiting","standby","preparing"],Ge=128*1048576,ee=(t,e)=>Math.hypot(t.x-e.x,t.y-e.y,t.z-e.z),le=(t,e)=>(t%e+e)%
e,Se=(t,e,n)=>({x:t.x+(e.x-t.x)*n,y:t.y+(e.y-t.y)*n,z:t.z+(e.z-t.z)*n});function Ae(t,e){let n=Math.min(t.length,Math.max(0,e)),i=t.nodes,r=0,o=i.length-1;for(;r<o;){let d=Math.ceil(
(r+o)/2);i[d].d<=n?r=d:o=d-1}let a=i[r],s=i[Math.min(r+1,i.length-1)];return{point:Se(a,s,s.d>a.d?(n-a.d)/(s.d-a.d):0),segment:r,heading:Math.atan2(s.x-a.x,s.y-a.y)}}function wt(t,e){
let n={point:t.nodes[0],along:0,distance:1/0};for(let i=1;i<t.nodes.length;i++){let r=t.nodes[i-1],o=t.nodes[i],a=o.x-r.x,s=o.y-r.y,d=o.z-r.z,c=a*a+s*s+d*d,f=c?Math.max(0,Math.min(
1,((e.x-r.x)*a+(e.y-r.y)*s+(e.z-r.z)*d)/c)):0,l=Se(r,o,f),y=ee(e,l);y<n.distance&&(n={point:l,along:r.d+(o.d-r.d)*f,distance:y})}return n}var ie=class extends ue{constructor(e){super(
yt(e),{deferPaths:!0}),this.frames=null,this.result=null,this.computeCount=0,this.nodeNames=[],this.assignments=this.source.behaviorAssignments,this.initialEvents=[];let n=new Map(
this.source.behaviors.map(i=>[i.id,i]));this.states=[],this.byId=new Map;for(let i of this.scenario.units.filter(r=>r.enabled!==!1).sort((r,o)=>r.id.localeCompare(o.id))){let r=this.
assignments.find(y=>y.targets.includes("unit:"+i.id)||i.groupId&&y.targets.includes("group:"+i.groupId)),o=r?Ie(n.get(r.behaviorId),r):null,a=o?.nodes.find(y=>y.id===o.initial),s=ke(
this.source,r,a,i),c=r?.route?.length>=2||a?.routeId?{...i,initial:s.points[0],route:s.points.slice(1),routeMode:a?.kind==="patrol"?"loop":s.mode,motion:{...i.motion,loopStart:0}}:
i,f=this.compile(c);this.paths.set(i.id,f);let l={unit:i,assignment:r,graph:o,path:f,basePath:f,pathCache:new Map,routeContexts:new Map,nearInside:new Map,node:null,nodeTime:0,position:{
...f.nodes[0]},heading:0,status:"idle",distance:0,progress:0,segment:-1,error:f.errorAt==="初期位置"?f.error:null,fired:new Set,triggerFired:new Set,triggerTimes:new Map,activated:!1,
observation:null,trace:[],routeStarted:null,routePaused:0};if(a?.joinMode==="nearest"){let y=this.terrain.project(i.initial,i.domain);l.position=y.point,y.error&&(l.error=y.error)}
this.states.push(l),this.byId.set(i.id,l);for(let y of o?.nodes??[])this.nodeNames.includes(o.id+":"+y.id)||this.nodeNames.push(o.id+":"+y.id)}this.inactiveUnits=this.scenario.units.
filter(i=>i.enabled===!1).map(i=>super.evaluateUnit(i,0));for(let i of this.assignments){let r=this.states.filter(o=>o.assignment===i);r.forEach((o,a)=>{o.initialPhase=le((i.phase??
0)+(i.spacing==="none"?o.unit.motion?.loopStart??0:a/r.length),1),o.status=o.error?"blocked":"standby",o.graph.initial&&(o.activated=!0,this.enter(o,o.graph.initial,0,!0),this.initialEvents.
push({type:"initialized",time:0,unitId:o.unit.id,nodeId:o.graph.initial}))})}for(let i of this.states)i.graph||Object.assign(i,super.evaluateUnit(i.unit,0))}enter(e,n,i,r=!1,o=!1){
let a=e.node;if(a?.kind==="follow"&&e.routeContexts.set(a.routeId??"default",{path:e.path,started:e.routeStarted,travel:e.routeTravel??0,offset:e.routeOffset??0,paused:i,join:e.join}),
e.node=e.graph.nodes.find(s=>s.id===n),e.nodeTime=i,e.sent=!1,e.elapsed=!1,e.destinationArrived=!1,e.join=null,e.nearInside=new Map([...e.nearInside].filter(([s])=>s.startsWith("tr\
igger:"))),["follow","patrol"].includes(e.node.kind)){let s=ke(this.source,e.assignment,e.node,e.unit),d=s.id+"|"+e.node.kind;if(r&&e.pathCache.set(d,e.path),!e.pathCache.has(d)){let c=!e.
node.routeId;e.pathCache.set(d,this.compile({...e.unit,initial:s.points[0],route:s.points.slice(1),routeMode:s.mode,motion:{...e.unit.motion,...c?{}:{loopStart:0}}}))}e.path=e.pathCache.
get(d),this.paths.set(e.unit.id,e.path)}if(e.error){e.status="blocked";return}if(e.status="idle",e.node.kind==="patrol"){if(r&&e.node.joinMode!=="nearest"){e.progress=(e.node.joinMode===
"start"?0:e.initialPhase)*e.path.length;let s=Ae(e.path,e.progress);e.position=s.point,e.heading=s.heading,e.segment=s.segment}else{let s=(e.node.joinMode??"nearest")==="nearest"?wt(
e.path,e.position):Ae(e.path,0);e.progress=s.along??0,e.join=s.point}e.readyAt=i+(r?e.path.delay:0),e.status=i<e.readyAt?"waiting":"moving"}else if(e.node.kind==="follow"){let s=o?
e.routeContexts.get(e.node.routeId??"default"):null;if(s&&s.path===e.path)e.routeStarted=s.started===null?null:s.started+i-s.paused,e.routeTravel=s.travel,e.routeOffset=s.offset,e.
join=s.join;else{let d=e.node.joinMode==="nearest"?wt(e.path,e.position):{point:e.path.nodes[0],along:0};e.routeOffset=d.along,e.routeTravel=d.along,e.routeArrived=!1,e.join=(!r||e.
node.joinMode==="nearest")&&ee(e.position,d.point)>1e-7?d.point:null,e.routeStarted=e.join?null:i-(e.path.actualSpeed?e.routeOffset/e.path.actualSpeed:0)-(e.routeOffset>0?e.path.delay:
0)}e.status=e.join?"moving":i<(e.routeStarted??i)+(r?e.path.delay:0)?"waiting":e.path.length&&e.path.actualSpeed?"moving":"idle"}else e.node.kind==="signal"?e.status="standby":e.node.
kind==="wait"?e.status=e.node.parameter==="preparation"?"preparing":"waiting":e.node.kind==="move"&&(e.status="moving")}activate(e,n,i,r,o){if(!e?.graph||e.status==="blocked")return!1;
let a=_e(e.graph).find(c=>c.event===n&&(n!=="near"||Z(c)===o?.conditionKey)&&(n!=="time"||Math.abs(this.nextTriggerTime(e,c)-i)<1e-8)&&(!e.triggerFired.has(c.id)||c.once===!1));if(!a)
return!1;let s=e.unit.id+"|trigger|"+a.id;if(o?.trace?.includes(s))return!1;if(o?(e.observation=o,e.trace=[...o.trace??[],s]):(e.observation=null,e.trace=[]),e.trace.length>64)throw Error(
"情報の中継が64段を超えました。");e.triggerFired.add(a.id),e.triggerTimes.set(a.id,i);let d=e.node?.id;return e.activated=!0,this.enter(e,a.to,i),r.push({type:"trigge\
red",time:i,unitId:e.unit.id,triggerId:a.id,event:n,nodeId:a.to}),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d??null,nodeId:a.to}),e.node.parameter==="preparation"&&r.
push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&r.push({type:"departed",time:i,unitId:e.unit.id,nodeId:e.node.id}),!0}nextTriggerTime(e,n){
return e.triggerFired.has(n.id)?n.once===!1?(e.triggerTimes.get(n.id)??0)+n.seconds:1/0:n.seconds}transition(e,n,i,r,o){if(!e?.graph||e.status==="blocked")return!1;if(this.activate(
e,n,i,r,o))return!0;if(!e.node)return!1;let a=e.graph.edges.find(c=>c.from===e.node.id&&c.when===n&&(n!=="near"||Z(c)===o?.conditionKey));if(!a)return!1;let s=e.unit.id+"|"+a.from+
"|"+Z(a);if(a.once&&e.fired.has(s)||o?.trace?.includes(s))return!1;if(a.once&&e.fired.add(s),o&&(e.observation=o,e.trace=[...o.trace??[],s]),e.trace.length>64)throw Error("情報の中継が64\
段を超えました。");e.node.kind==="follow"&&(e.pauseTime=i);let d=e.node.id;return this.enter(e,a.to,i,!1,a.resume),r.push({type:"nodeChanged",time:i,unitId:e.unit.id,from:d,
nodeId:a.to}),e.node.parameter==="preparation"&&r.push({type:"preparing",time:i,unitId:e.unit.id,nodeId:e.node.id}),e.node.kind==="follow"&&!a.resume&&r.push({type:"departed",time:i,
unitId:e.unit.id,nodeId:e.node.id}),!0}destination(e,n=e.node,i){let r=xe(this.source,e.assignment,n);return r?r.kind==="point"?r.point:i?.get(r.unitId)??this.byId.get(r.unitId)?.position??
null:null}predict(e,n,i,r){if(e.status==="blocked"||!e.node&&e.graph)return e.position;if(!e.graph||e.node.kind==="follow"&&!e.join){let c=e.graph?e.routeStarted??0:0;return ue.prototype.
evaluateUnit.call(this,e.unit,Math.max(0,n-c),!1).position}let o=Math.max(0,n-(this.currentTime??0));if(e.node.kind==="patrol"&&!e.join)return Ae(e.path,le(e.progress+(i.get(e.unit.
id)??e.path.actualSpeed)*Math.max(0,n-Math.max(this.currentTime??0,e.readyAt)),e.path.length||1)).point;let a=e.join??(e.node.kind==="move"?this.destination(e,e.node,r):null);if(!a)
return e.position;let s=ee(e.position,a),d=Math.min(s,e.path.actualSpeed*o);return Se(e.position,a,s?d/s:1)}replayPath(e,n){if(!e.graph)return e.path;if(!e.replayRoutes){e.replayRoutes=
[{time:0,node:e.graph.nodes.find(a=>a.id===e.graph.initial)}];for(let a of this.result.actionEvents)a.unitId===e.unit.id&&a.type==="nodeChanged"&&e.replayRoutes.push({time:a.time,node:e.
graph.nodes.find(s=>s.id===a.nodeId)});e.replayRoutes=e.replayRoutes.filter(a=>["follow","patrol"].includes(a.node?.kind))}let i=e.replayRoutes.findLast(a=>a.time<=n)?.node;if(!i)return e.
basePath;let r=ke(this.source,e.assignment,i,e.unit),o=r.id+"|"+i.kind;return e.pathCache.has(o)||e.pathCache.set(o,this.compile({...e.unit,initial:r.points[0],route:r.points.slice(
1),routeMode:r.mode,motion:{...e.unit.motion,...i.routeId?{loopStart:0}:{}}})),e.pathCache.get(o)}stateSnapshot(e,n=e.path){return{id:e.unit.id,position:{x:e.position.x,y:e.position.
y,z:e.position.z},heading:e.heading,status:e.status,distance:e.distance,routeDistance:n.length,error:e.error,errorAt:n.errorAt,actualSpeed:n.actualSpeed,startDelay:n.delay,nodeId:e.
node?.id,behaviorId:e.graph?.id,eta:null}}evaluate(e){let n=Math.max(0,Math.min(this.source.duration,Number(e)||0));if(!this.frames)return{time:0,units:[...this.states.map(y=>this.
stateSnapshot(y)),...this.inactiveUnits],actionsPending:!0,recordingPending:!0};let i=0,r=this.frames.length-1;for(;i<r;){let y=Math.ceil((i+r)/2);this.frames[y].time<=n?i=y:r=y-1}
let o=this.frames[i],a=this.frames[Math.min(i+1,this.frames.length-1)],s=a.time>o.time?(n-o.time)/(a.time-o.time):0,d=this.states.map((y,h)=>{let x=h*5,v=o.values,k=a.values,T=this.
nodeNames[o.nodes[h]-1],I=le(k[x+3]-v[x+3]+Math.PI,Math.PI*2)-Math.PI;return{...this.stateSnapshot(y,this.replayPath(y,n)),position:{x:v[x]+(k[x]-v[x])*s,y:v[x+1]+(k[x+1]-v[x+1])*s,
z:v[x+2]+(k[x+2]-v[x+2])*s},heading:v[x+3]+I*s,distance:v[x+4]+(k[x+4]-v[x+4])*s,status:ce[o.status[h]],nodeId:T?.split(":")[1],error:o.status[h]===3?"記録された地形制約停止":
null,actualSpeed:a.time>o.time?Math.max(0,(k[x+4]-v[x+4])/(a.time-o.time)):0}}),c=this.result,f=c.events.filter(y=>y.time<=n),l=this.source.mission;return{time:n,units:[...d,...this.
inactiveUnits],actionEvents:c.actionEvents.filter(y=>y.time<=n),mission:l?{...l.type==="state"?Ee(c.stateEntries,l,c.stateTargetCount,n):{},events:f,detectedCount:new Set(f.map(y=>y.
targetId)).size,targetCount:c.targetCount,reachedCount:new Set(c.actionEvents.filter(y=>y.type==="arrived"&&y.time<=n&&l.responderIds?.includes(y.unitId)).map(y=>y.unitId)).size,responderCount:c.
responderCount,status:c.successTime!==null&&c.successTime<=n?"success":n>=l.deadline?"failure":"pending",deadline:l.deadline}:void 0,recording:{frames:this.frames.length,bytes:this.
recordBytes,computeCount:this.computeCount,step:this.source.recording.step,interval:this.source.recording.interval},actionsPending:!1}}trailPoints(e,n,i=1e3){if(!this.frames)return[];
let r=this.states.findIndex(f=>f.unit.id===e);if(r<0)return[];let o=this.frames.filter(f=>f.time<=n),a=Math.max(1,Math.ceil(o.length/i)),s=o.filter((f,l)=>l%a===0||l===o.length-1).
map(f=>({x:f.values[r*5],y:f.values[r*5+1],z:f.values[r*5+2]})),d=this.frames.findLast(f=>f.time<=n),c=this.frames.find(f=>f.time>n)??d;if(d){let f=c.time>d.time?(n-d.time)/(c.time-
d.time):0,l=r*5;s.push({x:d.values[l]+(c.values[l]-d.values[l])*f,y:d.values[l+1]+(c.values[l+1]-d.values[l+1])*f,z:d.values[l+2]+(c.values[l+2]-d.values[l+2])*f})}return s}record(e,n){
if(n.at(-1)?.time===e)return;let i=this.states.length,r=new Float32Array(i*5),o=new Uint16Array(i),a=new Uint8Array(i);if(this.states.forEach((s,d)=>{r.set([s.position.x,s.position.
y,s.position.z,s.heading,s.distance],d*5),o[d]=s.node?this.nodeNames.indexOf(s.graph.id+":"+s.node.id)+1:0,a[d]=ce.indexOf(s.status)}),n.push({time:e,values:r,nodes:o,status:a}),n.
length>100001||n.length*(i*23+8)>Ge)throw Error("再生記録が128MiBを超えました。期間・個数・記録間隔を調整してください。")}get recordBytes(){return this.
frames?.reduce((e,n)=>e+8+n.values.byteLength+n.nodes.byteLength+n.status.byteLength,0)??0}};function We(t,e,n,i,r){let o=t.terrain.project(n,e.unit.domain);if(o.error)return e.status=
"blocked",e.error=o.error,!1;let a=ee(e.position,o.point),s=Math.min(a,i*r),d=Se(e.position,o.point,a?s/a:1),c=Math.max(1,Math.ceil(s/Math.min(125,t.terrain.cellSize/4)));for(let f=1;f<=
c;f++){let l=t.terrain.project(Se(e.position,d,f/c),e.unit.domain);if(l.error)return e.status="blocked",e.error=l.error,!1}return e.heading=Math.atan2(d.x-e.position.x,d.y-e.position.
y),e.position=t.terrain.project(d,e.unit.domain).point,e.distance+=s,e.status=a<=s+1e-7?"arrived":"moving",e.status==="arrived"}function*Mt(t,e=t.source?.mission??t.scenario.mission,n,i={}){
let r=t instanceof ie?t:new ie(t.source),o=i.horizon??e?.deadline??r.source.duration,a=i.record??!1,s=r.source.recording.step,d=r.source.recording.interval;if(!Number.isFinite(o)||
o<0||o>r.source.duration)throw Error("計算終了時刻が不正です。");if(r.computeCount)throw Error("計算済みです。新しい試行を作成してください。");r.computeCount++;
let c=r.states,f=[...r.initialEvents],l=new Map,y=new Set,h=[],x=a?[]:null,v=c.filter(m=>m.unit.faction!=="neutral"),k=e?.type==="state"?[]:e?.targetIds?e.targetIds.map(m=>r.byId.get(
m)).filter(Boolean):c.filter(m=>e?m.unit.faction===e.targetFaction:m.unit.faction!=="neutral");if(e&&e.type!=="state"&&e.targetIds?.some(m=>!r.scenario.units.some(w=>w.id===m&&w.faction===
e.targetFaction))||e?.type==="detect"&&!r.scenario.units.some(m=>m.faction===e.targetFaction))throw Error("成功条件に合う対象がありません。");let T=e?.type==="arriv\
e"?e.responderIds.filter(m=>r.byId.has(m)):[],I=e?.type==="state"?new de(e,c.filter(m=>m.assignment?.id===e.assignmentId).map(m=>m.unit.id)):null,S={success:!1,successTime:null,targetCount:e?.
type==="state"?v.length:k.length,detectedCount:0,responderCount:T.length,reachedCount:0,events:[],actionEvents:f,invalidUnits:c.filter(m=>m.error).length,constrainedPaths:0},R=0,D=0,
p=0,P=Math.max(1,...c.filter(m=>m.unit.sensor?.enabled).map(m=>m.unit.sensor.range)),Y=(m,w,z,A={})=>(f.push({type:w,time:z,unitId:m.unit.id,nodeId:m.node?.id,...A}),r.transition(m,
w,z,f,A));function re(){let m=new Map;for(let w of r.assignments){let z=new Map;for(let A of c.filter(g=>g.assignment===w&&g.node?.kind==="patrol"&&g.status!=="blocked"&&!g.join)){
let g=A.node.routeId??"default";z.has(g)||z.set(g,[]),z.get(g).push(A)}for(let A of z.values()){A.sort((g,E)=>g.progress/g.path.length-E.progress/E.path.length);for(let g=0;g<A.length;g++){
let E=A[g],F=A[(g+1)%A.length],b=A.length===1?E.path.length:le(F.progress/F.path.length-E.progress/E.path.length,1)*E.path.length,j=w.spacing==="fixed"?w.spacingDistance??500:E.path.
length/A.length,U=E.path.actualSpeed,$=U*(E.node.speedFraction??.7);m.set(E.unit.id,w.spacing==="none"||A.length===1?$:Math.max(0,Math.min(U,$+(w.gain??.01)*(b-j))))}}}return m}function oe(m,w){
let z=m.unit.communication,A=r.byId.get(m.node.receiverId??m.assignment.receiverId),g=A?ee(m.position,A.position):1/0,E=m.observation,F=Q(r.source,m.unit.id,"unified-report-v2")+"|"+
JSON.stringify([m.node.id,E?.targetId,E?.originObserverId??E?.observerId??m.unit.id]),b=null;z?.enabled?!A||A.error?b="受信先不在・配置不正":g>z.range?b="通信範囲外":
z.terrainLOS&&!Be(r.terrain,m.position,A.position)?b="地形遮蔽":B(F)>=z.probability&&(b="通信試行失敗"):b="通信無効",m.sent=!0;let j={receiverId:A?.unit.id,distance:Number.
isFinite(g)?g:null,reason:b,targetId:E?.targetId,targetPosition:E?.targetPosition,observationTime:E?.observationTime??E?.sampleTime??E?.time,originObserverId:E?.originObserverId??E?.
observerId??m.unit.id,trace:m.trace,sourcePosition:{...m.position},receiverPosition:A?{...A.position}:void 0};return b||h.push({...j,type:"received",time:w+z.delay,unitId:A.unit.id,
senderId:m.unit.id}),Y(m,b?"sendFailed":"sent",w,j)}function me(m){return[...(m.graph?.triggers??[]).filter(w=>w.event==="near").map(w=>({c:w,key:"trigger:"+w.id})),...(m.graph?.edges??
[]).filter(w=>w.from===m.node?.id&&w.when==="near").map(w=>({c:w,key:"edge:"+w.from+"|"+Z(w)}))]}function ge(m,w){let z=!1;for(let{c:A,key:g}of me(m)){let E=r.destination(m,A);if(!E)
continue;let F=et(m.position,E,A.distanceMode),b=F<=A.distance+1e-6,j=m.nearInside.get(g)??!1;if(m.nearInside.set(g,b),b&&!j&&!(g.startsWith("trigger:")&&A.once!==!1&&m.triggerFired.
has(A.id))){let U={destinationId:A.destinationId,distance:F,distanceMode:A.distanceMode??"absolute",conditionKey:Z(A)};if(Y(m,"near",w,U)){z=!0;break}}}return z}function ye(m,w,z){
let A=new Map(c.map(b=>[b.unit.id,{...b.position}])),g=new Set;for(let b of c)for(let{c:j}of me(b)){g.add(b);let U=xe(r.source,b.assignment,j);U?.kind==="unit"&&r.byId.has(U.unitId)&&
g.add(r.byId.get(U.unitId))}if(!g.size)return w;for(let b of g)if(b.status!=="blocked"&&(b.join&&b.path.actualSpeed&&(w=Math.min(w,m+ee(b.position,b.join)/b.path.actualSpeed)),!b.join&&
(!b.graph||["follow","patrol"].includes(b.node?.kind))&&b.path.actualSpeed&&b.path.length)){let j=b.node?.kind==="patrol"?b.progress:le(b.routeTravel??b.distance,b.path.length),U=b.
path.nodes.find($=>$.d>j+1e-7);U&&(w=Math.min(w,m+(U.d-j)/(z.get(b.unit.id)??b.path.actualSpeed)))}let E=new Map(c.map(b=>[b.unit.id,r.predict(b,w,z,A)])),F=w;for(let b of c)for(let{
c:j,key:U}of me(b)){if(b.nearInside.get(U)||U.startsWith("trigger:")&&j.once!==!1&&b.triggerFired.has(j.id))continue;let $=r.destination(b,j,A),u=r.destination(b,j,E);if(!$||!u)continue;
let N=b.position,L=E.get(b.unit.id),M=[N.x-$.x,N.y-$.y,j.distanceMode==="horizontal"?0:N.z-$.z],C=[L.x-u.x-M[0],L.y-u.y-M[1],j.distanceMode==="horizontal"?0:L.z-u.z-M[2]],H=C.reduce(
(K,W)=>K+W*W,0),G=2*M.reduce((K,W,St)=>K+W*C[St],0),ae=M.reduce((K,W)=>K+W*W,0)-j.distance*j.distance,be=G*G-4*H*ae;if(H>1e-12&&ae>1e-6&&be>=0){let K=(-G-Math.sqrt(be))/(2*H);K>1e-9&&
K<=1&&(F=Math.min(F,m+(w-m)*K))}}return F}function se(m){let w=!1;for(let g of c)for(let E=0;E<(g.graph?.triggers.length??0)&&r.activate(g,"time",m,f);E++)w=!0;let z=g=>{for(let E=0;E<
64;E++){if(g.status==="blocked")return;let F=ge(g,m);if(F){w=!0;continue}if(g.node?.kind==="report"&&!g.sent?F=oe(g,m):g.node?.kind==="wait"&&!g.elapsed&&m-g.nodeTime>=(g.node.parameter===
"preparation"?g.assignment.preparation??g.node.seconds:g.node.seconds)&&(g.elapsed=!0,F=Y(g,"elapsed",m)),w=w||F,!F)return}throw Error("即時ノード遷移が64段を超えました。循環を見直してください。")};
for(let g of c)z(g);let A=0;for(;;){if(h.sort((F,b)=>F.time-b.time||F.unitId.localeCompare(b.unitId)),!h[0]||h[0].time>m)return w;if(++A>1e5||f.length>1e5)throw Error("情報イベントが10万件を\
超えました。");let g=h.shift(),E=r.byId.get(g.unitId);f.push(g),E.observation=g,w=r.transition(E,"received",m,f,g)||w,z(E)}}se(0),I&&Object.assign(S,I.update(f)),a&&r.record(
0,x);for(let m=0;m<o;){let w=Math.min(o,(Math.floor((m+1e-8)/s)+1)*s,e?.deadline>m?e.deadline:1/0),z=1/0;for(let u of h)u.time>m+1e-8&&(z=Math.min(z,u.time));for(let u of c)if(u.status!==
"blocked"){if(u.node?.kind==="wait"&&!u.elapsed){let N=u.node.parameter==="preparation"?u.assignment.preparation??u.node.seconds:u.node.seconds;u.nodeTime+N>m+1e-8&&(z=Math.min(z,u.
nodeTime+N))}for(let N of u.graph?.triggers??[])if(N.event==="time"){let L=r.nextTriggerTime(u,N);L>m+1e-8&&(z=Math.min(z,L))}if((!u.graph||u.node?.kind==="follow")&&!u.join&&!u.path.
periodic&&u.path.length&&u.path.actualSpeed&&!u.routeArrived){let N=(u.graph?u.routeStarted??0:0)+u.path.delay+u.path.length/u.path.actualSpeed;N>m+1e-8&&(z=Math.min(z,N))}if(u.join&&
u.path.actualSpeed){let N=m+ee(u.position,u.join)/u.path.actualSpeed;N>m+1e-8&&(z=Math.min(z,N))}if(u.node?.kind==="move"&&u.status!=="arrived"&&u.path.actualSpeed&&xe(r.source,u.assignment,
u.node)?.kind==="point"){let N=m+ee(u.position,r.destination(u))/u.path.actualSpeed;N>m+1e-8&&(z=Math.min(z,N))}}r.currentTime=m;let A=re(),g=ye(m,Math.min(w,z),A),E=g-m,F=new Map(
c.map(u=>[u.unit.id,{...u.position}])),b=new Map(c.map(u=>[u.unit.id,r.predict(u,g,A,F)])),j=!1;for(let u of c)if(u.status!=="blocked"&&!(u.graph&&!u.node)){if(u.node?.kind==="foll\
ow"&&u.join){We(r,u,u.join,u.path.actualSpeed,E)&&(u.join=null,u.routeStarted=g-(u.path.actualSpeed?u.routeOffset/u.path.actualSpeed:0)-(u.routeOffset>0?u.path.delay:0),u.routeTravel=
u.routeOffset),j=!0;continue}if(!u.graph||u.node.kind==="follow"){let N=u.status,L=u.segment,M=u.graph?u.routeStarted??0:0,C=ue.prototype.evaluateUnit.call(r,u.unit,Math.max(0,g-M),
!1);if(u.graph){let H=u.distance+Math.max(0,C.distance-(u.routeTravel??0));u.routeTravel=C.distance,Object.assign(u,C),u.distance=H}else Object.assign(u,C);u.segment=Ae(u.path,u.path.
periodic?C.distance%u.path.length:C.distance).segment,(N!==u.status||L!==u.segment)&&(j=!0),u.status==="arrived"&&!u.routeArrived&&(u.routeArrived=!0,j=Y(u,"arrived",g)||j)}else if(u.
node.kind==="patrol"){if(g<=u.readyAt){u.status="waiting";continue}let N=g-Math.max(m,u.readyAt);if(u.join){We(r,u,u.join,u.path.actualSpeed,N)&&(u.join=null),j=!0;continue}if(!u.path.
length){u.status="blocked",u.error="周回経路の長さが0です。",j=!0;continue}let L=(A.get(u.unit.id)??u.path.actualSpeed)*N,M=u.progress+L;if(u.path.error&&M>=u.path.length){
u.position={...u.path.nodes.at(-1)},u.status="blocked",u.error=u.path.error,j=!0;continue}u.progress=le(M,u.path.length);let C=Ae(u.path,u.progress);u.position=C.point,u.heading=C.
heading,u.distance+=L,u.status="moving",C.segment!==u.segment&&(j=!0,u.segment=C.segment)}else if(u.node.kind==="move"){let N=r.destination(u,u.node,b),L=xe(r.source,u.assignment,u.
node)?.kind==="unit";if(!N){u.status="blocked",u.error="目的地が見つかりません。",j=!0;continue}(u.status!=="arrived"||L)&&We(r,u,N,u.path.actualSpeed,E)&&u.status==="a\
rrived"&&!u.destinationArrived&&(u.destinationArrived=!0,j=!0,Y(u,"arrived",g))}}if(Math.abs(g-w)<1e-8){let u=c.filter(M=>M.unit.sensor?.enabled&&M.status!=="blocked"&&M.node?.kind!==
"stop"&&M.node?.sensor!==!1),N=vt(u.map(M=>({unit:M.unit,position:qe(M.position,M.unit),state:M})),P),L=[];for(let M of v){if(M.error&&M.path.errorAt==="初期位置"||M.unit.detectability===
0)continue;let C=qe(M.position,{domain:M.unit.domain});for(let H of It(N,C,P)){++R%256===0&&(yield{time:m,result:S});let G=H.state,ae=G.unit.sensor,be=G.unit.id+"|"+M.unit.id;if(G.
unit.faction===M.unit.faction||y.has(be)||!ae.domains.includes(M.unit.domain))continue;let K=ee(H.position,C),W=bt(ae,K,M.unit.detectability??1,g-p);W<=0||ae.terrainLOS&&!Be(r.terrain,
H.position,C)||B(Q(r.source,G.unit.id,"unified-detect-v2")+"|"+JSON.stringify([M.unit.id,p,g]))<W&&(y.add(be),L.push({type:"detected",time:g,sampleTime:g,observationTime:g,observerId:G.
unit.id,unitId:G.unit.id,targetId:M.unit.id,distance:K,observerPosition:{...H.position},targetPosition:{...C},trace:[]}))}}L.sort((M,C)=>M.unitId.localeCompare(C.unitId)||M.targetId.
localeCompare(C.targetId));for(let M of L){let C=r.byId.get(M.unitId);(!e||e.type==="state"||C.unit.faction===e.observerFaction&&k.some(H=>H.unit.id===M.targetId))&&!l.has(M.targetId)&&
(l.set(M.targetId,M),S.events.push(M)),C.observation=M,j=Y(C,"detected",g,M)||j}p=g}if(j=se(g)||j,f.length+h.length>1e5)throw Error("行動イベントが10万件を超えました。");
S.detectedCount=S.events.filter(u=>!e||u.time<=e.deadline).length,S.reachedCount=new Set(f.filter(u=>u.type==="arrived"&&T.includes(u.unitId)&&(!e||u.time<=e.deadline)).map(u=>u.unitId)).
size,I&&Object.assign(S,I.update(f));let U=e?.type==="arrive"?S.reachedCount:S.detectedCount,$=e?.join==="all"?e.type==="arrive"?T.length:k.length:1;if(e&&e.type!=="state"&&$>0&&g<=
e.deadline&&U>=$&&S.successTime===null&&(S.success=!0,S.successTime=g),a&&(j||g-D>=d-1e-8||g===o)&&(r.record(g,x),D=g),m=g,yield{time:g,result:S},!a&&!c.some(u=>u.graph)&&e?.type===
"detect"&&S.detectedCount===k.length)break}return S.constrainedPaths=c.filter(m=>m.status==="blocked").length,a&&(r.frames=x,r.result=S),S}var Ne=t=>new ie(t);var _,J,fe=0,te="idle",he=null;function pe(){if(!_||!J)return;let t=_.evaluate(_.frames?J.time:0);if(_.frames&&J.showTrails){let e=_.states.length<=80?_.states.map(n=>n.unit.id):[J.
selected];t.trails=Object.fromEntries(e.filter(Boolean).map(n=>[n,_.trailPoints(n,t.time)]))}t.executionState=te,t.recordingRunning=te==="running",t.recordingPending=!_.frames,t.actionsPending=
!_.frames,he&&(t.missionError=he),self.postMessage({type:"snapshot",revision:J.revision,request:J.request,snapshot:t})}self.onmessage=({data:t})=>{if(t.type==="ping"){self.postMessage(
{type:"pong"});return}try{if(t.type==="scenario"){let e=++fe;J=t,he=null,_=t.recording?Ve(t.recording):Ne(t.scenario),te=_.frames?"ready":"idle",pe(),t.autoRecord&&!_.frames&&At(e)}else if(t.
revision===J?.revision)if(J={...J,...t,scenario:J.scenario},t.type==="calculate"){let e=++fe;_=Ne(J.scenario),J.time=0,he=null,At(e)}else t.type==="cancelRecording"?(fe++,te="cance\
lled",_=Ne(J.scenario),pe()):t.type==="exportRecording"?self.postMessage({type:"recordingExport",revision:t.revision,payload:Ke(_)}):pe()}catch(e){te="failed",he=e.message,pe(),self.
postMessage({type:"error",revision:t.revision,message:e.message})}};async function At(t){te="running",pe();try{let e=Mt(_,_.source.mission,void 0,{horizon:_.source.duration,record:!0}),
n=e.next(),i=performance.now(),r=0;for(;!n.done;){if(performance.now()-i>16&&(await new Promise(o=>setTimeout(o,0)),i=performance.now(),t!==fe))return;performance.now()-r>150&&(r=performance.
now(),self.postMessage({type:"recordingProgress",revision:J.revision,time:n.value.time,duration:_.source.duration})),n=e.next()}if(t!==fe)return;te="ready"}catch(e){if(t!==fe)return;
te="failed",he=e.message}pe()}})();
